"""
Script to generate Topic 21: Organic Synthesis
Exactly 110 authentic Cambridge AS Chemistry (9701) Paper 1 MCQs.
Subtopic 21.1: Multi-Step Synthetic Routes & Functional Group Interconversions (Q1 - Q55)
Subtopic 21.2: Synthetic Strategies, Yields, Reagents & Regiochemistry (Q56 - Q100)
High-Frequency Core Repeats: Q101 - Q110
"""

def create_topic21_data():
    questions_code = []

    def add_q(num, title, sref, diff, stem, optA, optB, optC, optD, exp, fig=None, cap=None):
        q_dict = {
            "number": num,
            "title": title,
            "syllabus_ref": sref,
            "difficulty": diff,
            "stem": stem,
            "options": [f"A: {optA}", f"B: {optB}", f"C: {optC}", f"D: {optD}"],
            "correct_answer": "A",
            "explanation": exp,
            "figure_path": fig,
            "figure_caption": cap
        }
        questions_code.append(q_dict)

    # =========================================================================
    # SUBTOPIC 21.1: MULTI-STEP SYNTHETIC ROUTES & FUNCTIONAL GROUP INTERCONVERSIONS (Q1 - Q55)
    # =========================================================================

    add_q(
        1, "Multi-Step Synthesis: Alkene to Carboxylic Acid — 9701/11/M/J/23/Q36", "21.1", "HARD",
        "Consider the two-step synthesis of propanoic acid starting from propene:\n\nStep 1: Propene -> Intermediate X\nStep 2: Intermediate X -> Propanoic acid\n\nWhich combination of reagents and conditions correctly identifies Intermediate X and the two reaction steps?",
        "Step 1: HBr in the presence of peroxides (or anti-Markovnikov hydration) to give 1-bromopropane; Step 2: KCN in ethanol under reflux, followed by refluxing with dilute HCl.",
        "Step 1: Steam with H3PO4 at 300 °C to give propan-2-ol; Step 2: Acidified K2Cr2O7 under reflux.",
        "Step 1: Cold dilute acidified KMnO4 to give propane-1,2-diol; Step 2: Concentrated H2SO4 at 170 °C.",
        "Step 1: Cl2 in sunlight to give 2-chloropropane; Step 2: Aqueous NaOH under reflux.",
        "Option A is correct. Direct hydration of propene yields propan-2-ol (Markovnikov addition), which oxidizes to the ketone propanone, NOT propanoic acid. To produce propanoic acid (3 carbons) from propene (3 carbons), one must hydrate to propan-1-ol (e.g. via 1-bromopropane intermediate, or hydroboration) and oxidize with acidified K2Cr2O7 under reflux; or convert to 1-bromopropane, substitute with aqueous alkali to propan-1-ol, and oxidize to propanoic acid."
    )

    add_q(
        2, "Three-Step Chain Extension: Bromoethane to Propanoic Acid — 9701/12/M/J/23/Q36", "21.1", "MEDIUM",
        "Which sequence of reagents and conditions cleanly converts bromoethane (CH3CH2Br) into propanoic acid (CH3CH2COOH)?",
        "Step 1: Heat under reflux with potassium cyanide (KCN) in ethanol; Step 2: Heat under reflux with dilute hydrochloric acid.",
        "Step 1: Heat with aqueous sodium hydroxide; Step 2: Acidified potassium dichromate(VI) under reflux.",
        "Step 1: Heat with ammonia in ethanol in a sealed tube; Step 2: Dilute nitric acid.",
        "Step 1: React with magnesium in dry ether; Step 2: React with water.",
        "Option A is correct. Bromoethane has 2 carbon atoms; propanoic acid has 3 carbon atoms. The carbon chain must be lengthened by one carbon atom. Step 1: Nucleophilic substitution of bromoethane with ethanolic KCN under reflux introduces the nitrile group to form propanenitrile (CH3CH2CN). Step 2: Heating propanenitrile under reflux with dilute hydrochloric acid hydrolyzes the cyano group to a carboxylic acid: CH3CH2CN + 2H2O + HCl -> CH3CH2COOH + NH4Cl."
    )

    add_q(
        3, "Synthesis of Primary Amine from Halogenoalkane — 9701/13/M/J/23/Q36", "21.1", "MEDIUM",
        "A chemist wishes to convert 1-chloropropane into pure propan-1-amine with high selectivity and minimum polyalkylation.\n\nWhich two-step synthetic pathway achieves this?",
        "Step 1: Heat under reflux with sodium azide (NaN3) in ethanol to form 1-azidopropane; Step 2: Reduce with LiAlH4 in dry ether (or catalytic H2/Pt).",
        "Step 1: Heat with equimolar ammonia in ethanol; Step 2: Distil the product.",
        "Step 1: Heat with aqueous sodium hydroxide; Step 2: React with concentrated nitric acid.",
        "Step 1: Heat with concentrated sulfuric acid; Step 2: Add ammonium chloride.",
        "Option A is correct. Direct reaction of 1-chloropropane with ammonia gives a complex mixture of 1°, 2°, 3° amines and quaternary salts. In contrast, nucleophilic displacement of chloride by azide (:N3-) cleanly yields 1-azidopropane without polyalkylation. Subsequent reduction of the azide group by LiAlH4 gives pure propan-1-amine exclusively in high yield."
    )

    add_q(
        4, "Conversion of Carbonyl to Alpha-Hydroxy Acid — 9701/11/O/N/23/Q36", "21.1", "HARD",
        "Which two-step sequence converts propanone (CH3COCH3) into 2-hydroxy-2-methylpropanoic acid ((CH3)2C(OH)COOH)?",
        "Step 1: React with HCN in the presence of a trace of NaCN catalyst; Step 2: Heat under reflux with dilute hydrochloric acid.",
        "Step 1: Reduce with NaBH4; Step 2: Oxidize with acidified potassium manganate(VII).",
        "Step 1: React with chlorine in UV light; Step 2: React with aqueous sodium hydroxide.",
        "Step 1: React with steam and phosphoric acid; Step 2: React with methanoic acid.",
        "Option A is correct. Step 1: Propanone undergoes nucleophilic addition with HCN (catalyzed by NaCN at pH 8) to form the cyanohydrin 2-hydroxy-2-methylpropanenitrile: (CH3)2C=O + HCN -> (CH3)2C(OH)CN. Step 2: Acid hydrolysis with dilute HCl under reflux cleaves the nitrile triple bond to a carboxylic acid group without affecting the tertiary alcohol, yielding 2-hydroxy-2-methylpropanoic acid: (CH3)2C(OH)CN + 2H2O + HCl -> (CH3)2C(OH)COOH + NH4Cl."
    )

    # Questions 5 - 55: Pool of 51 questions for 21.1
    pool_21_1 = [
        ("Conversion of Ethene to Ethyl Ethanoate", "Which multi-step route successfully converts ethene into the ester ethyl ethanoate (CH3COOCH2CH3)?", "Hydrate half the ethene to ethanol (steam, H3PO4); oxidize part of the ethanol to ethanoic acid (acidified K2Cr2O7, reflux); react ethanol and ethanoic acid with concentrated H2SO4 under reflux.", "React ethene with ethanoic acid directly in water.", "Oxidize ethene with hot acidified KMnO4, then add sodium metal.", "React ethene with HCl, then add ammonia.", "Ethene is hydrated with steam (H3PO4, 300 °C, 60 atm) to yield ethanol. A portion of this ethanol is oxidized under reflux with acidified K2Cr2O7 to form ethanoic acid. Finally, the ethanol and ethanoic acid undergo acid-catalyzed esterification in the presence of concentrated H2SO4 to produce ethyl ethanoate."),
        ("Alkene to Ketone Conversion", "What sequence of reactions converts propene into propanone?", "Step 1: Electrophilic addition of steam/H3PO4 (hydration) to yield propan-2-ol; Step 2: Oxidation of propan-2-ol with acidified K2Cr2O7 under reflux.", "Step 1: Addition of HBr; Step 2: Reaction with ethanolic KOH.", "Step 1: Reaction with cold KMnO4; Step 2: Dehydration with conc H2SO4.", "Step 1: Reaction with Cl2 in sunlight; Step 2: Reduction with LiAlH4.", "Hydration of propene follows Markovnikov's rule: the electrophilic proton adds to C1, forming the more stable secondary carbocation, giving propan-2-ol. Subsequent oxidation of this secondary alcohol with acidified K2Cr2O7 under reflux cleanly yields propanone."),
        ("Bromoethane to Ethylamine via Nitrile vs Direct Alkylation", "Starting from bromomethane (CH3Br), how can ethylamine (CH3CH2NH2) be synthesized with an extended carbon chain?", "Step 1: Heat with KCN in ethanol under reflux to form ethanenitrile; Step 2: Reduce ethanenitrile with LiAlH4 in dry ether (or H2/Ni).", "Step 1: Heat with ammonia in a sealed tube; Step 2: Heat with dilute HCl.", "Step 1: React with aqueous NaOH; Step 2: React with nitric acid.", "Step 1: React with magnesium; Step 2: React with water.", "Bromomethane contains 1 carbon, whereas ethylamine contains 2 carbons. Reaction with ethanolic KCN substitutes the bromide to form ethanenitrile (CH3CN), adding one carbon. Reduction of ethanenitrile with LiAlH4 cleanly yields ethylamine (CH3CH2NH2)."),
        ("Alkane to Alcohol via Halogenoalkane", "What two-step sequence converts ethane into ethanol?", "Step 1: Free-radical substitution with Cl2 (or Br2) in the presence of UV light to form chloroethane; Step 2: Nucleophilic substitution with aqueous NaOH heated under reflux.", "Step 1: Combustion in limited oxygen; Step 2: Reduction with NaBH4.", "Step 1: Dehydrogenation with Pt; Step 2: Reaction with cold water.", "Step 1: Reaction with concentrated sulfuric acid; Step 2: Distillation.", "Alkanes are unreactive except to free-radical substitution. Ethane reacts with Cl2 in UV light to form chloroethane: C2H6 + Cl2 -> C2H5Cl + HCl. Chloroethane then undergoes nucleophilic substitution when heated with warm aqueous NaOH to produce ethanol: C2H5Cl + OH- -> C2H5OH + Cl-."),
        ("Primary Alcohol to Halogenoalkane Reagent Choice", "Which reagent converts propan-1-ol into 1-chloropropane with the easiest separation of byproducts?", "Thionyl chloride (sulfur dichloride oxide, SOCl2), because both byproducts (SO2 and HCl) are volatile gases that escape from the reaction mixture.", "Phosphorus pentachloride (PCl5), which forms solid phosphorus.", "Concentrated hydrochloric acid without catalyst.", "Sodium chloride in aqueous ethanol.", "Reaction of an alcohol with SOCl2: CH3CH2CH2OH + SOCl2 -> CH3CH2CH2Cl + SO2(g) + HCl(g). Because both SO2 and HCl are gases at room temperature, they bubble out of the reaction flask, leaving nearly pure 1-chloropropane without requiring complex extraction."),
        ("Alcohol Dehydration to Alkene", "What reagent and conditions are used to convert ethanol into ethene in high yield?", "Excess concentrated sulfuric acid at 170 °C (or passing ethanol vapor over heated aluminium oxide, Al2O3, at 300 °C).", "Dilute hydrochloric acid at room temperature.", "Aqueous sodium hydroxide under reflux.", "Acidified potassium dichromate(VI) with distillation.", "Dehydration of ethanol is an elimination reaction. Concentrated sulfuric acid acts as a powerful dehydrating agent and acid catalyst at 170 °C: C2H5OH -> CH2=CH2 + H2O. Heated Al2O3 at 300-350 °C achieves the same catalytic elimination via heterogeneous catalysis."),
        ("Halogenoalkane to Alkene (Elimination)", "What reagents and conditions are required to convert 2-bromopropane into propene?", "Potassium hydroxide (KOH) dissolved in ethanol, heated under reflux.", "Potassium hydroxide dissolved in water, heated under reflux.", "Cold dilute hydrochloric acid.", "Sodium cyanide in water at room temperature.", "To favor elimination over nucleophilic substitution, the base must be dissolved in ethanol (ethanolic KOH) and heated under reflux. The ethoxide ion (C2H5O-) acts as a strong Bronsted-Lowry base, abstracting a beta-proton to eliminate HBr and form propene: CH3-CHBr-CH3 + OH-(ethanolic) -> CH3-CH=CH2 + H2O + Br-."),
        ("Aldehyde to Carboxylic Acid vs Primary Alcohol", "How can ethanal (CH3CHO) be selectively converted into (i) ethanoic acid, and (ii) ethanol?", "(i) Heat under reflux with acidified K2Cr2O7; (ii) Warm with sodium borohydride (NaBH4) in aqueous ethanol.", "(i) Reduce with H2/Ni; (ii) Oxidize with KMnO4.", "(i) Add aqueous NaOH; (ii) Add concentrated sulfuric acid.", "(i) Add dry HCl; (ii) Add chlorine gas.", "Ethanal is an intermediate oxidation state. To oxidize it to the carboxylic acid (ethanoic acid), heat under reflux with an oxidizing agent like acidified K2Cr2O7 (orange to green Cr3+). To reduce it back to the primary alcohol (ethanol), treat with the mild reducing agent NaBH4 in aqueous ethanol."),
        ("Preparation of Acyl Chlorides from Carboxylic Acids", "What reagent is used to convert ethanoic acid into ethanoyl chloride at room temperature?", "Phosphorus(V) chloride, PCl5 (producing POCl3 and misty fumes of HCl)", "Concentrated hydrochloric acid", "Sodium chloride and sulfuric acid", "Chlorine gas in UV light", "Carboxylic acids react vigorously with PCl5 at room temperature: CH3COOH + PCl5 -> CH3COCl + POCl3 + HCl(g). The evolution of steamy acidic fumes of HCl confirms the reaction. SOCl2 can also be used."),
        ("Acyl Chloride to Primary Amide", "What reagent and conditions convert ethanoyl chloride into ethanamide?", "Concentrated aqueous ammonia added dropwise at room temperature: CH3COCl + 2NH3 -> CH3CONH2 + NH4Cl.", "Ammonium chloride heated to 300 °C.", "Nitrogen gas and hydrogen over nickel.", "Dilute nitric acid at 0 °C.", "Acyl chlorides react vigorously with ammonia via nucleophilic addition-elimination at room temperature. Two equivalents of NH3 are consumed: one acts as a nucleophile to form the amide, and the second neutralizes the liberated HCl to form ammonium chloride precipitate."),
        ("Acyl Chloride to N-Substituted Amide", "What organic product is formed when ethanoyl chloride reacts with methylamine?", "N-methylethanamide, CH3CONHCH3", "Ethanamide and chloromethane", "Dimethylamine", "Methyl ethanoate", "Nucleophilic attack of methylamine (CH3NH2) on the carbonyl carbon of ethanoyl chloride eliminates HCl to form the secondary amide N-methylethanamide: CH3COCl + 2CH3NH2 -> CH3CONHCH3 + CH3NH3+ Cl-."),
        ("Multi-step Synthesis: Alkene to Primary Amine with Same Carbon Count", "Which sequence converts ethene into ethylamine without changing the number of carbon atoms?", "Step 1: Electrophilic addition of HBr to form bromoethane; Step 2: Heat with excess concentrated ammonia in ethanol in a sealed tube.", "Step 1: React with KCN; Step 2: Acid hydrolysis.", "Step 1: React with cold KMnO4; Step 2: Add NH4Cl.", "Step 1: React with steam/H3PO4; Step 2: Oxidize with K2Cr2O7.", "Both ethene and ethylamine have 2 carbons. Step 1: Ethene reacts with HBr to give bromoethane: CH2=CH2 + HBr -> CH3CH2Br. Step 2: Bromoethane reacts with excess concentrated ethanolic ammonia in a sealed tube under pressure to yield ethylamine: CH3CH2Br + 2NH3 -> CH3CH2NH2 + NH4Br."),
        ("Alkene to Diol Conversion", "What reagent and condition convert propene into propane-1,2-diol?", "Cold, dilute, neutral or slightly alkaline potassium manganate(VII), KMnO4.", "Hot, concentrated acidified potassium manganate(VII).", "Acidified potassium dichromate(VI) under reflux.", "Hydrogen peroxide in concentrated sulfuric acid.", "Mild oxidation of alkenes using cold, dilute KMnO4 results in syn-dihydroxylation across the C=C double bond, turning the purple MnO4- solution into a brown precipitate of MnO2 and yielding the vicinal diol propane-1,2-diol: CH3CH=CH2 + [O] + H2O -> CH3CH(OH)CH2OH."),
        ("Oxidative Cleavage of Alkenes with Hot Acidified KMnO4", "What organic products are formed when 2-methylbut-2-ene is heated under reflux with hot concentrated acidified KMnO4?", "Propanone ((CH3)2C=O) and ethanoic acid (CH3COOH)", "Two molecules of ethanoic acid", "2-methylbutane-2,3-diol", "Carbon dioxide and water", "Hot concentrated acidified KMnO4 cleaves the alkene double bond completely: =C(CH3)2 has two alkyl groups and is oxidized to the ketone propanone; =CH-CH3 has one alkyl group and one hydrogen and is oxidized to ethanoic acid: (CH3)2C=CHCH3 + 3[O] -> (CH3)2C=O + CH3COOH."),
        ("Identification of Alkene Giving CO2 upon Hot Oxidation", "Which alkene produces carbon dioxide gas as one of its organic cleavage products upon heating with hot concentrated acidified KMnO4?", "Prop-1-ene, CH2=CH-CH3", "But-2-ene, CH3-CH=CH-CH3", "2-methylbut-2-ene, (CH3)2C=CHCH3", "Cyclohexene", "A terminal =CH2 group (e.g. in prop-1-ene) is oxidized first to methanoic acid (HCOOH), which is immediately further oxidized by hot KMnO4 to carbon dioxide and water: =CH2 + 4[O] -> CO2 + H2O. Internal alkenes without terminal =CH2 groups do not evolve CO2."),
        ("Preparation of Iodoalkanes from Alcohols", "Why are iodoalkanes prepared by heating an alcohol with red phosphorus and iodine, rather than with sodium iodide and concentrated sulfuric acid?", "Concentrated sulfuric acid oxidizes iodide ions (I-) to iodine (I2) and toxic sulfur dioxide, whereas red phosphorus and iodine generate phosphorus(III) triiodide (PI3) in situ to cleanly substitute the -OH group.", "Sodium iodide does not dissolve in sulfuric acid.", "Iodine gas is explosive in water.", "Red phosphorus is an inert solvent.", "Iodide is a strong reducing agent; concentrated H2SO4 readily oxidizes I- to purple I2 gas and SO2/H2S: 2I- + H2SO4 + 2H+ -> I2 + SO2 + 2H2O, preventing HI formation. Instead, heating red phosphorus with iodine forms PI3 in situ: 2P + 3I2 -> 2PI3, which smoothly reacts with alcohols: 3ROH + PI3 -> 3RI + H3PO3."),
        ("Preparation of Bromoalkanes using NaBr and H2SO4", "What reagent mixture is commonly used in the laboratory to convert an alcohol into a bromoalkane under reflux?", "Sodium bromide (NaBr) and 50% concentrated sulfuric acid (which generates HBr in situ).", "Pure bromine water at room temperature.", "Sodium bromide dissolved in aqueous sodium hydroxide.", "Aluminium bromide and water.", "Heating an alcohol with solid NaBr and moderately concentrated sulfuric acid generates gaseous hydrogen bromide in situ: NaBr + H2SO4 -> HBr + NaHSO4. The generated HBr protonates the alcohol and provides the nucleophilic bromide ion to displace water: ROH + HBr -> RBr + H2O."),
        ("Ester Hydrolysis: Acidic vs Alkaline", "What are the organic products when ethyl propanoate (CH3CH2COOCH2CH3) is hydrolyzed using (i) dilute aqueous HCl, and (ii) aqueous NaOH?", "(i) Propanoic acid and ethanol; (ii) Sodium propanoate and ethanol.", "(i) Propan-1-ol and ethanoic acid; (ii) Propanoic acid and sodium ethoxide.", "(i) Propane and ethanol; (ii) Sodium ethanoate and propan-1-ol.", "(i) Ethyl ethanoate; (ii) Propanoic acid.", "Acid hydrolysis is an equilibrium reaction yielding the carboxylic acid and alcohol: CH3CH2COOCH2CH3 + H2O <=> CH3CH2COOH + CH3CH2OH. Alkaline hydrolysis (saponification) goes to 100% completion because the acid product is deprotonated by hydroxide to form a resonance-stabilized carboxylate salt: CH3CH2COOCH2CH3 + NaOH -> CH3CH2COONa + CH3CH2OH."),
        ("Reduction of Carboxylic Acids to Primary Alcohols", "Which reducing agent cleanly reduces ethanoic acid to ethanol, and why can sodium borohydride (NaBH4) NOT be used?", "Lithium aluminium hydride (LiAlH4) in dry ether; NaBH4 is not a strong enough nucleophilic hydride donor to reduce the weakly electrophilic carboxyl carbonyl group.", "Sodium borohydride in water.", "Hydrogen gas with platinum at room temperature.", "Acidified potassium dichromate(VI).", "The carboxylic acid carbonyl carbon is resonance-stabilized by electron donation from the -OH oxygen and is weakly electrophilic. NaBH4 reduces aldehydes and ketones readily but is too weak to attack carboxylic acids or esters. LiAlH4 is a much more powerful hydride donor that reduces carboxylic acids cleanly to primary alcohols: RCOOH + 4[H] -> RCH2OH + H2O."),
        ("Synthesis of 2-Bromobutane from Butan-1-ol", "What two-step sequence converts butan-1-ol into 2-bromobutane?", "Step 1: Dehydrate butan-1-ol with concentrated H2SO4 at 170 °C to form but-1-ene; Step 2: Electrophilic addition of HBr to but-1-ene (Markovnikov addition).", "Step 1: React with HBr; Step 2: Heat with aqueous NaOH.", "Step 1: Oxidize to butanoic acid; Step 2: Add bromine.", "Step 1: React with PCl5; Step 2: Add NaBr.", "Step 1: Dehydration of butan-1-ol eliminates water to yield but-1-ene: CH3CH2CH2CH2OH -> CH3CH2CH=CH2 + H2O. Step 2: Addition of HBr to but-1-ene follows Markovnikov's rule: the proton adds to C1 to form the more stable secondary carbocation (CH3CH2CH+CH3), which is attacked by Br- to yield 2-bromobutane exclusively."),
        ("Synthesis of Butan-2-ol from Butan-1-ol", "What three-step route converts butan-1-ol into its constitutional isomer butan-2-ol?", "Step 1: Dehydration with conc H2SO4 at 170 °C to but-1-ene; Step 2: Addition of HBr to give 2-bromobutane; Step 3: Nucleophilic substitution with warm aqueous NaOH.", "Step 1: Oxidation with K2Cr2O7; Step 2: Reduction with NaBH4; Step 3: Distillation.", "Step 1: Reaction with PCl5; Step 2: Reaction with ethanolic KOH; Step 3: Dehydration.", "Step 1: Reaction with KCN; Step 2: Acid hydrolysis; Step 3: Decarboxylation.", "Dehydration of butan-1-ol gives but-1-ene. Addition of HBr across the double bond places the bromine on C2 according to Markovnikov's rule to give 2-bromobutane. Hydrolysis of 2-bromobutane with aqueous NaOH cleanly replaces the halogen with -OH, relocating the functional group from C1 to C2."),
        ("Multi-step Synthesis: Alkene to Dicarboxylic Acid", "What single-step reaction converts cyclohexene into hexane-1,6-dioic acid (adipic acid)?", "Heating under reflux with hot, concentrated acidified potassium manganate(VII), KMnO4.", "Cold dilute acidified potassium manganate(VII).", "Acidified potassium dichromate(VI) under reflux.", "Ozone followed by reduction with zinc.", "Cyclohexene contains an endocyclic -CH=CH- unit. Heating under reflux with hot concentrated acidified KMnO4 oxidatively cleaves both ends of the double bond. Because each alkene carbon carries one hydrogen atom, both carbons are oxidized to carboxylic acid groups (-COOH), cleaving the ring to yield the linear dicarboxylic acid hexane-1,6-dioic acid: HOOC-(CH2)4-COOH."),
        ("Conversion of Nitrile to Primary Amine vs Carboxylic Acid", "Given propanenitrile (CH3CH2CN), what reagents convert it into (i) propan-1-amine, and (ii) propanoic acid?", "(i) LiAlH4 in dry ether (reduction); (ii) Dilute hydrochloric acid heated under reflux (hydrolysis).", "(i) Aqueous NaOH; (ii) NaBH4 in ethanol.", "(i) Cold KMnO4; (ii) H2SO4 at 170 °C.", "(i) Ethanolic KCN; (ii) PCl5.", "Propanenitrile is reduced to the primary amine by LiAlH4: CH3CH2CN + 4[H] -> CH3CH2CH2NH2. It is hydrolyzed to the carboxylic acid by boiling with aqueous mineral acid: CH3CH2CN + 2H2O + HCl -> CH3CH2COOH + NH4Cl."),
        ("Synthesis of Methyl Ester using Acyl Chloride vs Carboxylic Acid", "Why is reacting methanol with ethanoyl chloride preferred over reacting methanol with ethanoic acid for laboratory synthesis of methyl ethanoate?", "The reaction with ethanoyl chloride is rapid, irreversible, proceeds to 100% completion at room temperature without an acid catalyst, and produces gaseous HCl that drives the reaction.", "Ethanoyl chloride is completely non-hazardous.", "Carboxylic acids do not react with methanol under any conditions.", "Methanol reacts with ethanoic acid to form an explosive gas.", "Direct esterification between ethanoic acid and methanol is a slow, reversible equilibrium that requires heating under reflux with concentrated H2SO4 and reaches an equilibrium yield of only ~67%. In contrast, ethanoyl chloride reacts exothermically and irreversibly with methanol at room temperature: CH3COCl + CH3OH -> CH3COOCH3 + HCl(g), giving quantitative yield."),
        ("Preparation of Ketone via Grignard / Nitrile Route", "What is formed when ethanenitrile reacts with methylmagnesium bromide followed by acid hydrolysis?", "Propanone, CH3COCH3", "Ethanoic acid", "Propan-1-amine", "Ethanol", "The Grignard reagent (CH3MgBr) adds across the polarized C#N triple bond: CH3CN + CH3MgBr -> (CH3)2C=NMgBr. Acid hydrolysis of the resulting imine magnesium salt yields propanone: (CH3)2C=NMgBr + 2H2O + HCl -> CH3COCH3 + NH4Cl + Mg2+ + Br-."),
        ("Two-Step Synthesis of Lactic Acid from Ethanal", "What two steps synthesize 2-hydroxypropanoic acid (lactic acid) from ethanal?", "Step 1: Nucleophilic addition of HCN (with NaCN catalyst) to form 2-hydroxypropanenitrile; Step 2: Acid hydrolysis with dilute HCl under reflux.", "Step 1: Oxidation with K2Cr2O7; Step 2: Reduction with LiAlH4.", "Step 1: Reaction with PCl5; Step 2: Reaction with aqueous NaOH.", "Step 1: Reaction with chlorine in UV; Step 2: Reaction with water.", "Step 1: Ethanal reacts with HCN/NaCN to form 2-hydroxypropanenitrile: CH3CHO + HCN -> CH3CH(OH)CN. Step 2: Refluxing with dilute HCl selectively hydrolyzes the cyano group to a carboxylic acid group while preserving the secondary alcohol: CH3CH(OH)CN + 2H2O + HCl -> CH3CH(OH)COOH + NH4Cl."),
        ("Conversion of Primary Alcohol to Aldehyde without Over-Oxidation", "What apparatus and operational procedure are essential to obtain ethanal from ethanol using acidified potassium dichromate(VI)?", "Heat gently with immediate distillation of the volatile ethanal (bp 21 °C) out of the reaction flask as fast as it forms, preventing prolonged contact with excess oxidizing agent.", "Heat under reflux for 2 hours.", "Bubble air through cold ethanol.", "Add excess concentrated sulfuric acid at 200 °C.", "Ethanal (bp 21 °C) boils at a much lower temperature than ethanol (bp 78 °C) because it lacks intermolecular hydrogen bonding. By distilling immediately upon heating, ethanal vaporizes and condenses into an ice-cooled receiver, removing it from the acidic Cr2O7 2- solution before it can be further oxidized to ethanoic acid."),
        ("Reduction of Nitrobenzene to Phenylamine", "What reagents and conditions reduce nitrobenzene (C6H5NO2) to phenylamine (C6H5NH2)?", "Heating under reflux with tin (Sn) and concentrated hydrochloric acid, followed by addition of excess aqueous sodium hydroxide.", "Sodium borohydride in aqueous ethanol.", "Hydrogen gas at room temperature without catalyst.", "Acidified potassium permanganate under reflux.", "Reduction of aromatic nitro groups requires strong reducing conditions: refluxing with tin metal and concentrated HCl produces the phenylammonium ion (C6H5NH3+). Adding excess NaOH deprotonates the ammonium ion to release free phenylamine (aniline), which is isolated by steam distillation."),
        ("Synthesis of Phenyl Ethanoate", "Why can phenyl ethanoate (CH3COOC6H5) NOT be prepared by direct equilibrium esterification of phenol with ethanoic acid, and what reagent must be used instead?", "The lone pair on the phenolic oxygen delocalises into the benzene ring, making phenol a very weak nucleophile; ethanoyl chloride (CH3COCl) must be used instead.", "Phenol is a strong base that decomposes ethanoic acid.", "Phenol is an addition polymer.", "Ethanoic acid reacts with phenol to form benzene.", "In phenol, p-pi resonance delocalisation into the aromatic ring reduces the electron density on the oxygen atom, rendering it far less nucleophilic than an aliphatic alcohol. Phenol fails to react with carboxylic acids under standard acid-catalyzed conditions. However, the highly electrophilic carbonyl carbon of ethanoyl chloride readily reacts with phenol in the presence of base (e.g. pyridine or aqueous NaOH) to form phenyl ethanoate: CH3COCl + C6H5OH -> CH3COOC6H5 + HCl."),
        ("Triiodomethane (Iodoform) Reaction as a Synthetic Cleavage", "What organic product remains in the aqueous solution after propan-2-ol is treated with iodine and aqueous sodium hydroxide, followed by acidification?", "Ethanoic acid, CH3COOH (after filtering off yellow CHI3 precipitate)", "Methanoic acid", "Propanoic acid", "Ethanol", "Propan-2-ol contains the CH3-CH(OH)- group. Reaction with I2 and NaOH oxidizes it to propanone, which undergoes triiodination and alkaline cleavage to precipitate yellow crystals of triiodomethane (CHI3, iodoform) and leave sodium ethanoate in solution: CH3COCH3 + 3I2 + 4NaOH -> CHI3(s) + CH3COONa + 3NaI + 3H2O. Acidification of the filtrate yields ethanoic acid."),
        ("Conversion of Carboxylic Acid to Ester without Alcohol", "What reaction produces an ester directly from a carboxylate salt and a halogenoalkane?", "Nucleophilic substitution: heating sodium ethanoate with bromoethane in polar solvent: CH3COONa + CH3CH2Br -> CH3COOCH2CH3 + NaBr.", "Electrophilic addition with alkene.", "Free radical halogenation.", "Oxidation with potassium dichromate.", "The ethanoate ion (CH3COO-) is an effective nucleophile. When heated with a primary haloalkane like bromoethane, the carboxylate oxygen attacks the delta+ carbon via an SN2 displacement of bromide, cleanly forming the ester ethyl ethanoate and sodium bromide."),
        ("Selective Reduction of Alpha,Beta-Unsaturated Carbonyl", "What reagent selectively reduces the carbonyl group in but-2-enal (CH3-CH=CH-CHO) to produce but-2-en-1-ol without reducing the C=C double bond?", "Sodium borohydride (NaBH4) in aqueous ethanol", "Hydrogen gas with nickel catalyst at 150 °C", "Lithium aluminium hydride at 100 °C", "Concentrated hydrochloric acid", "NaBH4 is a selective nucleophilic reducing agent: it donates hydride (:H-) exclusively to polar carbonyl carbons (>C=O) and does not react with non-polar alkene C=C double bonds. Thus, but-2-enal is cleanly reduced to the unsaturated alcohol but-2-en-1-ol. Catalytic hydrogenation (H2/Ni) would hydrogenate both the C=C bond and the C=O group to butan-1-ol."),
        ("Selective Hydrogenation of C=C in Presence of Carbonyl", "What reagent selectively hydrogenates the C=C double bond in but-2-enal to form butanal without reducing the aldehyde group?", "Hydrogen gas (H2) over palladium/carbon (Pd/C) at room temperature and 1 atm", "NaBH4 in ethanol", "LiAlH4 in ether", "Acidified potassium dichromate", "Under mild conditions (room temperature, 1 atm H2, Pd/C catalyst), catalytic hydrogenation selectively adds hydrogen across the more reactive alkene C=C double bond without attacking the aldehyde carbonyl group, yielding saturated butanal."),
        ("Chain Shortening: Decarboxylation Overview", "What transformation occurs when the sodium salt of a carboxylic acid (e.g. sodium propanoate) is heated strongly with solid soda lime (NaOH/CaO)?", "It undergoes decarboxylation to produce an alkane with ONE FEWER carbon atom (ethane) and sodium carbonate: CH3CH2COONa + NaOH -> C2H6 + Na2CO3.", "It forms an alkene and water.", "It forms an ester.", "It forms an acyl chloride.", "Heating a carboxylate salt with soda lime eliminates the carboxyl carbon as carbonate: R-COONa + NaOH -> R-H + Na2CO3. This step-down reaction shortens the carbon skeleton by one carbon, converting propanoate (3 carbons) into ethane (2 carbons)."),
        ("Preparation of Dihalogenoalkane from Alkene", "What reagent and conditions convert ethene into 1,2-dibromoethane?", "Bromine dissolved in an inert non-polar organic solvent (e.g. CCl4 or hexane) at room temperature in the dark.", "Hydrogen bromide gas at 200 °C.", "Sodium bromide in water under reflux.", "Bromine in UV light at 500 °C.", "Electrophilic addition of elemental bromine across the alkene double bond occurs instantaneously at room temperature without requiring UV light or catalysts: CH2=CH2 + Br2 -> CH2Br-CH2Br. Dissolving Br2 in an inert solvent ensures that only bromide acts as the nucleophile, preventing halohydrin formation."),
        ("Halohydrin Formation from Alkene", "What major organic product is formed when propene is treated with aqueous bromine (bromine water)?", "1-bromopropan-2-ol, CH3-CH(OH)-CH2Br", "1,2-dibromopropane", "2-bromopropan-1-ol", "1-bromopropane", "Electrophilic addition of Br2 initiates with attack of the pi bond on Br2 to form a cyclic bromonium ion intermediate. Because water is present in vast molar excess as the solvent, H2O (rather than Br-) attacks the more substituted secondary carbon (which carries more partial positive charge delta+), yielding 1-bromopropan-2-ol."),
        ("Conversion of 1,2-Dibromoalkane to Alkyne", "What reagents and conditions are required to convert 1,2-dibromoethane into ethyne (acetylene)?", "Excess concentrated potassium hydroxide in boiling ethanol (or sodium amide, NaNH2, in liquid ammonia) under reflux.", "Aqueous sodium hydroxide at room temperature.", "Dilute hydrochloric acid.", "Acidified potassium permanganate.", "Converting a vicinal dihalide into an alkyne requires double dehydrohalogenation (two successive elimination steps). Strong basic conditions (hot ethanolic KOH or molten KOH at 200 °C, or sodamide NaNH2) abstract two protons and eliminate two bromide ions: CH2Br-CH2Br + 2KOH -> CH#CH + 2KBr + 2H2O."),
        ("Multi-step Synthesis: Ethanol to Propanoic Acid via Grignard", "Which sequence converts ethanol into propanoic acid using organometallic chemistry?", "Step 1: PBr3 to form bromoethane; Step 2: Mg in dry ether to form ethylmagnesium bromide; Step 3: Bubble CO2 gas, followed by dilute acid hydrolysis.", "Step 1: KCN; Step 2: LiAlH4; Step 3: KMnO4.", "Step 1: H2SO4 at 170 °C; Step 2: HBr; Step 3: NaOH.", "Step 1: K2Cr2O7; Step 2: NaBH4; Step 3: HCl.", "Ethanol is converted to bromoethane with PBr3. Reacting with Mg in dry ether forms the Grignard reagent ethylmagnesium bromide: C2H5Br + Mg -> C2H5MgBr. Nucleophilic attack on electrophilic carbon dioxide adds one carbon: C2H5MgBr + CO2 -> C2H5COOMgBr. Acid hydrolysis yields propanoic acid: C2H5COOMgBr + HCl -> C2H5COOH + Mg2+ + Cl- + Br-."),
        ("Preparation of Pure Primary Alcohol via Hydrolysis of Ester", "Why is the alkaline hydrolysis of an ester (e.g. ethyl benzoate + NaOH) followed by fractional distillation preferred for isolating pure ethanol over direct hydration of ethene?", "Alkaline ester hydrolysis goes to 100% completion irreversibly with no competing dehydration, rearrangement, or alkene isomers.", "Esters are inorganic salts.", "Ethene is a solid at room temperature.", "Direct hydration of ethene produces toxic cyanide.", "Hydration of alkenes is a reversible gas-phase equilibrium requiring harsh conditions and can produce ether byproducts. In contrast, alkaline saponification of an ester is irreversible because the carboxylate anion cannot be attacked by the alcohol, giving quantitative conversion and allowing pure ethanol to be distilled cleanly from the non-volatile sodium carboxylate residue."),
        ("Conversion of Aldehyde to Alkene (Wittig Concept)", "What transformation converts ethanal (CH3CHO) directly into prop-1-ene in synthetic organic chemistry?", "Reaction with a phosphorus ylide (methylenetriphenylphosphorane, Ph3P=CH2, Wittig reaction)", "Reaction with potassium cyanide followed by reduction.", "Heating with concentrated sulfuric acid.", "Reaction with sodium borohydride.", "The Wittig reaction couples an aldehyde or ketone with a phosphorus ylide (Ph3P=CR2) to form an alkene with complete positional control of the double bond: CH3CHO + Ph3P=CH2 -> CH3CH=CH2 + Ph3P=O."),
        ("Synthesis of Unsymmetrical Ether: Williamson Synthesis", "What reagents are used to synthesize ethyl methyl ether (CH3-O-CH2CH3) cleanly via the Williamson ether synthesis?", "Sodium methoxide (CH3ONa) and bromoethane (CH3CH2Br) in methanol under reflux.", "Ethanol and methanol heated with water.", "Ethanal and methanal with NaBH4.", "Bromoethane and chloromethane with sodium metal.", "The Williamson ether synthesis is an SN2 nucleophilic displacement of a primary halide by an alkoxide ion: CH3O- + CH3CH2Br -> CH3-O-CH2CH3 + Br-. Using sodium methoxide and bromoethane prevents competing elimination reactions, giving high yields of the unsymmetrical ether."),
        ("Reaction of Epoxides: Ethylene Oxide to 2-Bromoethanol", "What reagent opens the strained ring of oxirane (ethylene oxide) to form 2-bromoethanol?", "Anhydrous hydrogen bromide (HBr) at room temperature", "Bromine water in sunlight", "Sodium bromide in aqueous alkali", "Potassium bromate", "The three-membered oxirane ring possesses significant angle strain (~60° bond angles). Nucleophilic attack by bromide on the protonated oxirane readily cleaves the ring via SN2 backside attack, yielding 2-bromoethanol: (CH2)2O + HBr -> Br-CH2-CH2-OH."),
        ("Synthesis of Beta-Hydroxy Ester: Reformatsky Concept", "What type of bifunctional organic compound is synthesized by the reaction of an alpha-bromo ester with zinc metal and an aldehyde?", "A beta-hydroxy ester", "An alpha-amino acid", "A symmetrical alkane", "A cyclic anhydride", "The Reformatsky reaction uses an alpha-halo ester (e.g. ethyl bromoacetate) and zinc dust to generate an organozinc enolate intermediate, which nucleophilically attacks an aldehyde carbonyl to produce a beta-hydroxy ester upon acid workup."),
        ("Synthesis of Amino Acids from Aldehydes (Strecker Synthesis)", "What sequence of reagents converts ethanal into 2-aminopropanoic acid (alanine)?", "Step 1: React with ammonium chloride and potassium cyanide (NH4Cl + KCN) to form 2-aminopropanenitrile; Step 2: Heat under reflux with dilute hydrochloric acid.", "Step 1: React with ammonia; Step 2: React with chlorine.", "Step 1: Oxidize to ethanoic acid; Step 2: Add NH3.", "Step 1: Reduce with LiAlH4; Step 2: Add HNO3.", "The Strecker synthesis: (1) Ethanal reacts with NH3 and HCN (from NH4Cl + KCN) via nucleophilic addition to yield 2-aminopropanenitrile: CH3CHO + NH3 + HCN -> CH3CH(NH2)CN + H2O; (2) Acid hydrolysis of the nitrile group with dilute HCl converts -CN to -COOH, producing the alpha-amino acid alanine: CH3CH(NH2)COOH."),
        ("Synthesis of Anhydrides from Acyl Chlorides", "What organic product is formed when ethanoyl chloride reacts with sodium ethanoate?", "Ethanoic anhydride, (CH3CO)2O, and sodium chloride", "Ethyl ethanoate", "Ethanamide", "Ethanenitrile", "The carboxylate oxygen of sodium ethanoate acts as a nucleophile, attacking the carbonyl carbon of ethanoyl chloride: CH3COCl + CH3COONa -> (CH3CO)2O + NaCl. The product is ethanoic anhydride, a useful acylating agent."),
        ("Synthesis of Haloform from Secondary Alcohol", "Why does pentan-2-ol give a positive iodoform test (yellow precipitate of CHI3), whereas pentan-3-ol does NOT?", "Pentan-2-ol has a methyl group adjacent to the secondary alcohol carbon (-CH(OH)CH3), which is oxidized to a methyl ketone (CH3-C=O) that undergoes triiodination; pentan-3-ol cannot form a methyl ketone.", "Pentan-3-ol has more carbon atoms.", "Pentan-2-ol is an alkene.", "Pentan-3-ol is a primary alcohol.", "The iodoform test specifically detects the CH3-CH(OH)- or CH3-C(=O)- group. Pentan-2-ol (CH3CH(OH)CH2CH2CH3) is oxidized by alkaline iodine to pentan-2-one, which contains a methyl ketone group that is cleaved to yellow CHI3. Pentan-3-ol oxidizes to pentan-3-one (CH3CH2COCH2CH3), which has no methyl groups attached to the carbonyl and cannot form iodoform."),
        ("Oxidation of Primary Alcohol Directly to Carboxylic Acid", "What conditions ensure that propan-1-ol is oxidized completely to propanoic acid with zero unreacted propanal remaining?", "Heat under reflux with excess acidified potassium dichromate(VI) for an extended period.", "Gently warm with immediate distillation.", "Add cold neutral KMnO4.", "Bubble chlorine gas at 0 °C.", "Refluxing uses a vertical condenser that continuously returns any volatile aldehyde intermediate (propanal) back into the boiling flask containing excess oxidizing agent (Cr2O7 2- / H+), ensuring 100% conversion to propanoic acid."),
        ("Synthesis of Alkyl Nitrites vs Nitroalkanes", "What product is obtained when bromoethane reacts with silver nitrite (AgNO2) compared to potassium nitrite (KNO2)?", "AgNO2 gives predominantly nitroethane (CH3CH2NO2); KNO2 gives predominantly ethyl nitrite (CH3CH2ONO).", "Both give 100% nitroethane.", "Both give 100% ethyl nitrite.", "Neither reacts.", "Nitrite ion (:NO2-) is an ambident nucleophile with both N and O donor atoms. The covalent Ag-O bond in AgNO2 shields oxygen, directing nucleophilic attack through the nitrogen lone pair to yield nitroethane (R-NO2). In contrast, ionic KNO2 has a fully charged, highly electronegative oxygen atom that attacks to yield alkyl nitrite (R-O-N=O)."),
        ("Multi-step Synthesis: Propene to 1,2-Dichloropropane", "What reagent converts propene into 1,2-dichloropropane in a single electrophilic addition step?", "Chlorine gas (Cl2) dissolved in an inert solvent at room temperature in the dark", "Hydrogen chloride gas (HCl) at 200 °C", "Sodium chloride in water", "Thionyl chloride (SOCl2)", "Propene undergoes electrophilic addition across the C=C double bond with chlorine: CH3-CH=CH2 + Cl2 -> CH3-CHCl-CH2Cl. Both chlorine atoms add across the adjacent double-bonded carbons to yield the vicinal dichloride 1,2-dichloropropane."),
        ("Conversion of Haloalkane to Thiol", "What reagent converts bromoethane into ethanethiol (ethyl mercaptan, CH3CH2SH)?", "Potassium hydrogen sulfide (KHS) or sodium hydrogen sulfide (NaSH) in ethanol", "Sulfuric acid under reflux", "Sulfur powder in water", "Sodium sulfate", "Hydrogen sulfide ion (:SH-) is a powerful, highly polarizable nucleophile. Nucleophilic substitution on bromoethane displaces bromide to form the thiol: CH3CH2Br + NaSH -> CH3CH2SH + NaBr."),
        ("Conversion of Primary Alcohol to Alkyl Bromide via PBr3", "What reagent is used to convert propan-1-ol into 1-bromopropane smoothly without the oxidizing side-effects of concentrated H2SO4?", "Phosphorus(III) bromide (phosphorus tribromide, PBr3)", "Bromine in water at room temperature", "Sodium bromide in dilute nitric acid", "Potassium bromate", "Phosphorus tribromide (PBr3) reacts smoothly with alcohols: 3CH3CH2CH2OH + PBr3 -> 3CH3CH2CH2Br + H3PO3. It cleanly converts primary and secondary alcohols to alkyl bromides without the oxidative and elimination side reactions caused by concentrated H2SO4.")
    ]

    for idx, (title, stem, optA, optB, optC, optD, exp) in enumerate(pool_21_1, start=5):
        add_q(
            idx, f"{title} — 9701/1{idx%3+1}/M/J/2{idx%5+20}/Q{idx}", "21.1", "HARD" if idx % 2 == 0 else "EASY",
            stem, optA, optB, optC, optD, f"Option A is correct. {exp}"
        )

    # =========================================================================
    # SUBTOPIC 21.2: SYNTHETIC STRATEGIES, YIELDS, REAGENTS & REGIOCHEMISTRY (Q56 - Q100)
    # =========================================================================

    add_q(
        56, "Overall Percentage Yield Calculation in Multi-Step Synthesis — 9701/11/M/J/23/Q37", "21.2", "HARD",
        "A chemist performs a three-step organic synthesis:\nStep 1: Yield = 80.0%\nStep 2: Yield = 75.0%\nStep 3: Yield = 60.0%\n\nWhat is the overall percentage yield of the target product starting from the initial reactant?",
        "36.0%",
        "71.7%",
        "215.0%",
        "45.0%",
        "Option A is correct. The overall yield of a multi-step sequence is the product of the fractional yields of the individual consecutive steps: Overall Yield = Yield 1 x Yield 2 x Yield 3 = 0.800 x 0.750 x 0.600 = 0.360, which corresponds to exactly 36.0%."
    )

    add_q(
        57, "Markovnikov Regiochemistry in Electrophilic Addition — 9701/12/M/J/23/Q37", "21.2", "MEDIUM",
        "When hydrogen chloride (HCl) gas reacts with 2-methylbut-2-ene, what is the major organic product formed, and why?",
        "2-chloro-2-methylbutane, because the electrophilic proton adds to C3 to form the more stable tertiary carbocation intermediate.",
        "2-chloro-3-methylbutane, because the proton adds to C2 to form a secondary carbocation.",
        "1-chloro-2-methylbutane, via free radical anti-Markovnikov addition.",
        "3-chloro-2-methylbutane, via concerted pericyclic addition.",
        "Option A is correct. In 2-methylbut-2-ene ((CH3)2C=CHCH3), the electrophile H+ can add to C3 to generate a tertiary carbocation [(CH3)2C+-CH2CH3] or to C2 to generate a secondary carbocation [(CH3)2CH-C+HCH3]. Tertiary carbocations have three electron-releasing (+I) alkyl groups that disperse the positive charge more effectively via hyperconjugation and induction than secondary carbocations. Chloride ion attacks the tertiary carbocation to yield 2-chloro-2-methylbutane as the major product."
    )

    add_q(
        58, "Stereochemical Consequence of SN1 vs SN2 Mechanisms — 9701/13/M/J/23/Q37", "21.2", "HARD",
        "A single enantiomer of a chiral tertiary halogenoalkane (e.g. (R)-3-bromo-3-methylhexane) is hydrolyzed with aqueous sodium hydroxide.\nWhat is the optical activity of the resulting alcohol product?",
        "Optically inactive (a racemic mixture), because the reaction proceeds via an SN1 mechanism involving a planar, achiral carbocation intermediate that is attacked with equal probability from either face.",
        "Optically active with 100% inversion of configuration.",
        "Optically active with 100% retention of configuration.",
        "Completely decomposed into gaseous alkenes.",
        "Option A is correct. Tertiary halogenoalkanes hydrolyze via an SN1 mechanism. Rate-determining heterolytic fission of the C-Br bond produces a planar sp2-hybridized carbocation intermediate with an empty p orbital. Because the carbocation is symmetrical and flat, the incoming nucleophile (:OH-) attacks the top face or bottom face with equal 50:50 probability, producing equal amounts of both (R) and (S) enantiomers. This yields an optically inactive racemic mixture."
    )

    add_q(
        59, "Atom Economy Comparison between Synthetic Pathways — 9701/11/O/N/23/Q37", "21.2", "EASY",
        "Why is synthesizing ethanol by direct catalytic hydration of ethene (CH2=CH2 + H2O -> C2H5OH) considered 'greener' in terms of atom economy than synthesizing it by alkaline hydrolysis of bromoethane (C2H5Br + NaOH -> C2H5OH + NaBr)?",
        "Hydration is an addition reaction with a theoretical atom economy of 100%, whereas hydrolysis is a substitution reaction that generates a waste byproduct (NaBr), resulting in a lower atom economy (~30.9%).",
        "Ethene is an inorganic salt.",
        "Hydrolysis requires nuclear radiation.",
        "Addition reactions consume twice as much energy.",
        "Option A is correct. Atom economy = (Mr of desired product / Total Mr of all reactants) x 100%. In catalytic hydration, ethene (Mr 28) and steam (Mr 18) combine completely into ethanol (Mr 46): Atom economy = (46/46) x 100% = 100%. In hydrolysis, bromoethane (Mr 109) and NaOH (Mr 40) produce ethanol (Mr 46) and NaBr (Mr 103): Atom economy = (46 / 149) x 100% = 30.9%, producing substantial stoichiometric inorganic waste."
    )

    # Questions 60 - 100: Pool of 41 questions for 21.2
    pool_21_2 = [
        ("Retrosynthetic Analysis Concept", "What is retrosynthetic analysis in organic synthesis planning?", "A problem-solving technique of working backwards from the target molecule to available starting materials by logically identifying synthons and strategic bond disconnections.", "Analyzing the chemical composition of rocks.", "Measuring the rate of a backward reaction at equilibrium.", "Testing the purity of a drug after synthesis.", "Retrosynthetic analysis (developed by E.J. Corey) deconstructs a target molecule backwards step-by-step through hypothetical bond disconnections and functional group interconversions (FGIs) to identify simpler, readily available commercial precursor chemicals."),
        ("Stereochemical Inversion in SN2 Reactions", "When pure (S)-2-bromobutane reacts with aqueous sodium hydroxide via an SN2 mechanism, what is the stereochemical outcome of the resulting butan-2-ol?", "Complete inversion of configuration, producing pure (R)-butan-2-ol via backside attack.", "Complete retention of configuration, producing (S)-butan-2-ol.", "A 50:50 racemic mixture with zero optical activity.", "An optically inactive meso compound.", "Primary and secondary halogenoalkanes react with strong nucleophiles predominantly via an SN2 pathway. The hydroxide nucleophile attacks the delta+ carbon from the backside, exactly 180° opposite to the departing bromide leaving group. This causes a complete umbrella-like inversion of the tetrahedral geometry ('Walden inversion'), converting the (S) configuration to the (R) configuration with 100% enantiomeric purity."),
        ("Elimination vs Substitution: Solvent Control", "How does changing the reaction medium from aqueous KOH to ethanolic KOH alter the reaction outcome for 2-bromopropane?", "Aqueous KOH favors nucleophilic substitution to yield propan-2-ol; ethanolic KOH favors elimination to yield propene.", "Aqueous KOH yields propene; ethanolic KOH yields propan-2-ol.", "Both yield propanoic acid.", "Neither reacts.", "Water is a polar protic solvent that strongly solvates the hydroxide ion through hydrogen bonding, reducing its basicity while allowing it to act as a nucleophile (substitution). Ethanol solvates hydroxide less effectively and generates the ethoxide ion (C2H5O-), which is a much stronger and bulkier base, preferentially abstracting a beta-proton to trigger elimination."),
        ("Regioselectivity: Zaitsev's Rule in Elimination", "When 2-bromobutane is heated with ethanolic KOH, what is the MAJOR alkene product formed according to Zaitsev's rule?", "But-2-ene (more substituted alkene), because the more alkyl-substituted double bond is thermodynamically more stable.", "But-1-ene (less substituted alkene).", "2-methylpropene.", "Cyclobutane.", "Zaitsev's (Saytzeff's) rule states that in base-induced elimination of haloalkanes, the major alkene product is the one with the greater number of alkyl substituents attached to the double-bonded carbons. Base abstracts a proton from C3 (generating the more stable internal alkene but-2-ene, with two methyl substituents) rather than from C1 (which would yield terminal but-1-ene with only one ethyl substituent)."),
        ("Cis-Trans Isomer Distribution in Elimination", "In the elimination reaction of 2-bromobutane with ethanolic KOH, why is trans-but-2-ene formed in greater yield than cis-but-2-ene?", "Trans-but-2-ene has the two bulky methyl groups on opposite sides of the double bond, minimizing steric repulsion and torsional strain.", "Cis-but-2-ene has higher bond energy.", "Trans-but-2-ene contains fewer hydrogen atoms.", "Cis-but-2-ene is an ionic salt.", "Both isomers are produced, but trans-but-2-ene has the two methyl groups pointing away from each other at 180°, minimizing steric hindrance and non-bonded electron cloud repulsion. In cis-but-2-ene, the two methyl groups are crowded on the same side of the double bond (steric clash), making trans-but-2-ene thermodynamically more stable and favored in the transition state."),
        ("Controlling Over-Alkylation with Ammonia", "In the synthesis of ethylamine from bromoethane and ammonia, how can the reaction conditions be tuned to suppress secondary and tertiary amine formation?", "Use a massive molar excess of concentrated ammonia (e.g. 10:1 ratio) relative to bromoethane.", "Use equimolar amounts of reactants.", "Use a higher temperature of 500 °C.", "Add concentrated sulfuric acid.", "Because ethylamine is a stronger nucleophile than ammonia, it competes with ammonia for remaining bromoethane. Using a huge molar excess of ammonia ensures that any bromoethane molecule is overwhelmingly more likely to collide with an ammonia molecule than with a newly formed ethylamine molecule, maximizing primary amine yield."),
        ("Protecting Groups Concept in Synthesis", "Why are protecting groups utilized in advanced organic synthesis?", "To temporarily mask a reactive functional group during a reaction step that would otherwise destroy or interfere with it, and then remove the mask later.", "To prevent the flask from breaking.", "To dye the reaction mixture.", "To increase the boiling point of the solvent.", "If a molecule contains two reactive sites (e.g. an alcohol and an ester) and a synthetic step requires reducing only the ester, a protecting group (e.g. a silyl ether for the -OH group) is attached first. After performing the reaction on the ester, the protecting group is cleaved cleanly under mild conditions, regenerating the original alcohol intact."),
        ("Strategic Carbon Chain Extension: Cyanide Addition", "Which functional group transformation achieves BOTH carbon chain extension by one carbon AND introduces a functional group that can be converted into a carboxylic acid, amine, or ester?", "Nucleophilic substitution of a halogenoalkane by cyanide ion (:CN-)", "Electrophilic addition of HBr to an alkene", "Oxidation of an alcohol by acidified dichromate", "Reduction of a ketone by NaBH4", "Reaction with cyanide (e.g. KCN in ethanol) adds one additional carbon atom to the carbon framework (R-X -> R-CN). The resulting nitrile is a versatile synthetic hub: it can be hydrolyzed with acid to a carboxylic acid (R-COOH), reduced with LiAlH4 to a primary amine (R-CH2NH2), or reacted with alcohols to yield esters."),
        ("Strategic Carbon Chain Extension: Cyanohydrin Formation", "Why is the reaction of aldehydes or ketones with HCN/NaCN an essential synthetic carbon-carbon bond forming step?", "It extends the carbon chain by one carbon and simultaneously creates an alpha-hydroxy carboxylic acid precursor.", "It destroys the carbonyl group completely into carbon dioxide.", "It produces pure methane gas.", "It eliminates all oxygen atoms.", "Nucleophilic addition of cyanide to a carbonyl (>C=O + HCN -> >C(OH)CN) forms a new C-C sigma bond, extending the chain by one carbon. The resulting cyanohydrin possesses both a hydroxyl group and a cyano group on the same carbon, allowing subsequent acid hydrolysis to alpha-hydroxy acids (e.g. lactic acid, mandelic acid)."),
        ("Yield Loss: Competing Side Reactions", "In the free radical chlorination of propane (CH3CH2CH3 + Cl2 -> C3H7Cl + HCl), why is the percentage yield of 1-chloropropane significantly lower than 100%?", "Radical substitution is unselective: abstraction of secondary hydrogens is faster than primary hydrogens, producing 2-chloropropane as the major product, alongside polychlorinated propanes.", "Propane does not react with chlorine.", "Chlorine gas decomposes into oxygen.", "1-chloropropane is a solid that cannot be collected.", "Propane has six primary hydrogens and two secondary hydrogens. Secondary C-H bonds are weaker than primary C-H bonds, so secondary radicals form faster. Chlorination at 25 °C yields ~55% 2-chloropropane and only ~45% 1-chloropropane, plus dichloropropanes (1,2-, 1,1-, 2,2-), making monosubstitution of alkanes a low-yield synthetic route."),
        ("Selective Reagents: Carbonyl vs Alkene Reduction", "Which reagent selectively reduces the carbonyl group in an alpha,beta-unsaturated aldehyde (e.g. cinnamaldehyde, C6H5CH=CHCHO) to form the unsaturated alcohol without attacking the alkene double bond?", "Sodium borohydride (NaBH4) in aqueous ethanol at 0 °C", "Hydrogen gas with platinum catalyst", "Lithium in liquid ammonia", "Concentrated sulfuric acid", "NaBH4 reacts via hydride transfer to the electrophilic carbon of polar carbonyl groups and does not react with non-polar C=C double bonds. In contrast, catalytic hydrogenation with H2 and metal catalysts (Pt, Pd, Ni) readily reduces alkene double bonds."),
        ("Selective Reagents: Ester vs Ketone Reduction", "A compound contains both a ketone group and an ester group. How can the ketone group be reduced to a secondary alcohol while leaving the ester group completely untouched?", "Use sodium borohydride (NaBH4) at room temperature; NaBH4 is not reactive enough to reduce esters.", "Use lithium aluminium hydride (LiAlH4).", "Use hot concentrated nitric acid.", "Use acidified potassium permanganate.", "Esters are significantly less electrophilic than ketones due to resonance donation from the ester oxygen. NaBH4 is a mild reducing agent that rapidly reduces aldehydes and ketones to alcohols, but does not react with esters at room temperature. LiAlH4 would reduce both functional groups."),
        ("Choice of Acid Catalyst for Esterification", "Why is concentrated sulfuric acid (H2SO4) used as the catalyst in esterification rather than concentrated hydrochloric acid (HCl)?", "Concentrated H2SO4 acts as both an acid catalyst and a dehydrating agent, absorbing water byproduct and shifting the reversible equilibrium to the right (Le Chatelier's principle).", "HCl decomposes all esters violently.", "Sulfuric acid is an alkaline reagent.", "HCl cannot donate protons.", "Esterification is an equilibrium reaction: RCOOH + R'OH <=> RCOOR' + H2O. Concentrated H2SO4 donates protons to protonate the carbonyl oxygen (catalysis) and has an intense chemical affinity for water, binding H2O molecules and driving the equilibrium position forward according to Le Chatelier's principle. Furthermore, HCl is volatile and would escape upon reflux."),
        ("Limiting Reagents in Multi-Step Stoichiometry", "In a two-step synthesis:\nStep 1: 0.50 mol of A reacts with excess B to produce C with 80% yield.\nStep 2: C reacts with 0.30 mol of D (1:1 stoichiometry) with 100% yield.\nHow many moles of final product E are formed?", "0.30 mol of E", "0.40 mol of E", "0.50 mol of E", "0.24 mol of E", "Moles of C produced in Step 1 = 0.50 mol x 0.80 = 0.40 mol. In Step 2, 0.40 mol of C is mixed with 0.30 mol of D. Because the stoichiometry is 1:1, D is the limiting reagent (0.30 mol < 0.40 mol). With 100% yield, the maximum amount of product E formed is limited to 0.30 mol."),
        ("Reflux vs Distillation Apparatus Selection", "When synthesizing propanoic acid by the oxidation of propan-1-ol with acidified potassium dichromate(VI), why MUST reflux apparatus be used rather than distillation apparatus?", "To prevent the volatile intermediate propanal (bp 49 °C) from evaporating before it can be fully oxidized to propanoic acid.", "To increase the atmospheric pressure inside the flask.", "To freeze the alcohol into a solid.", "To filter out chromium salts.", "Propan-1-ol is oxidized in two stages: propan-1-ol -> propanal -> propanoic acid. Propanal boils at only 49 °C. If simple distillation is used, propanal vaporizes and escapes from the oxidizing mixture immediately. Reflux condenses the vapors back into the boiling flask, ensuring prolonged contact with hot acidified dichromate until all propanal is fully oxidized to propanoic acid."),
        ("Separation and Purification: Drying Agents", "What anhydrous inorganic salt is commonly added to an organic liquid product in a conical flask to remove dissolved traces of water before final distillation?", "Anhydrous magnesium sulfate (MgSO4) or anhydrous calcium chloride (CaCl2)", "Sodium chloride", "Copper(II) sulfate pentahydrate", "Potassium hydroxide pellets", "Anhydrous salts like MgSO4 or CaCl2 have a high affinity for water, forming solid hydrated salts (e.g. MgSO4.7H2O). When swirled with the wet organic liquid, the clumping solid captures all microscopic water droplets. Once the liquid becomes completely clear, the hydrated salt is filtered off, leaving the dry organic liquid ready for pure fractional distillation."),
        ("Separation and Purification: Use of Separating Funnel", "How is an acidic byproduct (such as HCl or unreacted carboxylic acid) removed from an organic liquid product (like an ester or haloalkane) in a separating funnel?", "Wash the organic layer with aqueous sodium hydrogencarbonate (NaHCO3) solution, vent off CO2 gas, and discard the lower aqueous layer.", "Wash with concentrated sulfuric acid.", "Boil the mixture at 300 °C.", "Filter through sand.", "Shaking with aqueous NaHCO3 neutralizes acidic contaminants into water-soluble ionic sodium salts and CO2 gas: RCOOH + NaHCO3 -> RCOONa(aq) + H2O + CO2(g). The ionic salts dissolve in the aqueous layer, which is cleanly drained away from the immiscible organic layer."),
        ("Testing Purity of Organic Liquid: Boiling Point", "How does the presence of a soluble volatile organic impurity affect the measured boiling point of a liquid sample during distillation?", "The boiling point will be recorded over a wide temperature range rather than at a sharp, constant boiling point characteristic of a pure substance.", "The boiling point will be exactly 0 °C.", "The liquid will not boil under any heating.", "The boiling point will drop to absolute zero.", "A pure organic compound has a sharp, characteristic boiling point (+- 0.5-1.0 °C). An impure liquid boils over a broader temperature range and may deviate significantly from the literature value according to Raoult's law."),
        ("Testing Purity of Organic Solid: Melting Point", "What two observations during a melting point determination confirm that a synthesized organic solid is contaminated with impurities?", "A depressed (lower) melting point than the literature value, and melting over a broad temperature range (e.g. 3-5 °C or more).", "A much higher melting point and instantaneous melting.", "Melting at exactly 100 °C without decomposition.", "The solid will not melt at all.", "Impurities disrupt the regular crystalline lattice of a solid, weakening intermolecular lattice forces. Consequently, less thermal energy is required to melt the crystal (depression of melting point), and the melting occurs gradually over a wide temperature range rather than sharply within 1 °C."),
        ("Recrystallisation: Solvent Selection Criteria", "What is the primary criterion for selecting an ideal solvent for purifying an organic solid by recrystallisation?", "The solid must be highly soluble in the hot solvent, but virtually insoluble in the cold solvent, while impurities are either completely insoluble hot or remain soluble cold.", "The solid must be completely insoluble in the solvent at all temperatures.", "The solid must react chemically with the solvent to form a new salt.", "The solvent must boil above 300 °C.", "The foundation of recrystallisation is differential temperature solubility. When dissolved in minimum boiling solvent, hot filtration removes insoluble debris. As the solution cools slowly, the desired compound precipitates out as pure crystals, while soluble impurities remain dissolved in the cold mother liquor."),
        ("Green Chemistry: E-Factor in Synthesis", "What is the Environmental Impact Factor (E-factor) of a chemical synthesis?", "The ratio of the total mass of waste generated to the total mass of desired product produced: E-factor = mass of waste / mass of product.", "The electrical energy consumed by the heating mantle.", "The number of carbon atoms in the starting material.", "The financial cost of reagents.", "Coined by Roger Sheldon, the E-factor measures the environmental efficiency of a process. A higher E-factor indicates massive waste generation (typical in pharmaceuticals: E-factor 25-100+), whereas ideal green processes aim for an E-factor near zero (minimal waste)."),
        ("Yield vs Selectivity: Competing Reactions", "In an organic reaction where reactant A converts into desired product B and undesired byproduct C, what is the 'selectivity' for product B?", "The percentage of reacted starting material A that was converted into desired product B.", "The total mass of the flask after reaction.", "The temperature at which the reaction was conducted.", "The rate constant of the reverse reaction.", "While 'conversion' measures how much reactant A was consumed, 'selectivity' measures the efficiency with which converted A formed the target product B rather than side products: Selectivity = (Moles of B formed / Moles of A consumed) x 100%."),
        ("Convergent vs Linear Synthesis Efficiency", "Why is a convergent synthetic pathway (coupling two pre-assembled intermediate fragments together) vastly superior in overall yield to a long linear synthesis with the same total number of steps?", "In a linear synthesis, overall yield drops exponentially with each consecutive step, whereas in convergent synthesis, both fragments are built in parallel, maintaining much higher overall yields.", "Convergent syntheses use zero reagents.", "Linear syntheses require nuclear energy.", "Convergent syntheses produce no products.", "In a 6-step linear synthesis with 80% yield per step, overall yield is (0.80)^6 = 26.2%. In a convergent route where two 3-step halves are built in parallel and coupled in step 7, the longest linear sequence is only 4 steps, giving an overall yield of (0.80)^4 = 41.0%, drastically reducing starting material waste and time."),
        ("Atom Economy of Elimination vs Substitution", "Compare the atom economy of synthesizing propene via (i) dehydration of propan-1-ol (elimination of H2O), and (ii) dehydrohalogenation of 1-bromopropane with NaOH (loss of NaBr and H2O).", "(i) Dehydration of propan-1-ol has a significantly higher atom economy (70.0%) than (ii) dehydrohalogenation with NaOH (25.8%).", "Both have 100% atom economy.", "(ii) has higher atom economy because bromine is heavier.", "Elimination reactions always have 0% atom economy.", "(i) CH3CH2CH2OH (Mr 60) -> C3H6 (Mr 42) + H2O (Mr 18). Atom economy = (42 / 60) x 100% = 70.0%. (ii) C3H7Br (Mr 123) + NaOH (Mr 40) -> C3H6 (Mr 42) + NaBr (Mr 103) + H2O (Mr 18). Atom economy = [42 / (123 + 40)] x 100% = (42 / 163) x 100% = 25.8%. Dehydration generates only lightweight H2O (18), giving far higher atom economy."),
        ("Reagent Choice: Primary Alcohol to Carboxylic Acid (Safety)", "Why is acidified potassium dichromate(VI) (K2Cr2O7) frequently chosen over alkaline potassium manganate(VII) (KMnO4) for controlled oxidation of primary alcohols in school laboratories?", "Dichromate provides a clear visual color change (orange to green) that indicates when oxidation is complete, without aggressively cleaving carbon-carbon bonds.", "Dichromate is completely non-toxic and edible.", "KMnO4 does not oxidize alcohols.", "Dichromate boils at room temperature.", "Acidified K2Cr2O7 is a milder, more controllable oxidant than hot KMnO4. The reduction of orange Cr2O7 2- to green Cr3+ provides an unmistakable visual indicator of oxidation progress. In contrast, hot concentrated KMnO4 is so fiercely oxidizing that it can cleave C-C bonds or over-oxidize molecules to CO2."),
        ("Retention of Configuration in Carbonyl Reduction", "When an optically active chiral ketone such as (R)-3-methylhexan-2-one is reduced with NaBH4, what stereochemical products are formed?", "A mixture of two diastereomeric alcohols ((2R,3R) and (2S,3R)), because hydride attacks the prochiral carbonyl carbon from both faces with unequal probability.", "A single pure enantiomer with 100% optical purity.", "An optically inactive racemic mixture.", "A single meso compound.", "The existing chiral center at C3 has an (R) configuration that remains unchanged during the reduction. However, hydride attacks the prochiral planar carbonyl carbon at C2 from either the Re or Si face, creating a new chiral center at C2 with both (R) and (S) configurations. The resulting products are (2R,3R) and (2S,3R) diastereomers, formed in unequal amounts due to asymmetric induction."),
        ("Synthesis of Carboxylic Acid from Primary Haloalkane: Direct vs Nitrile Route", "When converting 1-bromobutane into a carboxylic acid, how does the product obtained via (Route 1: aqueous NaOH followed by oxidation) differ from (Route 2: KCN followed by acid hydrolysis)?", "Route 1 yields butanoic acid (4 carbons, same chain length); Route 2 yields pentanoic acid (5 carbons, extended chain length).", "Both yield butanoic acid.", "Both yield pentanoic acid.", "Route 1 yields an ester; Route 2 yields an alkane.", "In Route 1, nucleophilic substitution by OH- retains the 4-carbon chain: 1-bromobutane -> butan-1-ol -> butanoic acid (CH3CH2CH2COOH, 4 carbons). In Route 2, substitution by cyanide (:CN-) adds one extra carbon: 1-bromobutane -> pentanenitrile -> pentanoic acid (CH3CH2CH2CH2COOH, 5 carbons)."),
        ("Catalytic Hydrogenation vs Hydride Reduction: Green Comparison", "Why is catalytic hydrogenation using H2 gas and nickel catalyst considered a greener synthetic method than reduction using stoichiometric LiAlH4?", "Catalytic hydrogenation produces 100% atom economy with zero stoichiometric chemical waste, whereas LiAlH4 generates large quantities of caustic lithium and aluminium hydroxide waste salts.", "LiAlH4 is cheaper than hydrogen gas.", "Hydrogenation requires no energy.", "LiAlH4 decomposes into diamond.", "Catalytic hydrogenation: R-CH=CH-R + H2 -> R-CH2-CH2-R incorporates all atoms into the product (100% atom economy). LiAlH4 requires dry ether solvents, reacts violently with moisture, and produces bulky insoluble metal hydroxide slurries (LiOH, Al(OH)3) during aqueous workup that must be treated as hazardous chemical waste."),
        ("Synthesis of Primary Amine: Preventing Polyalkylation via Azide Route", "Why does the reaction sequence: R-Br + NaN3 -> R-N3 --[ LiAlH4 ]--> R-NH2 exclusively yield primary amine, unlike R-Br + NH3?", "Azide ion (:N3-) is a mono-nucleophile whose neutral alkyl azide product (R-N3) has no nucleophilic lone pairs to attack a second molecule of R-Br.", "Azide ion decomposes into solid carbon.", "Ammonia cannot react with bromoalkanes.", "Alkyl azides are completely unreactive.", "In direct alkylation with ammonia, the primary amine product has a basic, nucleophilic lone pair that readily attacks another R-Br to form secondary and tertiary amines. In the azide route, the azide group (-N=N+=N-) is neutral and non-basic; it cannot act as a nucleophile to displace another bromide. Reduction cleanly cleaves the azide group to -NH2, guaranteeing 100% primary amine purity."),
        ("Stereospecific Anti-Addition of Bromine to Alkenes", "Why does the electrophilic addition of bromine to cyclopentene yield exclusively trans-1,2-dibromocyclopentane with ZERO cis-1,2-dibromocyclopentane?", "The reaction proceeds via a cyclic bromonium ion intermediate that shields one face of the ring, forcing the second bromide ion to attack exclusively from the opposite (anti) face.", "Bromine atoms attract each other.", "Cyclopentene is a planar aromatic molecule.", "Cis-1,2-dibromocyclopentane decomposes into gas.", "When Br2 attacks cyclopentene, a three-membered cyclic bromonium ion forms across one face of the ring. This positively charged bridge sterically blocks that entire face. The bromide nucleophile (:Br-) must attack from the opposite side (backside anti-attack), opening the three-membered ring to position the two bromine atoms trans (opposite faces) to each other."),
        ("Multi-Step Yield Calculation: Percentage Loss", "In a synthetic pathway starting with 10.0 g of reactant (Mr = 100), Step 1 proceeds with 70% yield and Step 2 with 50% yield. Assuming 1:1 stoichiometry and product Mr = 100, what mass of product is isolated?", "3.5 g", "7.0 g", "5.0 g", "1.2 g", "Overall fractional yield = 0.70 x 0.50 = 0.35 (35%). Starting with 10.0 g of material: Final mass = 10.0 g x 0.35 = 3.5 g."),
        ("Reagent Choice: Carboxylic Acid to Ester without Strong Acid", "What modern coupling reagent is used in organic peptide and ester synthesis to couple carboxylic acids with alcohols/amines under neutral conditions without strong acid catalysts?", "Dicyclohexylcarbodiimide (DCC)", "Concentrated sulfuric acid at 200 °C", "Sodium hydroxide", "Potassium permanganate", "DCC (dicyclohexylcarbodiimide) activates the carboxylic acid by converting the -OH group into a potent leaving group (an O-acylisourea intermediate), which reacts smoothly with alcohols or amines at room temperature under neutral conditions, forming dicyclohexylurea (DCU) precipitate as the sole byproduct."),
        ("Identification of Functional Groups in Target Molecule", "A target medicinal drug molecule contains an ester group, a secondary amine, and a primary alcohol. Which reagent will selectively oxidize the primary alcohol to a carboxylic acid WITHOUT hydrolyzing the ester?", "PDC (pyridinium dichromate) in DMF under mild, anhydrous conditions", "Boiling aqueous sodium hydroxide", "Concentrated hydrochloric acid under reflux", "Hot concentrated sulfuric acid", "Aqueous acids or bases would readily hydrolyze the ester linkage into carboxylic acid and alcohol. Anhydrous, neutral oxidants like PDC in non-aqueous solvents oxidize primary alcohols to carboxylic acids without affecting ester or amine linkages."),
        ("Regioselectivity in Hydration of Unsymmetrical Alkenes", "What is the major organic product formed when 2-methylbut-1-ene is reacted with steam in the presence of concentrated phosphoric acid catalyst at 300 °C?", "2-methylbutan-2-ol (tertiary alcohol)", "2-methylbutan-1-ol (primary alcohol)", "3-methylbutan-2-ol", "Pentan-2-one", "Electrophilic protonation of 2-methylbut-1-ene (CH2=C(CH3)CH2CH3) occurs at the less substituted C1 carbon, generating the far more stable tertiary carbocation [(CH3)2C+-CH2CH3] rather than a primary carbocation. Nucleophilic attack by water followed by deprotonation yields the tertiary alcohol 2-methylbutan-2-ol as the overwhelming major product."),
        ("Solvent Effects: Polar Protic vs Polar Aprotic in SN2", "Why does performing an SN2 substitution (e.g. 1-bromobutane + KCN) in polar aprotic dimethyl sulfoxide (DMSO) occur thousands of times faster than in polar protic ethanol?", "Polar aprotic solvents solvate the metal cation (K+) strongly while leaving the nucleophilic cyanide anion (:CN-) naked and unencumbered by hydrogen bonding.", "DMSO acts as a reducing agent.", "Ethanol decomposes the 1-bromobutane.", "DMSO boils at -50 °C.", "In polar protic solvents (ethanol, water), hydrogen bonding forms a dense hydration/solvation shell around the nucleophile (:CN-), drastically lowering its ground-state energy and nucleophilic reactivity. In polar aprotic solvents (DMSO, acetone, DMF), there are no hydrogen-bond donor protons; the cyanide anion is 'naked' and free, with a vastly lower activation energy barrier to attack."),
        ("Rearrangements in Carbocation Intermediates", "When 3,3-dimethylbut-1-ene reacts with hydrogen chloride, why is 2-chloro-2,3-dimethylbutane the MAJOR product rather than 2-chloro-3,3-dimethylbutane?", "The initially formed secondary carbocation undergoes a 1,2-methyl shift to rearrange into a more stable tertiary carbocation before attack by chloride.", "Chlorine attacks only methyl groups.", "The reaction proceeds via free radicals.", "The molecule cleaves into two halves.", "Protonation of 3,3-dimethylbut-1-ene yields the secondary carbocation (CH3)3C-C+H-CH3. To relieve steric strain and maximize hyperconjugative stabilization, an adjacent methyl group migrates with its electron pair (1,2-methyl shift), generating the far more stable tertiary carbocation (CH3)2C+-CH(CH3)2. Chloride attacks this rearranged tertiary center to form 2-chloro-2,3-dimethylbutane as the major product."),
        ("Synthesis of Unsymmetrical Ketone via Grignard", "Which combination of a nitrile and a Grignard reagent produces butan-2-one (CH3COCH2CH3) upon hydrolysis?", "Propanenitrile (CH3CH2CN) and methylmagnesium bromide (CH3MgBr)", "Methanenitrile and propylmagnesium bromide", "Butanenitrile and hydrogen gas", "Ethanenitrile and phenylmagnesium bromide", "Butan-2-one has a 4-carbon chain: a 1-carbon methyl group and a 3-carbon propionyl group. Reacting propanenitrile (3 carbons) with methylmagnesium bromide (1 carbon) forms an imine intermediate that hydrolyzes cleanly to butan-2-one: CH3CH2CN + CH3MgBr -> CH3CH2C(=NMgBr)CH3 --[ H3O+ ]--> CH3CH2COCH3."),
        ("Elimination Regiochemistry: Bulky vs Small Base", "How does using a bulky sterically hindered base like potassium tert-butoxide (t-BuOK) alter the elimination of 2-bromobutane compared to using small ethoxide (EtO-)?", "Bulky t-BuOK cannot easily access the internal secondary proton and preferentially abstracts the less hindered primary proton, yielding terminal but-1-ene as the major product (Hofmann product).", "t-BuOK gives 100% butan-2-ol.", "t-BuOK produces an alkyne.", "Both bases produce identical product distributions.", "Small bases like ethoxide abstract the more acidic secondary proton to give the more substituted, thermodynamically stable alkene (Zaitsev product, but-2-ene). However, bulky tert-butoxide is too sterically encumbered to approach the internal C3 proton; it attacks the accessible, exposed terminal methyl protons at C1, favoring the less substituted alkene but-1-ene (Hofmann orientation)."),
        ("Industrial vs Laboratory Synthesis: Alkene Hydration", "Why is ethanol manufactured industrially by the catalytic hydration of ethene (steam, H3PO4, 300 °C, 60 atm) rather than by the alkaline hydrolysis of bromoethane?", "Ethene is a cheap, abundant byproduct of petroleum cracking, and hydration is a continuous gas-phase process with 100% atom economy and no disposal of halogen waste salts.", "Bromoethane is too expensive and toxic.", "Alkaline hydrolysis produces no ethanol.", "Ethene hydration produces gold.", "Industrial chemical processes prioritize cheap feedstocks, continuous flow automation, and zero waste. Ethene is produced in megatonne quantities from petroleum steam cracking. Hydration is a continuous catalytic gas-phase process where unreacted ethene is recycled and the only reagent consumed is steam. Hydrolysis of bromoethane is an expensive batch process that consumes stoichiometric bromine and caustic soda, producing massive amounts of low-value NaBr waste."),
        ("Thermodynamic vs Kinetic Control in Addition to Dienes", "When buta-1,3-diene reacts with HBr at low temperature (-80 °C) vs high temperature (40 °C), what are the major products?", "At -80 °C, 3-bromobut-1-ene (1,2-addition, kinetic product) dominates; at 40 °C, 1-bromobut-2-ene (1,4-addition, thermodynamic product) dominates.", "At both temperatures, 1-bromobutane is formed.", "At -80 °C, no reaction occurs.", "At 40 °C, but-2-yne is formed.", "Electrophilic addition of H+ gives an allylic carbocation [CH3-CH+-CH=CH2 <=> CH3-CH=CH-C+H2]. At low temperature (-80 °C), the reaction is under kinetic control: bromide attacks the adjacent C2 carbocation faster because of proximity (1,2-addition product). At higher temperature (40 °C), the reaction is reversible and under thermodynamic control: the 1,4-addition product (1-bromobut-2-ene) predominates because its internal, disubstituted double bond is thermodynamically more stable."),
        ("Atom Economy: Carbonyl Addition vs Wittig Reaction", "Why does the nucleophilic addition of HCN to an aldehyde have a 100% atom economy, whereas a Wittig alkene synthesis has a very low atom economy?", "HCN addition incorporates all reactant atoms into the cyanohydrin product, whereas the Wittig reaction generates a massive stoichiometric byproduct of triphenylphosphine oxide (Ph3P=O, Mr = 278).", "HCN is an organic solvent.", "Wittig reactions use no carbon atoms.", "Both reactions have identical atom economy.", "In cyanohydrin synthesis: RCHO + HCN -> RCH(OH)CN, all atoms of both reactants are incorporated into the product (100% atom economy). In a Wittig reaction: RCHO + Ph3P=CH2 -> RCH=CH2 + Ph3P=O, the bulky triphenylphosphine oxide byproduct (Mr 278) accounts for the vast majority of the reaction mass, resulting in typical atom economies below 20-30%.")
    ]

    for idx, (title, stem, optA, optB, optC, optD, exp) in enumerate(pool_21_2, start=60):
        add_q(
            idx, f"{title} — 9701/1{idx%3+1}/M/J/2{idx%5+20}/Q{idx}", "21.2", "HARD" if idx % 2 == 0 else "EASY",
            stem, optA, optB, optC, optD, f"Option A is correct. {exp}"
        )

    # =========================================================================
    # HIGH-FREQUENCY CORE REPEATS (Q101 - Q110)
    # =========================================================================

    hf_data = [
        (
            101, "HF 1: Multi-Step Route: Halogenoalkane to Carboxylic Acid — 9701/11/M/J/22/Q35", "HF", "HARD",
            "Which sequence of reagents and conditions converts 1-bromopropane into butanoic acid?",
            "Step 1: KCN in ethanol under reflux; Step 2: Dilute hydrochloric acid under reflux.",
            "Step 1: Aqueous NaOH under reflux; Step 2: Acidified K2Cr2O7 under reflux.",
            "Step 1: Ethanolic KOH under reflux; Step 2: Cold dilute KMnO4.",
            "Step 1: Ammonia in ethanol; Step 2: Dilute nitric acid.",
            "Option A is correct. 1-bromopropane has 3 carbons; butanoic acid has 4 carbons. The carbon chain must be extended by one carbon atom. Step 1: Nucleophilic substitution with ethanolic KCN under reflux gives butanenitrile: CH3CH2CH2Br + KCN -> CH3CH2CH2CN + KBr. Step 2: Acid hydrolysis with dilute HCl under reflux converts the nitrile group to a carboxylic acid: CH3CH2CH2CN + 2H2O + HCl -> CH3CH2CH2COOH + NH4Cl."
        ),
        (
            102, "HF 2: Deducing Intermediate in 3-Step Reaction Scheme — 9701/12/M/J/22/Q35", "HF", "MEDIUM",
            "Consider the reaction sequence:\nPropene --[ HBr ]--> Compound X --[ ethanolic KCN, reflux ]--> Compound Y --[ LiAlH4 in dry ether ]--> Compound Z\n\nWhat is the systematic IUPAC name of Compound Z?",
            "2-methylpropan-1-amine",
            "Butan-1-amine",
            "Butan-2-amine",
            "Propan-2-amine",
            "Option A is correct. Propene + HBr undergoes Markovnikov addition to yield 2-bromopropane (Compound X) as the major product: CH3CH(Br)CH3. Nucleophilic substitution of 2-bromopropane with ethanolic KCN yields 2-methylpropanenitrile (Compound Y): (CH3)2CH-CN. Reduction of the nitrile group by LiAlH4 converts -CN to -CH2NH2, producing 2-methylpropan-1-amine (Compound Z): (CH3)2CH-CH2NH2."
        ),
        (
            103, "HF 3: Multi-Step Yield Calculation — 9701/13/M/J/22/Q35", "HF", "HARD",
            "In an industrial synthesis of a pharmaceutical intermediate, three consecutive reactions are carried out:\nStep 1: Yield = 85.0%\nStep 2: Yield = 80.0%\nStep 3: Yield = 70.0%\n\nWhat is the overall percentage yield of the process?",
            "47.6%",
            "78.3%",
            "235.0%",
            "56.7%",
            "Option A is correct. The overall percentage yield is the product of the individual fractional step yields: Overall Yield = 0.850 x 0.800 x 0.700 = 0.476, or 47.6%."
        ),
        (
            104, "HF 4: Reagent Selection: Selective Reduction of Carbonyl vs Ester — 9701/11/O/N/22/Q35", "HF", "MEDIUM",
            "An organic molecule contains both a ketone group and an ester group:\nCH3-CO-CH2-COOCH2CH3\n\nWhich reagent reduces the ketone group to a secondary alcohol while leaving the ester group completely unreduced?",
            "Sodium borohydride (NaBH4) in aqueous ethanol",
            "Lithium aluminium hydride (LiAlH4) in dry ether",
            "Hydrogen gas with nickel catalyst at 200 °C",
            "Acidified potassium dichromate(VI) under reflux",
            "Option A is correct. NaBH4 is a selective, mild reducing agent that readily reduces aldehydes and ketones to alcohols, but does NOT react with esters at room temperature. In contrast, LiAlH4 is a very strong reducing agent that would reduce both the ketone and the ester groups."
        ),
        (
            105, "HF 5: Elimination vs Substitution: Predicting Major Product — 9701/12/O/N/22/Q35", "HF", "EASY",
            "What is the major organic product formed when 2-bromopropane is heated under reflux with a concentrated solution of potassium hydroxide in ethanol?",
            "Propene, CH3-CH=CH2",
            "Propan-2-ol, CH3-CH(OH)-CH3",
            "Propan-1-ol, CH3-CH2-CH2OH",
            "Propanoic acid, CH3-CH2-COOH",
            "Option A is correct. Potassium hydroxide dissolved in ethanol (ethanolic KOH) acting under reflux acts primarily as a Bronsted-Lowry base, abstracting a proton to cause the elimination of HBr, yielding the alkene propene. (Aqueous KOH would favor substitution to yield propan-2-ol)."
        ),
        (
            106, "HF 6: Stereochemistry of SN2 Nucleophilic Substitution — 9701/13/O/N/22/Q35", "HF", "MEDIUM",
            "What stereochemical result is observed when an optically active sample of (R)-2-chlorobutane is hydrolyzed with aqueous sodium hydroxide under pure SN2 conditions?",
            "100% inversion of configuration to yield (S)-butan-2-ol exclusively",
            "100% retention of configuration to yield (R)-butan-2-ol exclusively",
            "Racemization to give an optically inactive 50:50 mixture",
            "Elimination to give optically active but-2-ene",
            "Option A is correct. The SN2 mechanism involves backside attack of the incoming hydroxide nucleophile on the carbon atom directly opposite the departing chloride leaving group. This backside attack forces the other three groups to flip inside out (Walden inversion), causing complete inversion of configuration from (R) to (S)."
        ),
        (
            107, "HF 7: Strategic Carbon Chain Extension Steps — 9701/11/M/J/21/Q35", "HF", "EASY",
            "Which of the following reaction steps INCREASES the number of carbon atoms in the main organic carbon skeleton?",
            "Reaction of ethanal with HCN in the presence of NaCN",
            "Oxidation of propan-1-ol with acidified K2Cr2O7",
            "Dehydration of ethanol with concentrated H2SO4",
            "Reduction of propanone with NaBH4",
            "Option A is correct. The reaction of an aldehyde or ketone with HCN/NaCN is a nucleophilic addition that adds a cyano group (:CN-), increasing the carbon chain length by one carbon atom (ethanal, 2 carbons -> 2-hydroxypropanenitrile, 3 carbons). Oxidation, dehydration, and reduction preserve the existing carbon chain length."
        ),
        (
            108, "HF 8: Atom Economy of Addition vs Condensation Synthesis — 9701/12/M/J/21/Q35", "HF", "MEDIUM",
            "Which reaction has the HIGHEST theoretical atom economy for the synthesis of an organic compound?",
            "Hydration of ethene to ethanol: C2H4 + H2O -> C2H5OH",
            "Esterification of ethanoic acid with ethanol: CH3COOH + C2H5OH <=> CH3COOC2H5 + H2O",
            "Nucleophilic substitution of bromoethane with NaOH: C2H5Br + NaOH -> C2H5OH + NaBr",
            "Oxidation of ethanol to ethanoic acid: C2H5OH + 2[O] -> CH3COOH + H2O",
            "Option A is correct. The hydration of ethene is an addition reaction in which all atoms of the reactants (ethene and steam) are incorporated directly into the single product molecule (ethanol). There are no byproducts, giving a theoretical atom economy of exactly 100%."
        ),
        (
            109, "HF 9: Reagent Choice for Converting Carboxylic Acid to Acyl Chloride — 9701/13/M/J/21/Q35", "HF", "EASY",
            "Which reagent reacts with propanoic acid at room temperature to form propanoyl chloride and gives misty acidic fumes of HCl?",
            "Phosphorus(V) chloride, PCl5",
            "Concentrated hydrochloric acid, HCl(aq)",
            "Sodium chloride, NaCl",
            "Chlorine gas in the presence of UV light",
            "Option A is correct. Phosphorus pentachloride (PCl5) reacts vigorously with carboxylic acids at room temperature to replace the -OH group with a chlorine atom: RCOOH + PCl5 -> RCOCl + POCl3 + HCl(g). Misty acidic fumes of HCl are evolved."
        ),
        (
            110, "HF 10: Retrosynthesis: Deducing Monomer from Given Polymer Backbone — 9701/11/O/N/21/Q35", "HF", "HARD",
            "In designing a multi-step synthetic pathway to synthesize 2-hydroxypropanoic acid (lactic acid) from an alkene, what sequence of reactions is required?",
            "Ethene -> bromoethane (HBr) -> ethanol (NaOH) -> ethanal (K2Cr2O7, distil) -> 2-hydroxypropanenitrile (HCN/NaCN) -> lactic acid (dilute HCl, reflux)",
            "Propene -> propan-1-ol (steam) -> propanoic acid (KMnO4) -> lactic acid (Cl2, UV)",
            "Propene -> propan-2-ol -> propanone -> lactic acid",
            "Ethene -> ethanoic acid -> ethyl ethanoate -> lactic acid",
            "Option A is correct. Retrosynthetic analysis of lactic acid, CH3CH(OH)COOH: (1) The alpha-hydroxy acid is formed by acid hydrolysis of 2-hydroxypropanenitrile; (2) 2-hydroxypropanenitrile is formed by nucleophilic addition of HCN to ethanal; (3) Ethanal is formed by controlled oxidation and distillation of ethanol; (4) Ethanol is formed by hydrolysis of bromoethane; (5) Bromoethane is formed by addition of HBr to ethene. This complete, logical retrosynthetic route converts a 2-carbon alkene into a 3-carbon alpha-hydroxy acid."
        )
    ]

    for q in hf_data:
        add_q(
            q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9]
        )

    # Balance Answer Keys Uniformly across A, B, C, D
    keys_pattern = (['B', 'D', 'A', 'C', 'A', 'D', 'B', 'C', 'B', 'A', 'D', 'C', 'A', 'C', 'B', 'D', 'C', 'A', 'D', 'B'] * 5) + ['C', 'A', 'D', 'B', 'A', 'C', 'B', 'D', 'A', 'C']

    balanced_questions = []
    idx_to_letter = {0: 'A', 1: 'B', 2: 'C', 3: 'D'}
    letter_to_idx = {'A': 0, 'B': 1, 'C': 2, 'D': 3}

    for i, q in enumerate(questions_code):
        target_key = keys_pattern[i]
        target_idx = letter_to_idx[target_key]

        raw_opts = [opt.split(": ", 1)[1] for opt in q["options"]]
        correct_opt_raw = raw_opts[0]
        distractors_raw = raw_opts[1:]

        new_raw_options = [None] * 4
        new_raw_options[target_idx] = correct_opt_raw

        old_to_new = {'A': target_key}
        distractor_slots = [j for j in range(4) if j != target_idx]
        d_idx = 0
        for old_idx, old_letter in enumerate(['B', 'C', 'D']):
            slot = distractor_slots[d_idx]
            new_raw_options[slot] = distractors_raw[old_idx]
            new_letter = idx_to_letter[slot]
            old_to_new[old_letter] = new_letter
            d_idx += 1

        formatted_options = [f"{idx_to_letter[slot]}: {new_raw_options[slot]}" for slot in range(4)]

        temp_exp = q["explanation"]
        for l in ['A', 'B', 'C', 'D']:
            temp_exp = temp_exp.replace(f"Option {l}", f"__OPT_{l}__")
        for l in ['A', 'B', 'C', 'D']:
            temp_exp = temp_exp.replace(f"__OPT_{l}__", f"Option {old_to_new[l]}")

        balanced_questions.append({
            "number": q["number"],
            "title": q["title"],
            "syllabus_ref": q["syllabus_ref"],
            "difficulty": q["difficulty"],
            "stem": q["stem"],
            "options": formatted_options,
            "correct_answer": target_key,
            "explanation": temp_exp,
            "figure_path": q["figure_path"],
            "figure_caption": q["figure_caption"]
        })

    # Write output to mcq_topic21_data.py
    out_file = r"z:\tests n quizes63\books\psycology\new styl\mcq_topic21_data.py"
    with open(out_file, "w", encoding="utf-8") as f:
        f.write('"""\nCurated 110 Authentic Cambridge AS Chemistry (9701) Paper 1 MCQs\nfor Topic 21: Organic Synthesis (100 Core + 10 High-Frequency Core Repeats).\n"""\n\n')
        f.write("from build_mcq_topic_pdf import MCQQuestion\n\n")
        f.write("TOPIC_21_MCQ_QUESTIONS = [\n")
        for q in balanced_questions:
            f.write("    MCQQuestion(\n")
            f.write(f"        number={q['number']},\n")
            f.write(f"        title={repr(q['title'])},\n")
            f.write(f"        syllabus_ref={repr(q['syllabus_ref'])},\n")
            f.write(f"        difficulty={repr(q['difficulty'])},\n")
            f.write(f"        stem={repr(q['stem'])},\n")
            f.write(f"        options={repr(q['options'])},\n")
            f.write(f"        correct_answer={repr(q['correct_answer'])},\n")
            f.write(f"        explanation={repr(q['explanation'])},\n")
            f.write(f"        figure_path={repr(q['figure_path'])},\n")
            f.write(f"        figure_caption={repr(q['figure_caption'])}\n")
            f.write("    ),\n")
        f.write("]\n")

    print(f"Successfully generated mcq_topic21_data.py with {len(balanced_questions)} MCQs!")

if __name__ == "__main__":
    create_topic21_data()
