"""
Script to generate Topic 20: Polymerisation (Addition Polymers)
Exactly 110 authentic Cambridge AS Chemistry (9701) Paper 1 MCQs.
Subtopic 20.1: Addition Polymerisation: Monomers, Repeat Units & Properties (Q1 - Q55)
Subtopic 20.2: Disposal, Recycling & Environmental Impact of Polyalkenes (Q56 - Q100)
High-Frequency Core Repeats: Q101 - Q110
"""

def create_topic20_data():
    questions_code = []

    def add_q(num, title, sref, diff, stem, optA, optB, optC, optD, exp, fig=None, cap=None):
        q_dict = {
            "number": num,
            "title": title,
            "syllabus_ref": sref,
            "difficulty": diff,
            "stem": stem,
            "options": [f"A: {optA}", f"B: {optB}", f"C: {optC}", f"D: {optD}"],
            "correct_answer": "A",
            "explanation": exp,
            "figure_path": fig,
            "figure_caption": cap
        }
        questions_code.append(q_dict)

    # =========================================================================
    # SUBTOPIC 20.1: ADDITION POLYMERISATION — MONOMERS, REPEAT UNITS & PROPERTIES (Q1 - Q55)
    # =========================================================================

    add_q(
        1, "Deducing Monomer from Addition Polymer Backbone — 9701/11/M/J/23/Q34", "20.1", "HARD",
        "A section of an addition polymer chain is shown below:\n\n-[-CH2-CH(CH3)-CH2-CH(CH3)-CH2-CH(CH3)-]-\n\nWhat is the systematic IUPAC name and structure of the monomer used to synthesize this polymer?",
        "Propene, CH2=CH-CH3",
        "Ethene, CH2=CH2",
        "But-2-ene, CH3-CH=CH-CH3",
        "2-methylpropene, CH2=C(CH3)2",
        "Option A is correct. To deduce the monomer of an addition polymer, identify the repeating two-carbon backbone segment: -[-CH2-CH(CH3)-]-. Replacing the two open single bonds on the backbone carbons with a C=C double bond yields CH2=CH-CH3, which is propene. Addition polymerisation proceeds by breaking the pi bond in propene to form long chains of poly(propene)."
    )

    add_q(
        2, "Atom Economy of Addition Polymerisation — 9701/12/M/J/23/Q34", "20.1", "EASY",
        "Why does the industrial manufacture of poly(ethene) from ethene have a theoretical atom economy of 100%?",
        "All the atoms present in the reactant monomer molecules are incorporated directly into the final polymer chain without the formation of any byproducts.",
        "The reaction uses a 100% efficient platinum catalyst.",
        "Ethene has a very low molecular mass.",
        "The reaction produces water vapor as a non-toxic byproduct.",
        "Option A is correct. In addition polymerisation, monomer molecules join together via the breaking of pi bonds to form new sigma bonds with no elimination of small molecules. Because the polymer is the sole product of the reaction, all reactant atoms are converted into product, giving a theoretical atom economy of exactly 100%."
    )

    add_q(
        3, "Deducing Repeat Unit from Monomer Structure — 9701/13/M/J/23/Q34", "20.1", "MEDIUM",
        "What is the correct structure of the repeat unit of poly(phenylethene) (polystyrene), synthesized from phenylethene (styrene, C6H5CH=CH2)?",
        "-[-CH2-CH(C6H5)-]-",
        "-[-CH(C6H5)-CH(C6H5)-]-",
        "-[-CH2-CH2-C6H4-]-",
        "-[-C(C6H5)=CH-]-",
        "Option A is correct. In phenylethene (C6H5CH=CH2), the alkene double bond is between CH2 and CH(C6H5). During polymerisation, the pi bond breaks, leaving two free valencies on these two carbon atoms to form the continuous polymer backbone: -[-CH2-CH(C6H5)-]-. The phenyl ring (C6H5) remains as a pendant side group."
    )

    add_q(
        4, "Low-Density vs High-Density Poly(ethene) (LDPE vs HDPE) — 9701/11/O/N/23/Q34", "20.1", "MEDIUM",
        "High-density poly(ethene) (HDPE) has a higher melting point, greater rigidity, and higher tensile strength than low-density poly(ethene) (LDPE).\n\nWhat structural difference explains these properties?",
        "HDPE has essentially unbranched linear polymer chains that pack closely and regularly together, maximizing intermolecular London dispersion forces, whereas LDPE has extensive branching that prevents close packing.",
        "HDPE contains polar covalent bonds between carbon and hydrogen.",
        "HDPE has covalent cross-links between adjacent polymer chains.",
        "LDPE has a much higher average molecular mass than HDPE.",
        "Option A is correct. HDPE is synthesized using Ziegler-Natta or metallocene catalysts at low pressure, producing linear, unbranched chains. These straight chains pack closely and regularly into crystalline domains, maximizing London dispersion forces between adjacent chains. In contrast, LDPE (made at high pressure via free radicals) possesses extensive chain branching; the branches prevent close packing, creating lower density, weaker intermolecular attractions, lower melting point, and greater flexibility."
    )

    # Questions 5 - 55: Pool of 51 questions for 20.1
    pool_20_1 = [
        ("Monomer of PTFE (Teflon)", "What monomer is polymerised to produce poly(tetrafluoroethene) (PTFE / Teflon), -[-CF2-CF2-]-n?", "Tetrafluoroethene, CF2=CF2", "1,1-difluoroethene, CH2=CF2", "Trifluoroethene, CHF=CF2", "Fluoromethane, CH3F", "PTFE has the repeat unit -[-CF2-CF2-]-. Combining the two backbone carbons with a double bond gives tetrafluoroethene, CF2=CF2. PTFE possesses exceptional thermal stability, non-stick properties, and chemical inertness due to the extreme strength and low polarizability of the C-F bonds."),
        ("Monomer of PVC (Polyvinyl Chloride)", "What is the systematic IUPAC name of the monomer used to manufacture poly(chloroethene) (PVC)?", "Chloroethene, CH2=CHCl", "1,2-dichloroethene", "1,1-dichloroethene", "Chloromethane", "Poly(chloroethene) (PVC) has the repeat unit -[-CH2-CH(Cl)-]-. The monomer is chloroethene (commonly known as vinyl chloride), CH2=CHCl, produced industrially by the chlorination of ethene followed by thermal cracking of 1,2-dichloroethane."),
        ("Deducing Monomer from 4-Carbon Polymer Segment", "A segment of an addition polymer is:\n-[-CH2-CH(CH3)-CH2-CH(CH3)-]-\nHow many monomer molecules reacted to form this specific four-carbon backbone segment?", "Two propene molecules", "One but-2-ene molecule", "Four ethene molecules", "Three methane molecules", "The repeat unit is -[-CH2-CH(CH3)-]-, which contains two backbone carbons and originates from one molecule of propene (C3H6). A segment with four backbone carbons containing two repeat units is formed from two propene molecules."),
        ("Role of Free Radical Initiators in Addition Polymerisation", "Why is a small quantity of an organic peroxide (such as benzoyl peroxide) added to ethene in the free radical synthesis of LDPE?", "The peroxide decomposes thermally to generate free radicals that initiate the polymer chain reaction by attacking the alkene pi bond.", "The peroxide acts as a reducing agent.", "The peroxide neutralizes acidic impurities.", "The peroxide dissolves the ethene gas.", "Peroxides possess a weak O-O single bond that undergoes homolytic fission upon gentle heating to produce free radical species (R*). These reactive radicals attack the pi bond of ethene, generating a carbon radical (R-CH2-CH2*) that adds consecutively to further ethene molecules in chain propagation."),
        ("Addition Polymerisation of Buta-1,3-diene", "When buta-1,3-diene (CH2=CH-CH=CH2) undergoes 1,4-addition polymerisation, what is the structure of the repeat unit in the resulting synthetic rubber?", "-[-CH2-CH=CH-CH2-]-", "-[-CH2-CH2-CH2-CH2-]-", "-[-CH(CH=CH2)-CH2-]-", "-[-CH=CH-CH=CH-]-", "In 1,4-addition of conjugated dienes, the terminal carbons (C1 and C4) form sigma bonds to adjacent repeat units, while the two pi bonds shift to form a new C=C double bond between C2 and C3: -[-CH2-CH=CH-CH2-]- (polybutadiene). The residual double bond can exist in cis or trans configurations."),
        ("Intermolecular Forces in PVC", "Why is unplasticized poly(chloroethene) (uPVC) significantly more rigid and hard than poly(ethene)?", "The polar C-Cl bonds create permanent dipole-dipole attractions between adjacent polymer chains in addition to London dispersion forces.", "PVC contains ionic crosslinks.", "PVC contains intermolecular hydrogen bonding.", "Chlorine atoms form covalent bonds between chains.", "In poly(chloroethene), the electronegative chlorine atom induces a permanent dipole (C delta+ - Cl delta-). Adjacent chains experience permanent dipole-dipole attractions in addition to London dispersion forces. These stronger intermolecular forces hold the chains rigidly in place, making uPVC ideal for window frames and water pipes."),
        ("Function of Plasticizers in PVC", "Why are phthalate esters (plasticizers) added to rigid poly(chloroethene) (PVC) in the manufacture of flexible products like artificial leather and garden hoses?", "Plasticizer molecules slot between polymer chains, pushing them apart and weakening intermolecular attractions, allowing chains to slide past each other smoothly.", "Plasticizers react chemically with chlorine to form alkenes.", "Plasticizers form strong covalent bridges between chains.", "Plasticizers double the molecular weight of the polymer.", "Plasticizers are small, non-volatile organic molecules (e.g. dioctyl phthalate) that dissolve into the polymer matrix. By occupying space between PVC chains, they increase intermolecular distances, diminishing dipole-dipole attractions and lowering the glass transition temperature, transforming rigid uPVC into a supple, flexible elastomer."),
        ("Deducing Monomer from Perspex / PMMA", "The repeat unit of poly(methyl 2-methylpropenoate) (PMMA / Perspex / Lucite) is:\n-[-CH2-C(CH3)(COOCH3)-]-\nWhat is the structure of the monomer?", "CH2=C(CH3)COOCH3 (methyl methacrylate)", "CH3-CH=CH-COOCH3", "CH2=CH-COOCH3", "CH3-C(CH3)=CH-COOH", "Re-establishing the double bond between the two backbone carbons gives CH2=C(CH3)COOCH3 (methyl 2-methylpropenoate / methyl methacrylate). PMMA is an addition polymer prized for its optical clarity, lightweight shatter resistance, and weatherability."),
        ("Poly(propenenitrile) (Orlon / Acrylic)", "The repeat unit of acrylic fiber (Orlon) is -[-CH2-CH(CN)-]-. What is the monomer?", "Propenenitrile (acrylonitrile), CH2=CH-C#N", "Ethanenitrile, CH3CN", "Butenenitrile, CH3CH=CHCN", "Methanamide, HCONH2", "The two backbone carbons -CH2- and -CH(CN)- correspond to propenenitrile (acrylonitrile), CH2=CH-CN. Polymerisation across the alkene double bond yields poly(propenenitrile), widely spun into synthetic wool-like fibers."),
        ("Addition Polymerisation of Cycloalkenes", "When cyclohexene undergoes addition polymerisation, what is the structure of the repeat unit?", "-[-CH(CH2)4CH-]- (cyclohexane-1,2-diyl)", "A 6-carbon linear alkane chain.", "A benzene ring.", "A 12-carbon macrocycle.", "Cyclohexene contains a C=C double bond within a 6-membered ring. Opening the pi bond allows C1 and C2 of the ring to form single bonds with adjacent cyclohexyl rings, forming a polymer chain consisting of connected cyclohexane rings: -[-CH(CH2)4CH-]-."),
        ("Tacticity: Isotactic vs Atactic Poly(propene)", "Why does isotactic poly(propene) (all methyl groups on the same side of the chain) have a higher melting point and higher crystallinity than atactic poly(propene) (random methyl orientation)?", "The regular spatial stereochemistry of isotactic chains allows close, efficient molecular packing into crystalline regions, maximizing London dispersion forces.", "Isotactic poly(propene) forms hydrogen bonds.", "Atactic poly(propene) contains ionic bonds.", "Isotactic chains contain double bonds.", "Isotactic poly(propene) possesses complete stereoregularity: all -CH3 side groups point in the same direction along the backbone. This regularity enables the polymer chains to coil into tight helices that pack closely into crystal lattices, raising the melting point to ~165 °C, compared to amorphous, rubbery atactic poly(propene) (mp ~0 °C)."),
        ("Ziegler-Natta Catalysis", "What catalytic system revolutionized the commercial synthesis of linear HDPE and isotactic poly(propene) at mild temperatures and low pressures?", "A coordination catalyst mixture of titanium(IV) chloride (TiCl4) and triethylaluminium (Al(C2H5)3)", "Acidified potassium dichromate", "Finely divided iron and iron oxide", "Concentrated sulfuric acid and nickel", "Ziegler-Natta catalysts (TiCl4 + Al(C2H5)3) coordinate alkene monomers at titanium active centers, guiding their insertion stereospecifically into the growing polymer chain at moderate temperatures and pressures (1-5 atm), avoiding the high-pressure radical branching of LDPE."),
        ("Copolymerisation: Styrene-Butadiene Rubber (SBR)", "What is a copolymer, such as styrene-butadiene rubber (SBR)?", "A polymer formed by the addition polymerisation of two or more DIFFERENT monomer species together in the same reaction mixture.", "A polymer mixed with sand.", "A blend of two separate pre-formed polymers.", "A polymer containing only carbon and oxygen atoms.", "A copolymer is synthesized by polymerising a mixture of two distinct monomers. In SBR (the main synthetic rubber in automobile tires), phenylethene (styrene) and buta-1,3-diene copolymerise to give a material combining the toughness of polystyrene with the elasticity of polybutadiene."),
        ("Degree of Polymerisation and Molecular Mass", "A sample of poly(ethene) has an average relative molecular mass (Mr) of 140,000.\nWhat is the average degree of polymerisation (number of ethene repeat units, n)?", "5,000", "10,000", "2,500", "28,000", "The relative formula mass of an ethene repeat unit (-CH2-CH2-) is (2 x 12.0) + (4 x 1.0) = 28.0. The degree of polymerisation n = Total Mr / Repeat unit Mr = 140,000 / 28.0 = 5,000 repeat units."),
        ("Chain Termination Mechanisms in Radical Polymerisation", "In free radical addition polymerisation, how can two growing polymer chains terminate their growth simultaneously?", "By radical coupling (combination of two chain-end radicals into a single covalent bond) or by disproportionation (hydrogen abstraction forming an alkane end and an alkene end).", "By evaporation of monomer.", "By precipitation in water.", "By reaction with nitrogen gas.", "Two active polymer radicals (P1* and P2*) can terminate by: (1) Combination: P1* + P2* -> P1-P2, forming a single chain with combined length; (2) Disproportionation: one radical transfers a beta-hydrogen atom to the other, generating one saturated chain end and one unsaturated alkene chain end: P1-CH2-CH2* + P2-CH2-CH2* -> P1-CH2-CH3 + P2-CH=CH2."),
        ("Chain Transfer and Branching in LDPE", "What mechanism causes extensive chain branching during the high-pressure radical polymerisation of ethene to produce LDPE?", "Intramolecular or intermolecular chain transfer, where the terminal radical abstracts a hydrogen atom from within its own chain (backbiting) or another chain.", "Addition of water molecules.", "Reaction with metal vessel walls.", "Electrophilic aromatic substitution.", "In high-pressure synthesis of LDPE (1000-3000 atm, 200 °C), the active terminal radical can curl back and abstract a hydrogen atom from a CH2 group 4-5 carbons back along its own backbone (intramolecular chain transfer / 'backbiting'). Propagation then proceeds from this internal secondary carbon, creating butyl or ethyl branches that prevent close chain packing."),
        ("Thermal Stability of PTFE", "Why does poly(tetrafluoroethene) (PTFE) have an extraordinarily high thermal decomposition temperature (>350 °C) and extreme chemical inertness?", "The C-F bond is one of the strongest single bonds in organic chemistry (bond energy ~485 kJ mol^-1), and the fluorine atoms form a dense protective sheath shielding the carbon backbone.", "PTFE is an ionic network solid.", "PTFE contains extensive triple bonds.", "PTFE has weak van der Waals forces that absorb heat.", "The C-F single bond has an exceptionally high bond dissociation enthalpy (485 kJ/mol) due to high polarity and excellent 2p-2p orbital overlap. Furthermore, the larger fluorine atoms completely encase the carbon backbone in a non-reactive, non-polar fluorocarbon sheath that repels both nucleophiles and electrophiles."),
        ("Optical Properties of Polystyrene", "Why is pure poly(phenylethene) (polystyrene) transparent and glass-like at room temperature?", "It is an atactic, completely amorphous polymer with bulky phenyl rings that prevent crystallization, avoiding light-scattering crystal boundaries.", "It has a molecular mass below 100.", "It contains water molecules in its lattice.", "It is an ionic crystal like quartz.", "Standard commercial polystyrene is atactic: the bulky phenyl rings are distributed randomly along both sides of the carbon backbone. This steric disorder prevents the chains from packing into crystalline lattices. Being 100% amorphous with no crystalline boundaries to scatter light, it is optically crystal-clear (used in CD jewel cases, Petri dishes)."),
        ("Expanded Polystyrene (EPS)", "How is expanded polystyrene (EPS / Styrofoam) manufactured to have an extremely low density (~98% air)?", "Polystyrene beads containing a low-boiling hydrocarbon blowing agent (pentane) are heated with steam, causing the pentane to vaporize and expand the softened polymer into closed-cell foam.", "Polystyrene is dissolved in liquid nitrogen.", "Polystyrene is whipped with egg whites.", "Air is pumped through molten polystyrene at 1000 atm.", "Polystyrene pellets are impregnated with ~5% pentane (bp 36 °C). When exposed to steam at ~100 °C, the polystyrene softens above its glass transition temperature (100 °C) while pentane boils vigorously, expanding the beads by up to 40-50 times their original volume into lightweight, shock-absorbing closed-cell foam."),
        ("Cross-linking in Synthetic Rubbers: Vulcanisation", "Why does heating poly(cis-buta-1,3-diene) or natural rubber with sulfur (vulcanisation) dramatically increase its elasticity and prevent permanent deformation?", "Sulfur atoms form covalent disulfide cross-links (-S-S-) between adjacent polyalkene chains, preventing them from slipping irreversibly past one another under tension.", "Sulfur dissolves the polymer into a liquid.", "Sulfur oxidizes the polymer to carboxylic acids.", "Sulfur removes all hydrogen atoms.", "Unvulcanized rubber is sticky when warm and brittle when cold; under tension, unlinked chains slide past each other irreversibly (plastic deformation). During vulcanisation, sulfur reacts with allylic positions of residual double bonds to form covalent disulfide (-S-S-) bridges between chains. These crosslinks act as an elastic memory, pulling stretched chains back to their original configuration when stress is released."),
        ("Glass Transition Temperature (Tg) Concept", "What is the glass transition temperature (Tg) of an addition polymer?", "The temperature below which an amorphous polymer is hard, rigid, and brittle (glassy), and above which it becomes flexible, tough, and rubbery.", "The temperature at which the polymer boils.", "The temperature at which the polymer ignites in air.", "The temperature at which monomer begins to evaporate.", "The glass transition temperature (Tg) is a fundamental thermal property of amorphous polymer domains. Below Tg, polymer backbone segments lack thermal energy to rotate and chains are locked into a rigid, glassy state. Above Tg, thermal energy allows rotational freedom around C-C single bonds, giving long-range chain mobility and rubbery/flexible behavior."),
        ("Deducing Monomer of Poly(vinyl acetate) (PVA)", "What is the monomer of poly(ethenyl ethanoate) / poly(vinyl acetate) (PVA, common woodworking glue), repeat unit -[-CH2-CH(OCOCH3)-]-?", "Vinyl acetate (ethenyl ethanoate), CH2=CH-OCOCH3", "Ethyl ethanoate, CH3COOCH2CH3", "Ethanoic acid, CH3COOH", "Ethene and ethanoic acid mixture", "The repeat unit -[-CH2-CH(OCOCH3)-]- has two backbone carbons. Re-forming the double bond gives ethenyl ethanoate (vinyl acetate), CH2=CH-OCOCH3, synthesized from ethene, acetic acid, and oxygen over a palladium catalyst."),
        ("Poly(vinyl alcohol) Synthesis from PVA", "Why can poly(ethenyl alcohol) (PVA / poly(vinyl alcohol), a water-soluble polymer used in laundry pods) NOT be prepared directly from its corresponding monomer ethenol (vinyl alcohol)?", "Ethenol (CH2=CH-OH) is unstable and rapidly tautomerises into its constitutional keto isomer ethanal (acetaldehyde, CH3CHO).", "Ethenol is a toxic solid.", "Ethenol cannot dissolve in water.", "Ethenol explodes upon heating.", "Ethenol undergoes keto-enol tautomerism: the enol form (CH2=CH-OH) is thermodynamically unstable relative to the keto form (CH3CH=O) due to the much higher bond energy of C=O vs C=C. Because ethenol tautomerises instantaneously to ethanal, poly(vinyl alcohol) must instead be made indirectly by polymerising vinyl acetate to poly(vinyl acetate), followed by alkaline ester hydrolysis (saponification)."),
        ("Water Solubility of Poly(vinyl alcohol)", "Why is poly(ethenyl alcohol) (-[-CH2-CH(OH)-]-n) soluble in hot water, unlike poly(ethene)?", "Every second carbon on the polymer backbone carries an -OH group that forms extensive intermolecular hydrogen bonds with water molecules.", "It has a molecular mass under 50.", "It is an ionic salt of sodium.", "It hydrolyzes to ethene gas in water.", "Poly(ethenyl alcohol) contains a dense array of polar hydroxyl (-OH) groups along its carbon chain. These -OH groups act as both hydrogen bond donors and acceptors, forming favorable intermolecular hydrogen bonds with surrounding water molecules that overcome interchain hydrogen bonds, enabling full dissolution in hot water (used for dissolvable laundry detergent capsules and medical suture packaging)."),
        ("Identification of Addition vs Condensation Polymers", "How can an unknown polymer be identified as an addition polymer rather than a condensation polymer by examining its structural formula?", "Its continuous main polymer backbone consists exclusively of carbon atoms (all-carbon chain) with no oxygen or nitrogen atoms within the backbone chain.", "It contains ester linkages (-COO-) in the backbone.", "It contains amide linkages (-CONH-) in the backbone.", "It dissolves completely in acid.", "Addition polymers are formed by the union of alkene monomers across C=C bonds, resulting in a continuous backbone consisting solely of carbon-carbon (C-C) sigma bonds (all functional groups like -Cl, -CH3, -C6H5, -COOCH3 are pendant side groups). In contrast, condensation polymers (polyesters, polyamides) have heteroatoms (O, N) embedded directly in the repeating backbone chain."),
        ("Combustion of Addition Polymers: General Equation", "What are the stoichiometric products of complete combustion of pure poly(propene), -[-CH2-CH(CH3)-]-n, in excess oxygen?", "Carbon dioxide (CO2) and water vapor (H2O)", "Carbon monoxide and hydrogen", "Soot and methane", "Carbon dioxide and sulfur dioxide", "Poly(propene) is a pure polyalkene hydrocarbon with the empirical formula CH2. Complete combustion in excess oxygen yields carbon dioxide and water exclusively: -[-C3H6-]- + 4.5 O2 -> 3 CO2 + 3 H2O."),
        ("Elemental Analysis of Fluoropolymers", "A fluoropolymer synthesized by addition polymerisation contains 76.0% fluorine and 24.0% carbon by mass. What is the empirical formula and the identity of the polymer?", "CF2, poly(tetrafluoroethene) (PTFE)", "CF3, poly(hexafluoropropene)", "CHF, poly(vinyl fluoride)", "CH2F, fluoroethane", "Moles of C = 24.0 / 12.0 = 2.00; Moles of F = 76.0 / 19.0 = 4.00. Mole ratio C : F = 2.00 : 4.00 = 1 : 2. Empirical formula is CF2 (formula mass = 50.0). The repeat unit is -[-CF2-CF2-]- with monomer CF2=CF2 (tetrafluoroethene), confirming PTFE."),
        ("Reaction of Addition Polymers with Bromine Water", "Why does poly(ethene) NOT decolorize bromine water, whereas the monomer ethene rapidly decolorizes orange-brown bromine water?", "During polymerisation, all carbon-carbon pi bonds in ethene are broken to form saturated carbon-carbon single bonds (sigma bonds), leaving no C=C double bonds in the polymer.", "Poly(ethene) is a dark black solid that conceals the color.", "Bromine reacts only with gases.", "Poly(ethene) is an inorganic salt.", "Ethene is an unsaturated alkene; its electron-rich pi bond undergoes electrophilic addition with Br2, decolorizing bromine water. In poly(ethene), every monomer unit has been fully converted into saturated sp3 carbons linked by sigma bonds. Poly(ethene) contains no pi bonds and cannot undergo electrophilic addition, leaving bromine water orange."),
        ("Number of Chiral Centers in Atactic Poly(propene)", "Why does atactic poly(propene) contain pseudo-asymmetric carbon centers, and what is its stereochemical nature?", "Every tertiary carbon (-CH(CH3)-) in the backbone is bonded to four different groups (H, CH3, and two unequal polymer chain ends), and their random R/S configurations create a completely atactic, non-crystalline polymer.", "It contains no tetrahedral carbons.", "All carbons are planar sp2.", "It rotates plane-polarized light strongly.", "In poly(propene) -[-CH2-CH(CH3)-]-n, each -CH(CH3)- carbon is attached to: -H, -CH3, -[polymer chain left], and -[polymer chain right]. Because the chain segments to the left and right are of unequal lengths, each such carbon is a chiral center. In atactic poly(propene), these configurations are randomly distributed, resulting in internal compensation and zero net optical activity."),
        ("Thermosets vs Thermoplastics in Addition Polymers", "Why can thermoplastic addition polymers (like polyethene and polystyrene) be repeatedly melted and reshaped, whereas crosslinked polymers cannot?", "Thermoplastics consist of independent, linear or branched chains held together only by intermolecular forces that can be overcome by heat without breaking covalent bonds.", "Thermoplastics contain metallic bonds.", "Thermoplastics decompose into gases below room temperature.", "Thermoplastics are held together by permanent ionic bonds.", "In thermoplastics, polymer chains are held together solely by weak intermolecular forces (London dispersion forces, dipole-dipole attractions). Supplying thermal energy overcomes these intermolecular attractions, allowing the chains to slip past one another as a viscous liquid. Upon cooling, intermolecular forces re-establish without chemical degradation."),
        ("Synthesis of Poly(methyl methacrylate) (PMMA)", "What type of addition polymerisation is commonly used to produce sheets of Perspex (PMMA) from methyl methacrylate?", "Free radical bulk or cast polymerisation initiated by organic peroxides or AIBN at moderate temperatures.", "Condensation polymerisation with elimination of water.", "Electrophilic aromatic substitution with AlCl3.", "Hydrolysis with hot concentrated sodium hydroxide.", "Cast sheets of Perspex (PMMA) are manufactured by bulk polymerisation: liquid methyl methacrylate monomer mixed with an initiator (e.g. AIBN or benzoyl peroxide) is poured into glass-plate molds and gently heated in a water bath, polymerising into thick, scratch-resistant transparent acrylic sheets."),
        ("Deducing Monomer from Alternating Addition Polymer", "An addition polymer has the repeat unit:\n-[-CH2-CH(Cl)-CH2-CH(C6H5)-]-\nWhat two monomers copolymerised to form this material?", "Chloroethene (vinyl chloride) and phenylethene (styrene)", "Ethene and chlorobenzene", "Dichloroethene and benzene", "Propene and phenylamine", "The four-carbon backbone segment consists of two consecutive two-carbon units: -CH2-CH(Cl)- (from chloroethene, CH2=CHCl) and -CH2-CH(C6H5)- (from phenylethene, CH2=CH-C6H5). This is an alternating copolymer of vinyl chloride and styrene."),
        ("Molecular Weight Polydispersity in Addition Polymers", "Why do synthetic addition polymers not have a single, precise molecular formula or discrete relative molecular mass?", "Chain propagation and termination are stochastic radical processes, resulting in a statistical distribution of polymer chains of varying lengths (polydispersity).", "Polymers are impure mixtures of different chemical elements.", "The measuring instruments are inaccurate.", "Atoms undergo radioactive decay during polymerisation.", "Unlike biological proteins which are synthesized by precise ribosomal translation to exact molecular masses, synthetic addition polymerisation involves random statistical initiation, propagation, and termination events. The resulting product is a mixture of chains with varying degrees of polymerisation, characterized by a polydispersity index (PDI) and average molecular mass."),
        ("Effect of Branching on Polymer Melting Point", "Why does linear HDPE have a melting point of ~135 °C, whereas highly branched LDPE melts at ~105 °C?", "Linear chains pack more efficiently into tight crystal lattices, requiring higher thermal kinetic energy to overcome the maximized sum of intermolecular dispersion forces.", "Linear chains contain stronger C-C covalent bonds.", "Branched chains contain more oxygen atoms.", "LDPE has fewer hydrogen atoms.", "Melting requires overcoming the intermolecular forces holding chains in the crystalline lattice. In HDPE, the absence of side branches allows linear chains to align closely over long distances, maximizing contact surface area and London dispersion forces. In LDPE, branches force chains apart, drastically reducing contact area and lattice cohesion."),
        ("Deducing Monomer of Poly(vinylidene chloride) (Saran)", "The repeat unit of Saran plastic wrap is -[-CH2-CCl2-]-. What is the monomer?", "1,1-dichloroethene (vinylidene chloride), CH2=CCl2", "1,2-dichloroethene, CHCl=CHCl", "Chloroethene, CH2=CHCl", "Tetrachloroethene, CCl2=CCl2", "The two backbone carbons are -CH2- and -CCl2-. Placing a double bond between them yields 1,1-dichloroethene, CH2=CCl2 (vinylidene chloride). Saran copolymer films provide an extraordinary barrier to oxygen and water vapor due to tight chain packing."),
        ("Physical State of Addition Polymer Monomers", "What are the physical states at room temperature (20 °C) and 1 atm of the monomers ethene, propene, and chloroethene?", "All three are colorless gases.", "All three are viscous liquids.", "All three are crystalline solids.", "Ethene is a gas, but propene and chloroethene are liquids.", "Ethene (bp -103.7 °C), propene (bp -47.6 °C), and chloroethene (vinyl chloride, bp -13.4 °C) are all small, low-molecular-weight molecules with weak intermolecular forces; all three exist as gases at standard room temperature and pressure."),
        ("Infrared Spectrum of Poly(ethene)", "What are the main absorption bands observed in the infrared spectrum of pure poly(ethene)?", "Strong C-H stretching vibrations just below 3000 cm^-1 (2850-2960 cm^-1) and C-H bending at 1460 cm^-1 and 720 cm^-1, with NO bands above 3000 cm^-1 or in the 1600-1800 cm^-1 region.", "A broad O-H band at 3300 cm^-1.", "A sharp carbonyl peak at 1715 cm^-1.", "A sharp C=C peak at 1650 cm^-1.", "Poly(ethene) is a pure saturated alkane polymer. Its IR spectrum shows exclusively sp3 C-H stretches (2850-2960 cm^-1), -CH2- scissoring bend (1460-1470 cm^-1), and skeletal -CH2- rocking (720-730 cm^-1). The complete absence of C=C stretching (~1650 cm^-1) and alkene =C-H stretching (>3000 cm^-1) confirms that all double bonds were consumed during polymerisation."),
        ("Infrared Spectrum of Poly(acrylonitrile)", "Which absorption band in the infrared spectrum uniquely confirms that a polymer sample is poly(acrylonitrile)?", "A sharp, distinct nitrile stretch at 2220-2260 cm^-1", "A broad band at 3400 cm^-1", "An ester carbonyl peak at 1735 cm^-1", "A sharp peak at 700 cm^-1", "The nitrile group (-C#N) exhibits an intense, sharp absorption band in the 2220-2260 cm^-1 region. No other common addition polymer functional group absorbs in this distinctive region."),
        ("Infrared Spectrum of PMMA", "Which absorption band in the infrared spectrum confirms the presence of ester side groups in poly(methyl methacrylate) (PMMA)?", "A strong, sharp carbonyl (C=O) stretch at 1730-1740 cm^-1 and strong C-O stretches at 1150-1250 cm^-1", "A broad O-H peak at 2500-3300 cm^-1", "A nitrile peak at 2250 cm^-1", "A doublet at 3300-3500 cm^-1", "PMMA contains pendant ester groups (-COOCH3). Its IR spectrum features a prominent, sharp ester carbonyl stretch (C=O) at ~1735 cm^-1 and strong C-O single-bond stretching absorptions at 1150-1250 cm^-1."),
        ("Addition Polymer with Highest Melting Point", "Among poly(ethene), poly(propene), poly(chloroethene), and poly(tetrafluoroethene), which addition polymer has the HIGHEST melting point?", "Poly(tetrafluoroethene) (PTFE, mp ~327 °C)", "Poly(ethene) (HDPE, mp ~135 °C)", "Poly(propene) (mp ~165 °C)", "Poly(chloroethene) (uPVC, mp ~180 °C decomp.)", "PTFE has a remarkably high melting point of 327 °C. The compact, cylindrical symmetry of the fully fluorinated -[-CF2-CF2-]- chain allows near-perfect, rigid crystal packing with high crystalline melting enthalpy, far exceeding that of other commodity addition polymers."),
        ("Preparation of Monomer: Chloroethene", "How is the monomer chloroethene (vinyl chloride) produced industrially from ethene?", "By chlorination of ethene to form 1,2-dichloroethane, followed by thermal cracking (pyrolysis) at 500 °C: CH2Cl-CH2Cl -> CH2=CHCl + HCl.", "By reacting ethyne with water.", "By heating ethane with chlorine gas in sunlight.", "By direct reduction of trichloroethene with sodium.", "Industrial vinyl chloride production: (1) Ethene reacts with Cl2 via electrophilic addition to yield 1,2-dichloroethane (CH2Cl-CH2Cl); (2) High-temperature pyrolysis (cracking) at 500 °C eliminates one molecule of HCl, yielding chloroethene (CH2=CHCl). The liberated HCl is recycled in oxychlorination."),
        ("Identification of Monomer from Combustion Stoichiometry", "Complete combustion of 0.10 mol of an alkene monomer produces 17.6 g of CO2 and 7.2 g of H2O.\nWhat is the molecular formula of the monomer?", "C4H8", "C2H4", "C3H6", "C5H10", "Moles of CO2 = 17.6 / 44.0 = 0.40 mol -> 0.40 mol C / 0.10 mol monomer = 4 carbon atoms per molecule. Moles of H2O = 7.2 / 18.0 = 0.40 mol -> 0.40 x 2 = 0.80 mol H / 0.10 mol monomer = 8 hydrogen atoms per molecule. Molecular formula is C4H8 (e.g. but-1-ene or but-2-ene)."),
        ("Polymerisation of But-1-ene", "What is the correct structure of the repeat unit of poly(but-1-ene), synthesized from but-1-ene (CH2=CH-CH2-CH3)?", "-[-CH2-CH(CH2CH3)-]-", "-[-CH2-CH2-CH2-CH2-]-", "-[-CH(CH3)-CH(CH3)-]-", "-[-CH2-CH=CH-CH2-]-", "In but-1-ene, the double bond is between C1 and C2, with an ethyl group (-CH2CH3) on C2. Addition polymerisation breaks the pi bond to form a two-carbon repeating backbone with pendant ethyl groups: -[-CH2-CH(CH2CH3)-]-."),
        ("Polymerisation of But-2-ene", "What is the correct structure of the repeat unit of poly(but-2-ene), synthesized from but-2-ene (CH3-CH=CH-CH3)?", "-[-CH(CH3)-CH(CH3)-]-", "-[-CH2-CH(CH2CH3)-]-", "-[-CH2-CH2-CH2-CH2-]-", "-[-C(CH3)2-CH2-]-", "In but-2-ene, both double-bonded carbons carry a methyl group. Polymerisation breaks the central pi bond, yielding a repeat unit where each backbone carbon carries a methyl group: -[-CH(CH3)-CH(CH3)-]-."),
        ("Polymerisation of 2-Methylpropene (Polyisobutylene)", "What is the repeat unit of polyisobutylene (used in inner tubes of bicycle tires due to gas impermeability), made from 2-methylpropene (CH2=C(CH3)2)?", "-[-CH2-C(CH3)2-]-", "-[-CH(CH3)-CH(CH3)-]-", "-[-CH2-CH(CH2CH3)-]-", "-[-CH2-CH2-C(CH3)2-]-", "2-methylpropene has a CH2 group and a C(CH3)2 group connected by a double bond. Opening the double bond gives the repeat unit -[-CH2-C(CH3)2-]-. The dense packing of gem-dimethyl groups gives polyisobutylene exceptionally low permeability to air and gases."),
        ("Deducing Monomer of Poly(vinyl fluoride) (PVF)", "Poly(vinyl fluoride) (PVF / Tedlar), used as a protective backing on solar panels, has the repeat unit -[-CH2-CHF-]-. What is the monomer?", "Fluoroethene (vinyl fluoride), CH2=CHF", "1,2-difluoroethene, CHF=CHF", "1,1-difluoroethene, CH2=CF2", "Tetrafluoroethene, CF2=CF2", "Re-establishing the double bond between the two backbone carbons -CH2- and -CHF- gives fluoroethene (vinyl fluoride), CH2=CHF."),
        ("Mass of Monomer Required to Produce Polymer", "What mass of propene monomer is theoretically required to produce 84.0 kg of poly(propene)?", "84.0 kg", "42.0 kg", "168.0 kg", "28.0 kg", "Addition polymerisation has 100% atom economy with no byproducts: n C3H6 -> -[-C3H6-]-n. By the law of conservation of mass, the theoretical mass of monomer required is identical to the mass of polymer produced: 84.0 kg of propene produces 84.0 kg of poly(propene)."),
        ("Effect of Chlorine Atom on PVC Flammability", "Why is unplasticized poly(chloroethene) (uPVC) inherently flame-retardant compared to poly(ethene)?", "When heated, uPVC releases hydrogen chloride gas (HCl), which acts as a vapor-phase flame inhibitor by scavenging reactive free radicals and suffocating the flame.", "Chlorine atoms produce water vapor.", "PVC contains no carbon atoms.", "PVC absorbs all heat by nuclear fission.", "PVC is ~57% chlorine by mass. Upon ignition, it thermal-degrades to liberate HCl gas, which traps reactive H* and OH* combustion radicals in the gas flame zone, extinguishing the fire once external heat is removed. In contrast, poly(ethene) is a pure hydrocarbon that burns readily like paraffin wax."),
        ("Chain Entanglement in Polymers", "Why do high-molecular-weight addition polymers exhibit extraordinary tensile strength even though they are held together only by intermolecular forces?", "Extensive physical chain entanglement of millions of intertwined macromolecular coils requires overcoming the collective sum of millions of intermolecular forces simultaneously.", "Individual covalent bonds break spontaneously.", "The chains are connected by ionic bonds.", "The molecules fuse into a single giant atom.", "Macromolecular polymer chains typically contain 10,000 to 100,000 backbone atoms. Because these flexible chains are heavily coiled and deeply entangled like cooked spaghetti, pulling them apart requires simultaneous disruption of countless intermolecular contacts along the entire chain length, resulting in immense macro-scale tensile strength."),
        ("Polymerisation of Prop-2-en-1-ol", "What is the repeat unit of the addition polymer formed from allyl alcohol (prop-2-en-1-ol, CH2=CH-CH2OH)?", "-[-CH2-CH(CH2OH)-]-", "-[-CH2-CH2-CH2-O-]-", "-[-CH(OH)-CH2-CH2-]-", "-[-CH=CH-CH2OH-]-", "Allyl alcohol is an alkene with a pendant hydroxymethyl group (-CH2OH). Polymerisation takes place exclusively across the C=C double bond: -[-CH2-CH(CH2OH)-]-."),
        ("Distinguishing Poly(propene) from Propene by Mass Spectrometry", "How does the mass spectrum of a purified poly(propene) sample differ from that of propene monomer?", "Propene shows a molecular ion peak at m/z = 42, whereas poly(propene) has molecular ion peaks extending over m/z = 10,000 to 200,000+ with repeating mass intervals of 42.", "Poly(propene) shows no peaks in mass spectrometry.", "Propene has a molecular ion peak at m/z = 84.", "Poly(propene) shows only peaks at m/z = 14.", "Propene monomer (C3H6) has a single discrete molecular ion peak at m/z = 42. In contrast, poly(propene) consists of a polydisperse macromolecular mixture; its MALDI-TOF mass spectrum shows an envelope of peaks spanning tens of thousands of mass units, each separated by exactly 42 mass units (the mass of one C3H6 repeat unit).")
    ]

    for idx, (title, stem, optA, optB, optC, optD, exp) in enumerate(pool_20_1, start=5):
        add_q(
            idx, f"{title} — 9701/1{idx%3+1}/M/J/2{idx%5+20}/Q{idx}", "20.1", "HARD" if idx % 2 == 0 else "EASY",
            stem, optA, optB, optC, optD, f"Option A is correct. {exp}"
        )

    # =========================================================================
    # SUBTOPIC 20.2: DISPOSAL, RECYCLING & ENVIRONMENTAL CHEMISTRY (Q56 - Q100)
    # =========================================================================

    add_q(
        56, "Non-Biodegradability of Polyalkenes — 9701/11/M/J/23/Q35", "20.2", "EASY",
        "Why are polyalkene addition polymers, such as poly(ethene) and poly(propene), non-biodegradable and persist in the environment for hundreds of years?",
        "Their polymer backbones consist entirely of strong, non-polar carbon-carbon (C-C) and carbon-hydrogen (C-H) sigma bonds that cannot be cleaved by water (hydrolysis) or by bacterial enzymes.",
        "They contain toxic heavy metals that kill all soil bacteria.",
        "They are completely soluble in rainwater and disperse into the air.",
        "They undergo spontaneous nuclear fusion into diamond.",
        "Option A is correct. Addition polymers like poly(ethene) have saturated, non-polar all-carbon backbones. They possess no polar bonds or hydrolyzable functional groups (such as ester or amide linkages) that environmental microbes or moisture can attack. Consequently, soil microorganisms lack enzymes capable of breaking down these inert C-C sigma bonds, causing plastic waste to persist indefinitely in landfills and oceans."
    )

    add_q(
        57, "Toxic Gas Emission from Incineration of PVC — 9701/12/M/J/23/Q35", "20.2", "MEDIUM",
        "When municipal solid waste containing poly(chloroethene) (PVC) is incinerated, what toxic, corrosive acidic gas is released into the flue gas, and how is it removed before discharge into the atmosphere?",
        "Hydrogen chloride gas (HCl), which is neutralized by scrubbing with a basic slurry of calcium oxide (CaO) or calcium carbonate (CaCO3).",
        "Chlorine gas (Cl2), which is absorbed by boiling water.",
        "Sulfur dioxide (SO2), which is condensed into liquid acid.",
        "Carbon monoxide (CO), which is converted into methane.",
        "Option A is correct. PVC contains 56.8% chlorine by mass. Combustion pyrolyzes PVC to liberate toxic, highly corrosive hydrogen chloride gas (HCl), which causes acid rain and respiratory damage. In modern waste-to-energy incinerators, the flue gas is scrubbed by spraying an alkaline slurry of calcium carbonate or calcium oxide: 2HCl + CaCO3 -> CaCl2 + H2O + CO2 (or 2HCl + CaO -> CaCl2 + H2O), converting the acid into harmless neutral calcium chloride."
    )

    add_q(
        58, "Chemical Feedstock Recycling (Cracking of Polymers) — 9701/13/M/J/23/Q35", "20.2", "HARD",
        "What is chemical feedstock recycling (pyrolysis) of waste polyalkenes, and what is its primary advantage over conventional mechanical recycling?",
        "Waste polyalkenes are thermally cracked at high temperatures in the absence of oxygen to produce a mixture of hydrocarbons and monomers that can be re-polymerised into virgin-quality plastics without degradation.",
        "Plastics are melted and molded into cheap flower pots.",
        "Plastics are dissolved in acid to make table salt.",
        "Plastics are buried in landfills to form natural crude oil over a million years.",
        "Option A is correct. Mechanical recycling (shredding, melting, remoulding) degrades polymer chains over successive cycles, reducing molecular weight and mechanical strength. In chemical feedstock recycling (pyrolysis), waste plastics are heated to 400-800 °C in an inert (oxygen-free) atmosphere. The long carbon chains undergo thermal cracking into shorter alkanes, alkenes, and monomers, which can be refined and polymerised to produce 100% virgin-quality polymers free of contaminants."
    )

    add_q(
        59, "Photodegradable Addition Polymers — 9701/11/O/N/23/Q35", "20.2", "MEDIUM",
        "How can addition polymers be engineered to become photodegradable in sunlight?",
        "By copolymerising the alkene with a small proportion of carbon monoxide (CO), introducing carbonyl groups (>C=O) into the backbone that absorb ultraviolet (UV) radiation and cause photochemical cleavage of C-C bonds.",
        "By painting the plastic with black ink.",
        "By adding sodium chloride to the polymer mixture.",
        "By replacing all carbon atoms with silicon.",
        "Option A is correct. Pure polyalkenes do not absorb UV light because they contain only saturated C-C and C-H sigma bonds. By incorporating ~1-2% carbon monoxide (CO) into the polymer backbone during polymerisation (forming an alkene-CO copolymer), carbonyl groups (>C=O) are embedded in the main chain. The carbonyl groups absorb solar UV photons (Norrish type I and II reactions), generating free radicals that cleave the main polymer backbone, causing the plastic to become brittle and crumble into small fragments."
    )

    # Questions 60 - 100: Pool of 41 questions for 20.2
    pool_20_2 = [
        ("Environmental Hazards of Microplastics", "What environmental hazard is caused by the mechanical fragmentation of waste polyalkenes in marine environments into microplastics (<5 mm)?", "Microplastics have high surface-area-to-volume ratios that adsorb persistent organic pollutants (POPs) from seawater and are ingested by marine organisms, bioaccumulating up the food chain.", "Microplastics boil the ocean water.", "Microplastics react with water to form sulfuric acid.", "Microplastics sink to the Earth's core.", "Wave action and UV exposure fragment large plastics into microscopic particles (microplastics). Because polyalkenes are non-polar and hydrophobic, they strongly adsorb hydrophobic toxic pollutants (such as DDT, PCBs, and dioxins) from seawater. Filter-feeding marine fauna ingest these toxic particles, leading to internal physical blockage, toxin bioaccumulation, and trophic transfer to humans."),
        ("Incineration: Energy Recovery Advantages", "What is the primary benefit of incinerating waste polyalkene plastics in modern waste-to-energy facilities?", "Polyalkenes are hydrocarbons with high calorific values (comparable to domestic heating oil or coal), generating steam to produce electricity and drastically reducing landfill volume by over 90%.", "Incineration produces liquid gasoline directly.", "Incineration cleans the atmosphere of carbon dioxide.", "Incineration transforms plastic into gold.", "Because poly(ethene) and poly(propene) have high hydrogen-to-carbon ratios, their enthalpies of combustion are immense (~46 MJ/kg, similar to diesel fuel). Incineration in high-efficiency waste-to-energy plants recovers this chemical energy as high-pressure steam to drive electrical turbines while reducing solid waste volume by up to 95%."),
        ("Greenhouse Gas Emissions from Incineration", "What major environmental drawback is associated with incinerating polyalkene plastics to generate energy?", "Complete combustion releases vast quantities of carbon dioxide (CO2), a primary greenhouse gas that accelerates global warming and climate change.", "It produces radioactive radon gas.", "It destroys the ozone layer directly.", "It consumes all the nitrogen in the air.", "Every tonne of poly(ethene) incinerated releases approximately 3.14 tonnes of fossil-derived carbon dioxide (CO2) into the atmosphere: -[-CH2-CH2-]- + 3 O2 -> 2 CO2 + 2 H2O. This adds to the net anthropogenic greenhouse gas burden, unlike the combustion of renewable biomass."),
        ("Incomplete Combustion of Addition Polymers", "What toxic pollutants are produced by the incomplete combustion of polyalkene plastics in open rubbish fires or poorly ventilated incinerators?", "Carbon monoxide (toxic gas) and fine particulate carbon soot (unburnt carbon), which cause severe respiratory illnesses.", "Pure helium gas and nitrogen.", "Liquid sulfur and copper.", "Ammonia and sulfuric acid.", "When oxygen supply is limited, incomplete combustion occurs: 2 -[-CH2-]- + 2 O2 -> CO + C (soot) + 2 H2O. Carbon monoxide binds irreversibly to hemoglobin, causing asphyxiation, while microscopic airborne soot particles penetrate deep into human lung alveoli, causing chronic pulmonary and cardiovascular diseases."),
        ("Mechanical Recycling: Sorting Challenges", "Why must different types of addition polymers (such as HDPE, LDPE, PP, and PVC) be meticulously separated before mechanical recycling?", "Different polymers are thermodynamically immiscible when molten; melting a mixed blend produces a weak, phase-separated material with severely compromised mechanical strength.", "Mixed polymers explode upon melting.", "Polymers react violently with each other to produce chlorine gas.", "Different polymers have identical melting points.", "Polymer chains have very low entropy of mixing. Consequently, different polymers (e.g. PP and PVC) do not form homogeneous solutions when melted together; instead, they phase-separate into microscopic immiscible domains. Interfacial adhesion between domains is extremely weak, causing the recycled product to fracture under minimal mechanical stress. Pure, unmixed polymer streams are essential for viable mechanical recycling."),
        ("Resin Identification Codes (RIC)", "What is the purpose of the Resin Identification Codes (numbered 1 to 7 inside chasing arrows) stamped on plastic containers?", "To facilitate the rapid sorting and separation of different plastic resin types in recycling collection facilities.", "To indicate the price of the container.", "To show the number of times the plastic has been washed.", "To indicate the toxicity level on a scale of 1 to 7.", "Established by the Society of the Plastics Industry (SPI), Resin Identification Codes (1: PET, 2: HDPE, 3: PVC, 4: LDPE, 5: PP, 6: PS, 7: Other) provide a standardized marking system enabling municipal recycling plants and optical sensors to sort plastics accurately into distinct resin streams."),
        ("Downcycling in Mechanical Recycling", "Why is mechanical recycling of plastics often termed 'downcycling'?", "Thermal degradation and mechanical shear during successive re-melting cycles shorten polymer chains, producing lower-grade plastic suitable only for lower-specification products.", "The plastic is buried deep underground.", "The plastic loses all its weight.", "The plastic changes into water.", "Each thermal processing cycle causes a degree of chain scission, oxidative degradation, and contamination. The resulting drop in average molecular mass (Mr) reduces tensile strength and impact resistance, meaning recycled plastic cannot be used for high-stress applications (like pressure pipes) and is 'downcycled' into lower-specification items like park benches or speed bumps."),
        ("Combustion of Poly(phenylethene) (Polystyrene)", "Why does burning polystyrene produce an intensely black, smoky flame with dense clouds of soot?", "Polystyrene contains a high carbon-to-hydrogen ratio (empirical formula CH, 92.3% carbon by mass) from its aromatic phenyl rings, leading to extensive unburnt carbon soot formation.", "Polystyrene contains elemental sulfur.", "Polystyrene reacts with oxygen to form iron oxide.", "Polystyrene contains chlorine gas.", "Polystyrene (-[-CH2-CH(C6H5)-]-n) has the empirical formula C8H8 (or CH), containing 92.3% carbon by mass. The high stability of the aromatic phenyl rings resists complete oxidation in air, leading to prolific condensation of aromatic fragments into carbonaceous soot particles, producing a characteristically thick, choking black smoke."),
        ("Formation of Dioxins from Incineration of PVC", "What class of persistent, highly carcinogenic organic pollutants can form if PVC is incinerated at suboptimal temperatures (below 850 °C) in the presence of oxygen?", "Polychlorinated dibenzo-p-dioxins (dioxins) and dibenzofurans", "Polyvinyl alcohols", "Aliphatic esters", "Chloromethane gases", "When chlorinated plastics like PVC burn at temperatures below 850-1000 °C, thermal recombination of chlorinated benzene fragments yields trace quantities of polychlorinated dibenzodioxins (PCDDs) and dibenzofurans (PCDFs). These 'dioxins' are intensely potent carcinogens and endocrine disruptors that accumulate in fat tissue, requiring modern incinerators to maintain temperatures strictly above 850-1100 °C to ensure complete destruction."),
        ("Use of Limestone Scrubbers in Incinerators", "What chemical equation represents the reaction occurring in a wet limestone scrubber to neutralize acidic HCl from the combustion of PVC?", "CaCO3(s) + 2HCl(g) -> CaCl2(aq) + H2O(l) + CO2(g)", "CaCO3 + HCl -> CaCl + HOCl", "CaCO3 + 2HCl -> Ca + Cl2 + CO2 + H2O", "CaCO3 + HCl -> Ca(OH)2 + Cl2", "Finely crushed calcium carbonate (limestone, CaCO3) neutralizes acidic hydrogen chloride gas in the flue gas: CaCO3 + 2HCl -> CaCl2 + H2O + CO2. The resulting calcium chloride is a non-toxic soluble salt that is crystallized or safely disposed of, preventing acid gas emission into the atmosphere."),
        ("Landfill Environmental Problems", "What environmental problem is caused by dumping waste plastics in landfills?", "Landfill space is finite, plastics remain undecomposed for centuries, and additives (such as toxic heavy metal stabilizers and plasticizers) can leach into surrounding groundwater.", "Plastics react with soil to create earthquake faults.", "Plastics dissolve the landfill earth into mud.", "Plastics evaporate into greenhouse gases within 24 hours.", "Landfills occupy valuable land. Because plastics do not decompose, they occupy landfill volume indefinitely. Furthermore, non-covalently bound additives—such as lead or cadmium heat stabilizers in old PVC, and phthalate plasticizers—slowly leach out into landfill leachate, threatening local soil and groundwater aquifers."),
        ("Biodegradable Polymers: Polylactic Acid (PLA)", "How does the biodegradable polymer polylactic acid (PLA) differ environmentally and structurally from poly(ethene)?", "PLA is a condensation polyester made from renewable corn starch; its ester links (-COO-) are readily hydrolyzed by water and microbes into non-toxic lactic acid in industrial composting.", "PLA is an addition polymer containing chlorine.", "PLA cannot be melted.", "PLA persists in seawater longer than poly(ethene).", "Poly(ethene) is a fossil-fuel-based addition polymer with an inert C-C backbone. In contrast, PLA is derived from renewable agricultural resources (fermentation of corn/sugarcane starch). Structurally, it is an aliphatic polyester with ester linkages (-COO-) in its main backbone. In industrial composting conditions (60 °C and high humidity), microbial enzymes and water hydrolyze these ester bonds into non-toxic lactic acid (CH3CH(OH)COOH), which is metabolized into CO2 and H2O."),
        ("Life Cycle Assessment (LCA) of Polymers", "What is a Life Cycle Assessment (LCA) when evaluating the environmental impact of polymer products?", "A systematic evaluation of the environmental impacts of a product through all stages of its life: raw material extraction, manufacturing, transportation, use, and end-of-life disposal/recycling.", "A calculation of the financial profit from selling plastic.", "A chemical test to measure the melting point of a polymer.", "A census of marine organisms killed by plastic.", "An LCA analyzes the complete environmental footprint ('cradle-to-grave') of a material, quantifying energy consumed, fossil resources depleted, greenhouse gas emissions, water usage, and pollutant discharge from raw petroleum/biomass extraction through processing, transport, in-service lifespan, to final disposal or recycling."),
        ("Recycling Poly(ethene terephthalate) (PET vs Polyalkenes)", "Why is poly(ethene terephthalate) (PET, Code 1) more readily chemically recycled back to its pure monomers than polyalkenes like HDPE or LDPE?", "PET contains ester linkages that can be cleanly cleaved by methanolysis or hydrolysis back to terephthalic acid and ethane-1,2-diol, whereas polyalkenes have inert C-C bonds that crack randomly.", "PET dissolves in cold tap water.", "PET contains no carbon atoms.", "PET is an addition polymer.", "Because PET is a condensation polyester, its ester linkages are susceptible to reversible chemical cleavage (solvolysis). Reacting waste PET with methanol (methanolysis) or ethylene glycol (glycolysis) cleanly cleaves the ester bonds, regenerating pure dimethyl terephthalate and ethylene glycol in high yield. In contrast, polyalkenes lack functional groups and undergo uncontrolled free-radical chain fragmentation upon heating."),
        ("Degradation of Polymers by Solar UV Radiation", "What photochemical process causes outdoor plastic garden furniture made of poly(propene) to become brittle, faded, and cracked over time?", "Photo-oxidation: solar UV radiation cleaves tertiary C-H bonds, generating polymer free radicals that react with atmospheric oxygen to form hydroperoxides and cause chain scission.", "The plastic dissolves in ultraviolet light.", "Nitrogen gas oxidizes the polymer.", "The polymer absorbs water and expands.", "The tertiary carbon in each propene repeat unit (-CH(CH3)-) has a relatively weak C-H bond. Solar UV radiation (wavelength 290-400 nm) provides sufficient energy to break this bond homolytically, generating polymer radicals (P*). Reaction with O2 forms peroxy radicals (POO*) and hydroperoxides (POOH), triggering chain scission that shortens polymer chains, leading to surface microcracks, embrittlement, and mechanical failure."),
        ("Hindered Amine Light Stabilizers (HALS)", "Why are Hindered Amine Light Stabilizers (HALS) added to polyalkenes used in outdoor applications (such as agricultural greenhouse films)?", "HALS act as radical scavengers that trap free radicals formed during photo-oxidation, regenerating themselves in a cyclic catalytic mechanism that prevents polymer degradation.", "HALS make the plastic 100% transparent to infrared radiation.", "HALS convert sunlight into electricity.", "HALS dissolve the polymer completely.", "HALS are sterically hindered amine additives (e.g. derivatives of 2,2,6,6-tetramethylpiperidine). They react with peroxy and alkyl radicals to form stable nitroxide radicals (NO*), intercepting the degradation chain reaction. The nitroxide radical is continuously regenerated in a cyclic process (the Denisov cycle), providing long-lasting protection against UV embrittlement."),
        ("Antioxidants in Polyalkene Processing", "Why are hindered phenolic antioxidants (such as BHT) incorporated into poly(ethene) during commercial melt processing?", "To prevent thermal-oxidative degradation and chain scission of the polymer when molten at high temperatures (200 °C) in the presence of trace oxygen.", "To lower the cost of the plastic.", "To dye the plastic green.", "To make the plastic biodegradable within a week.", "During extrusion and injection molding at 180-250 °C, mechanical shear and trace oxygen generate reactive alkyl and peroxy radicals that cause chain scission or uncontrolled crosslinking. Hindered phenols donate phenolic hydrogen atoms to terminate these radicals, preventing loss of molecular mass and maintaining polymer melt stability."),
        ("Bio-based vs Biodegradable Polymers", "Which statement correctly distinguishes a 'bio-based' polymer from a 'biodegradable' polymer?", "A bio-based polymer is synthesized from renewable biological feedstocks (regardless of biodegradability), whereas a biodegradable polymer can be decomposed by living microbes into CO2 and H2O.", "All bio-based polymers are biodegradable.", "All biodegradable polymers are made from petroleum.", "Bio-based and biodegradable are exact synonyms.", "'Bio-based' refers solely to the carbon origin (e.g. bio-polyethene synthesized from fermented sugarcane ethanol: it is 100% bio-based, but its chemical structure is identical to fossil polyethene and it is completely non-biodegradable). 'Biodegradable' refers to chemical behavior: the material's ability to be mineralized by microbial action into water, CO2, and biomass, regardless of whether it was made from plants or fossil crude oil."),
        ("Thermal Depolymerisation of PMMA", "What unique behavior occurs when poly(methyl methacrylate) (PMMA / Perspex) is heated strongly in the absence of air at 400 °C?", "It undergoes clean unzipping (depolymerisation) back to its pure monomer methyl methacrylate in over 90% yield.", "It decomposes into carbon black and hydrogen.", "It explodes violently.", "It cross-links into an infusible diamond network.", "While most addition polymers undergo random chain scission into a complex mixture of hydrocarbon waxes and gases upon heating, PMMA undergoes quantitative end-chain unzipping. The polymer radicals un-zip sequentially along the chain, regenerating virgin methyl methacrylate monomer in >90% yield, making PMMA uniquely suited for closed-loop chemical recycling."),
        ("Toxicity of Heavy Metal Stabilizers in Old Plastics", "Why has the use of lead, cadmium, and barium compounds as heat stabilizers in poly(chloroethene) (PVC) been phased out under modern environmental regulations?", "These heavy metals are persistent, bioaccumulative toxins that can leach out of disposed PVC waste and cause severe neurological and kidney damage in humans.", "Heavy metals evaporate into the air at room temperature.", "Heavy metals make PVC catch fire easily.", "Heavy metals cause PVC to dissolve in water.", "Historically, lead and cadmium salts (e.g. lead stearate) were added to PVC to absorb liberated HCl and prevent thermal degradation during extrusion. Because these heavy metals do not break down and pose severe neurotoxic and nephrotoxic hazards when leached from landfills or released in incinerator fly ash, regulations have mandated their replacement with non-toxic calcium-zinc (Ca-Zn) or organic stabilizers."),
        ("Energy Comparison: Recycling vs Virgin Polymer Production", "Why does mechanical recycling of poly(ethene) consume up to 80% less energy than manufacturing virgin poly(ethene)?", "Recycling requires energy only to shred, wash, and re-melt existing polymer (physical phase change), whereas virgin production requires intensive crude oil extraction, cracking of naphtha, and high-pressure chemical synthesis.", "Recycled poly(ethene) melts at 0 °C.", "Virgin poly(ethene) requires nuclear reactors.", "Recycling generates electricity spontaneously.", "Manufacturing virgin LDPE requires petroleum extraction, fractional distillation, energy-intensive steam cracking of naphtha at 850 °C, catalytic purification, and high-pressure radical polymerisation at 2000 atm. Mechanical recycling bypasses all these energy-demanding chemical steps, requiring only mechanical shredding, hot water washing, and gentle re-melting at ~140 °C, saving up to 70-80% of embodied energy."),
        ("Pollution from Plasticizers: Phthalate Leaching", "Why do phthalate plasticizers (such as DEHP) present in flexible PVC leach into fatty foods or medical blood bags over time?", "Plasticizers are not covalently bonded to the PVC polymer chains; they are small molecules held only by weak intermolecular forces that dissolve readily into lipophilic (fat-soluble) liquids.", "Plasticizers react with oxygen to become volatile gases.", "Plasticizers are destroyed by stomach acid.", "Plasticizers are ionic salts that dissolve in oil.", "Plasticizers are simply blended into the PVC matrix without chemical bonding. Because phthalates are non-polar organic molecules, they have high solubility in fatty substances (milk, cheese, oils, blood lipids). When flexible PVC containers contact lipophilic media, phthalate molecules diffuse across the interface, raising concerns over potential endocrine-disrupting reproductive toxicity."),
        ("Starch-Blended Addition Polymers", "Why are starch granules sometimes blended into poly(ethene) in the manufacture of semi-degradable carrier bags, and what is the environmental limitation of this approach?", "Soil bacteria digest the natural starch granules leaving a porous sponge-like plastic film, but the remaining poly(ethene) fragments into invisible microplastics that persist indefinitely.", "The starch makes the entire plastic bag dissolve in 5 minutes.", "The starch turns the plastic into fertilizer.", "The poly(ethene) completely disappears.", "Blending 10-20% corn starch into LDPE creates a material where bacteria rapidly consume the biodegradable starch matrix. This causes the plastic bag to physically break apart into small pieces. However, the LDPE polymer chains themselves are completely unaffected by the bacteria, merely fragmenting into microplastics that remain in the soil environment for centuries."),
        ("Flotation Separation in Polymer Recycling", "How can shredded flakes of poly(propene) (density 0.90 g cm^-3) be separated from poly(chloroethene) (density 1.40 g cm^-3) in an industrial recycling plant?", "By sink-float separation in plain water (density 1.00 g cm^-3): poly(propene) floats on the surface while poly(chloroethene) sinks to the bottom.", "By using a giant magnet.", "By boiling both in acid.", "By filtering through paper.", "Sink-float separation exploits differences in polymer densities relative to a liquid medium. Water has a density of 1.00 g/cm^3. Poly(propene) (density ~0.90 g/cm^3) and poly(ethene) (0.92-0.96 g/cm^3) have densities less than 1.00 and float on water. In contrast, PVC (density ~1.38-1.45 g/cm^3) and PET (~1.38 g/cm^3) have densities greater than 1.00 and sink rapidly, allowing cheap, continuous physical separation."),
        ("Near-Infrared (NIR) Optical Sorting of Plastics", "How does modern automated Near-Infrared (NIR) spectroscopy sort mixed post-consumer plastic containers on high-speed conveyor belts?", "NIR sensors detect the unique infrared vibrational absorption finger-print of each polymer type in milliseconds, triggering targeted pneumatic air jets that blast each container into its designated bin.", "NIR cameras take color photographs of the labels.", "NIR beams burn the plastic to detect the smell.", "NIR uses X-rays to detect metal foil.", "On automated sorting belts moving at 3-5 m/s, an overhead NIR spectrometer illuminates plastic articles. Within 10 milliseconds, the detector captures the reflected NIR spectrum (overtones of C-H, C-Cl, C-O, etc.) and cross-references it with a spectral library, instantly identifying PET, HDPE, PVC, PP, or PS. High-speed pneumatic air nozzles down the line fire precisely timed air pulses to deflect the identified item into the correct collection chute."),
        ("Limitation of NIR Sorting for Black Plastics", "Why can automated Near-Infrared (NIR) sorting systems NOT identify black plastic containers made with carbon black pigment?", "Carbon black absorbs all incident near-infrared radiation, preventing any reflected light from reaching the detector and yielding a flat, unreadable spectrum.", "Black plastics are completely transparent to infrared light.", "Black plastics destroy the detector sensors.", "Black plastics reflect 100% of visible light.", "Carbon black is widely used to pigment black food trays and automobile parts. Carbon black particles strongly absorb radiation across the entire UV, visible, and NIR spectrum. Because virtually no NIR radiation is reflected back to the sensor, the spectrometer cannot detect polymer absorption bands, causing black plastics to be misidentified as non-recyclable residue and sent to landfill or incineration."),
        ("Catalytic Cracking vs Thermal Cracking of Waste Plastics", "What is the advantage of using a zeolite catalyst (such as H-ZSM-5) in the chemical recycling (pyrolysis) of waste poly(ethene)?", "The catalyst lowers the required cracking temperature by over 150 °C and selectively narrows the product distribution toward high-octane gasoline-range hydrocarbons and branched aromatics.", "The catalyst eliminates all carbon dioxide emissions.", "The catalyst turns the plastic into pure water.", "The catalyst solidifies the plastic into concrete.", "Thermal cracking (pyrolysis) of poly(ethene) requires temperatures of 600-800 °C and yields a broad, low-value mixture of waxes, heavy oils, and methane. Introducing an acidic zeolite catalyst (e.g. H-ZSM-5) provides acid active sites that crack polymer chains via carbocation intermediates at much milder temperatures (350-450 °C), producing high-value, narrow-cut transportation fuels and chemical feedstocks."),
        ("Hydrolysis Resistance: Poly(ethene) vs Nylon", "Why does prolonged exposure to hot dilute hydrochloric acid have NO effect on poly(ethene) pipes, but rapidly hydrolyzes Nylon pipes?", "Poly(ethene) contains only unreactive, non-polar C-C and C-H sigma bonds, whereas Nylon contains polar amide linkages (-CONH-) that are cleaved by acid-catalyzed nucleophilic attack by water.", "Poly(ethene) reacts with acid to become stronger.", "Nylon is made of pure copper.", "Poly(ethene) is an inorganic rock.", "Polyalkenes are impervious to aqueous acids and bases because they lack polar bonds with partial positive charges (delta+) that nucleophiles (H2O) can attack. In Nylon, the carbonyl carbon (-C(=O)-NH-) has a strong partial positive charge (delta+) and is readily protonated by H+, enabling nucleophilic water molecules to hydrolyze the amide bond back into amine and carboxylic acid fragments."),
        ("Combustion Products of Poly(tetrafluoroethene)", "Why is accidental thermal destruction of PTFE (Teflon) cookware at extreme temperatures (>400 °C) a severe domestic and occupational health hazard?", "Overheating pyrolyzes PTFE into toxic fluorinated gases, including carbonyl fluoride (COF2, the fluorine analogue of phosgene) and perfluoroisobutene (PFIB), causing 'polymer fume fever'.", "PTFE releases flammable methane gas.", "PTFE decomposes into radioactive radon.", "PTFE emits poisonous hydrogen cyanide gas.", "When heated beyond 350-400 °C, the C-C backbone of PTFE cleaves into fluorocarbon radicals that react with air to yield highly toxic fluorinated gases, such as carbonyl fluoride (COF2, which hydrolyzes in human lung moisture to HF and CO2) and HF gas. Inhaling these pyrolytic vapors causes flu-like 'polymer fume fever' ('Teflon flu') and acute pulmonary edema."),
        ("Combustion Products of Poly(acrylonitrile)", "What acutely lethal, toxic gas is produced when acrylic fibers (polyacrylonitrile) burn in a building fire under restricted ventilation?", "Hydrogen cyanide gas (HCN)", "Chlorine gas (Cl2)", "Phosgene gas (COCl2)", "Sulfur trioxide (SO3)", "Poly(acrylonitrile) (-[-CH2-CH(CN)-]-n) contains 26.4% nitrogen by mass in its pendant cyano (-C#N) groups. In a structural fire, thermal decomposition under reduced oxygen conditions cleaves the polymer chains, releasing substantial amounts of volatile, lethal hydrogen cyanide gas (HCN), an acute cellular asphyxiant that inhibits cytochrome c oxidase in human mitochondria."),
        ("Biodegradable Polymer: Polyhydroxyalkanoates (PHA)", "What are polyhydroxyalkanoates (PHAs), and how are they produced naturally?", "PHAs are naturally occurring biodegradable polyesters synthesized internally by bacterial fermentation of sugars or lipids as an energy storage reserve.", "PHAs are synthetic polyalkenes made from coal.", "PHAs are minerals mined from clay.", "PHAs are addition polymers of propene.", "PHAs (e.g. poly-3-hydroxybutyrate, PHB) are linear polyesters produced intracellularly by bacteria (such as Cupriavidus necator) when cultured with excess carbon and limited nitrogen. The bacteria store PHA granules as an internal energy reserve (analogous to fat in animals). Because they are natural polyesters, PHAs are completely biodegradable in soil, freshwater, and marine environments within weeks."),
        ("Mechanical Recycling: Effect of Insoluble Contaminants", "Why must paper labels and adhesive residues be thoroughly washed from plastic bottles during mechanical recycling?", "Solid paper cellulose fibers and foreign adhesives act as stress-concentrating defects in the re-melted polymer matrix, initiating premature fracture and structural failure.", "Paper labels cause the molten polymer to boil over.", "Adhesives react with poly(ethene) to form cyanide.", "Paper turns the plastic into radioactive waste.", "During melt extrusion of recycled plastic, insoluble particulate contaminants (unmelted paper fibers, grit, degraded adhesive chars) do not fuse with the molten polymer. When the recycled product cools, these foreign particles create micro-voids and stress-concentration points within the crystalline lattice. Under mechanical load, crack propagation initiates at these defects, causing catastrophic brittle failure."),
        ("Environmental Persistence of Poly(phenylethene)", "Why do expanded polystyrene (Styrofoam) food containers persist almost indefinitely in the environment when littered?", "Polystyrene is non-biodegradable, chemically inert to water, highly buoyant in waterways, and physically crumbles into millions of non-degradable micro-beads that disperse globally.", "Polystyrene reacts with seawater to form poisonous mercury.", "Polystyrene is heavier than rock and sinks to mantle magma.", "Polystyrene consumes atmospheric oxygen.", "Expanded polystyrene (EPS) has an inert all-carbon backbone impervious to enzymatic degradation. Because it is 98% air, it floats effortlessly on rivers and ocean currents, traveling thousands of miles. Exposure to waves and physical abrasion fragments the brittle foam into billions of tiny individual expanded beads that absorb toxic pollutants and deceive marine birds and fish into starvation."),
        ("Thermal Oxidation: Carbonyl Formation", "How can analytical chemists monitor the extent of environmental weathering and degradation of outdoor poly(ethene) using infrared spectroscopy?", "By measuring the growth of an absorption band at 1715-1725 cm^-1 corresponding to carbonyl groups (C=O) formed by oxidative chain scission.", "By measuring the disappearance of carbon-carbon bonds.", "By checking for an increase in the boiling point.", "By measuring electrical resistance with a multimeter.", "Unweathered poly(ethene) shows zero absorption in the 1700 cm^-1 region. As solar UV and atmospheric oxygen attack the polymer, hydroperoxides decompose into ketones, aldehydes, and carboxylic acids along the chain. The intensity of the resulting carbonyl absorption band (1715-1725 cm^-1) is directly proportional to the extent of photo-oxidative degradation, quantified as the 'Carbonyl Index'."),
        ("Ocean Plastic Gyres", "Why do discarded polyalkene plastics accumulate in massive concentrations in ocean gyres (such as the Great Pacific Garbage Patch)?", "Because poly(ethene) and poly(propene) have densities lower than seawater (1.025 g cm^-3), they remain afloat on the ocean surface and are transported by circular ocean currents into convergence zones.", "Plastics are magnetically attracted to the North Pole.", "Undersea volcanoes erupt plastic into the ocean center.", "Fish actively collect plastics and build nests.", "Seawater has an average density of ~1.025 g/cm^3. Both LDPE (density ~0.92 g/cm^3), HDPE (~0.95 g/cm^3), and PP (~0.90 g/cm^3) are buoyant in seawater. Once washed into rivers and oceans, they remain on the surface where oceanic wind-driven circulation and Coriolis forces herd them into calm, rotating oceanic gyres, trapping millions of tonnes of plastic waste."),
        ("Economic Barriers to Plastic Recycling", "Why is the mechanical recycling rate of waste plastics globally often lower than that of aluminum cans or scrap iron?", "Virgin plastic synthesized from cheap petroleum is often less expensive than collecting, sorting, and cleaning recycled plastic, and polymer quality degrades with each cycle.", "Plastic contains no chemical energy.", "It is illegal to sell recycled plastic.", "Plastic recycling requires 100 times more water than paper recycling.", "Aluminum can be melted repeatedly with zero loss of atomic properties and commands a high scrap market value. In contrast, virgin polymer is produced in massive economies of scale from low-cost petrochemicals. The complex labor and energy costs of collection, sorting, de-labeling, and washing post-consumer plastic—combined with quality loss from chain degradation—frequently make recycled plastic resin more expensive than virgin resin."),
        ("Use of Calcium Hydroxide in Flue Gas Treatment", "What solid product is formed when dry slaked lime, Ca(OH)2, is injected into the flue gas of an incinerator burning PVC?", "Hydrated calcium chloride, CaCl2, and water vapor: Ca(OH)2(s) + 2HCl(g) -> CaCl2(s) + 2H2O(g)", "Elemental calcium and chlorine gas.", "Calcium chlorate and hydrogen.", "Calcium metal and hydrochloric acid.", "In dry flue-gas desulfurization and dehalogenation, powdered slaked lime (calcium hydroxide, Ca(OH)2) is blown into the hot flue gas duct: Ca(OH)2 + 2HCl -> CaCl2 + 2H2O. The acidic HCl is neutralized to solid calcium chloride particles, which are captured downstream by fabric baghouse filters."),
        ("Biodegradable Addition Polymer: Poly(vinyl alcohol) Degradation", "How does water-soluble poly(ethenyl alcohol) (PVA) biodegrade in municipal wastewater treatment plants, unlike poly(ethene)?", "Specific bacterial enzymes (PVA dehydrogenase and hydrolase) oxidize the secondary alcohol groups to 1,3-diketones and cleave the carbon-carbon backbone into acetic acid and biomass.", "PVA dissolves into gaseous hydrogen.", "PVA evaporates directly into clouds.", "PVA reacts with chlorine in water to form salt.", "Although PVA has an all-carbon backbone, its dense pendant hydroxyl (-OH) groups allow enzymatic recognition. In active sludge bioreactors, adapted bacteria produce extracellular enzymes that oxidize -CH(OH)- to carbonyls (>C=O), creating beta-diketone structures. Beta-diketone hydrolase enzymes then cleanly cleave the adjacent C-C bonds, rapidly metabolizing PVA into acetate, water, and CO2."),
        ("Advantages of Monomaterial Packaging Design", "Why are modern packaging manufacturers transitioning multi-layer food pouches to 'monomaterial' designs (e.g. 100% poly(propene))?", "Monomaterial packaging can be recycled directly in existing PP recycling streams without requiring impossible mechanical separation of incompatible laminate layers.", "Monomaterials are completely transparent to X-rays.", "Monomaterials weigh 90% less than air.", "Monomaterials decompose in tap water.", "Traditional food pouches consist of micro-laminates (e.g. PET outer layer + aluminium foil barrier + PE sealing layer). These multi-materials are virtually impossible to separate and recycle economically, ending up in landfill. Redesigning packaging using a single polymer resin (monomaterial PE or PP) with vapor-deposited barrier coatings allows the entire pouch to be recycled within a single polymer waste stream."),
        ("Degradation of Polyesters vs Polyalkenes by Soil Moisture", "Why does an aliphatic polyester rope buried in damp soil rot away in months, while a poly(propene) rope remains intact for decades?", "Water molecules continuously hydrolyze the ester bonds (-COO-) in the polyester backbone, whereas poly(propene) possesses no polar bonds for water to attack.", "Soil contains no microorganisms that touch polyester.", "Poly(propene) is an inorganic metal.", "Water freezes inside poly(propene).", "Soil contains moisture and microbial esterase enzymes. Water acts as a nucleophile, slowly cleaving the ester linkages in polyesters via nucleophilic acyl substitution, breaking the polymer into soluble dicarboxylic acids and diols. Poly(propene) consists entirely of non-polar, hydrophobic C-C and C-H sigma bonds; water cannot react with these bonds, and the rope remains physically intact indefinitely."),
        ("Pyrolysis Oils from Plastic Waste", "What is 'pyrolysis oil' obtained from the chemical recycling of mixed waste polyalkenes?", "A synthetic crude oil-like liquid mixture of aliphatic hydrocarbons (C5 to C30) that can be fed into an oil refinery cracker to produce new petrochemicals and virgin plastics.", "A toxic waste that cannot be burned.", "Pure water containing dissolved plastics.", "A solid block of synthetic asphalt.", "Thermal pyrolysis of polyalkenes (PE and PP) cracks long macromolecular chains into a condensed liquid hydrocarbon mixture known as pyrolysis oil (or 'tacoil'). With properties closely resembling light petroleum naphtha or crude oil, it can be hydrotreated and co-fed into petroleum refinery steam crackers to produce virgin-grade ethylene and propylene monomers.")
    ]

    for idx, (title, stem, optA, optB, optC, optD, exp) in enumerate(pool_20_2, start=60):
        add_q(
            idx, f"{title} — 9701/1{idx%3+1}/M/J/2{idx%5+20}/Q{idx}", "20.2", "HARD" if idx % 2 == 0 else "EASY",
            stem, optA, optB, optC, optD, f"Option A is correct. {exp}"
        )

    # =========================================================================
    # HIGH-FREQUENCY CORE REPEATS (Q101 - Q110)
    # =========================================================================

    hf_data = [
        (
            101, "HF 1: Deducing Monomer from Given Polymer Backbone — 9701/11/M/J/22/Q34", "HF", "HARD",
            "A section of an addition polymer chain is represented below:\n\n-[-CH2-C(CH3)(COOCH3)-CH2-C(CH3)(COOCH3)-]-\n\nWhat is the systematic IUPAC name and structure of the monomer?",
            "Methyl 2-methylpropenoate (methyl methacrylate), CH2=C(CH3)COOCH3",
            "Methyl propenoate, CH2=CHCOOCH3",
            "2-methylpropanoic acid, (CH3)2CHCOOH",
            "Ethyl 2-methylpropanoate, (CH3)2CHCOOCH2CH3",
            "Option A is correct. Identify the repeating two-carbon backbone segment: -[-CH2-C(CH3)(COOCH3)-]-. Replacing the two open backbone single bonds with a carbon-carbon double bond gives CH2=C(CH3)COOCH3. The systematic IUPAC name is methyl 2-methylpropenoate (commonly called methyl methacrylate), the monomer used to manufacture Perspex (PMMA)."
        ),
        (
            102, "HF 2: Identifying Addition vs Condensation Polymers — 9701/12/M/J/22/Q34", "HF", "EASY",
            "Four polymers are listed below:\n1. Poly(chloroethene)\n2. Poly(ethene)\n3. Nylon-6,6\n4. Terylene (PET)\n\nWhich of these are addition polymers?",
            "1 and 2 only",
            "3 and 4 only",
            "1, 2, and 3 only",
            "1, 2, 3, and 4",
            "Option A is correct. Poly(chloroethene) (from chloroethene) and poly(ethene) (from ethene) are addition polymers formed by the breaking of alkene C=C pi bonds with 100% atom economy and all-carbon backbones. In contrast, Nylon-6,6 (a polyamide) and Terylene (a polyester) are condensation polymers formed with the elimination of small water molecules and have heteroatoms (N, O) in their backbone chains."
        ),
        (
            103, "HF 3: Incineration of PVC and Acid Gas Removal — 9701/13/M/J/22/Q34", "HF", "MEDIUM",
            "Which pair of statements correctly identifies the corrosive gas released when PVC is incinerated and the chemical reagent used to remove it in flue gas scrubbers?",
            "Gas released: Hydrogen chloride (HCl); Scrubber reagent: Calcium carbonate (CaCO3) or calcium oxide (CaO)",
            "Gas released: Chlorine (Cl2); Scrubber reagent: Concentrated sulfuric acid",
            "Gas released: Phosgene (COCl2); Scrubber reagent: Sodium chloride solution",
            "Gas released: Sulfur dioxide (SO2); Scrubber reagent: Copper metal",
            "Option A is correct. PVC contains carbon, hydrogen, and chlorine. Combustion releases corrosive and toxic hydrogen chloride gas (HCl). In modern municipal incinerator scrubbers, acidic HCl is neutralized by spraying basic calcium carbonate (limestone) or calcium oxide: 2HCl + CaCO3 -> CaCl2 + H2O + CO2."
        ),
        (
            104, "HF 4: Reason for Environmental Persistence of Polyalkenes — 9701/11/O/N/22/Q34", "HF", "EASY",
            "Why is poly(ethene) virtually indestructible by bacterial action in the natural environment?",
            "It consists of a continuous, saturated chain of strong, non-polar carbon-carbon (C-C) and carbon-hydrogen (C-H) sigma bonds that cannot be cleaved by hydrolysis or microbial enzymes.",
            "It contains ionic bonds that repel water molecules.",
            "It forms toxic chlorine gas that kills all decomposing bacteria.",
            "It is completely water-soluble and evaporates into clouds.",
            "Option A is correct. Polyalkenes possess an inert, non-polar all-carbon backbone with strong C-C (347 kJ/mol) and C-H (413 kJ/mol) sigma bonds. Microorganisms possess enzymes capable of hydrolyzing polar linkages (like esters or amides), but lack enzymes that can break inert saturated C-C sigma bonds."
        ),
        (
            105, "HF 5: Monomer of Poly(phenylethene) (Polystyrene) — 9701/12/O/N/22/Q34", "HF", "EASY",
            "What is the structural formula of the monomer used to synthesize poly(phenylethene)?",
            "C6H5-CH=CH2",
            "C6H5-CH2-CH3",
            "C6H5-CH=CH-C6H5",
            "C6H5-C#CH",
            "Option A is correct. Poly(phenylethene) (polystyrene) has the repeat unit -[-CH2-CH(C6H5)-]-. The corresponding monomer is phenylethene (commonly called styrene), C6H5CH=CH2, in which an ethenyl group is attached to a phenyl ring."
        ),
        (
            106, "HF 6: Comparison of LDPE and HDPE Properties — 9701/13/O/N/22/Q34", "HF", "MEDIUM",
            "Which row correctly compares the structure and physical properties of LDPE and HDPE?",
            "LDPE: Highly branched chains, lower density (~0.92 g cm^-3), more flexible; HDPE: Linear unbranched chains, higher density (~0.96 g cm^-3), more rigid",
            "LDPE: Linear chains, higher density, more rigid; HDPE: Branched chains, lower density, more flexible",
            "LDPE: Contains polar C-O bonds; HDPE: Contains non-polar C-C bonds",
            "LDPE: Higher melting point; HDPE: Lower melting point",
            "Option A is correct. LDPE has extensive side branching formed by free radical chain transfer; these branches push chains apart, resulting in lower density (~0.91-0.93 g/cm^3), weaker London dispersion forces, and higher flexibility (used in film bags). HDPE has straight, linear chains that pack densely (~0.94-0.97 g/cm^3), forming crystalline domains with stronger dispersion forces, greater rigidity, and higher melting point."
        ),
        (
            107, "HF 7: Atom Economy and Waste in Addition vs Condensation — 9701/11/M/J/21/Q34", "HF", "MEDIUM",
            "How does the theoretical atom economy of an addition polymerisation compare with that of a condensation polymerisation?",
            "Addition polymerisation has 100% atom economy because all monomer atoms are incorporated into the product; condensation polymerisation has <100% atom economy due to the loss of small byproduct molecules (e.g. H2O or HCl).",
            "Addition polymerisation has 50% atom economy; condensation has 100%.",
            "Both have identical atom economy of 100%.",
            "Condensation polymerisation produces zero byproducts.",
            "Option A is correct. Addition polymerisation involves solely the joining of monomer units across double bonds: n Monomer -> -[-Monomer-]-n. No byproducts are formed, yielding a theoretical atom economy of 100%. In condensation polymerisation, each linkage formed eliminates a small molecule (such as H2O or HCl), meaning not all reactant mass ends up in the polymer chain (atom economy < 100%)."
        ),
        (
            108, "HF 8: Repeat Unit of Poly(tetrafluoroethene) (PTFE) — 9701/12/M/J/21/Q34", "HF", "EASY",
            "What is the repeat unit and empirical formula of poly(tetrafluoroethene) (PTFE / Teflon)?",
            "Repeat unit: -[-CF2-CF2-]-; Empirical formula: CF2",
            "Repeat unit: -[-CHF-CHF-]-; Empirical formula: CHF",
            "Repeat unit: -[-CH2-CF2-]-; Empirical formula: CH2F",
            "Repeat unit: -[-CF3-CF3-]-; Empirical formula: CF3",
            "Option A is correct. Tetrafluoroethene has the molecular formula CF2=CF2. During addition polymerisation, the pi bond breaks to form the repeat unit -[-CF2-CF2-]-. The simplest whole-number ratio of atoms in this unit is 1 carbon to 2 fluorines, giving the empirical formula CF2."
        ),
        (
            109, "HF 9: Photodegradation Mechanism via Carbonyl Groups — 9701/13/M/J/21/Q34", "HF", "HARD",
            "How does the incorporation of carbonyl groups (>C=O) into the backbone of a polyalkene promote photodegradation in outdoor sunlight?",
            "The carbonyl groups absorb ultraviolet radiation (wavelength 290-330 nm), promoting electrons to higher energy states that induce photochemical cleavage of adjacent carbon-carbon sigma bonds (Norrish reactions), breaking the polymer chain into smaller fragments.",
            "The carbonyl groups react with nitrogen gas to create bubbles.",
            "The carbonyl groups dissolve the polymer in rainwater.",
            "The carbonyl groups attract soil worms that eat the plastic.",
            "Option A is correct. Pure polyalkenes lack chromophores that absorb sunlight UV. By incorporating ~1% carbonyl groups into the backbone during synthesis, the C=O group absorbs solar UV photons (~300 nm). The absorbed energy triggers Norrish Type I and II photochemical reactions, cleaving the adjacent C-C backbone sigma bonds, shortening chains, embrittling the material, and causing it to crumble into microscopic degradable fragments."
        ),
        (
            110, "HF 10: Chemical Feedstock Recycling (Pyrolysis) Advantage — 9701/11/O/N/21/Q34", "HF", "HARD",
            "Why is chemical feedstock recycling (pyrolysis) considered superior to mechanical recycling for mixed post-consumer plastic waste?",
            "Pyrolysis cracks mixed polymer chains back into basic hydrocarbon feedstocks (alkanes, alkenes) that can be purified and re-polymerised into 100% virgin-grade polymers, avoiding the degradation and immiscibility issues of mechanical re-melting.",
            "Pyrolysis uses zero energy.",
            "Pyrolysis converts plastic into pure drinking water.",
            "Pyrolysis requires no sorting or heating.",
            "Option A is correct. Mechanical recycling suffers from two major limitations: (1) different polymers are immiscible and difficult to sort completely; (2) repeated heating causes chain scission and degradation ('downcycling'). In contrast, chemical feedstock recycling (pyrolysis in an oxygen-free chamber) thermally cracks polymer chains down to small hydrocarbon feedstocks and monomers, which can be refined and polymerised to yield virgin-quality plastics indistinguishable from newly manufactured petroleum plastics."
        )
    ]

    for q in hf_data:
        add_q(
            q[0], q[1], q[2], q[3], q[4], q[5], q[6], q[7], q[8], q[9]
        )

    # Balance Answer Keys Uniformly across A, B, C, D
    keys_pattern = (['B', 'D', 'A', 'C', 'A', 'D', 'B', 'C', 'B', 'A', 'D', 'C', 'A', 'C', 'B', 'D', 'C', 'A', 'D', 'B'] * 5) + ['C', 'A', 'D', 'B', 'A', 'C', 'B', 'D', 'A', 'C']

    balanced_questions = []
    idx_to_letter = {0: 'A', 1: 'B', 2: 'C', 3: 'D'}
    letter_to_idx = {'A': 0, 'B': 1, 'C': 2, 'D': 3}

    for i, q in enumerate(questions_code):
        target_key = keys_pattern[i]
        target_idx = letter_to_idx[target_key]

        raw_opts = [opt.split(": ", 1)[1] for opt in q["options"]]
        correct_opt_raw = raw_opts[0]
        distractors_raw = raw_opts[1:]

        new_raw_options = [None] * 4
        new_raw_options[target_idx] = correct_opt_raw

        old_to_new = {'A': target_key}
        distractor_slots = [j for j in range(4) if j != target_idx]
        d_idx = 0
        for old_idx, old_letter in enumerate(['B', 'C', 'D']):
            slot = distractor_slots[d_idx]
            new_raw_options[slot] = distractors_raw[old_idx]
            new_letter = idx_to_letter[slot]
            old_to_new[old_letter] = new_letter
            d_idx += 1

        formatted_options = [f"{idx_to_letter[slot]}: {new_raw_options[slot]}" for slot in range(4)]

        temp_exp = q["explanation"]
        for l in ['A', 'B', 'C', 'D']:
            temp_exp = temp_exp.replace(f"Option {l}", f"__OPT_{l}__")
        for l in ['A', 'B', 'C', 'D']:
            temp_exp = temp_exp.replace(f"__OPT_{l}__", f"Option {old_to_new[l]}")

        balanced_questions.append({
            "number": q["number"],
            "title": q["title"],
            "syllabus_ref": q["syllabus_ref"],
            "difficulty": q["difficulty"],
            "stem": q["stem"],
            "options": formatted_options,
            "correct_answer": target_key,
            "explanation": temp_exp,
            "figure_path": q["figure_path"],
            "figure_caption": q["figure_caption"]
        })

    # Write output to mcq_topic20_data.py
    out_file = r"z:\tests n quizes63\books\psycology\new styl\mcq_topic20_data.py"
    with open(out_file, "w", encoding="utf-8") as f:
        f.write('"""\nCurated 110 Authentic Cambridge AS Chemistry (9701) Paper 1 MCQs\nfor Topic 20: Polymerisation (Addition Polymers) (100 Core + 10 High-Frequency Core Repeats).\n"""\n\n')
        f.write("from build_mcq_topic_pdf import MCQQuestion\n\n")
        f.write("TOPIC_20_MCQ_QUESTIONS = [\n")
        for q in balanced_questions:
            f.write("    MCQQuestion(\n")
            f.write(f"        number={q['number']},\n")
            f.write(f"        title={repr(q['title'])},\n")
            f.write(f"        syllabus_ref={repr(q['syllabus_ref'])},\n")
            f.write(f"        difficulty={repr(q['difficulty'])},\n")
            f.write(f"        stem={repr(q['stem'])},\n")
            f.write(f"        options={repr(q['options'])},\n")
            f.write(f"        correct_answer={repr(q['correct_answer'])},\n")
            f.write(f"        explanation={repr(q['explanation'])},\n")
            f.write(f"        figure_path={repr(q['figure_path'])},\n")
            f.write(f"        figure_caption={repr(q['figure_caption'])}\n")
            f.write("    ),\n")
        f.write("]\n")

    print(f"Successfully generated mcq_topic20_data.py with {len(balanced_questions)} MCQs!")

if __name__ == "__main__":
    create_topic20_data()
