"""
Curated 110 Authentic Cambridge AS Chemistry (9701) Paper 1 MCQs
for Topic 16: Hydroxy Compounds (Alcohols) (100 Core + 10 High-Frequency Core Repeats).
"""

from build_mcq_topic_pdf import MCQQuestion

TOPIC_16_MCQ_QUESTIONS = [
    MCQQuestion(
        number=1,
        title='Classification of Alcohols as Primary, Secondary, or Tertiary — 9701/11/M/J/23/Q23',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Which of the following compounds is classified as a tertiary alcohol?',
        options=['A: 2-methylbutan-1-ol, CH3CH2CH(CH3)CH2OH', 'B: 2-methylbutan-2-ol, CH3-C(CH3)(OH)-CH2CH3', 'C: 3-methylbutan-2-ol, (CH3)2CH-CH(OH)-CH3', 'D: Pentan-3-ol, CH3CH2CH(OH)CH2CH3'],
        correct_answer='B',
        explanation='Option B is correct. An alcohol is classified based on the number of carbon atoms directly bonded to the carbinol carbon (the carbon bearing the -OH group). In 2-methylbutan-2-ol, the carbinol carbon is bonded to three other carbons (two methyl groups and one ethyl group), making it a tertiary (3°) alcohol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=2,
        title='Intermolecular Hydrogen Bonding and Boiling Point Trend — 9701/12/M/J/23/Q23',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Ethanol (Mr = 46.0) has a boiling point of 78.4 °C, whereas propane (Mr = 44.0) has a boiling point of -42.1 °C.\n\nWhat accounts for this enormous difference in boiling points?',
        options=['A: Ethanol has significantly stronger London dispersion forces due to its larger electron cloud.', 'B: Propane contains permanent dipole-dipole attractions that repel molecules.', 'C: Ethanol undergoes spontaneous dimerization through covalent bonding.', 'D: Ethanol molecules form strong intermolecular hydrogen bonds between the delta- oxygen and delta+ hydrogen of the hydroxyl (-OH) groups.'],
        correct_answer='D',
        explanation="Option D is correct. The O-H bond in ethanol is highly polar due to oxygen's high electronegativity. The lone pair on oxygen forms intermolecular hydrogen bonds with the delta+ hydrogen of neighboring ethanol molecules. Hydrogen bonds are significantly stronger than the weak London dispersion forces present between non-polar propane molecules, requiring much more thermal energy to separate.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=3,
        title='Reaction of Alcohols with Sodium Metal — 9701/13/M/J/23/Q23',
        syllabus_ref='16.1',
        difficulty='MEDIUM',
        stem='When small pieces of clean sodium metal are added to dry propan-1-ol, what is observed and what are the products?',
        options=['A: Gentle effervescence of hydrogen gas (H2) and formation of a colorless solution of sodium propoxide (CH3CH2CH2O- Na+).', 'B: Violent explosion with the liberation of oxygen gas.', 'C: Immediate formation of a white precipitate of sodium hydride.', 'D: Evolution of steamy acidic fumes of hydrogen chloride gas.'],
        correct_answer='A',
        explanation='Option A is correct. Alcohols react with sodium metal in a gentle redox reaction (much less vigorously than water does with sodium): 2ROH + 2Na -> 2RONa + H2(g). The acidic proton of the -OH group is reduced to hydrogen gas (tested with a squeaky pop), leaving the strongly basic alkoxide salt (sodium propoxide).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=4,
        title='Testing for Hydroxyl Groups with Phosphorus(V) Chloride — 9701/11/O/N/23/Q23',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What is the diagnostic observation when solid phosphorus(V) chloride, PCl5, is added to an anhydrous sample of butan-1-ol?',
        options=['A: Formation of a canary yellow precipitate of silver chloride.', 'B: An orange to green color change without any gas evolution.', 'C: Vigorous reaction with the evolution of steamy acidic fumes of hydrogen chloride gas (HCl) that turn damp blue litmus red.', 'D: A sweet fruity aroma of an ester.'],
        correct_answer='C',
        explanation='Option C is correct. PCl5 reacts immediately with hydroxyl groups at room temperature: ROH + PCl5 -> RCl + POCl3 + HCl(g). Steamy, choking acidic fumes of HCl gas are evolved, which turn damp blue litmus paper red and give dense white smoke of NH4Cl when held near a glass rod dipped in concentrated ammonia.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=5,
        title='Water Solubility Trend of Alcohols — 9701/13/M/J/220/Q5',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why are methanol, ethanol, and propan-1-ol completely miscible with water in all proportions, while hexan-1-ol is practically insoluble?',
        options=["A: The small alkyl group allows the -OH group to form extensive hydrogen bonds with water molecules, but in hexan-1-ol the long non-polar hydrophobic hydrocarbon chain disrupts water's hydrogen bond network.", 'B: Hexan-1-ol has a higher density than water.', 'C: Methanol reacts chemically with water to form carbonic acid.', 'D: Hexan-1-ol contains no hydroxyl groups.'],
        correct_answer='A',
        explanation='Option A is correct. Lower alcohols form favorable hydrogen bonds with water. As chain length increases, the non-polar hydrophobic alkyl chain dominates, requiring energy to disrupt water-water hydrogen bonds without sufficient compensating solute-solvent interactions, drastically reducing solubility.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=6,
        title='Industrial Preparation of Ethanol via Hydration — 9701/11/M/J/221/Q6',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What are the industrial conditions used to convert ethene into ethanol?',
        options=['A: Liquid water at 25 °C with nickel catalyst.', 'B: Concentrated sulfuric acid at 200 °C and 1 atm.', 'C: Hydrogen gas and carbon dioxide at 500 °C.', 'D: Steam (H2O(g)) at 300 °C and 60 atm pressure over a concentrated phosphoric(V) acid (H3PO4) catalyst.'],
        correct_answer='D',
        explanation='Option D is correct. Direct catalytic hydration of ethene uses steam at 300 °C, 60-70 atm pressure, and solid phosphoric(V) acid supported on porous silica pellets: C2H4(g) + H2O(g) <=> C2H5OH(g) (exothermic reversible reaction).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=7,
        title='Manufacture of Bioethanol via Fermentation — 9701/12/M/J/222/Q7',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What are the conditions required for the enzyme-catalyzed fermentation of aqueous glucose into ethanol?',
        options=['A: Pure oxygen bubbling through boiling glucose at 100 °C.', 'B: Aqueous glucose solution, yeast (containing zymase), anaerobic conditions (absence of air), and temperature around 35-37 °C.', 'C: High pressure of 100 atm and iron catalyst.', 'D: Ultraviolet light and dilute nitric acid.'],
        correct_answer='B',
        explanation='Option B is correct. Yeast produces the enzyme complex zymase that converts glucose into ethanol and CO2: C6H12O6 -> 2C2H5OH + 2CO2. Temperature must be kept ~35-37 °C (enzymes denature above 40 °C) in the strict absence of oxygen (anaerobic, to prevent oxidation of ethanol to ethanoic acid).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=8,
        title='Substitution of Alcohols with Thionyl Chloride — 9701/13/M/J/223/Q8',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What are the products when propan-2-ol reacts with thionyl chloride, SOCl2?',
        options=['A: 1-chloropropane, sulfur, and water', 'B: Propanone, sulfurous acid, and chlorine', 'C: 2-chloropropane, sulfur dioxide (SO2), and hydrogen chloride (HCl)', 'D: Propene, sulfuric acid, and hydrochloric acid'],
        correct_answer='C',
        explanation='Option C is correct. Reaction: CH3CH(OH)CH3 + SOCl2 -> CH3CH(Cl)CH3 + SO2(g) + HCl(g). Both byproducts are gases that escape, leaving pure 2-chloropropane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=9,
        title='Substitution of Alcohols with Hydrogen Bromide — 9701/11/M/J/224/Q9',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='How is bromoethane synthesized from ethanol in the laboratory?',
        options=['A: Bubbling bromine gas through cold ethanol.', 'B: Heating ethanol with sodium bromide and 50% concentrated sulfuric acid under reflux.', 'C: Adding dilute hydrobromic acid at room temperature.', 'D: Heating ethanol with silver bromide.'],
        correct_answer='B',
        explanation='Option B is correct. Solid NaBr reacts with 50% H2SO4 to generate HBr gas in situ: NaBr + H2SO4 -> NaHSO4 + HBr. The HBr then reacts with ethanol under reflux: C2H5OH + HBr -> C2H5Br + H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=10,
        title='Substitution of Alcohols with Phosphorus(III) Halides — 9701/12/M/J/220/Q10',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What are the products when three moles of methanol react with one mole of phosphorus(III) chloride, PCl3?',
        options=['A: Three moles of chloromethane (CH3Cl) and one mole of phosphorous acid (H3PO3)', 'B: Three moles of chloromethane, phosphorus, and chlorine gas', 'C: One mole of trimethyl phosphate and three moles of HCl', 'D: Methanoic acid and PH3'],
        correct_answer='A',
        explanation='Option A is correct. Reaction: 3CH3OH + PCl3 -> 3CH3Cl + H3PO3 (phosphorous acid). PCl3 provides a milder halogenation without producing gaseous HCl.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=11,
        title='Acidity of Alcohols vs Water — 9701/13/M/J/221/Q11',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='How does the acid strength (Ka) of ethanol compare with that of pure water, and why?',
        options=['A: Ethanol is much stronger acid than water because it has more hydrogen atoms.', 'B: Ethanol has identical acidity to water.', 'C: Ethanol is a strong acid that fully dissociates in water.', 'D: Ethanol is slightly weaker acid than water because the electron-donating (+I) ethyl group increases electron density on oxygen, destabilizing the ethoxide anion.'],
        correct_answer='D',
        explanation='Option D is correct. In the ethoxide ion (C2H5O-), the +I inductive effect of the alkyl group pushes electron density onto the negative oxygen atom, intensifying the negative charge and making ethoxide less stable than hydroxide (OH-). Hence, ethanol is a weaker acid than water (pKa ~16 vs 14).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=12,
        title='Combustion of Bioethanol — 9701/11/M/J/222/Q12',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What volume of oxygen gas (measured at RTP) is required for the complete combustion of 1.0 mol of ethanol?',
        options=['A: 24.0 dm^3 (1.0 mole of O2)', 'B: 48.0 dm^3 (2.0 moles of O2)', 'C: 72.0 dm^3 (3.0 moles of O2)', 'D: 120.0 dm^3 (5.0 moles of O2)'],
        correct_answer='C',
        explanation='Option C is correct. Combustion equation: C2H5OH(l) + 3O2(g) -> 2CO2(g) + 3H2O(l). Exactly 3.0 moles of O2 are needed per mole of ethanol. At RTP, 3.0 mol * 24.0 dm^3/mol = 72.0 dm^3.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=13,
        title='Boiling Point Comparison of Isomeric Butanols — 9701/12/M/J/223/Q13',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Which of the isomeric butanols has the LOWEST boiling point, and what explains this?',
        options=['A: 2-methylpropan-2-ol (82 °C), because its compact spherical shape provides the least surface area for London dispersion forces.', 'B: Butan-1-ol (117 °C), because it is straight-chain.', 'C: Butan-2-ol (99 °C), because it is secondary.', 'D: 2-methylpropan-1-ol (108 °C), because it contains a methyl branch.'],
        correct_answer='A',
        explanation='Option A is correct. All four isomers have one -OH group forming hydrogen bonds. However, 2-methylpropan-2-ol is spherical and compact, giving minimum surface contact area between molecules. This weakens the auxiliary London dispersion forces, giving it the lowest boiling point (82 °C) compared to linear butan-1-ol (117 °C).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=14,
        title='Reactivity of Alcohols with P and I2 — 9701/13/M/J/224/Q14',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='How is 1-iodobutane prepared from butan-1-ol?',
        options=['A: Heating butan-1-ol with potassium iodide and concentrated sulfuric acid.', 'B: Adding iodine crystals to butan-1-ol at 0 °C.', 'C: Warming butan-1-ol with red phosphorus and iodine (generating PI3 in situ).', 'D: Bubbling hydrogen iodide gas into pure butan-1-ol.'],
        correct_answer='C',
        explanation='Option C is correct. PI3 is prepared in situ by refluxing red phosphorus and iodine: 2P + 3I2 -> 2PI3. Then: 3C4H9OH + PI3 -> 3C4H9I + H3PO3.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=15,
        title='Reaction of Tertiary Alcohols with Concentrated HCl — 9701/11/M/J/220/Q15',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why does 2-methylpropan-2-ol react rapidly with concentrated hydrochloric acid at room temperature without requiring a catalyst?',
        options=['A: Tertiary alcohols are strong bases that neutralize HCl.', 'B: It readily forms a stable tertiary carbocation intermediate via an SN1 pathway, rapidly capturing chloride ions.', 'C: The C-O bond in tertiary alcohols is pure ionic.', 'D: Concentrated HCl is an oxidizing agent for tertiary alcohols.'],
        correct_answer='B',
        explanation='Option B is correct. Tertiary alcohols are readily protonated to form (CH3)3C-OH2+. Loss of water yields the stable 3° carbocation (CH3)3C+, which is immediately attacked by Cl- to precipitate insoluble 2-chloro-2-methylpropane (the basis of the Lucas test).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=16,
        title='Lucas Test for Alcohol Classification — 9701/12/M/J/221/Q16',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='In the Lucas test (concentrated HCl with anhydrous ZnCl2 catalyst), which class of alcohol forms an insoluble oily layer of chloroalkane almost instantaneously at room temperature?',
        options=['A: Primary alcohols (cloudiness after several hours or heating)', 'B: Secondary alcohols (cloudiness in 5-10 minutes)', 'C: Phenols (no reaction)', 'D: Tertiary alcohols (instant cloudiness/oily layer within 30 seconds)'],
        correct_answer='D',
        explanation='Option D is correct. Tertiary alcohols react immediately via SN1 to yield the insoluble tertiary alkyl chloride, causing instant turbidity/cloudiness. Secondary alcohols take 5-10 minutes, and primary alcohols do not react at room temperature.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=17,
        title='Viscosity of Polyhydric Alcohols — 9701/13/M/J/222/Q17',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why is propane-1,2,3-triol (glycerol) an extremely viscous, syrup-like liquid compared to propan-1-ol?',
        options=['A: Glycerol has a cyclic ring structure.', 'B: Glycerol contains double bonds that lock rotation.', 'C: Each molecule contains three hydroxyl (-OH) groups, creating a dense, three-dimensional network of intermolecular hydrogen bonds that restricts molecular flow.', 'D: Glycerol forms ionic bonds with itself.'],
        correct_answer='C',
        explanation='Option C is correct. Glycerol (HOCH2-CH(OH)-CH2OH) has three -OH groups per molecule, allowing extensive multi-directional intermolecular hydrogen bonding that physically cross-links adjacent molecules, producing very high viscosity.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=18,
        title='Alkoxide Formation and Basicity — 9701/11/M/J/223/Q18',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What is the relative base strength of the ethoxide ion (CH3CH2O-) compared to the hydroxide ion (OH-)?',
        options=['A: Ethoxide is a stronger base than hydroxide.', 'B: Ethoxide is a weaker base than hydroxide.', 'C: Both have identical basicity.', 'D: Ethoxide is a neutral species.'],
        correct_answer='A',
        explanation='Option A is correct. Because ethanol is a weaker acid than water (due to the +I inductive electron release of the ethyl group), its conjugate base, the ethoxide ion, is significantly more basic than the hydroxide ion.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=19,
        title='Reaction of Sodium with Diols — 9701/12/M/J/224/Q19',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='How many moles of hydrogen gas (H2) are evolved when one mole of ethane-1,2-diol reacts with an excess of sodium metal?',
        options=['A: 0.5 mole of H2', 'B: 2.0 moles of H2', 'C: 1.5 moles of H2', 'D: 1.0 mole of H2 (24.0 dm^3 at RTP)'],
        correct_answer='D',
        explanation='Option D is correct. Ethane-1,2-diol possesses two hydroxyl groups: HO-CH2-CH2-OH + 2Na -> NaO-CH2-CH2-ONa + H2(g). One mole of diol releases one mole of H2 gas.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=20,
        title='Preparation of Alcohols from Esters — 9701/13/M/J/220/Q20',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Which reaction converts an ester (e.g. ethyl ethanoate) into an alcohol and a carboxylic acid salt?',
        options=['A: Oxidation with acidified potassium dichromate', 'B: Alkaline hydrolysis (heating under reflux with aqueous sodium hydroxide)', 'C: Dehydration with concentrated sulfuric acid', 'D: Electrophilic addition with steam'],
        correct_answer='B',
        explanation='Option B is correct. Saponification / alkaline hydrolysis of an ester: CH3COOCH2CH3 + NaOH -> CH3COONa + CH3CH2OH. The alcohol is liberated cleanly and separated by fractional distillation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=21,
        title='Physical State of Small Alcohols — 9701/11/M/J/221/Q21',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why are methanol and ethanol liquids at room temperature, while chloromethane and chloroethane are gases, despite having higher molecular masses?',
        options=['A: Chloromethane has no dipole moment.', 'B: Alcohols form intermolecular hydrogen bonds that require substantial energy to overcome; chloroalkanes only form weaker dipole-dipole attractions.', 'C: Ethanol has a larger molecular size.', 'D: Chloroethane molecules repel each other.'],
        correct_answer='B',
        explanation='Option B is correct. Hydrogen bonding in alcohols (~20 kJ/mol) is several times stronger than permanent dipole-dipole forces (~3 kJ/mol) in haloalkanes. Consequently, methanol (bp 65 °C) and ethanol (bp 78 °C) are liquids, whereas CH3Cl (bp -24 °C) and C2H5Cl (bp 12 °C) are gases.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=22,
        title='Classification of Menthol — 9701/12/M/J/222/Q22',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Menthol contains the group -CH(OH)- attached to two ring carbons. What class of alcohol is menthol?',
        options=['A: Primary alcohol', 'B: Tertiary alcohol', 'C: Phenol', 'D: Secondary alcohol'],
        correct_answer='D',
        explanation='Option D is correct. Because the carbon bearing the -OH group is bonded to two adjacent ring carbon atoms and one hydrogen atom, it is classified as a secondary alcohol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=23,
        title='Classification of Cholesterol — 9701/13/M/J/223/Q23',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='In cholesterol, the -OH group is attached to a cyclohexane ring carbon that is bonded to two other ring carbons and one hydrogen. What is its classification?',
        options=['A: Secondary alcohol', 'B: Primary alcohol', 'C: Tertiary alcohol', 'D: Phenol'],
        correct_answer='A',
        explanation='Option A is correct. A carbinol carbon bonded to two carbons and one hydrogen is a secondary alcohol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=24,
        title='Identification of Alcohols by Sodium Effervescence — 9701/11/M/J/224/Q24',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='A neutral liquid reacts with sodium metal to evolve hydrogen gas, but does NOT react with 2,4-dinitrophenylhydrazine. What functional group is present?',
        options=['A: Aldehyde (-CHO)', 'B: Carboxylic acid (-COOH)', 'C: Alcohol (-OH)', 'D: Ketone (>C=O)'],
        correct_answer='C',
        explanation='Option C is correct. Alcohols are neutral liquids that react with sodium metal to evolve H2 gas (2ROH + 2Na -> 2RONa + H2). Because it does not react with 2,4-DNPH (which tests for carbonyl groups) and is neutral (carboxylic acids are acidic), it must be an alcohol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=25,
        title='Combustion Heat of Alcohol Homologues — 9701/12/M/J/220/Q25',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='How does the enthalpy of combustion of alcohols change per additional -CH2- group in the homologous series?',
        options=['A: It becomes more exothermic by approximately -650 kJ mol^-1 per -CH2- unit.', 'B: It becomes endothermic.', 'C: It decreases to zero.', 'D: It remains exactly constant.'],
        correct_answer='A',
        explanation='Option A is correct. Each additional methylene group (-CH2-) requires 1.5 more O2 molecules and forms one more CO2 and one more H2O, contributing an approximately constant increment of -650 kJ/mol to the heat of combustion.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=26,
        title='Safety of Methanol Toxicity — 9701/13/M/J/221/Q26',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Why is methanol (CH3OH) highly toxic to humans if ingested, causing blindness and death?',
        options=['A: Methanol reacts with stomach acid to form hydrogen cyanide.', 'B: Methanol freezes cellular water immediately.', 'C: Methanol precipitates insoluble copper salts in the blood.', 'D: Liver enzymes (alcohol dehydrogenase) oxidize methanol into methanal (formaldehyde) and methanoic acid (formic acid), which attack retinal cells and cause severe metabolic acidosis.'],
        correct_answer='D',
        explanation='Option D is correct. Methanol is metabolized by alcohol dehydrogenase into formaldehyde (a tissue fixative) and formic acid, which inhibits cytochrome oxidase and destroys the optic nerve, causing permanent blindness and fatal acidosis.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=27,
        title='Ethanol as a Fuel Additive — 9701/11/M/J/222/Q27',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why is bioethanol blended with petrol (e.g. E10 fuel) in modern automotive transport?',
        options=['A: It prevents water from boiling in the radiator.', 'B: It increases the octane rating, reduces net fossil CO2 emissions (carbon neutral cycle), and introduces oxygen to ensure cleaner combustion.', 'C: It makes petrol completely non-flammable.', 'D: It reduces engine temperature to 0 °C.'],
        correct_answer='B',
        explanation='Option B is correct. Ethanol has a high octane number (~108), reducing engine knock. As an oxygenated fuel, it promotes complete combustion, lowering toxic CO and hydrocarbon emissions, while being derived from renewable plant sugars.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=28,
        title='Hydrolysis of Primary Haloalkanes — 9701/12/M/J/223/Q28',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What are the reagents and conditions to produce propan-1-ol from 1-chloropropane with high yield?',
        options=['A: Heat with concentrated ethanolic potassium hydroxide.', 'B: Warm with concentrated sulfuric acid.', 'C: Heat under reflux with dilute aqueous sodium hydroxide, NaOH(aq).', 'D: Expose to ultraviolet light.'],
        correct_answer='C',
        explanation='Option C is correct. Aqueous NaOH under reflux provides the nucleophile (:OH-) in a polar aqueous environment, favoring substitution over elimination and giving propan-1-ol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=29,
        title='Reaction of Alcohols with Anhydrous Zinc Chloride and HCl — 9701/13/M/J/224/Q29',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What is the purpose of anhydrous ZnCl2 in the Lucas reagent (ZnCl2 in conc. HCl)?',
        options=['A: It absorbs evolved hydrogen gas.', 'B: It acts as a Lewis acid catalyst that coordinates to the hydroxyl oxygen, converting -OH into a better leaving group.', 'C: It oxidizes the alcohol to an aldehyde.', 'D: It precipitates sodium chloride.'],
        correct_answer='B',
        explanation='Option B is correct. The Zn2+ ion is an electron-pair acceptor (Lewis acid) that coordinates to the lone pair of the -OH oxygen. This weakens the C-O bond and creates a superior leaving group, accelerating nucleophilic attack by Cl-.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=30,
        title='Reactivity: Primary vs Tertiary with PCl5 — 9701/11/M/J/220/Q30',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='How do primary, secondary, and tertiary alcohols behave when treated with PCl5?',
        options=['A: All three classes react vigorously at room temperature to evolve steamy acidic fumes of HCl.', 'B: Only primary alcohols react.', 'C: Only tertiary alcohols react.', 'D: None react without heating to 200 °C.'],
        correct_answer='A',
        explanation='Option A is correct. The reaction with PCl5 is a general diagnostic test for the -OH group: primary, secondary, and tertiary alcohols all react vigorously at room temperature to replace -OH with -Cl and evolve HCl gas.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=31,
        title='Preparation of Ethanol from Ethene Atom Economy — 9701/12/M/J/221/Q31',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What is the percentage atom economy for the industrial hydration of ethene to ethanol (C2H4 + H2O -> C2H5OH)?',
        options=['A: 50%', 'B: 78%', 'C: 85%', 'D: 100%'],
        correct_answer='D',
        explanation='Option D is correct. In an addition reaction, all reactant atoms are incorporated into the single desired product: Atom Economy = (Mr of ethanol / total Mr of reactants) * 100 = (46 / 46) * 100 = 100%.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=32,
        title='Hydrogen Bonding in Ethanol vs Dimethyl Ether — 9701/13/M/J/222/Q32',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Ethanol (CH3CH2OH) and dimethyl ether (CH3OCH3) have the same formula C2H6O. Why does dimethyl ether boil at -24 °C while ethanol boils at +78 °C?',
        options=['A: Dimethyl ether has no oxygen atom.', 'B: Ethanol has a higher molecular mass.', 'C: Ethanol forms intermolecular hydrogen bonds; dimethyl ether lacks an O-H bond and can only form weak dipole-dipole attractions.', 'D: Dimethyl ether forms covalent network crystals.'],
        correct_answer='C',
        explanation='Option C is correct. Hydrogen bonding requires a hydrogen atom covalently bonded to a highly electronegative atom (N, O, F). Ethanol has an -OH group and forms strong hydrogen bonds. In dimethyl ether, all hydrogens are bonded to carbon (C-H), so no hydrogen bonding can occur between ether molecules.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=33,
        title='Reaction of Alcohols with Acyl Chlorides — 9701/11/M/J/223/Q33',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What products are formed when ethanol reacts with ethanoyl chloride, CH3COCl, at room temperature?',
        options=['A: Ethyl ethanoate (an ester) and steamy fumes of hydrogen chloride (HCl)', 'B: Ethanoic acid and chloroethane', 'C: Diethyl ether and water', 'D: Ethanal and chlorine gas'],
        correct_answer='A',
        explanation='Option A is correct. Alcohols react vigorously with acyl chlorides at room temperature: CH3COCl + C2H5OH -> CH3COOC2H5 + HCl(g). This provides an irreversible, high-yield route to esters without requiring an acid catalyst.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=34,
        title='Reaction of Alcohols with Acid Anhydrides — 9701/12/M/J/224/Q34',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What is formed when ethanol is warmed with ethanoic anhydride, (CH3CO)2O?',
        options=['A: Diethyl ether and water', 'B: Chloroethane and ethanoic acid', 'C: Ethyl ethanoate (ester) and ethanoic acid', 'D: Ethanal and ethyl ethanoate'],
        correct_answer='C',
        explanation='Option C is correct. Acid anhydrides react smoothly with alcohols upon gentle warming: (CH3CO)2O + C2H5OH -> CH3COOC2H5 + CH3COOH. The reaction is irreversible and produces no corrosive HCl fumes.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=35,
        title='Boiling Point of Diols vs Mono-alcohols — 9701/13/M/J/220/Q35',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why does ethane-1,2-diol have a much higher boiling point (197 °C) than propan-1-ol (97 °C) despite having very similar molecular masses (62 vs 60)?',
        options=['A: Ethane-1,2-diol contains double bonds.', 'B: Ethane-1,2-diol has two -OH groups per molecule, forming twice as many intermolecular hydrogen bonds.', 'C: Propan-1-ol is completely non-polar.', 'D: Ethane-1,2-diol is a solid polymer.'],
        correct_answer='B',
        explanation='Option B is correct. Ethane-1,2-diol possesses two hydroxyl groups per molecule. Each molecule can donate two hydrogen bonds and accept two hydrogen bonds, forming an extensive intermolecular network that requires immense thermal energy to break.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=36,
        title='Density of Alcohols — 9701/11/M/J/221/Q36',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Why are liquid mono-alcohols (C1 to C8) less dense than water (densities ~0.79 to 0.82 g/cm^3)?',
        options=['A: Alcohols contain air pockets in their liquid structure.', 'B: Hydrogen bonds push molecules far apart.', 'C: Water has heavier atoms than alcohol.', 'D: The bulky, low-density alkyl hydrocarbon chain occupies significant molecular volume relative to atomic mass.'],
        correct_answer='D',
        explanation='Option D is correct. Alkanes and aliphatic alcohols are composed predominantly of light carbon (12) and hydrogen (1) atoms packed in open arrangements; their densities are less than 1.0 g/cm^3.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=37,
        title='Reaction of Alcohols with Phosphorus(V) Oxide — 9701/12/M/J/222/Q37',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What happens when an alcohol is treated with phosphorus(V) oxide, P4O10?',
        options=['A: It forms a phosphate ester exclusively.', 'B: It oxidizes the alcohol to a carboxylic acid.', 'C: P4O10 acts as a powerful dehydrating agent, converting the alcohol into an alkene and phosphoric acid.', 'D: It reduces the alcohol to an alkane.'],
        correct_answer='C',
        explanation='Option C is correct. P4O10 has an extraordinary affinity for water. It dehydrates alcohols to alkenes: 4ROH + P4O10 -> 4(alkene) + 4HPO3.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=38,
        title='Classification of Benzyl Alcohol — 9701/13/M/J/223/Q38',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What class of alcohol is phenylmethanol (benzyl alcohol, C6H5-CH2OH)?',
        options=['A: Primary alcohol', 'B: Phenol', 'C: Secondary alcohol', 'D: Tertiary alcohol'],
        correct_answer='A',
        explanation='Option A is correct. In phenylmethanol, the -OH group is attached to an aliphatic -CH2- carbon (which is bonded to one aromatic ring carbon and two hydrogens). Because the carbinol carbon is bonded to only one other carbon, it is a primary alcohol (NOT a phenol).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=39,
        title='Phenol vs Aliphatic Alcohol — 9701/11/M/J/224/Q39',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why is phenol (C6H5OH) chemically distinct from an aliphatic alcohol like cyclohexanol?',
        options=['A: Phenol contains no oxygen atoms.', 'B: Cyclohexanol has a planar ring.', 'C: Phenol is an aliphatic alkane.', "D: In phenol, the -OH group is bonded directly to an aromatic benzene ring, allowing oxygen's lone pair to delocalise into the pi ring, making phenol significantly more acidic."],
        correct_answer='D',
        explanation='Option D is correct. In phenol, the unshared p orbital lone pair on oxygen overlaps with the delocalized aromatic pi cloud. This stabilizes the phenoxide ion (C6H5O-), making phenol ~1 million times more acidic than aliphatic alcohols and giving it unique aromatic chemistry.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=40,
        title='Reactivity with Hydrogen Halides: 3° vs 2° vs 1° — 9701/12/M/J/220/Q40',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What is the order of reactivity of alcohols towards substitution with concentrated HCl?',
        options=['A: Primary > Secondary > Tertiary', 'B: Tertiary > Secondary > Primary', 'C: All alcohols react at identical rates.', 'D: Secondary > Primary > Tertiary'],
        correct_answer='B',
        explanation='Option B is correct. Tertiary alcohols react fastest because protonation is followed by rapid loss of water to form a stable 3° carbocation (SN1). Primary alcohols must proceed via slow SN2 substitution and require heating with ZnCl2 catalyst.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=41,
        title='Preparation of Alcohols from Carbonyls using NaBH4 — 9701/13/M/J/221/Q41',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What type of alcohol is produced by the reduction of an aldehyde and a ketone respectively using sodium borohydride (NaBH4)?',
        options=['A: Aldehydes reduce to secondary alcohols; ketones reduce to tertiary alcohols.', 'B: Aldehydes reduce to primary alcohols; ketones reduce to secondary alcohols.', 'C: Both reduce to tertiary alcohols.', 'D: Both reduce to carboxylic acids.'],
        correct_answer='B',
        explanation="Option B is correct. Hydride reduction of aldehydes (R-CHO) yields primary alcohols (R-CH2OH). Hydride reduction of ketones (R-CO-R') yields secondary alcohols (R-CH(OH)-R'). Tertiary alcohols cannot be formed by reduction of carbonyl compounds.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=42,
        title='Preparation of Alcohols from Carboxylic Acids — 9701/11/M/J/222/Q42',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Which reducing agent is required to reduce a carboxylic acid (e.g. ethanoic acid) directly to a primary alcohol (ethanol)?',
        options=['A: Sodium borohydride (NaBH4) in aqueous ethanol', 'B: Hydrogen gas with nickel catalyst at 20 °C', 'C: Acidified potassium dichromate(VI)', 'D: Lithium aluminium hydride (LiAlH4) in dry ether'],
        correct_answer='D',
        explanation='Option D is correct. Carboxylic acids are resistant to mild reducing agents like NaBH4. The powerful reducing agent LiAlH4 in anhydrous ether is required to reduce the -COOH group to a primary alcohol (-CH2OH): RCOOH + 4[H] -> RCH2OH + H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=43,
        title='Fermentation Atom Economy — 9701/12/M/J/223/Q43',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='In the fermentation of glucose to ethanol (C6H12O6 -> 2C2H5OH + 2CO2), why is the atom economy only 51.1%?',
        options=['A: Carbon dioxide (CO2) is produced as an unavoidable byproduct, accounting for 48.9% of the mass of reactants.', 'B: Ethanol evaporates during the reaction.', 'C: Glucose is not completely pure.', 'D: Water is eliminated.'],
        correct_answer='A',
        explanation='Option A is correct. Atom economy = (Mass of 2C2H5OH / Mass of C6H12O6) * 100 = (2 * 46 / 180) * 100 = 92 / 180 = 51.1%. Almost half the mass is lost as carbon dioxide byproduct.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=44,
        title='Lucas Test Observation for Secondary Alcohol — 9701/13/M/J/224/Q44',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What visual change is seen when butan-2-ol is treated with Lucas reagent (ZnCl2 in conc. HCl) at room temperature?',
        options=['A: An immediate white precipitate within 5 seconds.', 'B: No reaction occurs even after 24 hours.', 'C: The clear solution becomes cloudy within 5 to 10 minutes as insoluble 2-chlorobutane droplets separate.', 'D: The solution turns vivid green.'],
        correct_answer='C',
        explanation='Option C is correct. Secondary alcohols react moderately fast via the SN1 pathway; the solution turns cloudy/turbid within 5 to 10 minutes as the insoluble chloroalkane separates into a separate oily layer.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=45,
        title='Solubility of Alcohols in Non-Polar Solvents — 9701/11/M/J/220/Q45',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why does octan-1-ol dissolve readily in hexane but poorly in water?',
        options=['A: The long non-polar octyl chain forms favorable London dispersion forces with hexane molecules, while it cannot form favorable interactions with water.', 'B: Hexane forms hydrogen bonds with octan-1-ol.', 'C: Octan-1-ol reacts with hexane to form an ester.', 'D: Water repels all organic molecules.'],
        correct_answer='A',
        explanation='Option A is correct. Octan-1-ol is predominantly a hydrophobic hydrocarbon chain. Mixing with hexane involves breaking weak London forces and forming similar London forces (delta-H ~ 0), making dissolution thermodynamically favorable.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=46,
        title='Classification of 2-methylpropan-1-ol — 9701/12/M/J/221/Q46',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='What is the structural classification of 2-methylpropan-1-ol, (CH3)2CH-CH2OH?',
        options=['A: Secondary alcohol', 'B: Tertiary alcohol', 'C: Phenol', 'D: Primary alcohol'],
        correct_answer='D',
        explanation='Option D is correct. The carbinol carbon (-CH2OH) is bonded to only one other carbon atom (the CH group), making it a primary alcohol, even though the adjacent carbon is branched.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=47,
        title='Detection of Water in Alcohols — 9701/13/M/J/222/Q47',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Which chemical reagent is used to detect trace water contamination in an alcohol sample?',
        options=['A: Aqueous silver nitrate', 'B: Anhydrous copper(II) sulfate (turns from white to blue)', 'C: Acidified potassium dichromate', 'D: Bromine water'],
        correct_answer='B',
        explanation='Option B is correct. Anhydrous CuSO4 is a white solid that absorbs water of crystallization to form hydrated copper(II) sulfate, CuSO4.5H2O, which is bright blue: CuSO4(s) + 5H2O -> CuSO4.5H2O(s).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=48,
        title='Drying Agents for Alcohols — 9701/11/M/J/223/Q48',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Which anhydrous salt is suitable for drying a wet sample of an alcohol after synthesis?',
        options=['A: Anhydrous calcium chloride', 'B: Solid phosphorus(V) oxide', 'C: Anhydrous magnesium sulfate (MgSO4) or anhydrous sodium sulfate (Na2SO4)', 'D: Concentrated sulfuric acid'],
        correct_answer='C',
        explanation='Option C is correct. Anhydrous MgSO4 and Na2SO4 are neutral drying agents that absorb water without reacting chemically with alcohols. (CaCl2 cannot be used because it forms coordinate complexes with alcohols; H2SO4 dehydrates alcohols).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=49,
        title='Industrial Methanol Synthesis — 9701/12/M/J/224/Q49',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What are the raw materials and conditions used in the modern industrial synthesis of methanol?',
        options=['A: Fermentation of methane with yeast.', 'B: Synthesis gas (CO + 2H2) passed over a Cu/ZnO/Al2O3 catalyst at 250 °C and 50-100 atm pressure.', 'C: Reaction of chloromethane with steam.', 'D: Cracking of petroleum fractions.'],
        correct_answer='B',
        explanation="Option B is correct. Methanol is produced industrially by passing 'syngas' (carbon monoxide and hydrogen, derived from steam reforming of natural gas) over a copper-zinc oxide catalyst: CO(g) + 2H2(g) <=> CH3OH(g) at 250 °C and 50-100 atm.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=50,
        title='Hydrogen Bonding Angle Around Oxygen — 9701/13/M/J/220/Q50',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='In the intermolecular hydrogen bond C-O-H ... O between two alcohol molecules, what is the approximate O-H ... O bond angle?',
        options=['A: Approximately 180° (linear arrangement of the three participating atoms)', 'B: 90°', 'C: 109.5°', 'D: 120°'],
        correct_answer='A',
        explanation='Option A is correct. Hydrogen bonds have directional covalent character; maximum electrostatic attraction and orbital overlap occur when the donor O-H bond points directly toward the lone pair of the acceptor oxygen atom, resulting in an O-H ... O angle of ~180° (linear).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=51,
        title='Boiling Point: Alcohols vs Carboxylic Acids — 9701/11/M/J/221/Q51',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why do carboxylic acids have higher boiling points than alcohols of similar molecular mass (e.g. ethanoic acid bp 118 °C vs propan-1-ol bp 97 °C)?',
        options=['A: Carboxylic acids have no London dispersion forces.', 'B: Alcohols cannot form hydrogen bonds.', 'C: Carboxylic acids are ionic liquids.', 'D: Carboxylic acids form stable hydrogen-bonded dimers in the liquid and vapor states, effectively doubling their molecular mass.'],
        correct_answer='D',
        explanation='Option D is correct. Carboxylic acid molecules form two reciprocal hydrogen bonds between their C=O and O-H groups, creating stable cyclic dimers. This dimerisation significantly increases intermolecular attraction, raising the boiling point well above that of alcohols.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=52,
        title='Relative Rates of Halogenation: PCl5 vs PBr3 vs PI3 — 9701/12/M/J/222/Q52',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='Which phosphorus halide is solid at room temperature and reacts most violently with alcohols?',
        options=['A: Phosphorus(III) bromide, PBr3', 'B: Phosphorus(III) iodide, PI3', 'C: Phosphorus(V) chloride, PCl5', 'D: All three react with equal vigor.'],
        correct_answer='C',
        explanation='Option C is correct. PCl5 is a crystalline solid containing [PCl4]+ and [PCl6]- ions that reacts vigorously and exothermically with alcohols at room temperature, releasing dense acidic fumes of HCl.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=53,
        title='Substitution Mechanism with HX for Primary Alcohols — 9701/13/M/J/223/Q53',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='What is the mechanism by which primary alcohols are converted into bromoalkanes by HBr?',
        options=['A: Protonation of the -OH group to form -OH2+, followed by backside SN2 displacement by bromide ion.', 'B: Unimolecular ionization to a carbocation (SN1).', 'C: Free radical abstraction.', 'D: Electrophilic addition.'],
        correct_answer='A',
        explanation='Option A is correct. Primary alcohols cannot form stable carbocations. Protonation converts -OH into the excellent leaving group water (-OH2+). Bromide ion then attacks the alpha-carbon from the rear via a concerted SN2 displacement, expelling H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=54,
        title='Identification of Unknown Alcohol — 9701/11/M/J/224/Q54',
        syllabus_ref='16.1',
        difficulty='HARD',
        stem='An alcohol C4H10O does NOT react with hot acidified potassium dichromate(VI) and gives an immediate oily layer with Lucas reagent. What is the alcohol?',
        options=['A: Butan-1-ol', 'B: Butan-2-ol', 'C: 2-methylpropan-2-ol (tertiary alcohol)', 'D: 2-methylpropan-1-ol'],
        correct_answer='C',
        explanation='Option C is correct. Resistance to oxidation by acidified K2Cr2O7 uniquely indicates a tertiary alcohol. Instant cloudiness with Lucas reagent confirms the tertiary structure: 2-methylpropan-2-ol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=55,
        title='Enthalpy of Vaporisation of Alcohols — 9701/12/M/J/220/Q55',
        syllabus_ref='16.1',
        difficulty='EASY',
        stem='Why does ethanol have a much higher enthalpy of vaporisation (38.6 kJ mol^-1) than propane (19.0 kJ mol^-1)?',
        options=['A: Ethanol has a higher molecular mass.', 'B: Hydrogen bonds in ethanol require additional thermal energy to break completely upon transition to the gaseous state.', 'C: Propane forms covalent bonds with nitrogen in air.', 'D: Ethanol is an ionic liquid.'],
        correct_answer='B',
        explanation='Option B is correct. Vaporising a liquid requires overcoming all intermolecular forces. Ethanol molecules are held together by both London forces and strong hydrogen bonds, requiring twice as much energy per mole to vaporise as propane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=56,
        title='Oxidation of Primary Alcohols — Controlling the Products — 9701/11/M/J/23/Q24',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='How can the oxidation of propan-1-ol by acidified potassium dichromate(VI) be controlled to yield propanal rather than propanoic acid?',
        options=['A: Heat the mixture under reflux for two hours with an excess of acidified dichromate.', 'B: Add concentrated sodium hydroxide and boil vigorously.', 'C: Carry out the reaction in an open beaker at room temperature.', 'D: Use an excess of propan-1-ol, add acidified dichromate slowly, and distill off the propanal immediately as it forms.'],
        correct_answer='D',
        explanation='Option D is correct. Propanal (an aldehyde) has a much lower boiling point (49 °C) than propan-1-ol (97 °C) and propanoic acid (141 °C) because aldehydes cannot form intermolecular hydrogen bonds. By distilling off the volatile propanal as soon as it forms, it is removed from contact with the oxidizing agent before it can undergo further oxidation to propanoic acid.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=57,
        title='Oxidation Behavior of Tertiary Alcohols — 9701/12/M/J/23/Q24',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What is observed when 2-methylpropan-2-ol is warmed with acidified potassium dichromate(VI)?',
        options=['A: The solution turns green and effervescence of CO2 is observed.', 'B: A silver mirror forms on the walls of the test tube.', 'C: No reaction occurs; the orange solution remains orange.', 'D: A brick-red precipitate is formed.'],
        correct_answer='C',
        explanation='Option C is correct. Oxidation of alcohols by Cr2O7 2- requires the removal of a hydrogen atom from the carbinol carbon (the carbon bonded to -OH). In 2-methylpropan-2-ol ((CH3)3C-OH), the carbinol carbon is bonded to three methyl groups and possesses no hydrogen atoms. Therefore, tertiary alcohols resist oxidation under mild acidic conditions, and the solution remains orange.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=58,
        title='Dehydration of Alcohols to Alkenes — 9701/13/M/J/23/Q24',
        syllabus_ref='16.2',
        difficulty='MEDIUM',
        stem='What reagents and conditions are used to dehydrate ethanol to ethene in a school laboratory?',
        options=['A: Heating with concentrated sulfuric acid (H2SO4) at approximately 170 °C (or passing vapor over hot Al2O3 at 300 °C).', 'B: Heating with aqueous sodium hydroxide under reflux.', 'C: Warming with acidified potassium manganate(VII).', 'D: Passing ethanol vapor over cold copper turnings.'],
        correct_answer='A',
        explanation='Option A is correct. Dehydration (elimination of water) from ethanol requires an acid catalyst and heat: heating with excess concentrated H2SO4 at 170 °C, or passing ethanol vapor over heated aluminium oxide (Al2O3) or pumice catalyst at ~300 °C: C2H5OH -> C2H4 + H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=59,
        title='Structural Requirement for the Tri-iodomethane (Iodoform) Reaction — 9701/11/O/N/23/Q24',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='Which of the following alcohols produces a yellow precipitate of tri-iodomethane (CHI3) when warmed with alkaline aqueous iodine?',
        options=['A: Butan-1-ol, CH3CH2CH2CH2OH', 'B: 2-methylpropan-2-ol, (CH3)3C-OH', 'C: Pentan-3-ol, CH3CH2CH(OH)CH2CH3', 'D: Butan-2-ol, CH3-CH(OH)-CH2CH3'],
        correct_answer='D',
        explanation='Option D is correct. The tri-iodomethane (iodoform) reaction requires a methyl carbinol group: CH3-CH(OH)-. The alkaline iodine oxidizes the group to a methyl carbonyl (CH3-C=O), which undergoes tri-iodination and cleavage by hydroxide to precipitate yellow crystals of CHI3 (tri-iodomethane). Butan-2-ol contains the CH3-CH(OH)- group and gives a positive test. (Ethanol is the only primary alcohol that gives a positive result; butan-1-ol, pentan-3-ol, and 2-methylpropan-2-ol do not).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=60,
        title='Oxidation of Secondary Alcohols — 9701/11/M/J/220/Q60',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What organic product is formed when propan-2-ol is heated under reflux with acidified potassium dichromate(VI)?',
        options=['A: Propanal', 'B: Propanone, CH3COCH3 (a ketone)', 'C: Propanoic acid', 'D: Carbon dioxide and water'],
        correct_answer='B',
        explanation='Option B is correct. Secondary alcohols are oxidized to ketones: CH3CH(OH)CH3 + [O] -> CH3COCH3 + H2O. Ketones cannot be easily oxidized further under mild conditions, so propanone is obtained in high yield.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=61,
        title='Dichromate Color Change During Oxidation — 9701/12/M/J/221/Q61',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='When an alcohol is oxidized by acidified potassium dichromate(VI), what color change is observed in the transition metal species?',
        options=['A: Purple to colorless', 'B: Orange (dichromate(VI), Cr2O7 2-) to Green (chromium(III), Cr3+)', 'C: Colorless to brown', 'D: Yellow to dark blue'],
        correct_answer='B',
        explanation='Option B is correct. The orange dichromate(VI) ion (Cr2O7 2-, where Cr is in the +6 oxidation state) is reduced to the green chromium(III) ion (Cr3+): Cr2O7 2- + 14H+ + 6e- -> 2Cr3+ + 7H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=62,
        title='Dehydration of Butan-2-ol Isomer Products — 9701/13/M/J/222/Q62',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='When butan-2-ol is heated with concentrated sulfuric acid at 170 °C, how many isomeric alkene products are formed?',
        options=['A: 1 alkene', 'B: 2 alkenes', 'C: 4 alkenes', 'D: 3 alkenes (but-1-ene, cis-but-2-ene, and trans-but-2-ene)'],
        correct_answer='D',
        explanation='Option D is correct. Elimination of water can remove H from C1 (forming but-1-ene) or from C3 (forming but-2-ene). Because but-2-ene exhibits geometric stereoisomerism, it forms two stereoisomers (cis-but-2-ene and trans-but-2-ene). Total = 3 alkene products.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=63,
        title='Major Product of Butan-2-ol Dehydration — 9701/11/M/J/223/Q63',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='Which alkene is the MAJOR product formed in the acid-catalyzed dehydration of butan-2-ol?',
        options=['A: Trans-but-2-ene', 'B: But-1-ene', 'C: Cis-but-2-ene', 'D: 2-methylpropene'],
        correct_answer='A',
        explanation="Option A is correct. By Zaitsev's rule, elimination yields the more substituted and thermodynamically stable alkene (but-2-ene). Trans-but-2-ene has less steric hindrance between the two methyl groups than cis-but-2-ene, making trans-but-2-ene the major product.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=64,
        title='Esterification Mechanism and Catalyst — 9701/12/M/J/224/Q64',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What type of reaction occurs when an alcohol reacts with a carboxylic acid in the presence of concentrated sulfuric acid, and what is the role of the acid?',
        options=['A: Electrophilic addition; H2SO4 is an oxidizing agent.', 'B: Free radical substitution; H2SO4 initiates radicals.', 'C: Condensation (esterification); concentrated H2SO4 acts as both an acid catalyst and a dehydrating agent.', 'D: Nucleophilic elimination; H2SO4 neutralizes base.'],
        correct_answer='C',
        explanation='Option C is correct. Esterification joins an alcohol and a carboxylic acid with elimination of water (condensation). Concentrated H2SO4 protonates the carbonyl oxygen to increase electrophilicity and removes water, shifting the dynamic equilibrium to the right.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=65,
        title='Fruity Smell of Esters — 9701/13/M/J/220/Q65',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What characteristic physical property is used to confirm the formation of an ester during a school laboratory preparation?',
        options=['A: A distinct sweet, fruity, pleasant aroma when poured into cold sodium carbonate solution.', 'B: The evolution of choking sulfur dioxide fumes.', 'C: A dense black precipitate.', 'D: A deep purple coloration.'],
        correct_answer='A',
        explanation='Option A is correct. Esters have low boiling points and characteristic pleasant, sweet, fruity aromas (used as artificial flavorings and perfumes). Pouring the reaction mixture into aqueous Na2CO3 neutralizes unreacted acid and vaporizes the fragrant ester.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=66,
        title='Identification of Primary Alcohols with Acidified Permanganate — 9701/11/M/J/221/Q66',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What color change occurs when ethanol is warmed with acidified potassium manganate(VII)?',
        options=['A: Orange to green', 'B: Colorless to yellow', 'C: Green to purple', 'D: Purple (MnO4-, Mn +7) to Colorless (Mn2+, Mn +2)'],
        correct_answer='D',
        explanation='Option D is correct. Acidified KMnO4 is a powerful oxidizing agent. The purple permanganate ion (MnO4-) is reduced to the virtually colorless manganese(II) ion (Mn2+): MnO4- + 8H+ + 5e- -> Mn2+ + 4H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=67,
        title='Oxidation of Methanol Products — 9701/12/M/J/222/Q67',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What are the sequential oxidation products when methanol is completely oxidized by acidified potassium dichromate(VI)?',
        options=['A: Ethanoic acid and water', 'B: Methanal (HCHO) -> Methanoic acid (HCOOH) -> Carbon dioxide (CO2) and water', 'C: Methanoic acid only', 'D: Dimethyl ether and oxygen'],
        correct_answer='B',
        explanation='Option B is correct. Methanol oxidizes first to methanal (HCHO), then to methanoic acid (HCOOH). Unlike other carboxylic acids, methanoic acid has an oxidizable -CHO aldehyde-like hydrogen, which is oxidized further to carbonic acid / carbon dioxide (CO2) and water.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=68,
        title='Iodoform Test for Ethanol — 9701/13/M/J/223/Q68',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='Why is ethanol the ONLY primary alcohol that gives a positive tri-iodomethane (iodoform) test?',
        options=['A: It has the lowest molecular mass of all alcohols.', 'B: It is the only alcohol that is liquid at room temperature.', 'C: It is the only primary alcohol that possesses the required CH3-CH(OH)- structural grouping (where R = H).', 'D: It forms hydrogen bonds with iodine.'],
        correct_answer='C',
        explanation='Option C is correct. The iodoform reaction requires the CH3-CH(OH)- group. In a primary alcohol, the carbinol carbon is attached to -H2 and one R group: R-CH2OH. Only when R = CH3 does it have the CH3-CH2OH structure, which is ethanol. All other primary alcohols have longer chains (R-CH2-CH2OH) lacking the CH3-CH(OH)- unit.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=69,
        title='Positive Iodoform Test Observation — 9701/11/M/J/224/Q69',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What is the visual appearance and characteristic smell of the precipitate formed in a positive iodoform test?',
        options=['A: A gelatinous brown precipitate smelling of rotten eggs.', 'B: A pale yellow crystalline precipitate with a persistent antiseptic/medicinal hospital smell.', 'C: A bright white precipitate with no smell.', 'D: A silver reflective mirror on glass.'],
        correct_answer='B',
        explanation='Option B is correct. Tri-iodomethane (CHI3) forms fine, pale yellow crystalline needles that precipitate from aqueous solution and possess a distinct medicinal, sweet antiseptic odor (historically used as a surgical antiseptic).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=70,
        title='Iodoform Reaction with Secondary Alcohols — 9701/12/M/J/220/Q70',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='Which secondary alcohol does NOT give a positive tri-iodomethane test?',
        options=['A: Pentan-3-ol, CH3CH2-CH(OH)-CH2CH3', 'B: Propan-2-ol, CH3-CH(OH)-CH3', 'C: Butan-2-ol, CH3-CH(OH)-CH2CH3', 'D: Pentan-2-ol, CH3-CH(OH)-CH2CH2CH3'],
        correct_answer='A',
        explanation='Option A is correct. Pentan-3-ol has two ethyl groups attached to the carbinol carbon (CH3CH2-CH(OH)-CH2CH3) and lacks the required methyl group (CH3-CH(OH)-). Propan-2-ol, butan-2-ol, and pentan-2-ol all contain the CH3-CH(OH)- unit and give a positive test.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=71,
        title='Dehydration Mechanism of Ethanol — 9701/13/M/J/221/Q71',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='In the acid-catalyzed dehydration of ethanol, what is the first step of the mechanism?',
        options=['A: Loss of a hydride ion to form a carbocation.', 'B: Abstraction of a proton by sulfate ion.', 'C: Homolytic fission of the C-O bond.', 'D: Protonation of the hydroxyl oxygen atom by H+ to form the alkyloxonium ion, CH3CH2-OH2+.'],
        correct_answer='D',
        explanation='Option D is correct. The lone pair on the hydroxyl oxygen atom accepts a proton (H+) from the acid catalyst: C2H5OH + H+ -> C2H5-OH2+. This converts the poor leaving group (-OH) into a good, neutral leaving group (H2O).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=72,
        title='Reflux Apparatus Purpose in Esterification — 9701/11/M/J/222/Q72',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='Why must the esterification of ethanoic acid and ethanol be conducted under reflux?',
        options=['A: To keep atmospheric oxygen out of the flask.', 'B: To freeze the reaction intermediate.', 'C: To heat the mixture at its boiling point for an extended period without losing volatile reactants or products as vapors.', 'D: To filter out solid precipitates continuously.'],
        correct_answer='C',
        explanation='Option C is correct. Both ethanol (bp 78 °C) and ethyl ethanoate (bp 77 °C) are highly volatile. Heating under reflux uses a vertical condenser to continually condense escaping vapors back into the boiling flask, allowing prolonged heating without loss of volume.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=73,
        title='Separation of Ester via Separating Funnel — 9701/12/M/J/223/Q73',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='After synthesizing ethyl ethanoate, why is the reaction mixture shaken with aqueous sodium carbonate in a separating funnel?',
        options=['A: To react with and remove unreacted ethanoic acid and sulfuric acid catalyst from the organic layer.', 'B: To dissolve the ester in the aqueous layer.', 'C: To oxidize unreacted ethanol to ethanoic acid.', 'D: To reduce the ester to an aldehyde.'],
        correct_answer='A',
        explanation='Option A is correct. The reaction mixture contains unreacted ethanoic acid, sulfuric acid, ethanol, and ester. Shaking with aqueous Na2CO3 neutralizes and extracts the acidic species into the lower aqueous layer as soluble sodium salts: 2CH3COOH + Na2CO3 -> 2CH3COONa + CO2 + H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=74,
        title='Hydrolysis of Esters: Acid vs Base — 9701/13/M/J/224/Q74',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='How does the acid-catalyzed hydrolysis of an ester differ from its base-promoted hydrolysis (saponification)?',
        options=['A: Acid hydrolysis yields only an alkene.', 'B: Alkaline hydrolysis produces an acyl chloride.', 'C: Acid hydrolysis is a reversible equilibrium; alkaline hydrolysis goes to completion (irreversible) because the carboxylate salt is formed.', 'D: Both reactions go to 100% completion.'],
        correct_answer='C',
        explanation='Option C is correct. Acid hydrolysis (H+/H2O) is reversible, establishing an equilibrium mixture. Alkaline hydrolysis (OH-/H2O) deprotonates the carboxylic acid to form a resonance-stabilized carboxylate anion (RCOO-), which cannot be attacked by the alcohol, driving the reaction irreversibly to completion.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=75,
        title="Reactivity of Alcohols with Potassium Dichromate vs Tollen's — 9701/11/M/J/220/Q75",
        syllabus_ref='16.2',
        difficulty='EASY',
        stem="An unknown alcohol is oxidized by acidified K2Cr2O7 to compound X. Compound X gives a silver mirror with Tollens' reagent. What class of alcohol was the starting material?",
        options=['A: Secondary alcohol', 'B: Primary alcohol', 'C: Tertiary alcohol', 'D: Phenol'],
        correct_answer='B',
        explanation="Option B is correct. Primary alcohols oxidize to aldehydes. Aldehydes (compound X) readily reduce ammoniacal silver nitrate (Tollens' reagent) to elemental silver, forming a mirror. Secondary alcohols oxidize to ketones, which do not react with Tollens' reagent.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=76,
        title="Fehling's Solution Test for Oxidation Product — 9701/12/M/J/221/Q76",
        syllabus_ref='16.2',
        difficulty='HARD',
        stem="An alcohol is oxidized to product Y, which produces a brick-red precipitate of copper(I) oxide (Cu2O) when heated with Fehling's solution. What was the alcohol?",
        options=['A: A secondary alcohol (e.g. propan-2-ol)', 'B: A tertiary alcohol (e.g. 2-methylpropan-2-ol)', 'C: A carboxylic acid', 'D: A primary alcohol (e.g. ethanol)'],
        correct_answer='D',
        explanation="Option D is correct. Fehling's solution is reduced from blue Cu2+ to brick-red Cu2O precipitate by aldehydes, which are produced exclusively by the oxidation of primary alcohols.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=77,
        title='Oxidation of Cyclohexanol — 9701/13/M/J/222/Q77',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What organic product is formed when cyclohexanol is heated with acidified potassium dichromate(VI)?',
        options=['A: Hexanedioic acid', 'B: Cyclohexene', 'C: Cyclohexanone (a cyclic ketone)', 'D: Benzene'],
        correct_answer='C',
        explanation='Option C is correct. Cyclohexanol is a secondary alcohol. Oxidation removes two hydrogens (one from -OH and one from the carbinol ring carbon) to form the cyclic ketone cyclohexanone.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=78,
        title='Dehydration of Cyclohexanol — 9701/11/M/J/223/Q78',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What alkene is formed when cyclohexanol is heated with concentrated phosphoric(V) acid?',
        options=['A: Cyclohexene', 'B: Benzene', 'C: Hex-1-ene', 'D: Hex-2-ene'],
        correct_answer='A',
        explanation='Option A is correct. Heating cyclohexanol with concentrated H3PO4 or concentrated H2SO4 eliminates water to form cyclohexene.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=79,
        title='Dehydration of 2-methylbutan-2-ol — 9701/12/M/J/224/Q79',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What are the two alkene products formed by the dehydration of 2-methylbutan-2-ol?',
        options=['A: Pent-1-ene and pent-2-ene', 'B: 3-methylbut-1-ene and 2-methylbut-2-ene', 'C: 2,3-dimethylbut-2-ene only', 'D: 2-methylbut-2-ene (major) and 2-methylbut-1-ene (minor)'],
        correct_answer='D',
        explanation='Option D is correct. Elimination of water from (CH3)2C(OH)CH2CH3 removes -OH from C2 and H from either C3 (giving the major, more substituted alkene 2-methylbut-2-ene) or C1 (giving the minor alkene 2-methylbut-1-ene).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=80,
        title='Chemical Test to Distinguish Propan-1-ol and Propan-2-ol — 9701/13/M/J/220/Q80',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='Which single chemical test cleanly differentiates propan-1-ol from propan-2-ol?',
        options=['A: Acidified potassium dichromate (both turn green).', 'B: The tri-iodomethane (iodoform) test: propan-2-ol produces a yellow precipitate of CHI3, while propan-1-ol gives no precipitate.', 'C: Reaction with sodium metal (both evolve hydrogen).', 'D: Reaction with PCl5 (both evolve HCl gas).'],
        correct_answer='B',
        explanation='Option B is correct. Both are oxidized by K2Cr2O7, both react with Na, and both react with PCl5. Only propan-2-ol has the CH3-CH(OH)- methyl carbinol group required to produce a yellow precipitate of tri-iodomethane (CHI3) with alkaline iodine.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=81,
        title='Ester Formation from Methanol and Propanoic Acid — 9701/11/M/J/221/Q81',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What is the systematic IUPAC name of the ester formed between propanoic acid and methanol?',
        options=['A: Propyl methanoate', 'B: Methyl propanoate', 'C: Ethyl ethanoate', 'D: Methyl ethanoate'],
        correct_answer='B',
        explanation="Option B is correct. The alkyl group from the alcohol comes first ('methyl' from methanol), followed by the carboxylate name ('propanoate' from propanoic acid): methyl propanoate (CH3CH2COOCH3).",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=82,
        title='Ester Formation from Ethanol and Methanoic Acid — 9701/12/M/J/222/Q82',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What is the structural formula of ethyl methanoate?',
        options=['A: CH3COOCH3', 'B: CH3CH2COOCH3', 'C: CH3COOCH2CH3', 'D: HCOOCH2CH3'],
        correct_answer='D',
        explanation='Option D is correct. Methanoic acid provides the HCOO- group, and ethanol provides the -CH2CH3 ethyl group: HCOOCH2CH3.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=83,
        title='Oxidation of Diols with Acidified Dichromate — 9701/13/M/J/223/Q83',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What organic product is obtained when propane-1,3-diol is heated under reflux with excess acidified potassium dichromate(VI)?',
        options=['A: Propanedioic acid (malonic acid), HOOC-CH2-COOH', 'B: Propanal', 'C: Propanone', 'D: Propanoic acid'],
        correct_answer='A',
        explanation='Option A is correct. Propane-1,3-diol (HOCH2-CH2-CH2OH) possesses two primary alcohol groups. Heating under reflux with excess oxidizer converts both primary alcohol groups into carboxylic acid groups, forming the dicarboxylic acid propanedioic acid.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=84,
        title='Oxidation of Propane-1,2-diol — 9701/11/M/J/224/Q84',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What products are formed when propane-1,2-diol is oxidized with acidified potassium dichromate(VI)?',
        options=['A: Propanoic acid only', 'B: Propanal and propanone', 'C: 2-oxopropanoic acid (pyruvic acid), CH3-CO-COOH', 'D: Carbon dioxide and water'],
        correct_answer='C',
        explanation='Option C is correct. Propane-1,2-diol has one primary alcohol group (oxidized to -COOH) and one secondary alcohol group (oxidized to -C=O), yielding 2-oxopropanoic acid (pyruvic acid).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=85,
        title='Distinguishing Alcohols by Rate of Oxidation — 9701/12/M/J/220/Q85',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='How can the reaction rate of primary, secondary, and tertiary alcohols with acidified K2Cr2O7 at 60 °C be used for classification?',
        options=['A: Primary and secondary alcohols turn orange dichromate green within minutes, whereas tertiary alcohols show no color change even after hours.', 'B: Tertiary alcohols react instantaneously within 1 second.', 'C: Secondary alcohols never react.', 'D: Primary alcohols do not react.'],
        correct_answer='A',
        explanation='Option A is correct. Primary and secondary alcohols possess carbinol C-H bonds that are easily oxidized, turning the orange solution green. Tertiary alcohols lack a carbinol hydrogen and remain persistently orange.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=86,
        title='Dehydration of 3,3-dimethylbutan-2-ol with Rearrangement — 9701/13/M/J/221/Q86',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='When 3,3-dimethylbutan-2-ol is heated with acid, 2,3-dimethylbut-2-ene is the major alkene product. What causes this unexpected product?',
        options=['A: The alcohol decomposes into methane and butene.', 'B: The acid removes a methyl group directly.', 'C: The reaction proceeds via free radicals.', 'D: A carbocation intermediate undergoes a 1,2-methyl shift to form a more stable tertiary carbocation before elimination.'],
        correct_answer='D',
        explanation='Option D is correct. Protonation and loss of water yields the secondary carbocation (CH3)3C-CH+-CH3. A 1,2-methyl shift immediately occurs to form the more stable tertiary carbocation (CH3)2C+-CH(CH3)2, which loses a proton to yield the tetrasubstituted alkene 2,3-dimethylbut-2-ene.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=87,
        title='Percentage Yield Calculation in Esterification — 9701/11/M/J/222/Q87',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='Heating 4.6 g of ethanol (Mr = 46.0) with excess ethanoic acid produces 5.5 g of ethyl ethanoate (Mr = 88.0). What is the percentage yield?',
        options=['A: 50.0%', 'B: 62.5%', 'C: 75.0%', 'D: 88.0%'],
        correct_answer='B',
        explanation='Option B is correct. Moles of ethanol = 4.6 / 46.0 = 0.10 mol. Theoretical yield of ethyl ethanoate = 0.10 mol * 88.0 g/mol = 8.8 g. Percentage yield = (5.5 / 8.8) * 100 = 62.5%.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=88,
        title='Iodoform Reaction Equations — 9701/12/M/J/223/Q88',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What are the two essential chemical steps in the tri-iodomethane reaction for ethanol?',
        options=['A: Step 1: Direct substitution of -OH by iodine; Step 2: Elimination of HI.', 'B: Step 1: Addition of I2 across C-C bond; Step 2: Hydrolysis.', 'C: Step 1: Oxidation of ethanol to ethanal (CH3CHO); Step 2: Tri-iodination of the methyl group to CI3CHO followed by alkaline cleavage into CHI3 and HCOO-.', 'D: Step 1: Reduction to ethane; Step 2: Halogenation.'],
        correct_answer='C',
        explanation='Option C is correct. Alkaline iodine (I2 + 2OH- -> IO- + I- + H2O) first oxidizes ethanol to ethanal: CH3CH2OH + IO- -> CH3CHO + I- + H2O. The three methyl protons are replaced by iodine: CH3CHO + 3IO- -> CI3CHO + 3OH-. Finally, hydroxide cleaves the C-C bond: CI3CHO + OH- -> CHI3(s) + HCOO-.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=89,
        title='Identification of Carbonyl vs Alcohol with Iodoform — 9701/13/M/J/224/Q89',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='Both ethanol and ethanal give a yellow precipitate with alkaline iodine. How can they be distinguished chemically?',
        options=['A: Add 2,4-DNPH: ethanal gives an orange precipitate; ethanol does not react.', 'B: Add acidified potassium dichromate(VI): ethanol turns the orange solution green; ethanal also oxidizes, but ethanol gives effervescence with sodium metal while ethanal does NOT.', "C: Add Tollens' reagent: both form silver mirrors.", 'D: Add sodium metal: ethanal evolves hydrogen gas.'],
        correct_answer='B',
        explanation='Option B is correct. Ethanol is an alcohol and does not react with 2,4-dinitrophenylhydrazine (2,4-DNPH). Ethanal contains a carbonyl group (>C=O) and immediately produces a vivid yellow-orange crystalline precipitate with 2,4-DNPH.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=90,
        title='Boiling Point of Esters vs Alcohols — 9701/11/M/J/220/Q90',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='Why does ethyl ethanoate (Mr = 88.0) have a lower boiling point (77 °C) than its isomer butanoic acid (Mr = 88.0, bp 164 °C) and pentan-1-ol (Mr = 88.0, bp 138 °C)?',
        options=['A: Ester molecules cannot form intermolecular hydrogen bonds with each other because they lack a hydrogen atom bonded to oxygen.', 'B: Esters are completely non-polar.', 'C: Esters decompose below 80 °C.', 'D: Esters have much smaller electron clouds.'],
        correct_answer='A',
        explanation='Option A is correct. Esters possess polar C=O and C-O bonds and exhibit dipole-dipole attractions, but have no O-H group. Without intermolecular hydrogen bonding, their intermolecular attractions are significantly weaker than those in carboxylic acids and alcohols of identical Mr.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=91,
        title='Industrial Uses of Esters — 9701/12/M/J/221/Q91',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='Which two properties make esters widely used as industrial solvents for paints, glues, and varnishes?',
        options=['A: Non-flammability and high boiling points.', 'B: Extreme acidity that dissolves metals.', 'C: Total insolubility in all organic liquids.', 'D: Low polarity/volatility balance capable of dissolving non-polar solutes, and high volatility allowing rapid evaporation without leaving greasy residue.'],
        correct_answer='D',
        explanation='Option D is correct. Esters (such as ethyl ethanoate and butyl ethanoate) are volatile, low-toxicity solvents that readily dissolve organic polymers, lacquers, and resins, evaporating quickly to leave smooth coatings.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=92,
        title='Dehydration of Polyols — 9701/13/M/J/222/Q92',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What is produced when ethane-1,2-diol is heated with concentrated sulfuric acid under mild conditions?',
        options=['A: Ethyne gas', 'B: Oxalic acid', 'C: 1,4-dioxane (a cyclic diether) via intermolecular dehydration', 'D: Carbon monoxide'],
        correct_answer='C',
        explanation='Option C is correct. Two molecules of ethane-1,2-diol undergo reciprocal intermolecular dehydration to form the stable 6-membered cyclic diether 1,4-dioxane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=93,
        title='Alcohol Identification from Combustion Products — 9701/11/M/J/223/Q93',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='Complete combustion of 0.10 mol of an alcohol produces 13.2 g of CO2 and 7.2 g of H2O. What is the alcohol?',
        options=['A: Propan-1-ol or propan-2-ol, C3H8O', 'B: Ethanol, C2H6O', 'C: Butan-1-ol, C4H10O', 'D: Methanol, CH4O'],
        correct_answer='A',
        explanation='Option A is correct. Moles of CO2 = 13.2 / 44.0 = 0.30 mol -> 0.30/0.10 = 3 carbons. Moles of H2O = 7.2 / 18.0 = 0.40 mol -> moles of H = 0.80 mol -> 0.80/0.10 = 8 hydrogens. Formula is C3H8O (propanol).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=94,
        title='Saponification of Fats and Oils — 9701/12/M/J/224/Q94',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What alcohol is produced as a byproduct in the commercial manufacture of soap by the alkaline hydrolysis of vegetable triglycerides?',
        options=['A: Ethanol', 'B: Ethane-1,2-diol', 'C: Propane-1,2,3-triol (glycerol)', 'D: Methanol'],
        correct_answer='C',
        explanation='Option C is correct. Vegetable oils and animal fats are triesters of glycerol (triglycerides). Heating with aqueous NaOH (saponification) hydrolyzes the ester linkages to produce sodium salts of fatty acids (soap) and propane-1,2,3-triol (glycerol).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=95,
        title='Oxidation of Unbranched Secondary Alcohol — 9701/13/M/J/220/Q95',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What is the product when octan-2-ol is heated with acidified potassium dichromate(VI)?',
        options=['A: Octanal', 'B: Octan-2-one (a ketone)', 'C: Octanoic acid', 'D: Heptanoic acid and CO2'],
        correct_answer='B',
        explanation='Option B is correct. Octan-2-ol is a secondary alcohol. Oxidation removes two hydrogens to form the corresponding 8-carbon ketone octan-2-one.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=96,
        title='Testing for Purity of Synthesized Liquid Ester — 9701/11/M/J/221/Q96',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='How can the purity of a prepared ester sample be determined accurately in a school laboratory?',
        options=['A: Test its pH with litmus paper.', 'B: Add sodium metal.', 'C: Measure its color in a colorimeter.', 'D: Measure its boiling point using distillation apparatus; a sharp, narrow boiling point matching literature values confirms high purity.'],
        correct_answer='D',
        explanation='Option D is correct. Pure liquids boil at a sharp, constant temperature characteristic of the pure substance. Impurities cause the liquid to boil over a wide temperature range and elevate the boiling point.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=97,
        title='Biodiesel Production via Transesterification — 9701/12/M/J/222/Q97',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='What chemical reaction is used to produce biodiesel fuel from plant oils?',
        options=['A: Catalytic cracking of vegetable oil.', 'B: Dehydration of vegetable oil with sulfuric acid.', 'C: Transesterification: reacting vegetable oil (triglyceride) with methanol in the presence of a strong base catalyst (KOH) to yield methyl esters of fatty acids and glycerol.', 'D: Hydrogenation of plant oils to solid wax.'],
        correct_answer='C',
        explanation='Option C is correct. Transesterification replaces the glycerol backbone of natural plant triglycerides with methanol, converting high-viscosity triglycerides into low-viscosity fatty acid methyl esters (FAME, biodiesel) suitable for diesel engines.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=98,
        title='Oxidation of Allyl Alcohol — 9701/13/M/J/223/Q98',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='What functional groups are present in allyl alcohol (prop-2-en-1-ol, CH2=CH-CH2OH), and how does cold dilute KMnO4 react with it?',
        options=['A: Alkene (C=C) and primary alcohol (-OH); cold dilute KMnO4 oxidizes the C=C bond to form propane-1,2,3-triol (glycerol).', 'B: Alkane and secondary alcohol.', 'C: Aldehyde and alkene.', 'D: Carboxylic acid and ketone.'],
        correct_answer='A',
        explanation='Option A is correct. Prop-2-en-1-ol contains both an alkene C=C double bond and a primary alcohol group. Mild dihydroxylation of the C=C bond by cold dilute KMnO4 adds two -OH groups across the double bond, converting allyl alcohol into glycerol (propane-1,2,3-triol).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=99,
        title='Alcohol Functional Group Interconversion Summary — 9701/11/M/J/224/Q99',
        syllabus_ref='16.2',
        difficulty='EASY',
        stem='Which reaction sequence converts propene into propan-1-ol?',
        options=['A: Propene + steam/H3PO4 directly.', 'B: Propene + hot concentrated KMnO4.', 'C: Propene + H2/Ni followed by water.', 'D: Propene + HBr / peroxides -> 1-bromopropane, followed by heating with aqueous NaOH -> propan-1-ol.'],
        correct_answer='D',
        explanation='Option D is correct. Direct hydration of propene with steam/H3PO4 gives propan-2-ol (Markovnikov). To obtain propan-1-ol, propene is reacted with HBr in the presence of peroxides (anti-Markovnikov addition) to form 1-bromopropane, which is then hydrolyzed with aqueous NaOH to give propan-1-ol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=100,
        title='Esterification Equilibrium Shift Techniques — 9701/12/M/J/220/Q100',
        syllabus_ref='16.2',
        difficulty='HARD',
        stem='In industrial ester synthesis, which two methods are commonly used to shift the reversible equilibrium toward higher ester yield?',
        options=['A: Adding water to dilute the mixture.', 'B: Using an excess of one reactant (e.g. alcohol) and continuously removing water or ester from the reaction mixture by fractional distillation.', 'C: Cooling the reaction to -20 °C.', 'D: Adding sodium hydroxide to neutralize acid.'],
        correct_answer='B',
        explanation="Option B is correct. By Le Chatelier's principle, using an excess of the cheaper reactant (often alcohol) and continuously removing water (or the volatile ester product) shifts the position of equilibrium to the right, driving the conversion toward completion.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=101,
        title='HF 1: Deducing Isomeric Alkenes from Alcohol Dehydration — 9701/11/M/J/22/Q23',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='An alcohol X of molecular formula C5H12O is heated with concentrated sulfuric acid at 170 °C.\nA mixture of three isomeric alkenes of molecular formula C5H10 is obtained, two of which are stereoisomers (cis-trans isomers).\n\nWhat is the structural formula of alcohol X?',
        options=['A: Pentan-1-ol, CH3-CH2-CH2-CH2-CH2OH', 'B: Pentan-3-ol, CH3-CH2-CH(OH)-CH2-CH3', 'C: Pentan-2-ol, CH3-CH(OH)-CH2-CH2-CH3', 'D: 2-methylbutan-2-ol, (CH3)2C(OH)CH2CH3'],
        correct_answer='C',
        explanation='Option C is correct. Dehydration of pentan-2-ol removes -OH from C2 and H from either C1 or C3: (1) removal from C1 yields pent-1-ene (no stereoisomers); (2) removal from C3 yields pent-2-ene, which exists as two geometric stereoisomers: cis-pent-2-ene and trans-pent-2-ene. Thus, pentan-2-ol produces exactly three alkene isomers (two being stereoisomers). Pentan-3-ol can only yield pent-2-ene (2 isomers). Pentan-1-ol yields only pent-1-ene (1 isomer).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=102,
        title='HF 2: The Tri-iodomethane (Iodoform) Reaction Test — 9701/12/M/J/21/Q23',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Four organic liquids are tested with alkaline aqueous iodine (I2 in aqueous NaOH):\nLiquid 1: Propan-1-ol; Liquid 2: Propan-2-ol; Liquid 3: Butan-2-ol; Liquid 4: 2-methylpropan-2-ol\n\nWhich liquids form a pale yellow precipitate of tri-iodomethane?',
        options=['A: Liquid 2 and Liquid 3 only', 'B: Liquid 1 and Liquid 2 only', 'C: Liquid 2, Liquid 3, and Liquid 4', 'D: Liquid 1 only'],
        correct_answer='A',
        explanation='Option A is correct. The tri-iodomethane reaction requires the specific methyl carbinol group: CH3-CH(OH)-. Propan-2-ol (CH3-CH(OH)-CH3) and butan-2-ol (CH3-CH(OH)-CH2CH3) both contain this structural unit and form a yellow precipitate of CHI3. Propan-1-ol is a primary alcohol lacking the methyl branch, and 2-methylpropan-2-ol is a tertiary alcohol lacking a carbinol hydrogen; neither forms a precipitate.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=103,
        title='HF 3: Distinguishing Alcohols by Successive Chemical Reagents — 9701/13/O/N/22/Q23',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='An unknown alcohol Y of formula C4H10O was investigated:\n• It turns acidified potassium dichromate(VI) from orange to green upon warming.\n• It forms a yellow precipitate when warmed with alkaline aqueous iodine.\n\nWhat is the systematic name of alcohol Y?',
        options=['A: Butan-1-ol', 'B: 2-methylpropan-1-ol', 'C: 2-methylpropan-2-ol', 'D: Butan-2-ol'],
        correct_answer='D',
        explanation='Option D is correct. Turning acidified K2Cr2O7 green means alcohol Y is oxidizable (primary or secondary alcohol, ruling out tertiary 2-methylpropan-2-ol). Forming a yellow precipitate with alkaline iodine proves the presence of the CH3-CH(OH)- group. The only 4-carbon alcohol with both features is the secondary alcohol butan-2-ol (CH3-CH(OH)-CH2CH3).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=104,
        title='HF 4: Stoichiometry of Sodium Reaction with Polyols — 9701/11/F/M/22/Q23',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='A sample of 0.050 mol of an unknown organic compound containing only carbon, hydrogen, and oxygen reacts with an excess of sodium metal to evolve exactly 1.20 dm^3 of hydrogen gas (measured at RTP).\n\nHow many hydroxyl (-OH) groups are present in one molecule of this compound?',
        options=['A: 1 hydroxyl group', 'B: 2 hydroxyl groups (it is a diol)', 'C: 3 hydroxyl groups', 'D: 4 hydroxyl groups'],
        correct_answer='B',
        explanation='Option B is correct. Moles of H2 gas evolved = 1.20 dm^3 / 24.0 dm^3 mol^-1 = 0.050 mol. The general equation is: R(OH)n + n Na -> R(ONa)n + (n/2) H2. Moles of H2 / moles of compound = 0.050 / 0.050 = 1.0 = n/2 => n = 2. Thus, each molecule contains exactly 2 hydroxyl groups (a diol).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=105,
        title='HF 5: Oxidation of Unsaturated Alcohols with Multiple Functional Groups — 9701/12/O/N/21/Q24',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Consider the unsaturated alcohol pent-3-en-2-ol, CH3-CH=CH-CH(OH)-CH3.\nWhat organic products are formed when one mole of pent-3-en-2-ol is heated under reflux with hot, concentrated, acidified potassium manganate(VII)?',
        options=['A: Ethanoic acid (CH3COOH) and 2-oxopropanoic acid (pyruvic acid, CH3-CO-COOH)', 'B: Propanone and ethanoic acid', 'C: Pentan-2-one and water', 'D: Carbon dioxide and butanoic acid'],
        correct_answer='A',
        explanation='Option A is correct. Hot concentrated KMnO4 oxidatively cleaves C=C double bonds and simultaneously oxidizes secondary alcohols to ketones. Cleaving C3=C4 yields ethanoic acid (CH3COOH) from the =CH-CH3 half. The remaining =CH-CH(OH)-CH3 half is oxidized at the double-bond carbon to a carboxylic acid (-COOH) and at the secondary alcohol carbon to a ketone (>C=O), yielding 2-oxopropanoic acid (CH3-CO-COOH).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=106,
        title='HF 6: Percentage Yield and Mass Calculations in Ester Preparation — 9701/13/M/J/22/Q23',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Ethanol (6.90 g, Mr = 46.0) is reacted with excess ethanoic acid in the presence of concentrated sulfuric acid catalyst. After purification, 9.24 g of ethyl ethanoate (Mr = 88.0) is collected.\n\nWhat is the percentage yield of ethyl ethanoate?',
        options=['A: 60.0%', 'B: 75.0%', 'C: 70.0%', 'D: 80.0%'],
        correct_answer='C',
        explanation='Option C is correct. Moles of ethanol used = 6.90 g / 46.0 g/mol = 0.150 mol. Theoretical yield of ethyl ethanoate = 0.150 mol * 88.0 g/mol = 13.20 g. Percentage yield = (actual mass / theoretical mass) * 100 = (9.24 g / 13.20 g) * 100 = 70.0%.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=107,
        title='HF 7: Chirality Changes in Alcohol Oxidation — 9701/11/O/N/21/Q23',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Butan-2-ol is an optically active compound containing one chiral center.\n\nWhat happens to the optical activity when butan-2-ol is oxidized by heating with acidified potassium dichromate(VI)?',
        options=['A: Optical activity is inverted (Walden inversion).', 'B: Optical activity is completely lost because the secondary alcohol is converted into butanone, which is achiral.', 'C: Optical activity is retained because butanoic acid is chiral.', 'D: The product forms an optically active single enantiomer.'],
        correct_answer='B',
        explanation='Option B is correct. Butan-2-ol (CH3-CH(OH)-CH2CH3) has a chiral C2 bonded to -H, -OH, -CH3, and -C2H5. Oxidation converts the secondary alcohol group into a carbonyl group (>C=O), producing butanone (CH3-CO-CH2CH3). In butanone, C2 is sp2 hybridised and planar with only three attached groups. It lacks a chiral stereocenter, so optical activity is completely lost.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=108,
        title='HF 8: Identifying Intermediates in Multi-Step Alcohol Synthesis — 9701/12/F/M/23/Q24',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Consider the reaction pathway:\nEthene  --[ Step 1: HBr ]-->  Compound P  --[ Step 2: KCN(ethanolic) ]-->  Compound Q  --[ Step 3: H+/H2O reflux ]-->  Compound R  --[ Step 4: LiAlH4 ]-->  Compound S\n\nWhat is the identity of final product Compound S?',
        options=['A: Ethanol, CH3CH2OH', 'B: Propan-2-ol, CH3CH(OH)CH3', 'C: Propanoic acid, CH3CH2COOH', 'D: Propan-1-ol, CH3CH2CH2OH'],
        correct_answer='D',
        explanation='Option D is correct. Step 1: Electrophilic addition of HBr to ethene yields bromoethane (P, CH3CH2Br). Step 2: Nucleophilic substitution with KCN yields propanenitrile (Q, CH3CH2CN). Step 3: Acid hydrolysis of the nitrile yields propanoic acid (R, CH3CH2COOH). Step 4: Reduction of propanoic acid by LiAlH4 in dry ether yields the primary alcohol propan-1-ol (S, CH3CH2CH2OH).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=109,
        title='HF 9: Dehydration of Symmetrical Alcohols — 9701/13/M/J/23/Q24',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Pentan-3-ol, CH3-CH2-CH(OH)-CH2-CH3, is heated with concentrated sulfuric acid.\n\nHow many distinct alkene products are formed by dehydration of pentan-3-ol?',
        options=['A: 2 alkenes (cis-pent-2-ene and trans-pent-2-ene)', 'B: 1 alkene', 'C: 3 alkenes', 'D: 4 alkenes'],
        correct_answer='A',
        explanation='Option A is correct. In pentan-3-ol, the carbinol carbon C3 is flanked by two identical -CH2- groups (C2 and C4). Elimination of water can only remove a hydrogen from C2 or C4, both yielding pent-2-ene (CH3-CH=CH-CH2-CH3). Pent-2-ene exhibits geometric stereoisomerism, existing as cis-pent-2-ene and trans-pent-2-ene. Thus, exactly 2 distinct alkene stereoisomers are formed.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=110,
        title='HF 10: Quantitative Combustive Analysis of an Alcohol — 9701/11/M/J/23/Q25',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='A saturated monohydric alcohol contains 60.0% carbon, 13.3% hydrogen, and 26.7% oxygen by mass.\nWhen vaporised, 0.150 g of this alcohol occupies 59.8 cm^3 at 100 °C and 1.01 * 10^5 Pa.\n\nWhat is the molecular formula and identity of this alcohol? (R = 8.31 J K^-1 mol^-1)',
        options=['A: C2H6O (Mr = 46.0, ethanol)', 'B: C4H10O (Mr = 74.0, butanol)', 'C: C3H8O (Mr = 60.0, propanol)', 'D: C4H8O (Mr = 72.0, butenol)'],
        correct_answer='C',
        explanation='Option C is correct. Moles of C = 60.0/12.0 = 5.0; H = 13.3/1.0 = 13.3; O = 26.7/16.0 = 1.67. Dividing by 1.67: C: 5.0/1.67 = 3.0; H: 13.3/1.67 = 8.0; O: 1.67/1.67 = 1.0. Empirical formula is C3H8O (formula mass = 60.0). Using pV = nRT = (m/Mr)RT: Mr = mRT / pV = (0.150 * 8.31 * 373) / (101000 * 59.8 * 10^-6) = 464.95 / 6.0398 = 60.1 g/mol. Molecular formula = C3H8O.',
        figure_path=None,
        figure_caption=None
    ),
]
