"""
Curated 110 Authentic Cambridge AS Chemistry (9701) Paper 1 MCQs
for Topic 13: An Introduction to AS Level Organic Chemistry (100 Core + 10 High-Frequency Core Repeats).
"""

from build_mcq_topic_pdf import MCQQuestion

TOPIC_13_MCQ_QUESTIONS = [
    MCQQuestion(
        number=1,
        title='Types of Chemical Formula — Empirical vs Molecular — 9701/11/M/J/23/Q13',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='A volatile liquid compound contains 54.5% carbon, 9.1% hydrogen, and 36.4% oxygen by mass. Its relative molecular mass, Mr, is 88.0.\n\nWhat are the empirical formula and molecular formula of this compound?',
        options=['A: Empirical formula: CH2O; Molecular formula: C3H6O3', 'B: Empirical formula: C2H4O; Molecular formula: C4H8O2', 'C: Empirical formula: C4H8O2; Molecular formula: C4H8O2', 'D: Empirical formula: C2H4O; Molecular formula: C2H4O'],
        correct_answer='B',
        explanation='Option B is correct. Moles of C = 54.5 / 12.0 = 4.54; moles of H = 9.1 / 1.0 = 9.10; moles of O = 36.4 / 16.0 = 2.275. Dividing by smallest (2.275): C: 4.54/2.275 = 2.0; H: 9.10/2.275 = 4.0; O: 2.275/2.275 = 1.0. Thus, empirical formula is C2H4O (empirical formula mass = 2(12) + 4(1) + 16 = 44.0). Since Mr = 88.0, the molecular formula multiplier is 88.0 / 44.0 = 2, giving C4H8O2.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=2,
        title='Interpreting Skeletal Formulas — 9701/12/M/J/23/Q13',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='In a skeletal formula of an organic molecule, what do the vertices (corners) and line ends represent?',
        options=['A: A methyl group (-CH3) only at every vertex and line end.', 'B: Any heteroatom (oxygen, nitrogen, halogen) unless labelled.', 'C: An unsaturated double bond.', "D: A carbon atom with the appropriate number of hydrogen atoms attached to satisfy carbon's four-covalent valency."],
        correct_answer='D',
        explanation='Option D is correct. In skeletal notation, carbon-carbon bonds are drawn as lines in a zig-zag format. Carbon atoms and attached hydrogen atoms are not explicitly written: each vertex (corner) and each line termination represents a carbon atom together with enough implicit hydrogen atoms to give that carbon a total of four covalent bonds.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=3,
        title='IUPAC Nomenclature of Branched Halogenoalkanes — 9701/13/M/J/23/Q13',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the correct systematic IUPAC name for the compound CH3-CH(CH3)-CH(Br)-CH2-CH3?',
        options=['A: 3-bromo-2-methylpentane', 'B: 3-bromo-4-methylpentane', 'C: 2-methyl-3-bromopentane', 'D: 1-bromo-1-ethyl-2-methylpropane'],
        correct_answer='A',
        explanation="Option A is correct. Number the longest continuous carbon chain (5 carbons = pentane) from the end that gives substituents the lowest locant set. Numbering from left: C2 has methyl, C3 has bromo (locants 2,3). Numbering from right: C3 has bromo, C4 has methyl (locants 3,4). Lower locant set is (2,3). Substituents are cited alphabetically: 'bromo' before 'methyl'. Hence: 3-bromo-2-methylpentane.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=4,
        title='General Formula of Homologous Series — 9701/11/O/N/23/Q13',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='Which homologous series has the general formula CnH2nO and does NOT decolorize aqueous bromine?',
        options=['A: Alkenols (unsaturated alcohols)', 'B: Cycloalkanes', 'C: Non-cyclic aliphatic aldehydes and ketones', 'D: Carboxylic acids'],
        correct_answer='C',
        explanation='Option C is correct. Both aliphatic aldehydes and aliphatic ketones have the general formula CnH2nO with one degree of unsaturation (a carbonyl group C=O). Because they contain no carbon-carbon double bonds (C=C), they do not decolorize aqueous bromine by addition.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=5,
        title='Identifying Functional Groups in Complex Molecules — 9701/12/O/N/23/Q13',
        syllabus_ref='13.1',
        difficulty='MEDIUM',
        stem='The molecule phenylephrine has the structure HO-C6H4-CH(OH)-CH2-NH-CH3.\n\nWhich functional groups are present in phenylephrine?',
        options=['A: Phenol, secondary alcohol, and secondary amine', 'B: Primary alcohol, tertiary amine, and ketone', 'C: Phenol, primary alcohol, and primary amine', 'D: Ester, secondary alcohol, and amide'],
        correct_answer='A',
        explanation='Option A is correct. HO-C6H4- is a phenolic hydroxyl group attached directly to an aromatic benzene ring; -CH(OH)- is attached to two carbon atoms (the ring and CH2), making it a secondary alcohol; -NH- is bonded to two alkyl carbons (-CH2- and -CH3), classifying it as a secondary amine.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=6,
        title='Homologous Series Characteristics — 9701/11/M/J/221/Q6',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='Which property is TRUE for all members of a homologous series?',
        options=['A: They possess identical physical boiling points.', 'B: They have identical empirical formulas.', 'C: They exhibit identical molecular masses.', 'D: They share the same general formula and identical functional group, displaying a gradation in physical properties.'],
        correct_answer='D',
        explanation='Option D is correct. All members of a homologous series possess the same functional group and general formula, differing by successive -CH2- units. This produces similar chemical properties and regular gradations in physical properties like boiling point.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=7,
        title='Displayed Formula Definition — 9701/12/M/J/222/Q7',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='What is explicitly shown in a fully displayed formula of an organic molecule?',
        options=['A: Only the functional group bonds.', 'B: Every single atom and every covalent bond connecting them.', 'C: Only the carbon backbone bonds.', 'D: The 3D spatial orientation of orbitals.'],
        correct_answer='B',
        explanation='Option B is correct. A displayed formula shows every single atom and every covalent bond (single, double, or triple) in the molecule explicitly.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=8,
        title='IUPAC Naming of Alkenes — 9701/13/M/J/223/Q8',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the systematic IUPAC name for (CH3)2C=CH-CH3?',
        options=['A: 3-methylbut-2-ene', 'B: 2-methylbut-3-ene', 'C: 2-methylbut-2-ene', 'D: Pent-2-ene'],
        correct_answer='C',
        explanation='Option C is correct. The longest carbon chain with the C=C bond has 4 carbons (but-2-ene). Numbering from the left gives the methyl substituent the lowest locant: 2-methylbut-2-ene.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=9,
        title='Functional Group of Esters — 9701/11/M/J/224/Q9',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='Which grouping of atoms represents the ester functional group?',
        options=['A: -CONH2', 'B: -COO- (or -COOCH2-)', 'C: -COCl', 'D: -O-'],
        correct_answer='B',
        explanation='Option B is correct. An ester contains a carbonyl group bonded directly to an alkoxy oxygen: -C(=O)O-.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=10,
        title='Molecular Formula Determination — 9701/12/M/J/220/Q10',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='A hydrocarbon contains 85.7% carbon by mass and has Mr = 56. What is its molecular formula?',
        options=['A: C4H8', 'B: C3H6', 'C: C4H10', 'D: C5H10'],
        correct_answer='A',
        explanation='Option A is correct. Ratio: C = 85.7/12 = 7.14; H = 14.3/1 = 14.3. Ratio 1:2 -> empirical CH2 (mass 14). Mr = 56 / 14 = 4 -> C4H8.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=11,
        title='IUPAC Name for Dicarboxylic Acid — 9701/13/M/J/221/Q11',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='What is the systematic IUPAC name for HOOC-CH2-CH2-COOH?',
        options=['A: Succinic acid', 'B: 1,4-dicarboxyethane', 'C: Butanedioic ester', 'D: Butanedioic acid'],
        correct_answer='D',
        explanation='Option D is correct. A 4-carbon unbranched chain with carboxylic acid groups at both ends is butanedioic acid.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=12,
        title='Structural Formula Convention — 9701/11/M/J/222/Q12',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the correct condensed structural formula for 2,2-dimethylpropane?',
        options=['A: CH3CH2CH(CH3)2', 'B: CH3(CH2)3CH3', 'C: C(CH3)4', 'D: (CH3)2CHCH2CH3'],
        correct_answer='C',
        explanation='Option C is correct. 2,2-dimethylpropane (neopentane) has a central carbon bonded to four methyl groups: C(CH3)4.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=13,
        title='Functional Group of Nitriles — 9701/12/M/J/223/Q13',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='Which functional group is present in ethanenitrile?',
        options=['A: -C#N (cyano group)', 'B: -NH2 (amino group)', 'C: -NO2 (nitro group)', 'D: -CONH2 (amide group)'],
        correct_answer='A',
        explanation='Option A is correct. Nitriles contain a carbon-nitrogen triple bond: -C#N.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=14,
        title='IUPAC Naming of Haloalkanes — 9701/13/M/J/224/Q14',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the IUPAC name for CH3-CH(Cl)-CH(Cl)-CH3?',
        options=['A: 1,2-dichlorobutane', 'B: 2,2-dichlorobutane', 'C: 2,3-dichlorobutane', 'D: 1,4-dichlorobutane'],
        correct_answer='C',
        explanation='Option C is correct. 4-carbon chain with chloro substituents at carbons 2 and 3: 2,3-dichlorobutane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=15,
        title='Degree of Unsaturation — 9701/11/M/J/220/Q15',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='How many degrees of unsaturation (double bond equivalents) are present in C6H10O?',
        options=['A: 1', 'B: 2', 'C: 3', 'D: 0'],
        correct_answer='B',
        explanation='Option B is correct. Formula: C + 1 - (H/2) = 6 + 1 - 5 = 2. This corresponds to two double bonds, one triple bond, or combinations of rings and double bonds.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=16,
        title='Identification of Acyl Chlorides — 9701/12/M/J/221/Q16',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='Which formula represents an acyl chloride?',
        options=['A: CH3CH2Cl', 'B: CH3CHCl2', 'C: CH3OCH2Cl', 'D: CH3COCl'],
        correct_answer='D',
        explanation='Option D is correct. Acyl chlorides contain the -C(=O)Cl functional group, as in CH3COCl (ethanoyl chloride).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=17,
        title='IUPAC Name for Branched Alcohol — 9701/13/M/J/222/Q17',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='What is the IUPAC name for CH3-C(CH3)(OH)-CH2-CH3?',
        options=['A: 3-methylbutan-3-ol', 'B: 2-methylbutan-3-ol', 'C: 2-methylbutan-2-ol', 'D: Pentan-2-ol'],
        correct_answer='C',
        explanation='Option C is correct. Longest chain containing -OH is 4 carbons (butan-2-ol). Methyl branch at C2: 2-methylbutan-2-ol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=18,
        title='Classification of Alcohols — 9701/11/M/J/223/Q18',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='Which molecule is a tertiary alcohol?',
        options=['A: 2-methylpropan-2-ol', 'B: Propan-2-ol', 'C: 2-methylpropan-1-ol', 'D: Butan-1-ol'],
        correct_answer='A',
        explanation='Option A is correct. In 2-methylpropan-2-ol, the carbon bearing the -OH group is bonded to three other carbon atoms (three methyl groups), making it tertiary.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=19,
        title='Functional Groups in Amino Acids — 9701/12/M/J/224/Q19',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='Which two functional groups are present in all 2-amino acids?',
        options=['A: Amide and alcohol', 'B: Ester and amine', 'C: Aldehyde and ketone', 'D: Carboxylic acid (-COOH) and primary amine (-NH2)'],
        correct_answer='D',
        explanation='Option D is correct. Amino acids contain both a carboxylic acid group (-COOH) and an amine group (-NH2) attached to the alpha-carbon.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=20,
        title='General Formula of Alkanes — 9701/13/M/J/220/Q20',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the general formula for all open-chain saturated hydrocarbons (alkanes)?',
        options=['A: CnH2n', 'B: CnH2n+2', 'C: CnH2n-2', 'D: CnH2n+1'],
        correct_answer='B',
        explanation='Option B is correct. Open-chain alkanes possess the general formula CnH2n+2.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=21,
        title='General Formula of Cycloalkanes — 9701/11/M/J/221/Q21',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='What is the general formula for monocyclic cycloalkanes?',
        options=['A: CnH2n+2', 'B: CnH2n', 'C: CnH2n-2', 'D: CnH2n-4'],
        correct_answer='B',
        explanation='Option B is correct. Ring formation eliminates two hydrogens compared to open-chain alkanes, giving CnH2n.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=22,
        title='Naming of Cyclic Hydrocarbons — 9701/12/M/J/222/Q22',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the IUPAC name of a saturated 6-membered ring hydrocarbon?',
        options=['A: Benzene', 'B: Hexene', 'C: Cyclohexene', 'D: Cyclohexane'],
        correct_answer='D',
        explanation='Option D is correct. A saturated six-carbon ring with single C-C bonds is cyclohexane (C6H12).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=23,
        title='Identification of Ketones — 9701/13/M/J/223/Q23',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='Which condensed formula represents a ketone?',
        options=['A: CH3COCH3', 'B: CH3CH2CHO', 'C: CH3COOCH3', 'D: CH3OCH3'],
        correct_answer='A',
        explanation='Option A is correct. CH3COCH3 (propanone) contains a carbonyl group bonded to two alkyl carbons, characteristic of a ketone.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=24,
        title='Identification of Ethers — 9701/11/M/J/224/Q24',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the functional group present in CH3-O-CH2CH3?',
        options=['A: Ester', 'B: Alcohol', 'C: Ether', 'D: Peroxide'],
        correct_answer='C',
        explanation="Option C is correct. An oxygen atom bonded between two alkyl groups (R-O-R') is an ether (methoxyethane).",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=25,
        title='IUPAC Name of Aldehyde — 9701/12/M/J/220/Q25',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='What is the IUPAC name for CH3-CH(CH3)-CH2-CHO?',
        options=['A: 3-methylbutanal', 'B: 2-methylbutanal', 'C: 3-methylbutanone', 'D: Pentanal'],
        correct_answer='A',
        explanation='Option A is correct. The carbonyl carbon of the aldehyde is always numbered C1. The chain is 4 carbons (butanal) with methyl at C3: 3-methylbutanal.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=26,
        title='Skeletal Formula of Benzene — 9701/13/M/J/221/Q26',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='How is benzene represented in skeletal notation?',
        options=['A: A pentagon with a double bond', 'B: A zig-zag line of 6 carbons', 'C: An open ring of 6 CH2 groups', 'D: A regular hexagon with an inscribed circle (or alternating double bonds)'],
        correct_answer='D',
        explanation='Option D is correct. Benzene (C6H6) is depicted as a hexagon with a circle representing the delocalized 6 pi electrons.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=27,
        title='Empirical Formula from Combustion Data — 9701/11/M/J/222/Q27',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='Complete combustion of 0.20 mol of a hydrocarbon produces 0.80 mol CO2 and 0.80 mol H2O. What is the hydrocarbon?',
        options=['A: C4H10', 'B: C4H8', 'C: C2H4', 'D: C3H6'],
        correct_answer='B',
        explanation='Option B is correct. Moles of C = 0.80 / 0.20 = 4; moles of H = (0.80 * 2) / 0.20 = 8. Hydrocarbon is C4H8.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=28,
        title='Carboxylic Acid Salt Naming — 9701/12/M/J/223/Q28',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='What is the IUPAC name for CH3CH2COONa?',
        options=['A: Sodium propionate', 'B: Sodium ethanoate', 'C: Sodium propanoate', 'D: Sodium butanoate'],
        correct_answer='C',
        explanation='Option C is correct. The 3-carbon carboxylate ion is propanoate, so the salt is sodium propanoate.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=29,
        title='Primary Amine Nomenclature — 9701/13/M/J/224/Q29',
        syllabus_ref='13.1',
        difficulty='EASY',
        stem='What is the systematic IUPAC name for CH3-CH2-CH2-NH2?',
        options=['A: Propylamine', 'B: Propan-1-amine', 'C: Ethylmethylamine', 'D: 1-aminopropane'],
        correct_answer='B',
        explanation='Option B is correct. The systematic IUPAC name for a 3-carbon chain with an amino group at carbon-1 is propan-1-amine.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=30,
        title='Hybrid Functional Molecules — 9701/11/M/J/220/Q30',
        syllabus_ref='13.1',
        difficulty='HARD',
        stem='Which functional groups are present in CH2=CH-COOH?',
        options=['A: Alkene (C=C) and carboxylic acid (-COOH)', 'B: Alkyne and ester', 'C: Alcohol and aldehyde', 'D: Alkane and ketone'],
        correct_answer='A',
        explanation='Option A is correct. Propenoic acid contains both a carbon-carbon double bond (alkene) and a carboxylic acid group.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=31,
        title='Homolytic vs Heterolytic Bond Fission — 9701/11/M/J/23/Q14',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='What occurs during homolytic fission of a covalent bond?',
        options=['A: One atom takes both shared electrons, forming a cation and an anion.', 'B: A pair of electrons is transferred to an electrophile to form a dative bond.', 'C: The bond vibrates until it dissociates into two ions of opposite charge.', 'D: The covalent bond breaks symmetrically such that each departing atom retains one of the two shared bonding electrons, producing two uncharged free radicals.'],
        correct_answer='D',
        explanation='Option D is correct. In homolytic fission (homolysis), the covalent bond breaks evenly. Each bonding partner leaves with one electron from the shared pair (depicted by single-headed curly arrows / fish-hooks), resulting in the generation of two highly reactive, neutral species with unpaired electrons known as free radicals: X-Y -> X. + Y..',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=32,
        title='Definition and Behavior of an Electrophile — 9701/12/M/J/23/Q14',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='Which statement correctly defines an electrophile in organic reaction mechanisms?',
        options=['A: A species with a lone pair of electrons that donates them to form a dative covalent bond.', 'B: A neutral species with an unpaired electron that abstracts a hydrogen atom.', 'C: An electron-deficient species (either positively charged or possessing an electron-deficient dipole delta+) that attacks regions of high electron density by accepting an electron pair.', 'D: A proton donor according to the Bronsted-Lowry acid-base definition.'],
        correct_answer='C',
        explanation="Option C is correct. An electrophile ('electron-lover') is an electron-poor species (such as Br+, NO2+, H+, or the delta+ carbon in a carbonyl group) that seeks out electron-rich centers (like the pi bond of an alkene or benzene ring) and accepts a lone pair of electrons to form a new covalent bond.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=33,
        title='Definition and Behavior of a Nucleophile — 9701/13/M/J/23/Q14',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='Which species can act as a nucleophile in organic substitution reactions?',
        options=['A: :OH-, :CN-, :NH3, and H2O: (species possessing a non-bonding lone pair of electrons)', 'B: Br+, NO2+, and AlCl3 (electron-deficient Lewis acids)', 'C: Cl. and CH3. (free radicals with single unpaired electrons)', 'D: CH4 and C2H6 (saturated alkanes with no lone pairs)'],
        correct_answer='A',
        explanation="Option A is correct. A nucleophile ('nucleus-lover') is an electron-rich species containing at least one non-bonding lone pair of electrons (e.g., hydroxide :OH-, cyanide :CN-, ammonia :NH3, water :OH2). It attacks electron-deficient carbon centers (delta+) and donates its lone pair to form a new dative/covalent bond.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=34,
        title='Classification of Reaction Types — 9701/11/O/N/23/Q14',
        syllabus_ref='13.2',
        difficulty='MEDIUM',
        stem='The conversion of bromoethane into ethene by heating with ethanolic potassium hydroxide is classified as which type of reaction?',
        options=['A: Electrophilic addition', 'B: Nucleophilic substitution', 'C: Elimination', 'D: Free radical substitution'],
        correct_answer='C',
        explanation='Option C is correct. When CH3CH2Br is heated with ethanolic KOH (where OH- acts as a Bronsted-Lowry base rather than a nucleophile), a hydrogen halide molecule (HBr) is removed from adjacent carbon atoms to form a C=C double bond (CH2=CH2 + KBr + H2O). This removal of atoms without replacement is an elimination reaction.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=35,
        title='Free Radical Substitution Mechanism Stages — 9701/12/O/N/23/Q14',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='In the photochemical chlorination of methane, which step represents a propagation reaction?',
        options=['A: Cl2 -> 2Cl. (under UV light)', 'B: CH3. + Cl2 -> CH3Cl + Cl.', 'C: CH3. + Cl. -> CH3Cl', 'D: CH3. + CH3. -> C2H6'],
        correct_answer='B',
        explanation='Option B is correct. A propagation step consumes one free radical and generates a new free radical, maintaining the radical chain: (1) Cl. + CH4 -> .CH3 + HCl; (2) .CH3 + Cl2 -> CH3Cl + Cl.. Option A is initiation (0 radicals -> 2 radicals). Options C and D are termination steps (2 radicals -> 0 radicals).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=36,
        title='Curly Arrow Convention — 9701/11/M/J/221/Q36',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='In organic reaction mechanisms, what does a standard double-barbed curly arrow represent?',
        options=['A: The physical movement of an atomic nucleus.', 'B: The shift of a single unpaired electron.', 'C: The direction of thermodynamic heat flow.', 'D: The movement of a pair of electrons from a lone pair or covalent bond to an atom or bond.'],
        correct_answer='D',
        explanation='Option D is correct. A full double-barbed curly arrow depicts the movement of an electron pair from an electron-rich site (lone pair or bond) to an electron-deficient site.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=37,
        title='Fish-hook Arrow Convention — 9701/12/M/J/222/Q37',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='What does a single-barbed (fish-hook) curly arrow denote in organic chemistry?',
        options=['A: The transfer of two electrons in an elimination reaction.', 'B: A resonance contributor.', 'C: The movement of a single unpaired electron.', 'D: A coordinate bond.'],
        correct_answer='C',
        explanation='Option C is correct. A single-headed (fish-hook) arrow indicates the movement of a single electron, frequently employed in free radical mechanisms.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=38,
        title='Carbocation Stability Order — 9701/13/M/J/223/Q38',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='What is the correct order of carbocation stability from most stable to least stable?',
        options=['A: Tertiary (3°) > Secondary (2°) > Primary (1°) > Methyl', 'B: Methyl > Primary (1°) > Secondary (2°) > Tertiary (3°)', 'C: Primary > Tertiary > Secondary > Methyl', 'D: Secondary > Tertiary > Primary > Methyl'],
        correct_answer='A',
        explanation='Option A is correct. Alkyl groups are electron-donating via inductive effect (+I), dispersing the positive charge on the carbon. Tertiary carbocations have three alkyl groups providing maximum charge dispersal, making 3° > 2° > 1° > methyl.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=39,
        title='Electrophilic Addition Mechanism — 9701/11/M/J/224/Q39',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='Which reaction proceeds via an electrophilic addition mechanism?',
        options=['A: Methane reacting with chlorine in UV light.', 'B: Bromoethane reacting with aqueous sodium hydroxide.', 'C: Ethanol reacting with acidified potassium dichromate.', 'D: Ethene reacting with hydrogen bromide to form bromoethane.'],
        correct_answer='D',
        explanation='Option D is correct. Alkenes possess a pi bond with high electron density that attacks electrophiles like H-Br, undergoing electrophilic addition.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=40,
        title='Nucleophilic Substitution Mechanism — 9701/12/M/J/220/Q40',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='Which reaction proceeds via a nucleophilic substitution mechanism?',
        options=['A: Propene reacting with steam over H3PO4.', 'B: 1-bromopropane reacting with aqueous NaOH to form propan-1-ol.', 'C: Ethanol reacting with hot concentrated sulfuric acid.', 'D: Ethane reacting with bromine under UV light.'],
        correct_answer='B',
        explanation='Option B is correct. Haloalkanes contain a polar C-Br bond attacked by nucleophilic :OH- ions, substituting the halogen atom.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=41,
        title='Hydrolysis Reaction Definition — 9701/13/M/J/221/Q41',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='What defines a hydrolysis reaction in organic chemistry?',
        options=['A: The simple physical dissolution of a substance in water.', 'B: A reaction where a covalent bond in a molecule is cleaved by the chemical action of water (often catalyzed by acid or base).', 'C: The removal of water from a molecule to form an alkene.', 'D: The hydration of an alkene across a double bond.'],
        correct_answer='B',
        explanation='Option B is correct. Hydrolysis is a bond-breaking chemical reaction involving water, e.g., the hydrolysis of esters into carboxylic acids and alcohols.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=42,
        title='Condensation Reaction Definition — 9701/11/M/J/222/Q42',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='What characterizes a condensation reaction?',
        options=['A: A gas turning into a liquid upon cooling.', 'B: Addition of hydrogen across a multiple bond.', 'C: The breakdown of a polymer into monomers.', 'D: Two molecules combine to form a larger single molecule with the elimination of a small molecule such as H2O or HCl.'],
        correct_answer='D',
        explanation='Option D is correct. In organic synthesis, condensation involves the joining of two molecules accompanied by the loss of a small molecule like water or hydrogen chloride.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=43,
        title='Reduction of Carbonyl Compounds — 9701/12/M/J/223/Q43',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='Which reagent reduces an aldehyde or ketone to an alcohol?',
        options=['A: Sodium borohydride, NaBH4 (in aqueous ethanol)', 'B: Acidified potassium dichromate(VI)', 'C: Concentrated sulfuric acid', "D: Tollens' reagent"],
        correct_answer='A',
        explanation='Option A is correct. NaBH4 acts as a source of hydride ions (:H-), reducing aldehydes to primary alcohols and ketones to secondary alcohols.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=44,
        title='Oxidation in Organic Chemistry — 9701/13/M/J/224/Q44',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='In organic chemistry, what does oxidation typically involve?',
        options=['A: The addition of hydrogen across a C=C bond.', 'B: The loss of an electron pair by a nucleophile.', 'C: An increase in the number of carbon-oxygen bonds and/or a decrease in carbon-hydrogen bonds.', 'D: The substitution of chlorine by fluorine.'],
        correct_answer='C',
        explanation='Option C is correct. Organic oxidation involves the gain of oxygen bonds (e.g., alcohol -> aldehyde -> carboxylic acid) or the loss of hydrogen bonds.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=45,
        title='Inductive Effect Definition — 9701/11/M/J/220/Q45',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='What is the positive inductive effect (+I effect)?',
        options=['A: The electron-donating ability of alkyl groups through sigma bonds toward a partially positive carbon center.', 'B: The withdrawal of electrons by highly electronegative atoms like fluorine.', 'C: The delocalization of pi electrons in aromatic rings.', 'D: The polarization of light by chiral centers.'],
        correct_answer='A',
        explanation='Option A is correct. Alkyl groups push electron density along sigma bonds toward electron-deficient centers (+I inductive effect), stabilizing carbocations.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=46,
        title="Markovnikov's Rule Basis — 9701/12/M/J/221/Q46",
        syllabus_ref='13.2',
        difficulty='HARD',
        stem="What is the underlying mechanistic basis for Markovnikov's rule in alkene addition?",
        options=['A: The halogen atom always prefers to bond to the carbon with more hydrogen atoms.', 'B: Steric hindrance prevents addition at tertiary carbons.', 'C: Hydrogen bonds direct the incoming electrophile.', 'D: The reaction proceeds predominantly via the more stable carbocation intermediate.'],
        correct_answer='D',
        explanation='Option D is correct. The electrophilic addition of HX to an unsymmetrical alkene generates two possible carbocations; the proton adds to the carbon with more hydrogens to form the more stable (more alkyl-substituted) carbocation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=47,
        title='SN1 Mechanism Characteristics — 9701/13/M/J/222/Q47',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='Which feature is characteristic of an SN1 nucleophilic substitution reaction?',
        options=['A: A concerted one-step mechanism with a five-coordinate transition state.', 'B: A two-step mechanism involving a planar carbocation intermediate, typical for tertiary halogenoalkanes.', 'C: Second-order kinetics dependent on both substrate and nucleophile concentrations.', 'D: Complete inversion of optical configuration.'],
        correct_answer='B',
        explanation='Option B is correct. SN1 (Substitution Nucleophilic Unimolecular) proceeds via rate-determining loss of leaving group to form a carbocation intermediate, followed by rapid attack of nucleophile. Favored by 3° substrates.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=48,
        title='SN2 Mechanism Characteristics — 9701/11/M/J/223/Q48',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='Which feature is characteristic of an SN2 nucleophilic substitution reaction?',
        options=['A: Formation of a stable carbocation intermediate.', 'B: First-order kinetics independent of nucleophile concentration.', 'C: A one-step concerted mechanism with backside attack causing Walden inversion of configuration.', 'D: Racemisation of chiral optical centers.'],
        correct_answer='C',
        explanation='Option C is correct. SN2 proceeds via simultaneous nucleophile attack from the rear and leaving group departure, causing inversion of configuration (Walden inversion).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=49,
        title='Reflux Technique in Organic Synthesis — 9701/12/M/J/224/Q49',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='Why is a reaction mixture heated under reflux during organic preparations?',
        options=['A: To increase the atmospheric pressure above the liquid.', 'B: To heat the mixture at its boiling temperature without losing volatile reactants or products as vapor.', 'C: To separate two liquids with different boiling points.', 'D: To freeze the reaction intermediate.'],
        correct_answer='B',
        explanation='Option B is correct. A vertical condenser cools escaping vapors back to liquid, allowing continuous heating at boiling point without solvent loss.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=50,
        title='Role of UV Light in Halogenation — 9701/13/M/J/220/Q50',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='What is the role of ultraviolet (UV) radiation in the reaction between alkanes and halogens?',
        options=['A: It provides the energy required to homolytically cleave the X-X bond to produce halogen free radicals.', 'B: It ionizes the alkane into a carbocation.', 'C: It acts as a heterogeneous catalyst.', 'D: It polarizes the carbon-hydrogen bond.'],
        correct_answer='A',
        explanation='Option A is correct. The photon energy of UV light matches the bond dissociation enthalpy of Cl-Cl or Br-Br, causing homolytic fission to start the chain reaction.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=51,
        title='Distinguishing Addition from Substitution — 9701/11/M/J/221/Q51',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='How does an addition reaction fundamentally differ from a substitution reaction?',
        options=['A: Addition only occurs in alkanes.', 'B: Substitution always breaks double bonds.', 'C: Addition requires high temperatures whereas substitution occurs at 0 °C.', 'D: In addition, two reactant molecules combine to form a single product with 100% atom economy; in substitution, an atom or group is replaced with formation of a byproduct.'],
        correct_answer='D',
        explanation='Option D is correct. Addition combines all reactants into one product (pi bond breaks, two sigma bonds form); substitution replaces one atom/group with another.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=52,
        title='Free Radical Termination Step — 9701/12/M/J/222/Q52',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='Which reaction is an example of a termination step in a free radical mechanism?',
        options=['A: Cl. + CH4 -> .CH3 + HCl', 'B: Cl2 -> 2Cl.', 'C: 2Cl. -> Cl2', 'D: .CH3 + Cl2 -> CH3Cl + Cl.'],
        correct_answer='C',
        explanation='Option C is correct. Termination occurs when any two free radicals collide and combine their unpaired electrons to form a covalent bond, extinguishing the radicals.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=53,
        title='Nucleophilic Attack at Carbonyls — 9701/13/M/J/223/Q53',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='Why is the carbonyl carbon in ethanal susceptible to nucleophilic attack?',
        options=['A: Oxygen is more electronegative than carbon, polarizing the C=O bond so the carbon carries a significant partial positive charge (delta+).', 'B: The carbon has an expanded octet of 10 electrons.', 'C: The carbonyl bond is completely non-polar.', 'D: Carbon has two non-bonding lone pairs.'],
        correct_answer='A',
        explanation="Option A is correct. Oxygen's higher electronegativity draws pi and sigma electrons toward itself (C(delta+)=O(delta-)), leaving the carbonyl carbon electron-deficient and vulnerable to nucleophilic attack.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=54,
        title='Steric Hindrance in SN2 — 9701/11/M/J/224/Q54',
        syllabus_ref='13.2',
        difficulty='HARD',
        stem='Why do tertiary halogenoalkanes NOT react via the SN2 mechanism?',
        options=['A: Tertiary halogenoalkanes cannot form carbocations.', 'B: The C-X bond enthalpy is too high to break.', 'C: Three bulky alkyl groups surround the central carbon, sterically blocking the incoming nucleophile from attacking from the rear.', 'D: Tertiary carbons have no vacant orbitals.'],
        correct_answer='C',
        explanation='Option C is correct. Backside attack in SN2 requires space around the carbon; in 3° haloalkanes, the three bulky alkyl groups cause extreme steric hindrance, blocking nucleophile access.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=55,
        title='Elimination vs Substitution Regiochemistry — 9701/12/M/J/220/Q55',
        syllabus_ref='13.2',
        difficulty='EASY',
        stem='What reaction conditions favor elimination over substitution for 2-bromopropane?',
        options=['A: Shaking with dilute aqueous sodium hydroxide at room temperature.', 'B: Heating with concentrated ethanolic potassium hydroxide at high temperature.', 'C: Treating with cold acidified water.', 'D: Exposing to chlorine in ultraviolet light.'],
        correct_answer='B',
        explanation='Option B is correct. High temperature, ethanolic solvent, and high base concentration favor elimination (forming propene) over substitution (forming propan-2-ol).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=56,
        title='Hybridisation in Ethene — 9701/11/M/J/23/Q15',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='What is the orbital hybridisation of the carbon atoms in ethene, C2H4, and what is the approximate H-C-H bond angle?',
        options=['A: sp3 hybridised; bond angle 109.5°', 'B: sp hybridised; bond angle 180°', 'C: dsp2 hybridised; bond angle 90°', 'D: sp2 hybridised; bond angle approximately 120°'],
        correct_answer='D',
        explanation='Option D is correct. Each carbon in ethene forms three sigma bonds (two C-H and one C-C) by mixing one 2s and two 2p orbitals to form three sp2 hybrid orbitals in a planar trigonal arrangement with 120° angles. The unhybridised 2p orbital on each carbon overlaps sideways to form the pi bond.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=57,
        title='Nature and Overlap of Sigma vs Pi Bonds — 9701/12/M/J/23/Q15',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='Which statement accurately contrasts a sigma (sigma) bond with a pi (pi) bond in organic molecules?',
        options=['A: A pi bond is formed by end-on overlap and is significantly stronger than a sigma bond.', 'B: Sigma bonds can only exist between identical atoms whereas pi bonds only form between different elements.', 'C: A sigma bond is formed by direct end-on (head-to-head) overlap of orbitals with electron density concentrated along the internuclear axis; a pi bond is formed by sideways (lateral) overlap of parallel p orbitals with electron density above and below the axis.', 'D: Free rotation is possible around a pi bond without breaking it.'],
        correct_answer='C',
        explanation='Option C is correct. Sigma bonds result from direct end-on overlap along the line connecting the nuclei, giving maximum overlap and cylindrical electron density. Pi bonds form by weaker lateral overlap of parallel p orbitals, concentrating electron density in two lobes above and below the internuclear plane. This sideways overlap prevents free rotation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=58,
        title='Hybridisation and Geometry in Ethyne — 9701/13/M/J/23/Q15',
        syllabus_ref='13.3',
        difficulty='MEDIUM',
        stem='In the ethyne molecule (H-C#C-H), what is the hybridisation of the carbon atoms, the number of sigma and pi bonds, and the molecular geometry?',
        options=['A: sp hybridisation; 3 sigma bonds and 2 pi bonds; linear geometry with 180° bond angles', 'B: sp2 hybridisation; 2 sigma bonds and 3 pi bonds; planar geometry with 120° bond angles', 'C: sp3 hybridisation; 5 sigma bonds and 0 pi bonds; tetrahedral geometry with 109.5° bond angles', 'D: sp hybridisation; 1 sigma bond and 4 pi bonds; bent geometry with 104.5° bond angles'],
        correct_answer='A',
        explanation='Option A is correct. Each carbon in H-C#C-H forms two sp hybrid orbitals at 180° (one sigma to H, one sigma to C). Total sigma bonds = 2 (C-H) + 1 (C-C) = 3 sigma bonds. The two unhybridised p orbitals on each carbon overlap sideways to produce 2 perpendicular pi bonds. Geometry is linear (180°).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=59,
        title='Bond Angles in Propene — 9701/13/M/J/224/Q59',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='What are the approximate bond angles around C1 (CH2=), C2 (=CH-), and C3 (-CH3) in propene, CH2=CH-CH3?',
        options=['A: C1: 109.5°, C2: 120°, C3: 180°', 'B: C1: 180°, C2: 120°, C3: 109.5°', 'C: C1: 120°, C2: 109.5°, C3: 120°', 'D: C1: 120°, C2: 120°, C3: 109.5°'],
        correct_answer='D',
        explanation='Option D is correct. Carbons 1 and 2 are sp2 hybridised with trigonal planar geometry (120°). Carbon 3 is sp3 hybridised with tetrahedral geometry (109.5°).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=60,
        title='Number of Sigma and Pi Bonds in Propanone — 9701/11/M/J/220/Q60',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='How many sigma bonds and pi bonds are present in a molecule of propanone, CH3COCH3?',
        options=['A: 8 sigma bonds and 2 pi bonds', 'B: 9 sigma bonds and 1 pi bond', 'C: 10 sigma bonds and 0 pi bonds', 'D: 7 sigma bonds and 2 pi bonds'],
        correct_answer='B',
        explanation='Option B is correct. Propanone has 6 C-H sigma bonds, 2 C-C sigma bonds, 1 C-O sigma bond, and 1 C=O pi bond. Total = 9 sigma bonds and 1 pi bond.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=61,
        title='Planarity of Carbonyl Group — 9701/12/M/J/221/Q61',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='Why is the carbonyl group (>C=O) planar?',
        options=['A: The carbon is sp3 hybridised with two lone pairs.', 'B: The carbonyl carbon is sp2 hybridised with three coplanar sigma bonds directed at 120° angles.', 'C: The carbon is sp hybridised with a linear axis.', 'D: Double bonds always cause tetrahedral geometry.'],
        correct_answer='B',
        explanation='Option B is correct. The carbonyl carbon forms three sigma bonds using sp2 hybrid orbitals oriented at ~120° in a plane, with the pi bond formed by unhybridised p orbital overlap.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=62,
        title='Restricted Rotation Around Double Bonds — 9701/13/M/J/222/Q62',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='Why is free rotation impossible around the carbon-carbon double bond in alkenes at room temperature?',
        options=['A: The sigma bond is too short to allow rotation.', 'B: The hydrogen atoms collide with each other.', 'C: The carbon atoms carry identical partial charges that repel.', 'D: Rotation would disrupt the parallel sideways overlap of the p orbitals, requiring ~260 kJ mol^-1 to break the pi bond.'],
        correct_answer='D',
        explanation='Option D is correct. A pi bond requires parallel alignment of the overlapping p orbitals. Twisting around the C-C axis breaks this sideways overlap, requiring significant energy (~260 kJ/mol), which cannot occur at room temperature.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=63,
        title='Number of Pi Bonds in Benzene — 9701/11/M/J/223/Q63',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='How many pi electrons are delocalised in the aromatic ring of benzene, C6H6?',
        options=['A: 6 pi electrons (one from each sp2 hybridised carbon atom)', 'B: 12 pi electrons', 'C: 3 pi electrons', 'D: 4 pi electrons'],
        correct_answer='A',
        explanation='Option A is correct. Each of the 6 carbon atoms in benzene is sp2 hybridised and contributes one electron from its unhybridised 2p orbital, forming a continuous delocalised pi cloud of 6 electrons.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=64,
        title='Bond Length Comparison — 9701/12/M/J/224/Q64',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='Which sequence lists carbon-carbon bonds in order of DECREASING bond length (longest to shortest)?',
        options=['A: C#C > C=C > C-C', 'B: C=C > C-C > C#C', 'C: C-C (single) > C=C (double) > C#C (triple)', 'D: C-C > C#C > C=C'],
        correct_answer='C',
        explanation='Option C is correct. As the number of shared electron pairs increases, electrostatic attraction for the two nuclei increases, drawing them closer together: C-C (0.154 nm) > C=C (0.134 nm) > C#C (0.120 nm).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=65,
        title='Bond Energy Comparison — 9701/13/M/J/220/Q65',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='Which sequence ranks carbon-carbon bonds in order of INCREASING bond dissociation enthalpy (weakest to strongest)?',
        options=['A: C-C (single) < C=C (double) < C#C (triple)', 'B: C#C < C=C < C-C', 'C: C=C < C-C < C#C', 'D: C-C < C#C < C=C'],
        correct_answer='A',
        explanation='Option A is correct. Triple bond involves sharing 6 electrons (one sigma and two pi bonds) with bond energy ~837 kJ/mol, double bond is ~612 kJ/mol, and single bond is ~348 kJ/mol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=66,
        title='Hybridisation of Nitrile Carbon — 9701/11/M/J/221/Q66',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='What is the hybridisation of the carbon and nitrogen atoms in ethanenitrile, CH3-C#N?',
        options=['A: The carbon is sp2 and nitrogen is sp3', 'B: The carbon is sp3 and nitrogen is sp', 'C: Both atoms are sp2 hybridised', 'D: Both the nitrile carbon and nitrogen are sp hybridised'],
        correct_answer='D',
        explanation='Option D is correct. In the -C#N group, both carbon and nitrogen form one sigma bond and hold two pi bonds (or one lone pair on N), corresponding to sp hybridisation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=67,
        title='Coplanar Atoms in Ethene — 9701/12/M/J/222/Q67',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='How many atoms lie in the exact same geometric plane in an ethene molecule (C2H4)?',
        options=['A: Only the 2 carbon atoms', 'B: All 6 atoms (both carbons and all four hydrogens)', 'C: 4 atoms (the two carbons and two hydrogens)', 'D: 5 atoms'],
        correct_answer='B',
        explanation='Option B is correct. Ethene is completely planar; all 6 atoms (2 carbons and 4 hydrogens) lie in the same spatial plane due to sp2 hybridisation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=68,
        title='Carbon Atom Geometry in Diamond vs Graphite — 9701/13/M/J/223/Q68',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='What is the hybridisation of carbon atoms in diamond and graphite respectively?',
        options=['A: Diamond: sp2; Graphite: sp3', 'B: Diamond: sp; Graphite: sp2', 'C: Diamond: sp3 (tetrahedral); Graphite: sp2 (trigonal planar sheets)', 'D: Diamond: sp3; Graphite: sp'],
        correct_answer='C',
        explanation='Option C is correct. In diamond, each carbon is sp3 hybridised forming 4 tetrahedral sigma bonds. In graphite, each carbon is sp2 hybridised forming 3 planar trigonal sigma bonds with delocalised pi electrons.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=69,
        title='Sigma Bonds in Buta-1,3-diene — 9701/11/M/J/224/Q69',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='How many sigma bonds are present in a molecule of buta-1,3-diene (CH2=CH-CH=CH2)?',
        options=['A: 11 sigma bonds', 'B: 9 sigma bonds', 'C: 7 sigma bonds', 'D: 8 sigma bonds'],
        correct_answer='B',
        explanation='Option B is correct. Formula C4H6: 6 C-H sigma bonds + 3 C-C sigma bonds = 9 sigma bonds (plus 2 pi bonds).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=70,
        title='Shape Around Oxygen in Alcohols — 9701/12/M/J/220/Q70',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='What is the shape and approximate bond angle around the oxygen atom in methanol (CH3-O-H)?',
        options=['A: Bent (V-shaped) with bond angle approximately 104.5° - 109°', 'B: Trigonal planar with bond angle 120°', 'C: Linear with bond angle 180°', 'D: Tetrahedral with bond angle 109.5°'],
        correct_answer='A',
        explanation='Option A is correct. Oxygen has four electron pairs (two bonding pairs and two non-bonding lone pairs) in a tetrahedral arrangement. Lone pair repulsion reduces the C-O-H angle to ~104.5° - 108.5°.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=71,
        title='Shape Around Nitrogen in Amines — 9701/13/M/J/221/Q71',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='What is the molecular geometry around the nitrogen atom in methylamine, CH3NH2?',
        options=['A: Trigonal planar with bond angle 120°', 'B: Tetrahedral with bond angle 109.5°', 'C: T-shaped with bond angle 90°', 'D: Trigonal pyramidal with bond angle approximately 107°'],
        correct_answer='D',
        explanation='Option D is correct. Nitrogen has three single bonding pairs and one non-bonding lone pair. The electron pair geometry is tetrahedral, yielding a trigonal pyramidal molecular geometry (~107°).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=72,
        title='Number of Pi Bonds in Carbon Dioxide — 9701/11/M/J/222/Q72',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='How many sigma and pi bonds are present in carbon dioxide, O=C=O?',
        options=['A: 4 sigma bonds and 0 pi bonds', 'B: 1 sigma bond and 3 pi bonds', 'C: 2 sigma bonds and 2 pi bonds', 'D: 3 sigma bonds and 1 pi bond'],
        correct_answer='C',
        explanation='Option C is correct. Each double bond consists of 1 sigma and 1 pi bond. Thus, O=C=O contains 2 sigma bonds and 2 pi bonds.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=73,
        title='Hybridisation in Carbocations — 9701/12/M/J/223/Q73',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='What is the orbital hybridisation and geometry of the positively charged carbon in a methyl carbocation, +CH3?',
        options=['A: sp2 hybridised with trigonal planar geometry (120°)', 'B: sp3 hybridised with pyramidal geometry (107°)', 'C: sp hybridised with linear geometry (180°)', 'D: unhybridised with spherical geometry'],
        correct_answer='A',
        explanation='Option A is correct. The +CH3 carbocation carbon has three bonding electron pairs and an empty 2p orbital, resulting in sp2 hybridisation and planar geometry with 120° bond angles.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=74,
        title='Bond Length in Benzene vs Cyclohexene — 9701/13/M/J/224/Q74',
        syllabus_ref='13.3',
        difficulty='HARD',
        stem='How does the carbon-carbon bond length in benzene compare with ethane and ethene?',
        options=['A: It alternates between short 0.134 nm and long 0.154 nm.', 'B: It is shorter than a triple bond (0.110 nm).', 'C: It is intermediate between C-C single (0.154 nm) and C=C double (0.134 nm), with all six C-C bonds equal at 0.139 nm.', 'D: It is identical to the single bond in ethane (0.154 nm).'],
        correct_answer='C',
        explanation='Option C is correct. Due to pi electron delocalization, all six C-C bonds in benzene are identical in length (0.139 nm), intermediate between pure single and pure double bonds.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=75,
        title='Pi Bond Formation Orbitals — 9701/11/M/J/220/Q75',
        syllabus_ref='13.3',
        difficulty='EASY',
        stem='Which atomic orbitals overlap to form the pi bond in methanal, H2C=O?',
        options=['A: End-on overlap of sp2 hybrid orbitals.', 'B: Sideways overlap of the unhybridised 2p orbital of carbon with a 2p orbital of oxygen.', 'C: Overlap of a 1s hydrogen orbital with an sp2 carbon orbital.', 'D: Overlap of two 2s orbitals.'],
        correct_answer='B',
        explanation='Option B is correct. The pi bond in the C=O group arises from the lateral (sideways) overlap of parallel 2p orbitals on carbon and oxygen.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=76,
        title='Classification of Structural Isomerism — 9701/11/M/J/23/Q16',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='What are the three main types of structural isomerism recognized in AS Level Chemistry?',
        options=['A: Cis-trans isomerism, optical isomerism, and conformational isomerism', 'B: Enantiomerism, diastereomerism, and geometric isomerism', 'C: Addition isomerism, substitution isomerism, and elimination isomerism', 'D: Chain isomerism, positional isomerism, and functional group isomerism'],
        correct_answer='D',
        explanation='Option D is correct. Structural isomers have the same molecular formula but different structural formulas (different connectivity of atoms). The three categories are: (1) Chain isomerism (different carbon skeleton branching); (2) Positional isomerism (same skeleton, functional group in different locations); (3) Functional group isomerism (same formula, different functional group).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=77,
        title='Functional Group Isomerism Pair — 9701/12/M/J/23/Q16',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='Which pair of compounds represents functional group isomers with the molecular formula C3H6O?',
        options=['A: Propan-1-ol and propan-2-ol', 'B: Propanoic acid and methyl ethanoate', 'C: Propanal (aldehyde) and propanone (ketone)', 'D: Cyclopropane and propene'],
        correct_answer='C',
        explanation='Option C is correct. Both propanal (CH3CH2CHO) and propanone (CH3COCH3) have molecular formula C3H6O, but propanal contains an aldehyde functional group (-CHO) whereas propanone contains a ketone group (>C=O). They are functional group isomers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=78,
        title='Conditions for Cis-Trans (Geometric) Isomerism — 9701/13/M/J/23/Q16',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='Which two conditions MUST be satisfied for an alkene to exhibit cis-trans (geometric) stereoisomerism?',
        options=['A: Restricted rotation around the carbon-carbon double bond (C=C) AND two different groups attached to EACH carbon of the double bond.', 'B: A chiral center with four different groups attached AND a carbon-carbon double bond.', 'C: At least one triple bond AND identical groups on opposite sides of the molecule.', 'D: A saturated carbon chain of at least five carbon atoms.'],
        correct_answer='A',
        explanation='Option A is correct. Geometric (cis-trans) isomerism requires: (1) Restricted rotation about the C=C bond (due to the pi bond); and (2) Each individual carbon atom of the C=C bond must be bonded to two non-identical groups (i.e. Cab=Ccd, where a!=b and c!=d). If either carbon has two identical groups (e.g. Ca2=Ccd), cis-trans isomerism is impossible.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=79,
        title='Chirality and Optical Activity — 9701/11/O/N/23/Q16',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='What defines a chiral carbon atom (stereocenter) in an organic molecule?',
        options=['A: A carbon atom bonded to a double bond and two hydrogen atoms.', 'B: A carbon atom that forms coordinate bonds with transition metal ions.', 'C: A carbon atom located at the center of an aromatic benzene ring.', 'D: A carbon atom bonded to four completely different atoms or groups of atoms, resulting in non-superimposable mirror images (enantiomers).'],
        correct_answer='D',
        explanation='Option D is correct. A chiral center (asymmetric carbon) is bonded tetrahedrally to four distinct atoms or groups. This asymmetry means the molecule lacks a plane of symmetry, creating two non-superimposable mirror image structures (enantiomers) that rotate the plane of plane-polarized light in opposite directions.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=80,
        title='Identifying Chiral Centers in Alcohols — 9701/12/O/N/23/Q16',
        syllabus_ref='13.4',
        difficulty='MEDIUM',
        stem='Which four-carbon alcohol contains a chiral carbon atom and exists as a pair of optical isomers?',
        options=['A: Butan-1-ol, CH3-CH2-CH2-CH2OH', 'B: Butan-2-ol, CH3-CH(OH)-CH2-CH3', 'C: 2-methylpropan-1-ol, (CH3)2CH-CH2OH', 'D: 2-methylpropan-2-ol, (CH3)3C-OH'],
        correct_answer='B',
        explanation='Option B is correct. In butan-2-ol, C2 is bonded to four different groups: -H, -OH, -CH3, and -CH2CH3. Thus, C2 is a chiral stereocenter, and butan-2-ol exists as two enantiomers. In all other isomers, every carbon has at least two identical groups (-H2, -H3, or -(CH3)2).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=81,
        title='Structural Isomers of Butane — 9701/11/M/J/221/Q81',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='How many structural isomers exist for the alkane with molecular formula C4H10?',
        options=['A: 3', 'B: 2 (butane and 2-methylpropane)', 'C: 4', 'D: 1'],
        correct_answer='B',
        explanation='Option B is correct. C4H10 has exactly two structural chain isomers: unbranched butane (CH3CH2CH2CH3) and branched 2-methylpropane ((CH3)3CH).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=82,
        title='Structural Isomers of Pentane — 9701/12/M/J/222/Q82',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='How many structural isomers exist for the alkane with molecular formula C5H12?',
        options=['A: 2', 'B: 4', 'C: 5', 'D: 3 (pentane, 2-methylbutane, and 2,2-dimethylpropane)'],
        correct_answer='D',
        explanation='Option D is correct. C5H12 has three chain isomers: pentane, 2-methylbutane (isopentane), and 2,2-dimethylpropane (neopentane).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=83,
        title='Positional Isomers of Dichlorobenzene — 9701/13/M/J/223/Q83',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='How many positional isomers exist for dichlorobenzene (C6H4Cl2)?',
        options=['A: 3 (1,2-dichlorobenzene, 1,3-dichlorobenzene, and 1,4-dichlorobenzene)', 'B: 2', 'C: 4', 'D: 1'],
        correct_answer='A',
        explanation='Option A is correct. The chlorine atoms can be 1,2 (ortho), 1,3 (meta), or 1,4 (para), yielding three positional isomers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=84,
        title='Functional Group Isomers of Carboxylic Acids — 9701/11/M/J/224/Q84',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='Which functional group class is isomeric with aliphatic carboxylic acids of formula CnH2nO2?',
        options=['A: Aldehydes', 'B: Alcohols', 'C: Esters', 'D: Ethers'],
        correct_answer='C',
        explanation="Option C is correct. Both aliphatic carboxylic acids (R-COOH) and esters (R-COOR') share the general formula CnH2nO2 and are functional group isomers.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=85,
        title='Cis-Trans in But-2-ene — 9701/12/M/J/220/Q85',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='Why does but-2-ene show cis-trans isomerism while but-1-ene does not?',
        options=['A: In but-2-ene, each double-bond carbon has -H and -CH3; in but-1-ene, C1 has two identical -H atoms.', 'B: But-1-ene has a higher boiling point than but-2-ene.', 'C: But-2-ene contains a chiral carbon atom.', 'D: But-1-ene has sp hybridised carbons.'],
        correct_answer='A',
        explanation='Option A is correct. Cis-trans isomerism requires two different groups on EACH carbon of the C=C bond. In but-1-ene, C1 is bonded to two identical hydrogen atoms (=CH2), so swapping them produces the same molecule.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=86,
        title='Physical Property Differences of Cis-Trans Isomers — 9701/13/M/J/221/Q86',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='How do cis- and trans-1,2-dichloroethene differ in physical properties such as boiling point and dipole moment?',
        options=['A: Both isomers are non-polar with identical boiling points.', 'B: The trans isomer is highly polar with a higher boiling point.', 'C: The cis isomer has a lower melting point due to hydrogen bonding.', 'D: The cis isomer is polar with a higher boiling point; the trans isomer is non-polar (dipoles cancel) with a lower boiling point.'],
        correct_answer='D',
        explanation='Option D is correct. In cis-1,2-dichloroethene, both polar C-Cl bonds point to the same side, creating a net molecular dipole and higher boiling point (60 °C). In trans, the dipoles point in opposite directions and cancel completely (net dipole = 0), lowering the boiling point (48 °C).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=87,
        title='Chirality in Halogenoalkanes — 9701/11/M/J/222/Q87',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='Which molecule contains a chiral center?',
        options=['A: 1-bromobutane', 'B: 2-bromobutane', 'C: 2-bromopropane', 'D: 2-bromo-2-methylpropane'],
        correct_answer='B',
        explanation='Option B is correct. In 2-bromobutane, C2 is bonded to -H, -Br, -CH3, and -CH2CH3 (four different groups), making it chiral.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=88,
        title='Racemic Mixture Definition — 9701/12/M/J/223/Q88',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='What is an equimolar (50:50) mixture of two optical enantiomers called, and what is its net optical rotation?',
        options=['A: A meso compound; it rotates light clockwise.', 'B: A pure enantiomer; it rotates light 180°.', 'C: A racemic mixture (or racemate); it exhibits zero net optical rotation because the equal and opposite rotations cancel.', 'D: A diastereomer; it has a high specific rotation.'],
        correct_answer='C',
        explanation='Option C is correct. A racemate contains equal amounts of (+) and (-) enantiomers. The optical rotation caused by one isomer is precisely cancelled by the equal and opposite rotation of the other, resulting in optical inactivity.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=89,
        title='Number of Optical Isomers for 1 Chiral Center — 9701/13/M/J/224/Q89',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='An organic molecule has exactly one chiral carbon atom. How many stereoisomers exist for this molecule?',
        options=['A: 4', 'B: 2 (a pair of non-superimposable enantiomers)', 'C: 3', 'D: 1'],
        correct_answer='B',
        explanation='Option B is correct. A molecule with n chiral centers and no internal symmetry has 2^n stereoisomers. For n=1, 2^1 = 2 enantiomers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=90,
        title='Optical Activity Detection — 9701/11/M/J/220/Q90',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='How can two optical enantiomers be distinguished experimentally in a laboratory?',
        options=['A: By measuring the direction of rotation of plane-polarized light using a polarimeter.', 'B: By measuring their boiling points.', 'C: By observing their solubility in water.', 'D: By comparing their mass spectra molecular ion peaks.'],
        correct_answer='A',
        explanation='Option A is correct. Enantiomers have identical physical properties (boiling point, density, refractive index, solubility in achiral solvents) except that they rotate the plane of plane-polarized light in equal and opposite directions (+ / d- vs - / l-).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=91,
        title='Isomerism in Pent-2-ene — 9701/12/M/J/221/Q91',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='What type of stereoisomerism is exhibited by pent-2-ene, CH3-CH=CH-CH2-CH3?',
        options=['A: Optical isomerism', 'B: Conformational isomerism only', 'C: No isomerism is possible', 'D: Cis-trans (E/Z) isomerism'],
        correct_answer='D',
        explanation='Option D is correct. Pent-2-ene has a C=C bond where C2 is bonded to -H and -CH3, and C3 is bonded to -H and -CH2CH3. Since both carbons have two different groups, it exists as cis-pent-2-ene and trans-pent-2-ene.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=92,
        title='Chirality in 3-methylhexane — 9701/13/M/J/222/Q92',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='Which carbon atom in 3-methylhexane, CH3-CH2-CH(CH3)-CH2-CH2-CH3, is the chiral stereocenter?',
        options=['A: Carbon-2', 'B: Carbon-4', 'C: Carbon-3', 'D: Carbon-1'],
        correct_answer='C',
        explanation='Option C is correct. Carbon-3 is bonded to four different groups: -H, -CH3 (methyl), -CH2CH3 (ethyl), and -CH2CH2CH3 (propyl).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=93,
        title='Positional Isomers of Propanol — 9701/11/M/J/223/Q93',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='What type of isomerism exists between propan-1-ol and propan-2-ol?',
        options=['A: Positional isomerism', 'B: Chain isomerism', 'C: Functional group isomerism', 'D: Stereoisomerism'],
        correct_answer='A',
        explanation='Option A is correct. Both molecules possess the same 3-carbon chain and the same alcohol functional group (-OH), but the group is at C1 in propan-1-ol and C2 in propan-2-ol (positional isomers).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=94,
        title='Chain Isomerism Example — 9701/12/M/J/224/Q94',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='Which pair of molecules represents chain isomers?',
        options=['A: Propan-1-ol and propan-2-ol', 'B: Ethanoic acid and methyl methanoate', 'C: Pentane and 2,2-dimethylpropane', 'D: But-1-ene and but-2-ene'],
        correct_answer='C',
        explanation='Option C is correct. Pentane (straight 5-carbon chain) and 2,2-dimethylpropane (branched chain) have the same formula C5H12 but different carbon skeleton branching, making them chain isomers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=95,
        title='Total Isomers of C3H6Cl2 — 9701/13/M/J/220/Q95',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='How many structural isomers exist for the dichloropropane molecule C3H6Cl2?',
        options=['A: 3', 'B: 4 (1,1-dichloropropane, 1,2-dichloropropane, 1,3-dichloropropane, and 2,2-dichloropropane)', 'C: 5', 'D: 2'],
        correct_answer='B',
        explanation='Option B is correct. The four isomers are: 1,1-dichloropropane, 1,2-dichloropropane, 1,3-dichloropropane, and 2,2-dichloropropane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=96,
        title='Functional Group Isomerism of Alkenes and Cycloalkanes — 9701/11/M/J/221/Q96',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='What type of isomerism is demonstrated by hex-1-ene and cyclohexane (both C6H12)?',
        options=['A: Chain isomerism', 'B: Positional isomerism', 'C: Optical isomerism', 'D: Functional group isomerism'],
        correct_answer='D',
        explanation='Option D is correct. Open-chain alkenes (with C=C functional group) and ring cycloalkanes (saturated cyclic rings) share formula CnH2n and are functional group isomers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=97,
        title='Stereoisomerism in 1,2-dimethylcyclopropane — 9701/12/M/J/222/Q97',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='Which type of stereoisomerism can be exhibited by 1,2-dimethylcyclopropane?',
        options=['A: Neither cis-trans nor optical isomerism', 'B: Chain isomerism only', 'C: Both cis-trans and optical isomerism', 'D: Functional group isomerism only'],
        correct_answer='C',
        explanation='Option C is correct. The rigid three-membered ring restricts rotation, enabling cis and trans isomers. Furthermore, the trans isomer lacks an internal plane of symmetry and exists as a pair of chiral enantiomers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=98,
        title='Lack of Chirality in Glycine — 9701/13/M/J/223/Q98',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='Why is glycine (2-aminoethanoic acid, H2N-CH2-COOH) the only standard amino acid that is optically inactive?',
        options=['A: Its alpha-carbon is bonded to two identical hydrogen atoms, so it is achiral (lacks 4 different groups).', 'B: It contains an amide bond instead of an amine.', 'C: It exists purely as a gaseous free radical.', 'D: It has a double bond between nitrogen and carbon.'],
        correct_answer='A',
        explanation='Option A is correct. In glycine, the central alpha-carbon is attached to -NH2, -COOH, and TWO -H atoms. Because two groups are identical, it is achiral and optically inactive.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=99,
        title='Isomerism of C2H6O — 9701/11/M/J/224/Q99',
        syllabus_ref='13.4',
        difficulty='EASY',
        stem='What are the two structural isomers of C2H6O, and what type of isomerism do they exhibit?',
        options=['A: Ethanol and ethanal; positional isomerism', 'B: Ethanol and ethanoic acid; chain isomerism', 'C: Methoxymethane and dimethyl ketone; geometric isomerism', 'D: Ethanol (CH3CH2OH) and methoxymethane (CH3OCH3); functional group isomerism'],
        correct_answer='D',
        explanation='Option D is correct. C2H6O has two isomers: ethanol (an alcohol) and methoxymethane / dimethyl ether (an ether). They belong to different functional group classes, exhibiting functional group isomerism.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=100,
        title='E/Z Nomenclature System Basis — 9701/12/M/J/220/Q100',
        syllabus_ref='13.4',
        difficulty='HARD',
        stem='What is the Cahn-Ingold-Prelog (CIP) priority rule used in E/Z isomerism based on?',
        options=['A: The total molecular mass of the entire substituent group.', 'B: The atomic number of the atoms directly attached to the double-bond carbons (higher atomic number = higher priority).', 'C: The alphabetical order of substituent names.', 'D: The number of hydrogen atoms in the substituent.'],
        correct_answer='B',
        explanation='Option B is correct. The CIP priority rules rank substituents based on the atomic number of the atom directly bonded to the stereocenter (e.g. -Br (35) > -Cl (17) > -OH (8) > -CH3 (6) > -H (1)). If high-priority groups are on opposite sides, it is E (entgegen); on the same side, it is Z (zusammen).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=101,
        title='HF 1: Determining Empirical and Molecular Formulas from Percentage Composition — 9701/12/M/J/22/Q13',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='An organic liquid X has the percentage composition by mass: C, 62.07%; H, 10.34%; O, 27.59%. In a mass spectrometer, the molecular ion peak M+ occurs at m/z = 116.0.\n\nWhat is the molecular formula of compound X?',
        options=['A: C3H6O', 'B: C5H8O3', 'C: C6H12O2', 'D: C4H8O2'],
        correct_answer='C',
        explanation='Option C is correct. Moles of C = 62.07/12.0 = 5.1725; moles of H = 10.34/1.0 = 10.34; moles of O = 27.59/16.0 = 1.7244. Divide by smallest (1.7244): C: 5.1725/1.7244 = 3.0; H: 10.34/1.7244 = 6.0; O: 1.7244/1.7244 = 1.0. Empirical formula = C3H6O (formula mass = 3(12) + 6(1) + 16 = 58.0). Since M+ = 116.0, multiplier = 116.0 / 58.0 = 2. Molecular formula = C6H12O2.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=102,
        title='HF 2: Identifying the Number of Chiral Centers in Complex Drug Molecules — 9701/11/O/N/21/Q15',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Menthol is a cyclic organic compound with the structural formula shown below:\n2-isopropyl-5-methylcyclohexan-1-ol\n\nHow many chiral carbon atoms (stereocenters) are present in one molecule of menthol?',
        options=['A: 3 chiral centers (C1 bearing -OH, C2 bearing isopropyl, and C5 bearing methyl)', 'B: 1 chiral center', 'C: 2 chiral centers', 'D: 4 chiral centers'],
        correct_answer='A',
        explanation='Option A is correct. Analyzing the cyclohexane ring: C1 is bonded to -H, -OH, C2, and C6 (different pathways around the ring); C2 is bonded to -H, -CH(CH3)2, C1, and C3; C5 is bonded to -H, -CH3, C4, and C6. Each of these three carbons has four distinctly different groups attached. Thus, menthol contains exactly 3 chiral centers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=103,
        title='HF 3: Systematic IUPAC Naming with Multiple Functional Groups — 9701/13/M/J/22/Q14',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='What is the systematic IUPAC name for CH3-CH(OH)-CH2-CH=CH2?',
        options=['A: Pent-1-en-4-ol', 'B: 4-hydroxypent-1-ene', 'C: 2-hydroxypent-4-ene', 'D: Pent-4-en-2-ol'],
        correct_answer='D',
        explanation='Option D is correct. Under IUPAC nomenclature rules, the principal functional group suffix (alcohol, -ol) takes precedence over the alkene unsaturation (-en-) for determining the lowest locant. Numbering from the right would give the alcohol locant 4, while numbering from the left gives the alcohol locant 2 (pent-4-en-2-ol). Hence, the correct systematic name is pent-4-en-2-ol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=104,
        title='HF 4: Total Number of Isomers with Formula C4H8 — 9701/12/F/M/22/Q16',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Including both structural isomers and stereoisomers (cis-trans), how many isomeric compounds have the molecular formula C4H8?',
        options=['A: 4', 'B: 6 (but-1-ene, cis-but-2-ene, trans-but-2-ene, 2-methylpropene, cyclobutane, and methylcyclopropane)', 'C: 5', 'D: 3'],
        correct_answer='B',
        explanation='Option B is correct. Formula C4H8 has 1 degree of unsaturation. Alkenes: (1) but-1-ene, (2) cis-but-2-ene, (3) trans-but-2-ene, (4) 2-methylpropene. Cycloalkanes: (5) cyclobutane, (6) methylcyclopropane. Total number of isomers = 6.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=105,
        title='HF 5: Hybridisation of Carbon Atoms Across an Unsaturated Chain — 9701/11/M/J/21/Q14',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Consider the compound CH2=CH-C#C-CH3.\n\nFrom left to right, what are the orbital hybridisations of the five carbon atoms?',
        options=['A: sp2, sp2, sp, sp, sp3', 'B: sp2, sp2, sp2, sp2, sp3', 'C: sp3, sp2, sp, sp, sp3', 'D: sp, sp, sp2, sp2, sp3'],
        correct_answer='A',
        explanation='Option A is correct. C1 (CH2=) forms 3 sigma bonds -> sp2; C2 (=CH-) forms 3 sigma bonds -> sp2; C3 (-C#) forms 2 sigma bonds -> sp; C4 (#C-) forms 2 sigma bonds -> sp; C5 (-CH3) forms 4 sigma bonds -> sp3. Sequence: sp2, sp2, sp, sp, sp3.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=106,
        title='HF 6: Mechanism of Free Radical Substitution — Identification of Termination Products — 9701/12/O/N/22/Q15',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='During the reaction between methane and chlorine in the presence of ultraviolet light, trace amounts of ethane, C2H6, are detected in the product mixture.\n\nWhich reaction accounts for the formation of ethane?',
        options=['A: CH4 + .CH3 -> C2H6 + .H', 'B: .CH3 + Cl2 -> C2H6 + 2Cl.', 'C: .CH3 + .CH3 -> C2H6 (a termination step between two methyl radicals)', 'D: CH3Cl + CH3Cl -> C2H6 + Cl2'],
        correct_answer='C',
        explanation='Option C is correct. In the propagation steps, a high concentration of methyl free radicals (.CH3) is generated. When two methyl radicals collide, their single unpaired electrons pair up to form a C-C covalent bond (.CH3 + .CH3 -> C2H6). This radical-radical collision consumes both radicals without generating new ones, representing a classic termination step.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=107,
        title='HF 7: Distinguishing Enantiomers Using Physical and Chemical Properties — 9701/13/O/N/21/Q16',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Which property is DIFFERENT for two optical enantiomers of lactic acid (2-hydroxypropanoic acid)?',
        options=['A: Their boiling points at standard atmospheric pressure.', 'B: The direction in which they rotate the plane of plane-polarized light in a polarimeter.', 'C: Their solubility in pure water at 25 °C.', 'D: Their acid dissociation constant (Ka) in aqueous solution.'],
        correct_answer='B',
        explanation='Option B is correct. Enantiomers possess identical scalar physical properties (boiling point, melting point, density, Ka, solubility in achiral solvents) because the internal interatomic distances and energies are mirror-symmetric. They differ ONLY in their interaction with chiral phenomena: the direction in which they rotate plane-polarized light (+ vs -) and their reaction rates with other chiral reagents/enzymes.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=108,
        title='HF 8: Calculating Sigma and Pi Bonds in Complex Molecules — 9701/11/F/M/23/Q15',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Acrylonitrile (propenenitrile), CH2=CH-C#N, is used in the manufacture of acrylic fibers.\n\nHow many sigma (sigma) bonds and pi (pi) bonds are present in one molecule of acrylonitrile?',
        options=['A: 5 sigma bonds and 4 pi bonds', 'B: 7 sigma bonds and 2 pi bonds', 'C: 4 sigma bonds and 5 pi bonds', 'D: 6 sigma bonds and 3 pi bonds'],
        correct_answer='D',
        explanation='Option D is correct. Counting bonds: 3 C-H single bonds = 3 sigma; 1 C=C double bond = 1 sigma + 1 pi; 1 C-C single bond = 1 sigma; 1 C#N triple bond = 1 sigma + 2 pi. Total sigma bonds = 3 + 1 + 1 + 1 = 6 sigma bonds. Total pi bonds = 1 + 2 = 3 pi bonds.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=109,
        title='HF 9: Predicting Stereoisomerism in Dienes — 9701/12/M/J/23/Q16',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='How many geometric (cis-trans) stereoisomers exist for hexa-2,4-diene, CH3-CH=CH-CH=CH-CH3?',
        options=['A: 3 stereoisomers (cis-cis, trans-trans, and cis-trans)', 'B: 4 stereoisomers', 'C: 2 stereoisomers', 'D: 1 stereoisomer'],
        correct_answer='A',
        explanation='Option A is correct. Hexa-2,4-diene has two C=C bonds, each capable of cis (Z) or trans (E) configurations. Due to the symmetrical nature of the carbon chain, the (cis, trans) and (trans, cis) arrangements are identical by 180° rotation. Thus, there are only 3 distinct geometric isomers: (1) cis,cis-hexa-2,4-diene; (2) trans,trans-hexa-2,4-diene; (3) cis,trans-hexa-2,4-diene.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=110,
        title='HF 10: Deductive Identification of Structural Isomers with C3H8O — 9701/13/M/J/23/Q17',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Three isomeric organic liquids, P, Q, and R, all have the molecular formula C3H8O.\n• P and Q react with sodium metal to evolve hydrogen gas.\n• P can be oxidized by acidified potassium dichromate(VI) to an aldehyde.\n• R does NOT react with sodium metal.\n\nWhat are compounds P, Q, and R?',
        options=['A: P is propan-2-ol, Q is propan-1-ol, and R is propanoic acid', 'B: P is propan-1-ol, Q is methoxyethane, and R is propan-2-ol', 'C: P is propan-1-ol, Q is propan-2-ol, and R is methoxyethane', 'D: P is methoxyethane, Q is propan-1-ol, and R is propan-2-ol'],
        correct_answer='C',
        explanation='Option C is correct. C3H8O has 3 structural isomers: propan-1-ol, propan-2-ol, and methoxyethane (CH3-O-C2H5). Alcohols react with sodium metal to form alkoxides and H2 gas (2ROH + 2Na -> 2RONa + H2), so P and Q are alcohols. Primary alcohols oxidize to aldehydes, identifying P as propan-1-ol (1° alcohol) and Q as propan-2-ol (2° alcohol). Ethers lack O-H bonds and do not react with sodium, confirming R as methoxyethane.',
        figure_path=None,
        figure_caption=None
    ),
]
