"""
Curated 110 Authentic Cambridge AS Chemistry (9701) Paper 1 MCQs
for Topic 14: Hydrocarbons (Alkanes & Alkenes) (100 Core + 10 High-Frequency Core Repeats).
"""

from build_mcq_topic_pdf import MCQQuestion

TOPIC_14_MCQ_QUESTIONS = [
    MCQQuestion(
        number=1,
        title='Incomplete Combustion of Alkanes — 9701/11/M/J/23/Q17',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What are the toxic primary products formed during the incomplete combustion of alkanes in a limited oxygen supply?',
        options=['A: Carbon dioxide, CO2, and sulfur dioxide, SO2', 'B: Carbon monoxide, CO, and solid carbon particulate soot, C', 'C: Methane, CH4, and ozone, O3', 'D: Nitrogen dioxide, NO2, and steam'],
        correct_answer='B',
        explanation='Option B is correct. In a limited supply of oxygen, complete oxidation to CO2 cannot occur. Instead, incomplete combustion takes place, producing highly toxic carbon monoxide gas (CO, which binds irreversibly to hemoglobin) and unburnt carbon particulates (soot/smoke, causing respiratory distress).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=2,
        title='Mechanism of Photochemical Chlorination of Alkanes — 9701/12/M/J/23/Q17',
        syllabus_ref='14.1',
        difficulty='MEDIUM',
        stem='In the free radical chlorination of ethane under ultraviolet light, which equation represents an essential propagation step?',
        options=['A: Cl2 -> 2Cl. (under UV irradiation)', 'B: CH3CH3 + Cl. -> CH3CH2Cl + H.', 'C: CH3CH2. + Cl. -> CH3CH2Cl', 'D: CH3CH2. + Cl2 -> CH3CH2Cl + Cl.'],
        correct_answer='D',
        explanation='Option D is correct. The propagation steps in the chlorination of ethane are: (1) Cl. + CH3CH3 -> CH3CH2. + HCl; and (2) CH3CH2. + Cl2 -> CH3CH2Cl + Cl.. Option A is initiation; Option C is termination; Option B incorrectly shows hydrogen radical abstraction (which does not occur because H-Cl bond enthalpy is so much higher than C-Cl).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=3,
        title='Catalytic Cracking of Long-Chain Alkanes — 9701/13/M/J/23/Q17',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What are the standard industrial conditions used for the catalytic cracking of long-chain hydrocarbons, and what types of products are formed?',
        options=['A: Zeolite (aluminosilicate) catalyst at approximately 500 °C; produces shorter-chain branched alkanes and alkenes.', 'B: Concentrated sulfuric acid at 100 °C; produces carboxylic acids and esters.', 'C: Nickel catalyst at 150 °C; produces cycloalkanes and hydrogen gas.', 'D: Iron catalyst at 450 °C and 200 atm; produces aromatic compounds exclusively.'],
        correct_answer='A',
        explanation='Option A is correct. Catalytic cracking passes vaporised heavy gas oil over a synthetic zeolite (silica/alumina) catalyst at ~500 °C under slight pressure. C-C bonds undergo heterolytic/homolytic cleavage to produce shorter, high-demand fuels (branched alkanes with high octane ratings) and valuable unsaturated chemical feedstocks (alkenes like ethene and propene).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=4,
        title='Multi-Halogenation in Free Radical Substitution — 9701/11/O/N/23/Q17',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='When methane is reacted with an excess of chlorine gas in the presence of strong UV light, what is the ultimate principal organic product formed?',
        options=['A: Chloromethane, CH3Cl', 'B: Dichloromethane, CH2Cl2', 'C: Tetrachloromethane, CCl4', 'D: Hexachloroethane, C2Cl6'],
        correct_answer='C',
        explanation='Option C is correct. With excess chlorine, successive propagation cycles replace each remaining hydrogen atom on the carbon: CH4 -> CH3Cl -> CH2Cl2 -> CHCl3 -> CCl4. With sufficient Cl2 and UV irradiation, all four hydrogens are substituted, yielding tetrachloromethane (CCl4) as the final major organic product.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=5,
        title='Homolytic Fission in Initiation — 9701/13/M/J/220/Q5',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='Why does the Cl-Cl bond break in preference to the C-H bond during the initiation stage of alkane chlorination?',
        options=['A: The Cl-Cl bond enthalpy (242 kJ mol^-1) is much lower than the C-H bond enthalpy (413 kJ mol^-1), so UV photons selectively cleave Cl-Cl.', 'B: The C-H bond is completely ionic.', 'C: Chlorine molecules absorb infrared radiation rather than UV.', 'D: Carbon atoms repel ultraviolet radiation.'],
        correct_answer='A',
        explanation='Option A is correct. The Cl-Cl bond is relatively weak (242 kJ/mol), so UV light of wavelength ~330 nm carries sufficient quantum energy (E=hf) to cause homolytic fission of Cl-Cl, whereas the strong C-H bond (413 kJ/mol) cannot be cleaved directly.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=6,
        title='Environmental Impact of Unburnt Hydrocarbons — 9701/11/M/J/221/Q6',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='What environmental problem is caused by unburnt hydrocarbons emitted from vehicle exhaust pipes?',
        options=['A: They cause immediate ozone hole depletion in the stratosphere.', 'B: They acidify rain to pH 1.0.', 'C: They neutralize alkaline lake waters.', 'D: They react with nitrogen oxides and sunlight to form photochemical smog and ground-level ozone.'],
        correct_answer='D',
        explanation='Option D is correct. Unburnt volatile organic compounds (VOCs) react with NOx under sunlight to generate peroxyacetyl nitrate (PAN) and tropospheric ozone, creating irritating photochemical smog.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=7,
        title='Thermal vs Catalytic Cracking — 9701/12/M/J/222/Q7',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='How does thermal cracking differ from catalytic cracking in its primary product yield?',
        options=['A: Thermal cracking requires platinum catalysts at room temperature.', 'B: Thermal cracking uses high temperature (700-1000 °C) and pressure to produce a high proportion of straight-chain alkenes (ethene, propene).', 'C: Thermal cracking only yields methane and hydrogen.', 'D: Thermal cracking produces exclusively cyclic aromatics.'],
        correct_answer='B',
        explanation='Option B is correct. Thermal cracking operates at severe temperatures (700-1000 °C) and pressures (up to 70 atm) via free radical mechanisms, yielding large fractions of terminal alkenes.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=8,
        title='Mechanism of Bromine Abstraction — 9701/13/M/J/223/Q8',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='In the bromination of propane, why is 2-bromopropane the major mono-substituted product rather than 1-bromopropane?',
        options=['A: Bromine atoms are too large to fit at the terminal position.', 'B: 1-bromopropane has a much higher boiling point.', 'C: The secondary 2-propyl radical formed as an intermediate is more stable than the primary 1-propyl radical due to the +I inductive effect of two methyl groups.', 'D: Secondary C-H bonds are completely unreactive.'],
        correct_answer='C',
        explanation='Option C is correct. Hydrogen abstraction can form a 1° radical (CH3CH2CH2.) or a 2° radical (CH3CH.CH3). The 2° radical is stabilized by two electron-donating methyl groups (+I effect), lowering the activation energy for its formation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=9,
        title='Combustion Stoichiometry of Propane — 9701/11/M/J/224/Q9',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What volume of oxygen gas (measured at RTP) is required for the complete combustion of 1.0 dm^3 of propane, C3H8?',
        options=['A: 3.0 dm^3', 'B: 5.0 dm^3', 'C: 4.0 dm^3', 'D: 10.0 dm^3'],
        correct_answer='B',
        explanation="Option B is correct. Equation: C3H8(g) + 5O2(g) -> 3CO2(g) + 4H2O(l). By Avogadro's law, gas volume ratios equal mole ratios at the same T and P. Thus, 1.0 dm^3 of C3H8 requires 5.0 dm^3 of O2.",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=10,
        title='Greenhouse Effect and Alkanes — 9701/12/M/J/220/Q10',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Why is methane (CH4) a potent greenhouse gas compared to carbon dioxide?',
        options=['A: Methane absorbs infrared radiation intensely across key atmospheric window wavelengths, having a global warming potential ~28 times greater than CO2.', 'B: Methane reacts with water to form carbonic acid.', "C: Methane destroys the Earth's magnetic field.", 'D: Methane forms a physical reflective cloud of ice in the mesosphere.'],
        correct_answer='A',
        explanation='Option A is correct. Methane molecules possess C-H stretching and bending vibrational modes that absorb infrared radiation strongly in the thermal infrared window, trapping re-radiated heat.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=11,
        title='Fractional Distillation of Crude Oil — 9701/13/M/J/221/Q11',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='On what physical property does the separation of crude oil fractions in a fractionating column depend?',
        options=['A: Differences in chemical reactivity with water.', 'B: Differences in density of solid precipitates.', 'C: Differences in solubility in ethanol.', 'D: Differences in boiling points, which depend directly on molecular size and intermolecular London dispersion forces.'],
        correct_answer='D',
        explanation='Option D is correct. Crude oil is separated by fractional distillation: smaller hydrocarbons have fewer electrons, weaker London dispersion forces, and lower boiling points, condensing near the top of the tower.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=12,
        title='Reactivity of Alkanes — 9701/11/M/J/222/Q12',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Why are alkanes generally inert to attack by acids, bases, oxidizing agents, and nucleophiles at room temperature?',
        options=['A: Alkanes possess delocalized pi electron clouds that shield the bonds.', 'B: Carbon atoms in alkanes are sp hybridised.', 'C: Alkanes contain only strong, non-polar C-C and C-H sigma bonds with no region of high or low electron density to attract attacking reagents.', 'D: Alkanes form strong hydrogen bonds that resist reaction.'],
        correct_answer='C',
        explanation='Option C is correct. The C-C and C-H bonds have high bond energies (348 and 413 kJ/mol) and almost identical electronegativities (C=2.5, H=2.1), leaving no polar delta+ sites or lone pairs for reagents to attack.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=13,
        title='Catalytic Reforming of Alkanes — 9701/12/M/J/223/Q13',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What is the purpose of catalytic reforming of straight-chain alkanes in petroleum refining?',
        options=['A: To convert straight-chain alkanes into branched alkanes and cyclic/aromatic hydrocarbons to increase the octane rating of fuels.', 'B: To convert alkanes into synthetic detergents.', 'C: To completely crack all fuel into pure hydrogen.', 'D: To oxidize alkanes into carboxylic acids.'],
        correct_answer='A',
        explanation='Option A is correct. Straight-chain alkanes knock easily in car engines. Catalytic reforming (using Pt catalyst at 500 °C) isomerises them into branched and aromatic rings (like benzene/toluene), greatly boosting octane numbers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=14,
        title='Combustion Analysis of Pentane — 9701/13/M/J/224/Q14',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='How many moles of water are produced by the complete combustion of one mole of pentane, C5H12?',
        options=['A: 5 moles', 'B: 12 moles', 'C: 6 moles', 'D: 10 moles'],
        correct_answer='C',
        explanation='Option C is correct. Combustion equation: C5H12 + 8O2 -> 5CO2 + 6H2O. Each mole of C5H12 contains 12 hydrogen atoms, producing 6 moles of H2O.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=15,
        title='Propagation Steps in Halogenation — 9701/11/M/J/220/Q15',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What is the net energetic characteristic of the two propagation steps in alkane chlorination?',
        options=['A: Propagation requires constant input of external UV light.', 'B: The overall propagation sequence is exothermic, providing the thermodynamic driving force for continuous chain reaction.', 'C: Propagation creates two radicals from one radical.', 'D: Propagation forms ionic salts.'],
        correct_answer='B',
        explanation='Option B is correct. The sum of the two propagation steps equals the overall reaction (CH4 + Cl2 -> CH3Cl + HCl), which is exothermic (delta-H ~ -100 kJ/mol), sustaining the reaction without further initiation once radicals exist.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=16,
        title='Limiting Multi-Substitution — 9701/12/M/J/221/Q16',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='How can the reaction conditions be adjusted to maximize the yield of monochloromethane (CH3Cl) over higher chlorinated products?',
        options=['A: Use a large excess of chlorine gas.', 'B: Carry out the reaction at 500 °C in darkness.', 'C: Add concentrated sulfuric acid as a catalyst.', 'D: Use a large excess of methane relative to chlorine.'],
        correct_answer='D',
        explanation='Option D is correct. With a large excess of methane, a chlorine radical is far more likely to collide with an unreacted CH4 molecule than with a CH3Cl molecule, minimizing poly-substitution.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=17,
        title='Alkanes as Non-Polar Solvents — 9701/13/M/J/222/Q17',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='Why are liquid alkanes (such as hexane) immiscible with water but excellent solvents for non-polar grease?',
        options=['A: Hexane reacts vigorously with water to form hexanol.', 'B: Water molecules are non-polar and repel hexane.', 'C: Hexane molecules cannot form hydrogen bonds with water molecules; the London forces between hexane and grease molecules are favorable for dissolution.', 'D: Hexane has a very high dielectric constant.'],
        correct_answer='C',
        explanation='Option C is correct. Water molecules form extensive hydrogen bond networks. Hexane cannot form hydrogen bonds to disrupt water-water attractions, but easily dissolves non-polar compounds via London dispersion forces.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=18,
        title='Isomer Distribution in Free Radical Chlorination — 9701/11/M/J/223/Q18',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='When propane reacts with chlorine in UV light, what are the two mono-chloro structural isomers formed?',
        options=['A: 1-chloropropane and 2-chloropropane', 'B: 1-chloropropane and 3-chloropropane', 'C: 2-chloropropane and 2,2-dichloropropane', 'D: Chlorocyclopropane and chloropropene'],
        correct_answer='A',
        explanation='Option A is correct. Monochlorination of propane yields two positional isomers: 1-chloropropane (substitution at C1/C3) and 2-chloropropane (substitution at C2).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=19,
        title='Termination Step Combining Alkyl Radicals — 9701/12/M/J/224/Q19',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='In the photochemical bromination of bromoethane, which species would NOT be formed in a termination step?',
        options=['A: 1,2-dibromoethane', 'B: 1,1-dibromoethane', 'C: 1,4-dibromobutane', 'D: Hydrogen gas, H2'],
        correct_answer='D',
        explanation='Option D is correct. Termination involves radical pairing (R. + Br. -> RBr, or R. + R. -> R-R). Free hydrogen atoms (.H) are never formed in organic free radical mechanisms, so H2 is never formed as a termination product.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=20,
        title='Relative Reactivity: Fluorine vs Chlorine vs Bromine vs Iodine — 9701/13/M/J/220/Q20',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Which halogens react explosively and which does not react at all with alkanes under standard photochemical conditions?',
        options=['A: Chlorine is inert; iodine is explosive.', 'B: Fluorine reacts explosively; iodine does not react at all (endothermic).', 'C: Bromine is explosive; fluorine is inert.', 'D: All halogens react at identical rates.'],
        correct_answer='B',
        explanation='Option B is correct. Fluorination is violently explosive even in the dark (delta-H highly exothermic, low activation energy); iodination is endothermic and does not take place because I. is too unreactive to abstract hydrogen.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=21,
        title='Octane Rating and Branching — 9701/11/M/J/221/Q21',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='Why do highly branched alkanes burn more smoothly in petrol engines than straight-chain isomers?',
        options=['A: Branched alkanes have higher boiling points than straight chains.', "B: Branching slows the formation of pre-ignition peroxides during compression, preventing engine 'knocking'.", 'C: Branched alkanes have higher carbon-to-hydrogen ratios.', 'D: Branched alkanes are completely non-flammable.'],
        correct_answer='B',
        explanation='Option B is correct. Branched alkanes produce more stable intermediate radicals and burn with a controlled flame front, resisting auto-ignition (knocking) under engine compression.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=22,
        title='Carbon Footprint of Fuels — 9701/12/M/J/222/Q22',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Which alkane releases the LEAST mass of CO2 per kilojoule of energy released upon complete combustion?',
        options=['A: Propane, C3H8', 'B: Octane, C8H18', 'C: Hexadecane, C16H34', 'D: Methane, CH4'],
        correct_answer='D',
        explanation='Option D is correct. Methane has the highest H:C ratio (4:1) of any hydrocarbon. A higher proportion of its combustion heat comes from forming O-H bonds (in H2O) rather than C=O bonds (in CO2), emitting less CO2 per MJ of energy.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=23,
        title='Chain Length and Viscosity — 9701/13/M/J/223/Q23',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='How does the viscosity of liquid alkanes change as carbon chain length increases?',
        options=['A: Viscosity increases because longer chains have greater surface contact area and stronger London dispersion forces that tangle molecules.', 'B: Viscosity decreases because longer chains flow faster.', 'C: Viscosity remains completely constant.', 'D: Viscosity increases due to formation of covalent crosslinks.'],
        correct_answer='A',
        explanation='Option A is correct. As chain length grows, polarisability increases, London dispersion forces strengthen, and long chains become physically entangled, causing viscosity to increase steadily.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=24,
        title='Free Radical Inhibitors — 9701/11/M/J/224/Q24',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Why does the addition of trace amounts of oxygen gas temporarily retard the photochemical chlorination of methane?',
        options=['A: Oxygen dissolves all chlorine gas.', 'B: Oxygen cools the reaction vessel to -50 °C.', 'C: Oxygen reacts with alkyl free radicals to form unreactive peroxy radicals (ROO.), terminating chain propagation.', 'D: Oxygen absorbs ultraviolet light completely.'],
        correct_answer='C',
        explanation='Option C is correct. Molecular oxygen (O2) has diradical character and scavenges alkyl radicals (.CH3 + O2 -> CH3OO.), which are far less reactive and cannot propagate the chain until oxygen is consumed.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=25,
        title='Cracking of Dodecane — 9701/12/M/J/220/Q25',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='In the cracking of dodecane (C12H26), one molecule yields one molecule of octane (C8H18) and two molecules of an identical alkene. What is the alkene?',
        options=['A: Ethene, C2H4', 'B: Propene, C3H6', 'C: But-1-ene, C4H8', 'D: Methane, CH4'],
        correct_answer='A',
        explanation='Option A is correct. Conservation of atoms: C12H26 -> C8H18 + 2(C2H4). Carbons: 12 - 8 = 4, divided by 2 = 2 (C2H4, ethene).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=26,
        title='Combustion of Cycloalkanes — 9701/13/M/J/221/Q26',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='What is the balanced equation for the complete combustion of one mole of cyclohexane (C6H12)?',
        options=['A: C6H12 + 6O2 -> 6CO + 6H2O', 'B: C6H12 + 12O2 -> 6CO2 + 6H2', 'C: C6H12 + 8O2 -> 6CO2 + 6H2O', 'D: C6H12 + 9O2 -> 6CO2 + 6H2O'],
        correct_answer='D',
        explanation='Option D is correct. C6H12 requires 6 moles of O2 for carbon (forming 6CO2) and 3 moles of O2 for hydrogen (forming 6H2O). Total O2 = 6 + 3 = 9 moles.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=27,
        title='Pollutants in Exhaust Gases — 9701/11/M/J/222/Q27',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='Which compound is NOT a direct pollutant emitted in internal combustion engine exhaust gases?',
        options=['A: Carbon monoxide, CO', 'B: Ozone, O3', 'C: Nitrogen monoxide, NO', 'D: Unburnt hydrocarbons'],
        correct_answer='B',
        explanation='Option B is correct. Ozone is a secondary pollutant formed in the troposphere via photochemical reactions of NO2 and VOCs in sunlight; it is not emitted directly from car exhausts.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=28,
        title='Stability of Alkyl Radicals — 9701/12/M/J/223/Q28',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Why is the tertiary butyl radical, .(CH3)3C, significantly more stable than the primary butyl radical?',
        options=['A: Tertiary radicals have complete electron octets.', 'B: Tertiary radicals are planar while primary radicals are spherical.', 'C: Hyperconjugation and the electron-donating inductive effect (+I) of three methyl groups delocalise the unpaired electron.', 'D: Tertiary radicals form hydrogen bonds.'],
        correct_answer='C',
        explanation='Option C is correct. Alkyl groups donate electron density toward the electron-deficient trivalent carbon atom via inductive effect and hyperconjugation, stabilizing 3° > 2° > 1° radicals.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=29,
        title='Boiling Point of Alkane Isomers — 9701/13/M/J/224/Q29',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='Why does 2,2-dimethylpropane have a lower boiling point (9.5 °C) than pentane (36.1 °C) despite having the identical molecular mass?',
        options=['A: Pentane contains polar covalent bonds.', 'B: Its spherical, branched shape provides less surface contact area between molecules, resulting in weaker London dispersion forces.', 'C: 2,2-dimethylpropane forms intramolecular hydrogen bonds.', 'D: Pentane has a higher vapor pressure.'],
        correct_answer='B',
        explanation='Option B is correct. Branching makes molecules more compact and spherical. Spheres touch at only one point, reducing molecular surface contact area. Less surface contact produces weaker London dispersion forces, lowering the boiling point.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=30,
        title='Homologous Series Enthalpy of Combustion — 9701/11/M/J/220/Q30',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='How does the standard enthalpy of combustion (delta-H_c) change per additional -CH2- unit down the alkane homologous series?',
        options=['A: It becomes more exothermic by approximately -650 kJ mol^-1 per -CH2- group.', 'B: It becomes endothermic.', 'C: It decreases to zero.', 'D: It doubles for every carbon atom.'],
        correct_answer='A',
        explanation='Option A is correct. Each additional -CH2- group requires 1.5 extra O2 molecules and forms one more CO2 and H2O, adding approximately -650 kJ/mol of exothermic energy.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=31,
        title='Free Radical Dimerisation — 9701/12/M/J/221/Q31',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='During the photobromination of 2-methylpropane, what is the hydrocarbon formed if two tertiary butyl radicals undergo termination?',
        options=['A: 2,2,4-trimethylpentane', 'B: Octane', 'C: 2,3-dimethylbutane', 'D: 2,2,3,3-tetramethylbutane'],
        correct_answer='D',
        explanation='Option D is correct. Coupling of two (CH3)3C. radicals forms (CH3)3C-C(CH3)3, which is 2,2,3,3-tetramethylbutane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=32,
        title='Soot Particle Health Hazards — 9701/13/M/J/222/Q32',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='What is the primary human health hazard associated with PM2.5 carbon soot particles from diesel engines?',
        options=['A: They cause immediate tooth decay.', 'B: They neutralize stomach hydrochloric acid.', 'C: They penetrate deep into the alveoli of the lungs, carrying carcinogenic polycyclic aromatic hydrocarbons into the bloodstream.', 'D: They deplete calcium from bones.'],
        correct_answer='C',
        explanation='Option C is correct. Particulate matter <= 2.5 micrometers (PM2.5) bypasses nasal filtration, penetrating deep into lung alveoli and causing severe cardiovascular and respiratory diseases and cancer.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=33,
        title='Oxidation of Alkanes by KMnO4 — 9701/11/M/J/223/Q33',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What is observed when an alkane (such as hexane) is shaken with cold, acidified potassium manganate(VII)?',
        options=['A: No reaction occurs; the purple color of KMnO4 remains unchanged.', 'B: The purple solution turns green immediately.', 'C: A brown precipitate of MnO2 forms with vigorous effervescence.', 'D: The hexane is oxidized to hexanoic acid.'],
        correct_answer='A',
        explanation='Option A is correct. Alkanes are saturated and lack electron-rich pi bonds; they are completely resistant to oxidation by cold acidified KMnO4.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=34,
        title='Industrial Source of Alkanes — 9701/12/M/J/224/Q34',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='What is the primary natural source from which alkanes are industrially extracted?',
        options=['A: Fermentation of sugar cane', 'B: Electrolysis of brine', 'C: Crude petroleum oil and natural gas', 'D: Destructive distillation of wood'],
        correct_answer='C',
        explanation='Option C is correct. Petroleum (crude oil) and natural gas are the overwhelming industrial sources of alkanes, formed by geothermal heating and compression of prehistoric marine biomass over millions of years.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=35,
        title='Radical Abstraction Selectivity — 9701/13/M/J/220/Q35',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='Why is bromine significantly more regioselective than chlorine in free radical substitution reactions of alkanes?',
        options=['A: Bromine is a smaller atom than chlorine.', 'B: The hydrogen abstraction step by Br. is endothermic and has a late transition state resembling the carbocation/radical intermediate, whereas for Cl. it is exothermic with an early transition state.', 'C: Bromine radicals are positively charged.', 'D: Chlorine cannot form secondary radicals.'],
        correct_answer='B',
        explanation="Option B is correct. By Hammond's postulate, because hydrogen abstraction by Br. is endothermic, the transition state resembles the radical intermediate, making the energy difference between 1° and 2°/3° pathways much larger (high regioselectivity).",
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=36,
        title='Catalytic Converter Chemistry for Alkanes — 9701/11/M/J/221/Q36',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='What reaction takes place on the platinum/palladium catalyst in a three-way catalytic converter to remove unburnt alkanes?',
        options=['A: Reduction to solid carbon and hydrogen gas.', 'B: Hydrolysis by exhaust steam to alcohols.', 'C: Polymerisation into solid plastics.', 'D: Complete oxidation by excess oxygen: CxHy + (x + y/4)O2 -> xCO2 + y/2 H2O'],
        correct_answer='D',
        explanation='Option D is correct. The oxidation catalyst (Pt/Pd) oxidizes unburnt hydrocarbons and toxic CO into harmless CO2 and H2O: CxHy + O2 -> CO2 + H2O; 2CO + O2 -> 2CO2.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=37,
        title='Methane Hydrates — 9701/12/M/J/222/Q37',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What are methane hydrates (clathrates) found in deep ocean sediments and permafrost?',
        options=['A: Solid salts of methane and sodium hydroxide.', 'B: Liquid solutions of methane in liquid ammonia.', 'C: Crystalline water ice cages that trap methane gas molecules under high pressure and low temperature.', 'D: Polymeric chains of methane linked by covalent bonds.'],
        correct_answer='C',
        explanation='Option C is correct. Methane clathrate is a solid lattice of water molecules physically encaging methane gas molecules, stable under high hydrostatic ocean pressures and near-freezing temperatures.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=38,
        title='Thermodynamic Stability of Alkanes — 9701/13/M/J/223/Q38',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Although alkanes are thermodynamically unstable with respect to combustion in air (exothermic), why are they kinetically stable at room temperature?',
        options=['A: They possess a very high activation energy barrier due to the need to break strong C-H and C-C covalent bonds.', 'B: Their combustion is an endothermic equilibrium.', 'C: They are protected by an impenetrable electrostatic shield.', 'D: Oxygen molecules cannot collide with alkanes at 25 °C.'],
        correct_answer='A',
        explanation='Option A is correct. While delta-G for alkane combustion is large and negative, the reaction does not occur at 25 °C without a spark because the activation energy (breaking strong covalent bonds) is very high, imparting kinetic stability.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=39,
        title='Free Radical Chlorination in Darkness — 9701/11/M/J/224/Q39',
        syllabus_ref='14.1',
        difficulty='EASY',
        stem='What happens when a mixture of methane and chlorine gas is kept at room temperature in complete darkness?',
        options=['A: The mixture explodes violently within 5 seconds.', 'B: Methane is converted slowly into carbon soot.', 'C: Chlorine gas condenses into a yellow liquid.', 'D: No reaction occurs because no UV photons are present to supply the activation energy for homolytic fission of Cl2.'],
        correct_answer='D',
        explanation='Option D is correct. Without UV light (or temperatures > 300 °C), Cl-Cl bonds cannot undergo homolytic cleavage to generate the initiating chlorine radicals, so the mixture remains completely unreacted.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=40,
        title='Cracking Byproduct Uses — 9701/12/M/J/220/Q40',
        syllabus_ref='14.1',
        difficulty='HARD',
        stem='Why are the alkene byproducts of catalytic cracking (such as ethene and propene) of such immense economic importance to the chemical industry?',
        options=['A: They are used directly as aircraft lubricating oils.', 'B: They serve as reactive raw monomers for the manufacture of addition polymers (polyethene, polypropene) and alcohols.', 'C: They are used as non-toxic fire extinguishants.', 'D: They are used to sweeten fruit juices.'],
        correct_answer='B',
        explanation='Option B is correct. Alkenes contain reactive C=C double bonds, making them prime feedstocks for synthesis of plastics, synthetic rubbers, epoxy resins, antifreeze, and pharmaceuticals.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=41,
        title='Mechanism of Bromine Addition to Ethene — 9701/11/M/J/23/Q18',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What type of reaction mechanism occurs when ethene reacts with bromine dissolved in an inert organic solvent, and what is the visual observation?',
        options=['A: Nucleophilic substitution; a white precipitate is formed.', 'B: Electrophilic addition; the orange-brown bromine solution is immediately decolorized.', 'C: Free radical substitution; the solution turns intense purple.', 'D: Elimination; bubbles of hydrogen bromide gas are evolved.'],
        correct_answer='B',
        explanation='Option B is correct. The high electron density of the C=C pi bond induces a dipole in the Br2 molecule (Br(delta+)-Br(delta-)). The delta+ bromine acts as an electrophile, accepting electrons from the pi bond to form a carbocation / bromonium ion intermediate, which is attacked by Br- to yield 1,2-dibromoethane. The orange color of bromine disappears (decolorization).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=42,
        title='Markovnikov Addition of HBr to Propene — 9701/12/M/J/23/Q18',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='When hydrogen bromide, HBr, reacts with propene (CH3-CH=CH2), what is the major organic product and what explains its formation?',
        options=['A: 1-bromopropane; the primary carbocation is more stable due to steric factors.', 'B: 1,2-dibromopropane; both carbons add bromine simultaneously.', 'C: Cyclopropane; HBr causes cyclization of the propene chain.', 'D: 2-bromopropane; the reaction proceeds via the more stable secondary carbocation intermediate (CH3-CH+-CH3).'],
        correct_answer='D',
        explanation='Option D is correct. Electrophilic addition of H+ can form either a primary carbocation (CH3CH2CH2+) or a secondary carbocation (CH3CH+CH3). The secondary carbocation has two electron-donating methyl groups (+I inductive effect) that disperse the positive charge, lowering its activation energy. Attack by Br- on the 2° carbocation yields 2-bromopropane as the major product.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=43,
        title='Oxidation of Alkenes by Cold, Dilute KMnO4 — 9701/13/M/J/23/Q18',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What organic product and color change occur when propene is shaken with cold, dilute, acidified potassium manganate(VII)?',
        options=['A: Propane-1,2-diol is formed; the purple solution is decolorized (or forms a brown precipitate of MnO2 in neutral conditions).', 'B: Carbon dioxide and ethanoic acid are formed with vigorous effervescence.', 'C: Propanone is formed with no color change.', 'D: Propanoic acid is formed; the solution turns bright green.'],
        correct_answer='A',
        explanation='Option A is correct. Cold, dilute KMnO4 acts as a mild oxidizing agent that hydrolyzes the alkene across the double bond without cleaving the C-C sigma bond, adding two -OH groups to give a vicinal diol (propane-1,2-diol). The purple MnO4- ion is reduced to colorless Mn2+ (in acid) or brown MnO2 precipitate (in neutral/alkaline medium).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=44,
        title='Oxidative Cleavage of Alkenes by Hot, Concentrated KMnO4 — 9701/11/O/N/23/Q18',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='An alkene X is heated under reflux with hot, concentrated, acidified potassium manganate(VII). The only organic products obtained are propanone (CH3COCH3) and ethanoic acid (CH3COOH).\n\nWhat is the structural formula of alkene X?',
        options=['A: 2-methylbut-1-ene, CH2=C(CH3)-CH2CH3', 'B: Pent-2-ene, CH3-CH=CH-CH2CH3', 'C: 2-methylbut-2-ene, (CH3)2C=CH-CH3', 'D: 3-methylbut-1-ene, CH2=CH-CH(CH3)2'],
        correct_answer='C',
        explanation='Option C is correct. Under hot concentrated KMnO4, the C=C bond is completely cleaved: =CR2 fragments oxidize to ketones (R2C=O), =CHR fragments oxidize to carboxylic acids (RCOOH), and =CH2 fragments oxidize to CO2 + H2O. Since the products are propanone ((CH3)2C=O) and ethanoic acid (CH3COOH), the original alkene must be (CH3)2C=CH-CH3 (2-methylbut-2-ene).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=45,
        title='Industrial Hydration of Ethene — 9701/11/M/J/220/Q45',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What catalyst and conditions are used in the direct industrial manufacture of ethanol from ethene and steam?',
        options=['A: Concentrated phosphoric(V) acid (H3PO4) adsorbed on silica at 300 °C and 60 atm pressure.', 'B: Nickel catalyst at 150 °C and 1 atm.', 'C: Concentrated sulfuric acid at 0 °C.', 'D: Iron catalyst at 450 °C and 200 atm.'],
        correct_answer='A',
        explanation='Option A is correct. The industrial hydration of ethene (C2H4 + H2O -> C2H5OH) uses steam over a solid H3PO4 catalyst supported on silica at 300 °C and 60 atm.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=46,
        title='Catalytic Hydrogenation of Alkenes — 9701/12/M/J/221/Q46',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What catalyst, temperature, and industrial application are associated with the addition of hydrogen to alkenes?',
        options=['A: Iron catalyst at 450 °C; used in cracking petroleum.', 'B: Vanadium(V) oxide at 450 °C; used in making sulfuric acid.', 'C: Zeolite catalyst at 500 °C; used in making branched fuels.', 'D: Finely divided Nickel catalyst at 150 °C (or Pt at RTP); used in hardening vegetable oils to make margarine.'],
        correct_answer='D',
        explanation='Option D is correct. Hydrogenation of liquid vegetable oils (containing polyunsaturated alkenes) over a nickel catalyst at ~150 °C saturates C=C bonds, raising the melting point to produce semi-solid margarine.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=47,
        title='Electrophilic Addition of Bromine Water — 9701/13/M/J/222/Q47',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='When propene is bubbled through aqueous bromine water (Br2(aq)), what is the major organic product formed?',
        options=['A: 1,2-dibromopropane', 'B: 1-bromopropan-2-ol, CH3-CH(OH)-CH2Br', 'C: 2-bromopropan-1-ol', 'D: Propan-2-ol'],
        correct_answer='B',
        explanation='Option B is correct. In aqueous bromine, water molecules are present in overwhelming concentration compared to Br- ions. After the electrophile Br+ attacks to form the secondary carbocation (CH3-CH+-CH2Br), nucleophilic H2O attacks the 2° carbon, forming a halohydrin: 1-bromopropan-2-ol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=48,
        title='Cleavage Products of Terminal =CH2 Group — 9701/11/M/J/223/Q48',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='When a terminal alkene containing a =CH2 group is treated with hot, concentrated, acidified KMnO4, what oxidation products are formed from that terminal group?',
        options=['A: Methanoic acid (HCOOH)', 'B: Methanal (HCHO)', 'C: Carbon dioxide (CO2) and water (H2O)', 'D: Methanol (CH3OH)'],
        correct_answer='C',
        explanation='Option C is correct. Under hot concentrated KMnO4, a terminal =CH2 group is initially oxidized to methanoic acid (HCOOH), which undergoes rapid further oxidation by KMnO4 into carbon dioxide (CO2) and water (H2O), producing visible effervescence.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=49,
        title='Cleavage Products of 2,3-dimethylbut-2-ene — 9701/12/M/J/224/Q49',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What single organic product is formed when 2,3-dimethylbut-2-ene, (CH3)2C=C(CH3)2, is heated with hot, concentrated, acidified KMnO4?',
        options=['A: Ethanoic acid', 'B: Propanone, CH3COCH3', 'C: 2-methylpropanoic acid', 'D: Carbon dioxide'],
        correct_answer='B',
        explanation='Option B is correct. The symmetrical alkene (CH3)2C=C(CH3)2 cleaves across the C=C bond. Both sides consist of =C(CH3)2 groups, yielding two molecules of propanone ((CH3)2C=O).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=50,
        title='Addition of Chlorine to But-2-ene — 9701/13/M/J/220/Q50',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the systematic name of the product formed by the addition of chlorine to but-2-ene?',
        options=['A: 2,3-dichlorobutane', 'B: 1,2-dichlorobutane', 'C: 1,4-dichlorobutane', 'D: 2-chlorobutane'],
        correct_answer='A',
        explanation='Option A is correct. Addition of Cl2 across the C2=C3 double bond adds one chlorine to each carbon, yielding 2,3-dichlorobutane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=51,
        title='Carbocation Rearrangement Likelihood — 9701/11/M/J/221/Q51',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Why does 3,3-dimethylbut-1-ene yield 2-bromo-2,3-dimethylbutane as the predominant product upon addition of HBr?',
        options=['A: Bromine directly displaces a methyl group.', 'B: Hydrogen attacks both ends of the double bond.', 'C: The reaction proceeds via a free radical mechanism.', 'D: The initial secondary carbocation undergoes a 1,2-methyl shift to form a more stable tertiary carbocation before attack by bromide.'],
        correct_answer='D',
        explanation='Option D is correct. Addition of H+ forms (CH3)3C-CH+-CH3 (a 2° carbocation). A methyl group migrates with its electron pair (1,2-hydride/methyl shift) to produce (CH3)2C+-CH(CH3)2, which is tertiary and much more stable.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=52,
        title='Test for Unsaturation — 9701/12/M/J/222/Q52',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='Which observation confirms that an unknown liquid hydrocarbon contains an alkene C=C double bond?',
        options=['A: Effervescence with sodium carbonate solution.', "B: A silver mirror with Tollens' reagent.", 'C: Decolorization of bromine water from orange-brown to colorless without needing UV light.', "D: A brick-red precipitate with Fehling's solution."],
        correct_answer='C',
        explanation='Option C is correct. Bromine water tests for C=C unsaturation: addition across the double bond rapidly decolorizes the orange-brown bromine solution at room temperature without requiring UV light or catalysts.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=53,
        title='Stability Order of Carbocations — 9701/13/M/J/223/Q53',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Why is (CH3)3C+ more stable than CH3CH2CH2+?',
        options=['A: Three electron-releasing methyl groups disperse the positive charge across the molecule via the +I inductive effect, lowering electrostatic potential.', 'B: The primary carbocation is too small to exist.', 'C: The tertiary carbocation has a complete outer octet of 10 electrons.', 'D: The primary carbocation forms hydrogen bonds.'],
        correct_answer='A',
        explanation='Option A is correct. Alkyl groups are electron-donating (+I). The 3° carbocation has three alkyl groups dispersing the positive charge, making it far more stable than the 1° carbocation with only one alkyl group.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=54,
        title='Addition of Interhalogens (ICl) — 9701/11/M/J/224/Q54',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='When iodine monochloride (I-Cl) reacts with propene, which atom acts as the electrophile and what is the major product?',
        options=['A: Chlorine acts as the electrophile; major product is 1-chloro-2-iodopropane.', 'B: Both atoms act as nucleophiles.', 'C: Iodine acts as the electrophile (I delta+) because chlorine is more electronegative; major product is 2-chloro-1-iodopropane.', 'D: Iodine replaces a hydrogen on the methyl group.'],
        correct_answer='C',
        explanation='Option C is correct. Chlorine is more electronegative than iodine (Cl=3.0, I=2.5), so I carries a partial positive charge (I delta+-Cl delta-). The pi bond attacks I+, forming the more stable secondary carbocation CH3-CH+-CH2I, which is then attacked by Cl- to yield 2-chloro-1-iodopropane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=55,
        title='Deducing Alkene from KMnO4 Oxidation — 9701/12/M/J/220/Q55',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Heating an alkene with hot concentrated KMnO4 yields only butanoic acid, CH3CH2CH2COOH. What is the identity of the alkene?',
        options=['A: Oct-1-ene', 'B: Oct-4-ene, CH3CH2CH2CH=CHCH2CH2CH3', 'C: Hex-3-ene', 'D: But-1-ene'],
        correct_answer='B',
        explanation='Option B is correct. A single product of butanoic acid indicates a symmetrical alkene where both halves are =CH-CH2CH2CH3. The original alkene is oct-4-ene.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=56,
        title='Addition Polymerisation of Alkenes — 9701/13/M/J/221/Q56',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What type of reaction converts ethene molecules into polyethene, and what change in bonding occurs?',
        options=['A: Condensation polymerisation; water is eliminated.', 'B: Elimination; hydrogen gas is evolved.', 'C: Substitution; chlorine atoms replace hydrogens.', 'D: Addition polymerisation; pi bonds break and new C-C sigma bonds form between monomer units.'],
        correct_answer='D',
        explanation='Option D is correct. Addition polymerisation occurs when thousands of alkene monomers join together: the pi bond in each C=C breaks to form new C-C sigma bonds linking the monomers into a long saturated polymer chain.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=57,
        title='Stereochemistry of Alkene Addition — 9701/11/M/J/222/Q57',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Why does the bromination of cyclohexene yield trans-1,2-dibromocyclohexane rather than the cis isomer?',
        options=['A: The cis isomer is too reactive to isolate.', 'B: Bromine molecules can only attack from the top face.', 'C: The reaction proceeds via a cyclic bromonium ion intermediate, forcing the incoming bromide ion to attack from the opposite face (anti-addition).', 'D: The reaction proceeds via free radical substitution.'],
        correct_answer='C',
        explanation='Option C is correct. Electrophilic attack by Br2 forms a three-membered cyclic bromonium ion that blocks one face of the ring. The bromide nucleophile must attack from the opposite face (backside attack), resulting strictly in anti-addition (trans product).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=58,
        title='Addition of Sulfuric Acid to Alkenes — 9701/12/M/J/223/Q58',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the product when ethene is absorbed into concentrated sulfuric acid at room temperature, and what happens upon subsequent boiling with water?',
        options=['A: Ethyl hydrogensulfate is formed; boiling with water hydrolyzes it to ethanol.', 'B: Ethanoic acid is formed directly.', 'C: Diethyl ether is formed as a gas.', 'D: Ethene is oxidized to carbon dioxide.'],
        correct_answer='A',
        explanation='Option A is correct. Ethene reacts with concentrated H2SO4 via electrophilic addition to form ethyl hydrogensulfate (CH3CH2OSO3H). Adding water and warming hydrolyzes the ester to ethanol and regenerates sulfuric acid: CH3CH2OSO3H + H2O -> CH3CH2OH + H2SO4.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=59,
        title='Reactivity: Alkenes vs Benzene — 9701/13/M/J/224/Q59',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Why do alkenes readily undergo electrophilic addition while benzene undergoes electrophilic substitution?',
        options=['A: Benzene contains only single sigma bonds.', 'B: Alkenes have lower electron density than benzene.', 'C: Benzene is non-planar.', 'D: Addition to benzene would destroy its exceptionally stable delocalised 6 pi electron aromatic resonance system.'],
        correct_answer='D',
        explanation='Option D is correct. Benzene possesses ~150 kJ/mol of aromatic resonance stabilization energy. Electrophilic addition would break the delocalized ring, permanently destroying aromaticity. Hence, benzene undergoes substitution to regenerate the stable 6 pi aromatic ring.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=60,
        title='Oxidation of Cyclohexene — 9701/11/M/J/220/Q60',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the product when cyclohexene is heated with hot, concentrated, acidified KMnO4?',
        options=['A: Cyclohexanol', 'B: Hexanedioic acid (adipic acid), HOOC-(CH2)4-COOH', 'C: Cyclohexanone', 'D: Carbon dioxide and water only'],
        correct_answer='B',
        explanation='Option B is correct. Cleaving the C=C bond in cyclohexene breaks open the ring. Both double-bond carbons are =CH- groups, so each is oxidized to a carboxylic acid group (-COOH), yielding the open-chain dicarboxylic acid hexanedioic acid.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=61,
        title='Heterolytic Cleavage of Halogen Molecule — 9701/12/M/J/221/Q61',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='During electrophilic addition of Br2, what causes the non-polar bromine molecule to become polarized?',
        options=['A: The solvent permanently ionizes bromine molecules.', 'B: The high electron density in the C=C pi bond repels the electron cloud of the approaching Br2 molecule, inducing a temporary dipole (Br delta+-Br delta-).', 'C: Ultraviolet light creates ionic dipoles.', 'D: Air pressure squeezes the bromine electrons.'],
        correct_answer='B',
        explanation='Option B is correct. As Br2 nears the electron-rich pi cloud, electrostatic repulsion pushes electrons away from the closer Br atom to the further Br atom, creating an induced dipole (Br delta+-Br delta-).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=62,
        title='Markownikoff Addition with Water — 9701/13/M/J/222/Q62',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the major product when 2-methylpropene is reacted with steam in the presence of an acid catalyst?',
        options=['A: 2-methylpropan-1-ol (primary alcohol)', 'B: Butan-2-ol', 'C: Butan-1-ol', 'D: 2-methylpropan-2-ol (tertiary alcohol)'],
        correct_answer='D',
        explanation='Option D is correct. Protonation of (CH3)2C=CH2 forms the tertiary carbocation (CH3)3C+ (much more stable than the 1° carbocation). Attack by H2O yields 2-methylpropan-2-ol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=63,
        title='Oxidation of 2-methylbut-1-ene — 9701/11/M/J/223/Q63',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What products are obtained when 2-methylbut-1-ene, CH2=C(CH3)CH2CH3, is oxidized with hot concentrated acidified KMnO4?',
        options=['A: Carbon dioxide (CO2), water (H2O), and butanone (CH3COCH2CH3)', 'B: Ethanoic acid and propanoic acid', 'C: 2-methylbutanoic acid only', 'D: Methanoic acid and butan-2-ol'],
        correct_answer='A',
        explanation='Option A is correct. The terminal =CH2 fragment oxidizes to CO2 + H2O. The =C(CH3)CH2CH3 fragment oxidizes to the ketone butanone (CH3COCH2CH3).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=64,
        title='Addition of HCl to Alkenes vs HBr — 9701/12/M/J/224/Q64',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='Why does electrophilic addition of HCl to alkenes occur more slowly than addition of HBr under identical conditions?',
        options=['A: Chlorine is less electronegative than bromine.', 'B: Chloride ions are too large to attack carbocations.', 'C: The H-Cl bond enthalpy (431 kJ mol^-1) is higher than that of H-Br (366 kJ mol^-1), resulting in a higher activation energy for electrophilic protonation.', 'D: HCl exists only as a solid at room temperature.'],
        correct_answer='C',
        explanation='Option C is correct. The rate-determining step involves breaking the H-X bond as H+ is transferred to the alkene pi bond. Because H-Cl has a stronger bond than H-Br, more energy is required, making the reaction slower.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=65,
        title='Identification of Alkene Structure from Gas Volume — 9701/13/M/J/220/Q65',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Complete combustion of 20 cm^3 of a gaseous alkene requires 90 cm^3 of oxygen gas at RTP. What is the alkene?',
        options=['A: Propene, C3H6', 'B: Ethene, C2H4', 'C: But-1-ene, C4H8', 'D: Pent-1-ene, C5H10'],
        correct_answer='A',
        explanation='Option A is correct. Equation for alkene CnH2n: CnH2n + 1.5n O2 -> n CO2 + n H2O. Volume ratio O2 / alkene = 1.5n = 90 / 20 = 4.5. Thus, n = 4.5 / 1.5 = 3 (propene, C3H6).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=66,
        title='Relative Rates of Halogen Addition — 9701/11/M/J/221/Q66',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='Which halogen reacts most rapidly with ethene in electrophilic addition?',
        options=['A: Iodine > Bromine > Chlorine', 'B: All halogens react at identical rates', 'C: Fluorine cannot react with alkenes', 'D: Chlorine > Bromine > Iodine'],
        correct_answer='D',
        explanation='Option D is correct. Electrophilic reactivity depends on the electrophilicity and polarizability of the halogen; chlorine reacts more rapidly than bromine, which reacts faster than iodine.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=67,
        title='Addition of Hydrogen Cyanide to Alkenes — 9701/12/M/J/222/Q67',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Why do alkenes NOT react with hydrogen cyanide (HCN) under normal conditions?',
        options=['A: HCN is an insoluble gas.', 'B: Alkenes have high electron density and repel nucleophilic cyanide ions (:CN-); HCN lacks an effective electrophilic species to initiate attack.', 'C: Cyanide ions destroy C-C sigma bonds.', 'D: Alkenes are strong Bronsted bases that neutralize HCN.'],
        correct_answer='B',
        explanation='Option B is correct. Alkenes are electron-rich nucleophiles and require an initial electrophilic attack. HCN contains a weak, poorly electrophilic H+ and a nucleophilic :CN- ion, so no reaction occurs (unlike carbonyls which are electrophilic).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=68,
        title='Oxidation of But-2-ene with Hot KMnO4 — 9701/13/M/J/223/Q68',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What single organic product is formed when but-2-ene (CH3-CH=CH-CH3) is heated with hot concentrated acidified KMnO4?',
        options=['A: Ethanol, CH3CH2OH', 'B: Ethanal, CH3CHO', 'C: Ethanoic acid, CH3COOH', 'D: Carbon dioxide and water'],
        correct_answer='C',
        explanation='Option C is correct. Both halves of the symmetrical but-2-ene molecule consist of =CH-CH3 groups, which are oxidized to carboxylic acid groups, producing two molecules of ethanoic acid (CH3COOH).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=69,
        title='Polyalkene Repeat Unit Deduction — 9701/11/M/J/224/Q69',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What is the monomer used to produce the polymer with repeat unit -[CH2-CH(Cl)]-n?',
        options=['A: 1,2-dichloroethene', 'B: Chloroethene (vinyl chloride), CH2=CHCl', 'C: Chloroethane', 'D: 1,1-dichloroethene'],
        correct_answer='B',
        explanation='Option B is correct. Restoring the C=C double bond between the two carbon atoms of the repeat unit gives CH2=CHCl (chloroethene).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=70,
        title='Combustion Heat of Alkenes vs Alkanes — 9701/12/M/J/220/Q70',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='Why do alkenes burn with a more smoky (sootier) flame than the corresponding alkanes?',
        options=['A: Alkenes have a higher carbon-to-hydrogen ratio, increasing the likelihood of incomplete combustion to carbon particulates (soot).', 'B: Alkenes contain toxic sulfur impurities.', 'C: Alkenes burn at a lower temperature than alkanes.', 'D: Alkenes produce hydrogen gas during combustion.'],
        correct_answer='A',
        explanation='Option A is correct. Ethene (C:H = 1:2) has a higher proportion of carbon than ethane (C:H = 1:3). More oxygen is required per gram to achieve complete oxidation, resulting in a luminous, smoky flame due to incandescent soot particles.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=71,
        title='Formation of Diols via OsO4 vs KMnO4 — 9701/13/M/J/221/Q71',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='In addition to cold dilute KMnO4, which reagent can convert an alkene into a vicinal diol via syn-addition?',
        options=['A: Hot concentrated nitric acid', 'B: Acidified potassium dichromate(VI)', 'C: Lithium aluminium hydride', 'D: Osmium tetroxide (OsO4) followed by reduction'],
        correct_answer='D',
        explanation='Option D is correct. Osmium tetroxide (OsO4) selectively oxidizes alkenes to 1,2-diols via a cyclic osmate ester, giving stereospecific syn-dihydroxylation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=72,
        title='Asymmetrical Alkene Addition Regioselectivity — 9701/11/M/J/222/Q72',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='In the reaction between 2-methylbut-1-ene and HBr, what percentage of the product is expected to be 2-bromo-2-methylbutane under ionic conditions?',
        options=['A: 50% (equal mixture of 1-bromo and 2-bromo)', 'B: 0% (anti-Markovnikov is favored)', 'C: Virtually 100% (predominant Markovnikov product via the tertiary carbocation)', 'D: 25%'],
        correct_answer='C',
        explanation='Option C is correct. The difference in activation energy between forming the 3° carbocation and the 1° carbocation is so large (~40 kJ/mol) that the 3° pathway overwhelmingly dominates, producing almost exclusively the tertiary haloalkane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=73,
        title='Anti-Markovnikov Addition Mechanism — 9701/12/M/J/223/Q73',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Why does the addition of HBr to propene in the presence of peroxides (ROOR) yield 1-bromopropane?',
        options=['A: The reaction switches to a free radical mechanism where the bromine radical (.Br) attacks first, forming the more stable secondary carbon radical.', 'B: Peroxides act as a powerful nucleophile.', 'C: Peroxides reverse the electronegativity of bromine.', 'D: Peroxides destroy the pi bond without adding.'],
        correct_answer='A',
        explanation='Option A is correct. In the presence of peroxides, RO. radicals generate .Br. The .Br radical adds to C1 of propene to produce the more stable 2° radical (CH3-CH.-CH2Br), which abstracts H from HBr to form 1-bromopropane (anti-Markovnikov).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=74,
        title='Addition of Water Across Cyclohexene — 9701/13/M/J/224/Q74',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the product formed when cyclohexene reacts with steam in the presence of concentrated H3PO4 catalyst?',
        options=['A: Cyclohexanone', 'B: Hexan-1-ol', 'C: Cyclohexanol', 'D: Adipic acid'],
        correct_answer='C',
        explanation='Option C is correct. Electrophilic addition of H2O across the C=C double bond of cyclohexene yields the cyclic alcohol cyclohexanol.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=75,
        title='Distinguishing Alkanes from Alkenes — 9701/11/M/J/220/Q75',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Which single chemical test immediately distinguishes hexane from hex-1-ene?',
        options=['A: Hexane forms a white precipitate with silver nitrate.', 'B: Hex-1-ene decolorizes aqueous bromine water from orange to colorless at room temperature; hexane produces no color change.', 'C: Hex-1-ene reacts with sodium metal to evolve hydrogen.', 'D: Hexane turns blue litmus paper red.'],
        correct_answer='B',
        explanation='Option B is correct. Hex-1-ene contains an unsaturated C=C bond that rapidly undergoes electrophilic addition with aqueous bromine, decolorizing it. Saturated hexane shows no reaction in the absence of UV light.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=76,
        title='Oxidative Cleavage of Pent-2-ene — 9701/12/M/J/221/Q76',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What two organic acids are formed when pent-2-ene, CH3-CH=CH-CH2-CH3, is refluxed with hot concentrated acidified KMnO4?',
        options=['A: Methanoic acid and butanoic acid', 'B: Two molecules of propanoic acid', 'C: Ethanoic acid and propanone', 'D: Ethanoic acid (CH3COOH) and propanoic acid (CH3CH2COOH)'],
        correct_answer='D',
        explanation='Option D is correct. Cleavage of the C2=C3 bond divides the molecule into a 2-carbon =CH-CH3 fragment (oxidized to ethanoic acid) and a 3-carbon =CH-CH2CH3 fragment (oxidized to propanoic acid).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=77,
        title='Physical State of Small Alkenes — 9701/13/M/J/222/Q77',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What are the physical states of ethene, propene, and but-1-ene at standard room temperature and pressure (298 K, 100 kPa)?',
        options=['A: Ethene is a gas; propene and but-1-ene are liquids.', 'B: All three are volatile liquids.', 'C: All three are colorless gases.', 'D: Ethene is a liquid; the others are solids.'],
        correct_answer='C',
        explanation='Option C is correct. The C2 to C4 alkenes (ethene, propene, but-1-ene, but-2-ene, 2-methylpropene) have low molecular masses and weak London dispersion forces, existing as gases at RTP.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=78,
        title='Testing for Carbon Dioxide from Cleavage — 9701/11/M/J/223/Q78',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='When an unknown alkene is heated with hot concentrated KMnO4, the gas evolved turns limewater cloudy. What structural feature does this prove?',
        options=['A: The alkene contains a terminal =CH2 double-bond group.', 'B: The alkene is a cyclic hydrocarbon.', 'C: The alkene contains a tertiary carbon atom.', 'D: The alkene is completely symmetrical.'],
        correct_answer='A',
        explanation='Option A is correct. Only terminal =CH2 groups are oxidized to CO2 gas (and H2O) by hot concentrated KMnO4. The evolution of CO2 (which precipitates CaCO3 in limewater) proves the presence of a terminal =CH2 group.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=79,
        title='Carbocation Hybridisation and Attack — 9701/12/M/J/224/Q79',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What is the shape of the carbocation intermediate in electrophilic addition, and from which direction can the nucleophile attack?',
        options=['A: Tetrahedral; attack occurs only from the front.', 'B: Linear; attack occurs along the molecular axis.', 'C: Pyramidal; attack is restricted to the base.', 'D: Trigonal planar; the nucleophile can attack with equal probability from either the top face or bottom face.'],
        correct_answer='D',
        explanation='Option D is correct. The positively charged carbon of a carbocation is sp2 hybridised with an empty unhybridised p orbital perpendicular to the trigonal plane (120°). Nucleophiles can attack this empty p lobe from either the top or bottom with equal probability.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=80,
        title='Bromonium Ion vs Open Carbocation — 9701/13/M/J/220/Q80',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What experimental evidence demonstrates that bromine addition to alkenes involves a cyclic bromonium ion rather than a simple open carbocation?',
        options=['A: The evolution of hydrogen bromide gas.', 'B: The stereospecific formation of trans products (anti-addition) when reacting with cyclic alkenes.', 'C: The formation of equal amounts of cis and trans products.', 'D: The immediate reduction of bromine to bromide.'],
        correct_answer='B',
        explanation='Option B is correct. If an open, freely rotating carbocation formed, nucleophilic attack would occur from both faces to give a mixture of cis and trans isomers. The exclusive formation of trans products proves the presence of a bridged bromonium ion preventing rotation and blocking syn attack.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=81,
        title='Hydration vs Hydrogenation Reaction Conditions — 9701/11/M/J/221/Q81',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='How do the reagents and conditions for converting an alkene to an alcohol differ from those for converting an alkene to an alkane?',
        options=['A: Both use hydrogen gas over a platinum catalyst.', 'B: Alcohol: Steam (H2O(g)) with concentrated H3PO4 at 300 °C / 60 atm; Alkane: Hydrogen gas (H2(g)) with Ni catalyst at 150 °C.', 'C: Both use cold acidified potassium manganate(VII).', 'D: Both use sodium borohydride at room temperature.'],
        correct_answer='B',
        explanation='Option B is correct. Alkene -> alcohol is hydration (addition of steam over solid H3PO4 catalyst at high temperature and pressure); alkene -> alkane is hydrogenation (addition of H2 gas over Ni catalyst at ~150 °C).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=82,
        title='Addition of Halogens in Non-Polar Solvents — 9701/12/M/J/222/Q82',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='When bromine is dissolved in tetrachloromethane (CCl4) and added to ethene, what is the sole product?',
        options=['A: Bromoethane', 'B: 1-bromo-2-chloroethane', 'C: Ethanol', 'D: 1,2-dibromoethane, CH2Br-CH2Br'],
        correct_answer='D',
        explanation='Option D is correct. In an inert non-polar solvent like CCl4, no competing nucleophiles (like water) exist. The only nucleophile available to attack the bromonium ion is the bromide ion (Br-), forming 1,2-dibromoethane as the exclusive product.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=83,
        title='Effect of Alkyl Substitution on Alkene Stability — 9701/13/M/J/223/Q83',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='How does increasing alkyl substitution around the C=C double bond affect the thermodynamic stability of alkenes?',
        options=['A: Stability increases: tetra-substituted > tri-substituted > di-substituted > mono-substituted > ethene.', 'B: Stability decreases because alkyl groups crowd the double bond.', 'C: All alkene isomers have identical thermodynamic stability.', 'D: Alkyl substitution causes spontaneous decomposition.'],
        correct_answer='A',
        explanation='Option A is correct. Alkyl groups donate electron density to the pi system via hyperconjugation and strengthen bonding, making more highly substituted alkenes (like (CH3)2C=C(CH3)2) thermodynamically more stable than less substituted isomers.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=84,
        title='Cleavage Products of 2-methylpent-2-ene — 9701/11/M/J/224/Q84',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What organic products are formed when 2-methylpent-2-ene, (CH3)2C=CH-CH2-CH3, is heated with hot concentrated acidified KMnO4?',
        options=['A: Ethanoic acid and butanone', 'B: Propanal and propanoic acid', 'C: Propanone, (CH3)2C=O, and propanoic acid, CH3CH2COOH', 'D: Carbon dioxide and 2-methylbutanoic acid'],
        correct_answer='C',
        explanation='Option C is correct. Cleaving the double bond in (CH3)2C=CH-CH2-CH3 produces propanone from the (CH3)2C= fragment and propanoic acid from the =CH-CH2-CH3 fragment.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=85,
        title='Industrial Polymerisation Conditions — 9701/12/M/J/220/Q85',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What catalyst and conditions are used in the low-pressure Ziegler-Natta polymerisation of ethene to high-density polyethene (HDPE)?',
        options=['A: Titanium(IV) chloride and triethylaluminium catalyst (TiCl4 / Al(C2H5)3) at ~60 °C and low pressure.', 'B: Concentrated sulfuric acid at 200 °C.', 'C: Ultraviolet light in liquid ammonia.', 'D: Iron catalyst at 450 °C and 200 atm.'],
        correct_answer='A',
        explanation='Option A is correct. Ziegler-Natta coordination catalysts (TiCl4 with Al(C2H5)3) enable coordination polymerisation of ethene at modest temperatures (~60 °C) and atmospheric pressure, producing unbranched linear HDPE with high density and tensile strength.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=86,
        title='Electrophilic Addition Transition State — 9701/13/M/J/221/Q86',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='In the reaction coordinate diagram for the electrophilic addition of HBr to an alkene, what represents the highest energy barrier (rate-determining transition state)?',
        options=['A: The attack of the bromide nucleophile on the carbocation.', 'B: The dissolution of HBr in the solvent.', 'C: The diffusion of product molecules away from each other.', 'D: The transition state leading to the formation of the carbocation intermediate.'],
        correct_answer='D',
        explanation='Option D is correct. The rate-determining step is the initial protonation of the alkene pi bond to form the high-energy carbocation intermediate. This step has the highest activation energy on the reaction coordinate.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=87,
        title='Bromination of Phenylethene — 9701/11/M/J/222/Q87',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='When phenylethene (styrene, C6H5-CH=CH2) is treated with bromine in the dark at room temperature, what reaction occurs?',
        options=['A: Electrophilic substitution into the benzene ring to form 4-bromostyrene.', 'B: Electrophilic addition across the alkene side chain to form 1,2-dibromo-1-phenylethane; the benzene ring remains unreacted.', 'C: Free radical substitution of the phenyl ring.', 'D: Elimination of hydrogen bromide to form phenylacetylene.'],
        correct_answer='B',
        explanation='Option B is correct. The aliphatic alkene double bond has high, localized electron density and reacts rapidly with bromine via electrophilic addition, whereas the aromatic benzene ring requires a halogen carrier catalyst (AlBr3) and does not react in the dark.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=88,
        title='Hydration of But-1-ene Regiochemistry — 9701/12/M/J/223/Q88',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the major alcohol formed when but-1-ene is reacted with steam in the presence of concentrated phosphoric acid catalyst?',
        options=['A: Butan-1-ol (primary alcohol)', 'B: 2-methylpropan-2-ol', 'C: Butan-2-ol (secondary alcohol)', 'D: Ethanoic acid'],
        correct_answer='C',
        explanation='Option C is correct. Addition of H+ to but-1-ene forms the secondary carbocation CH3-CH2-CH+-CH3 in preference to the primary carbocation CH3-CH2-CH2-CH2+ due to stabilization by two alkyl groups. Attack by H2O gives butan-2-ol as the major product.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=89,
        title='PTFE Monomer and Properties — 9701/13/M/J/224/Q89',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='What is the monomer of poly(tetrafluoroethene) (PTFE / Teflon), and what property makes the polymer non-stick and chemically inert?',
        options=['A: Fluoroethene; weak London dispersion forces.', 'B: Tetrafluoroethene (CF2=CF2); the extremely strong C-F bonds (485 kJ mol^-1) and protective fluorine sheath prevent chemical attack.', 'C: 1,1-difluoroethene; high water solubility.', 'D: Trichlorofluoromethane; low boiling point.'],
        correct_answer='B',
        explanation='Option B is correct. PTFE is synthesized from CF2=CF2. The C-F bond is one of the strongest single bonds in organic chemistry (485 kJ/mol), and the small, highly electronegative fluorine atoms tightly pack around the carbon backbone, forming an unreactive, non-stick barrier.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=90,
        title='Cleavage of 3-methylhex-3-ene — 9701/11/M/J/220/Q90',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What organic products are formed when 3-methylhex-3-ene, CH3-CH2-C(CH3)=CH-CH2-CH3, is refluxed with hot concentrated acidified KMnO4?',
        options=['A: Pentan-3-one (CH3CH2COCH2CH3) and propanoic acid (CH3CH2COOH)', 'B: Butanone and butanoic acid', 'C: Hexan-3-one and ethanoic acid', 'D: Carbon dioxide and 2-methylpentanoic acid'],
        correct_answer='A',
        explanation='Option A is correct. Cleaving across C3=C4 yields pentan-3-one from the =C(CH3)CH2CH3 carbon and propanoic acid from the =CH-CH2CH3 carbon.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=91,
        title='Dichromate vs Permanganate Reactivity with Alkenes — 9701/12/M/J/221/Q91',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Why is acidified potassium manganate(VII) used to test for alkenes rather than acidified potassium dichromate(VI)?',
        options=['A: K2Cr2O7 decomposes explosively in the presence of hydrocarbons.', 'B: KMnO4 is a reducing agent that adds hydrogen.', 'C: K2Cr2O7 turns colorless upon reduction.', 'D: KMnO4 oxidizes alkenes rapidly at room temperature, producing an immediate color change; K2Cr2O7 is a milder oxidizer and does not react readily with C=C bonds at room temperature.'],
        correct_answer='D',
        explanation='Option D is correct. Potassium manganate(VII) is a much stronger oxidizing agent than potassium dichromate(VI) (E° +1.51 V vs +1.33 V) and readily attacks alkene pi bonds at room temperature, while K2Cr2O7 reacts sluggishly or not at all with isolated C=C bonds.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=92,
        title='Markownikoff Addition of HI to Propene — 9701/13/M/J/222/Q92',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the product of the addition of hydrogen iodide (HI) to propene in the dark?',
        options=['A: 1-iodopropane (propyl iodide)', 'B: 1,2-diiodopropane', 'C: 2-iodopropane (isopropyl iodide)', 'D: Cyclopropane and iodine'],
        correct_answer='C',
        explanation='Option C is correct. HI adds via electrophilic addition. Protonation yields the secondary carbocation CH3-CH+-CH3, which is captured by iodide to form 2-iodopropane as the dominant Markovnikov product.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=93,
        title='Reaction of Ethene with Chlorine Water — 9701/11/M/J/223/Q93',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='When ethene gas is passed into aqueous chlorine water, what is the major organic product formed?',
        options=['A: 2-chloroethanol, CH2Cl-CH2OH', 'B: 1,2-dichloroethane', 'C: Chloroethane', 'D: Ethanol'],
        correct_answer='A',
        explanation='Option A is correct. In aqueous chlorine, the electrophile Cl+ attacks ethene to form the chloronium ion intermediate +CH2-CH2Cl. Because water molecules are in overwhelming excess compared to chloride ions, H2O attacks the intermediate, forming 2-chloroethanol (a chlorohydrin).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=94,
        title='Catalytic Hydrogenation Stoichiometry of Dienes — 9701/12/M/J/224/Q94',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What volume of hydrogen gas (measured at RTP) is required to completely hydrogenate 0.50 mol of buta-1,3-diene to butane?',
        options=['A: 12.0 dm^3', 'B: 48.0 dm^3', 'C: 24.0 dm^3', 'D: 6.0 dm^3'],
        correct_answer='C',
        explanation='Option C is correct. Buta-1,3-diene contains two C=C double bonds. Complete saturation requires 2 moles of H2 per mole of diene: 0.50 mol * 2 = 1.0 mol of H2. At RTP, 1.0 mol of any gas occupies 24.0 dm^3.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=95,
        title='Chiral Center Generation in Alkene Addition — 9701/13/M/J/220/Q95',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Which reaction generates a chiral carbon atom from an achiral starting material?',
        options=['A: Addition of Br2 to ethene forming 1,2-dibromoethane.', 'B: Addition of HBr to but-1-ene forming 2-bromobutane.', 'C: Addition of H2 to propene forming propane.', 'D: Addition of HBr to 2-methylpropene forming 2-bromo-2-methylpropane.'],
        correct_answer='B',
        explanation='Option B is correct. But-1-ene is achiral. Addition of HBr yields 2-bromobutane (CH3-CH(Br)-CH2CH3). C2 is bonded to -H, -Br, -CH3, and -CH2CH3 (four different groups), creating a chiral center.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=96,
        title='Cleavage of Methylenecyclohexane — 9701/11/M/J/221/Q96',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What products are obtained when methylenecyclohexane (=CH2 attached to a cyclohexane ring) is oxidized by hot concentrated acidified KMnO4?',
        options=['A: Hexanedioic acid and methanol', 'B: Cyclohexanol and methanoic acid', 'C: Benzoic acid and water', 'D: Cyclohexanone, carbon dioxide, and water'],
        correct_answer='D',
        explanation='Option D is correct. The exocyclic =CH2 group oxidizes to CO2 + H2O. The ring carbon of the double bond (=C<) is bonded to two ring carbons, oxidizing to the cyclic ketone cyclohexanone.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=97,
        title='Combustion Enthalpy of Alkene Isomers — 9701/12/M/J/222/Q97',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='How does the enthalpy of combustion of trans-but-2-ene compare with cis-but-2-ene, and what explains the difference?',
        options=['A: Cis-but-2-ene is significantly more stable because dipoles attract.', 'B: Both have precisely identical combustion enthalpies.', 'C: Trans-but-2-ene is slightly less exothermic (more stable) because the two bulky methyl groups are on opposite sides, minimizing steric repulsion.', 'D: Trans-but-2-ene decomposes spontaneously upon heating.'],
        correct_answer='C',
        explanation='Option C is correct. In cis-but-2-ene, the two methyl groups are on the same side of the double bond, causing mutual steric hindrance (van der Waals repulsion). In trans-but-2-ene, the methyl groups are opposite (180°), relieving steric strain. Trans is ~4 kJ/mol more stable, releasing less heat upon combustion.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=98,
        title='Addition of Bromine in the Presence of Sodium Chloride — 9701/13/M/J/223/Q98',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='When ethene reacts with bromine in the presence of concentrated aqueous sodium chloride, which product is formed in addition to 1,2-dibromoethane?',
        options=['A: 1-bromo-2-chloroethane', 'B: 1,2-dichloroethane only', 'C: Bromoethane', 'D: Chloroethane'],
        correct_answer='A',
        explanation='Option A is correct. The electrophile Br+ attacks ethene to form the bromonium ion. In the second step, either Br-, Cl- (from NaCl), or H2O can act as the nucleophile. Attack by Cl- yields 1-bromo-2-chloroethane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=99,
        title='Deducing Alkene from Quantitative Cleavage — 9701/11/M/J/224/Q99',
        syllabus_ref='14.2',
        difficulty='EASY',
        stem='Complete oxidative cleavage of 0.10 mol of an alkene by hot concentrated KMnO4 produces 0.10 mol of CO2, 0.10 mol of propanone, and 0.10 mol of ethanoic acid. What is the alkene?',
        options=['A: 2-methylbut-2-ene', 'B: Hex-2-ene', 'C: Cyclohexene', 'D: 2-methylpenta-1,4-diene, CH2=C(CH3)-CH2-CH=CH2 or 4-methylpenta-1,3-diene, CH2=CH-CH=C(CH3)2'],
        correct_answer='D',
        explanation='Option D is correct. Cleavage of 4-methylpenta-1,3-diene (CH2=CH-CH=C(CH3)2) produces: CO2 from terminal =CH2; ethanoic acid from the middle =CH-CH= segment (or two segments); and propanone from =C(CH3)2. This matches the 1:1:1 mole ratio of products.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=100,
        title='Industrial Polymerisation of Propene — 9701/12/M/J/220/Q100',
        syllabus_ref='14.2',
        difficulty='HARD',
        stem='What is the structure of the repeat unit in poly(propene), and what type of polymerisation reaction forms it?',
        options=['A: -[CH2-CH2-CH2]-n formed by condensation polymerisation.', 'B: -[CH2-CH(CH3)]-n formed by addition polymerisation.', 'C: -[CH(CH3)-CH(CH3)]-n formed by free radical substitution.', 'D: -[C(CH3)2-CH2]-n formed by elimination.'],
        correct_answer='B',
        explanation='Option B is correct. Propene (CH2=CH-CH3) undergoes addition polymerisation: the C=C pi bond breaks and monomers link through C-C sigma bonds to form poly(propene), having repeat unit -[CH2-CH(CH3)]-.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=101,
        title='HF 1: Deducing Alkene Structure from Hot Concentrated KMnO4 Oxidation Products — 9701/11/M/J/22/Q18',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='An unsaturated hydrocarbon Y of molecular formula C7H14 is heated with hot, concentrated, acidified potassium manganate(VII).\nEffervescence is observed, and the gas evolved turns limewater milky. The only organic product remaining in the reaction mixture is 3-methylbutanoic acid, (CH3)2CH-CH2-COOH.\n\nWhat is the structural formula of hydrocarbon Y?',
        options=['A: 2-methylhex-2-ene, (CH3)2C=CH-CH2-CH2-CH3', 'B: 4-methylhex-1-ene, CH2=CH-CH(CH3)-CH2-CH3', 'C: 5-methylhex-1-ene, CH2=CH-CH2-CH(CH3)2', 'D: 2,4-dimethylpent-2-ene, (CH3)2C=CH-CH(CH3)2'],
        correct_answer='C',
        explanation='Option C is correct. The evolution of CO2 (which turns limewater milky) proves that hydrocarbon Y contains a terminal =CH2 group. The only organic product is 3-methylbutanoic acid, (CH3)2CH-CH2-COOH (5 carbons). Reconnecting the =CH2 carbon to the carbonyl carbon of the acid yields: CH2=CH-CH2-CH(CH3)2 (5-methylhex-1-ene, total 7 carbons).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=102,
        title='HF 2: Regiochemistry and Relative Yields in Unsymmetrical Alkene Addition — 9701/12/M/J/21/Q18',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='2-methylbut-2-ene reacts with hydrogen chloride, HCl, in the dark.\n\nWhich statement correctly identifies the major product and explains why it forms in higher yield than the minor product?',
        options=['A: 2-chloro-2-methylbutane is the major product because it is formed via a tertiary carbocation intermediate which is more stable than the secondary carbocation intermediate.', 'B: 2-chloro-3-methylbutane is the major product because primary carbocations are more reactive.', 'C: 1-chloro-2-methylbutane is the major product due to steric hindrance at C2.', 'D: An equimolar 50:50 mixture is formed because chlorine attacks both ends of the double bond equally.'],
        correct_answer='A',
        explanation='Option A is correct. Addition of H+ to 2-methylbut-2-ene ((CH3)2C=CH-CH3) can occur at C3 to form the tertiary carbocation (CH3)2C+-CH2CH3, or at C2 to form the secondary carbocation (CH3)2CH-CH+-CH3. The 3° carbocation is stabilized by three alkyl groups (+I effect), lowering the activation energy barrier. Attack by Cl- gives 2-chloro-2-methylbutane as the predominant product.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=103,
        title='HF 3: Free Radical Chlorination — Relative Abundance of Propagation Intermediates — 9701/13/O/N/22/Q17',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='In the photochemical chlorination of propane at 25 °C, hydrogen abstraction can occur at a methyl group or at the central CH2 group.\n• There are 6 methyl hydrogens and 2 methylene hydrogens.\n• Secondary C-H bonds are approximately 4 times more reactive towards chlorine radicals than primary C-H bonds.\n\nWhat is the expected ratio of 1-chloropropane to 2-chloropropane in the product mixture?',
        options=['A: 3 : 1', 'B: 1 : 1', 'C: 1 : 4', 'D: 3 : 4 (or approximately 43% 1-chloropropane and 57% 2-chloropropane)'],
        correct_answer='D',
        explanation='Option D is correct. Relative rate = (number of hydrogens) * (relative reactivity). For 1-chloropropane: 6 primary H * 1 = 6. For 2-chloropropane: 2 secondary H * 4 = 8. Ratio of 1-chloropropane to 2-chloropropane = 6 : 8 = 3 : 4 (3/7 = 42.9% vs 4/7 = 57.1%).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=104,
        title='HF 4: Addition of Bromine Water to Polyunsaturated Compounds — 9701/11/F/M/22/Q18',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='One mole of an unsaturated hydrocarbon Z reacts completely with exactly two moles of bromine, Br2, in the dark to form a saturated tetrabromo compound.\nOxidation of one mole of Z with hot concentrated acidified KMnO4 produces one mole of butanedioic acid (HOOC-CH2-CH2-COOH) and two moles of carbon dioxide (CO2).\n\nWhat is the structural formula of hydrocarbon Z?',
        options=['A: Hexa-2,4-diene, CH3-CH=CH-CH=CH-CH3', 'B: Hexa-1,5-diene, CH2=CH-CH2-CH2-CH=CH2', 'C: Cyclohexa-1,4-diene', 'D: Hex-1-yne, CH#C-CH2-CH2-CH2-CH3'],
        correct_answer='B',
        explanation='Option B is correct. Reacting with 2 moles of Br2 to form a tetrabromo alkane confirms 2 degrees of unsaturation (two C=C double bonds). The products of hot KMnO4 oxidation are two moles of CO2 (proving TWO terminal =CH2 groups) and one mole of HOOC-CH2-CH2-COOH (4 carbons in the central chain). Reassembling the fragments: CH2=CH-CH2-CH2-CH=CH2 (hexa-1,5-diene).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=105,
        title='HF 5: Addition of Hydrogen Halide to Alkenes in the Presence of Alcohol Solvents — 9701/12/O/N/21/Q18',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='When propene gas is bubbled into a solution of hydrogen bromide dissolved in pure ethanol, what products are formed?',
        options=['A: A mixture of 2-bromopropane, 1-bromopropane, and 2-ethoxypropane', 'B: 2-bromopropane only', 'C: Ethyl bromide and propan-2-ol only', 'D: Propanoic acid and bromoethane'],
        correct_answer='A',
        explanation='Option A is correct. H+ from HBr adds to propene to form the carbocations CH3-CH+-CH3 (major) and CH3-CH2-CH2+ (minor). The carbocations can be attacked by bromide ions (yielding 2-bromopropane and 1-bromopropane) OR by the nucleophilic solvent ethanol (CH3CH2OH:), which upon deprotonation yields the ether 2-ethoxypropane.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=106,
        title='HF 6: Stereoisomeric Products of Alkene Addition Reactions — 9701/13/M/J/22/Q18',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='When trans-but-2-ene is reacted with hydrogen bromide, HBr, which statement concerning the product is TRUE?',
        options=['A: An optically active single enantiomer of 2-bromobutane is obtained.', 'B: 1-bromobutane is formed as the sole product.', 'C: 2-bromobutane is formed, which contains one chiral center and is produced as a racemic (optically inactive) mixture.', 'D: The product shows cis-trans isomerism.'],
        correct_answer='C',
        explanation='Option C is correct. Addition of HBr to but-2-ene gives 2-bromobutane, CH3-CH(Br)-CH2-CH3. C2 is a chiral center bonded to -H, -Br, -CH3, and -CH2CH3. Because the intermediate carbocation is planar (sp2), the bromide ion can attack from either face with equal probability (50% top, 50% bottom), yielding an equimolar racemic mixture that has zero net optical rotation.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=107,
        title='HF 7: Catalytic Cracking Equation and Balancing — 9701/11/O/N/21/Q17',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='One mole of a straight-chain alkane C15H32 is cracked to produce one mole of octane (C8H18), one mole of propene (C3H6), and an unknown quantity of ethene (C2H4).\n\nHow many moles of ethene are produced per mole of C15H32?',
        options=['A: 1 mole of ethene', 'B: 2 moles of ethene', 'C: 3 moles of ethene', 'D: 4 moles of ethene'],
        correct_answer='B',
        explanation='Option B is correct. Equation: C15H32 -> C8H18 + C3H6 + n C2H4. Balancing carbon atoms: 15 = 8 + 3 + 2n => 15 - 11 = 4 => 2n = 4 => n = 2. Balancing hydrogen atoms: 32 = 18 + 6 + 2(4) = 32 (verified). Thus, 2 moles of ethene are produced.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=108,
        title='HF 8: Distinguishing Alkene Isomers by Oxidation Products — 9701/12/F/M/23/Q18',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='Two isomeric alkenes, P and Q, both have the molecular formula C5H10.\n• Alkene P produces a carboxylic acid and a gas that turns limewater milky when heated with hot concentrated acidified KMnO4.\n• Alkene Q produces a ketone and a carboxylic acid under the same conditions.\n\nWhat are the identities of P and Q?',
        options=['A: P is pent-2-ene; Q is 2-methylbut-1-ene', 'B: P is 2-methylbut-1-ene; Q is pent-1-ene', 'C: P is 3-methylbut-1-ene; Q is cyclopentane', 'D: P is pent-1-ene; Q is 2-methylbut-2-ene'],
        correct_answer='D',
        explanation='Option D is correct. Alkene P produces CO2 gas (from a terminal =CH2) and a carboxylic acid (butanoic acid), identifying P as pent-1-ene (CH2=CH-CH2CH2CH3). Alkene Q produces a ketone and a carboxylic acid, requiring a =C(R)2 group and a =CHR group; 2-methylbut-2-ene ((CH3)2C=CH-CH3) cleaves to propanone (ketone) and ethanoic acid (carboxylic acid).',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=109,
        title='HF 9: Identifying Addition Polymer Monomers — 9701/13/M/J/23/Q19',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='A section of an addition polymer chain has the structure:\n-[CH2-CH(CH3)-CH2-CH(Cl)-CH2-CH(CH3)-CH2-CH(Cl)]-\n\nWhat were the two monomers used in an equimolar ratio to synthesize this co-polymer?',
        options=['A: Propene (CH2=CH-CH3) and chloroethene (CH2=CHCl)', 'B: Ethene and 2-chloropropane', 'C: But-1-ene and chloroethane', 'D: Prop-2-en-1-ol and chloromethane'],
        correct_answer='A',
        explanation='Option A is correct. Dividing the polymer chain into two-carbon repeating segments: the first repeat unit is -[CH2-CH(CH3)]- (which derives from the monomer propene, CH2=CH-CH3) and the second repeat unit is -[CH2-CH(Cl)]- (which derives from chloroethene / vinyl chloride, CH2=CHCl). The alternating structure indicates co-polymerisation of propene and chloroethene.',
        figure_path=None,
        figure_caption=None
    ),
    MCQQuestion(
        number=110,
        title='HF 10: Environmental Role of Catalytic Converters in Hydrocarbon Removal — 9701/11/M/J/23/Q19',
        syllabus_ref='HF',
        difficulty='HARD',
        stem='In a three-way catalytic converter fitted to a car exhaust, unburnt octane (C8H18) and nitrogen monoxide (NO) react together on the platinum-rhodium surface.\n\nWhat are the non-toxic products formed by this catalyzed reaction?',
        options=['A: Carbon monoxide (CO), ammonia (NH3), and oxygen (O2)', 'B: Carbon soot (C), nitrogen dioxide (NO2), and steam', 'C: Carbon dioxide (CO2), water (H2O), and nitrogen gas (N2)', 'D: Methane (CH4), nitric acid (HNO3), and hydrogen'],
        correct_answer='C',
        explanation='Option C is correct. The catalytic converter simultaneously oxidizes unburnt hydrocarbons and reduces nitrogen oxides: C8H18 + 25NO -> 8CO2 + 9H2O + 12.5N2. All three resulting products (CO2, H2O, and N2) are non-toxic atmospheric constituents.',
        figure_path=None,
        figure_caption=None
    ),
]
