"""
Compile Hamna Cambridge AS Biology Topic 7 Examination Pack with Official Syllabus Subtopics,
14 Embedded High-Legibility Diagrams, and Section D: 10 High-Frequency Examiner FAQs
"""
import os
import fitz
from topic7_transport_plants_data import get_topic7_questions, get_topic7_faqs
from build_as_biology_pdf import build_topic_pdf

OUTPUT_DIR = r"z:\tests n quizes63\books\psycology\new styl\AS biology cambrege"
PDF_NAME = "Hamna_Bio_Topic7_Transport_Plants.pdf"
PDF_PATH = os.path.join(OUTPUT_DIR, PDF_NAME)

TOPIC_TITLE = "TOPIC 7 — TRANSPORT IN PLANTS"
TOPIC_SUBTITLE = "Vascular Histology, Cohesion-Tension Transpiration, Xeromorphic Adaptations & Phloem Mass Flow"

# Exact subtopics from official Cambridge 9700 syllabus
SUBTOPICS = [
    "7.1 Structure of transport tissues: plan diagrams of transverse sections (TS) of stems, roots, and leaves of herbaceous dicotyledonous plants; precise spatial distribution of xylem and phloem in stem (peripheral ring, internal xylem), root (central stele, star/cross-shaped xylem), and leaf midrib (upper/adaxial xylem, lower/abaxial phloem); ultrastructure and cellular adaptations of xylem vessel elements (lignified secondary walls, hollow lumen from autolysis of protoplast, absent/perforated end walls, bordered pits for lateral bypass); ultrastructure and interdependence of phloem sieve tube elements (reduced peripheral cytoplasm, absence of nucleus, vacuole, ribosomes, perforated sieve plates with callose-lined pores) and companion cells (prominent nucleus, abundant mitochondria, dense ribosomes, extensive plasmodesmata, transfer cell wall ingrowths).",
    "7.2 Transport mechanisms: uptake and transport of dissolved mineral ions and water across root cortex; apoplast pathway (porous cellulose cell walls and intercellular spaces) vs symplast pathway (living cytoplasm interconnected via plasmodesmata); endodermal checkpoint and the role of the suberised, hydrophobic Casparian strip in forcing apoplastic water into symplast for selective membrane filtration; transpiration as the loss of water vapour from aerial parts of the plant via evaporation from wet mesophyll cell walls into intercellular spaces followed by diffusion through stomata down water potential gradient; cohesion-tension theory (transpiration pull/tension, hydrogen bonding cohesion of unbroken water column, adhesion to hydrophilic cellulose and lignin); experimental investigation of water uptake using calibrated potometers; xerophytic leaf adaptations (sunken stomata, epidermal trichomes, rolled leaves in Ammophila arenaria, thick waxy cuticle); translocation of sucrose and amino acids from sources to sinks via phloem; chemiosmotic phloem loading in companion cells via H+-ATPase proton pumps and secondary active H+/sucrose cotransporters; mass flow hypothesis driven down hydrostatic pressure gradients (delta-P) generated by osmotic water movement at source and sink; classical aphid stylet and girdling evidence."
]

def main():
    print(f"Loading Topic 7 questions and FAQs...")
    qs = get_topic7_questions()
    faqs = get_topic7_faqs()
    total_marks = sum(sum(p.marks for p in q.parts) for q in qs)
    print(f"Loaded {len(qs)} questions ({total_marks} marks) and {len(faqs)} examiner FAQs.")

    print(f"Building PDF: {PDF_PATH}...")
    build_topic_pdf(PDF_PATH, TOPIC_TITLE, TOPIC_SUBTITLE, SUBTOPICS, qs, faqs=faqs)

    doc = fitz.open(PDF_PATH)
    page_count = len(doc)
    print(f"Successfully generated {PDF_NAME} with {page_count} pages.")

    # Render previews of key pages: cover, diagram pages, FAQ pages, and mark scheme
    preview_pages = [0, 1, 3, 5, 7, 9, 11, 13, 15, page_count - 5, page_count - 4, page_count - 3, page_count - 2, page_count - 1]
    for p_idx in preview_pages:
        if 0 <= p_idx < page_count:
            page = doc[p_idx]
            pix = page.get_pixmap(dpi=150)
            preview_path = os.path.join(OUTPUT_DIR, f"preview_topic7_p{p_idx+1}.png")
            pix.save(preview_path)
            print(f"Saved preview: {preview_path}")

if __name__ == "__main__":
    main()
